/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(g){function c(a){a&&!a.size&&(a.size=[320,200]);this.parent=h.View;this.parent(a);this.constructor=c}function d(a){this.parent=b.EventSource;this.parent(a);this.constructor=d}var f=g.vs,e=f.util,b=f.core,h=f.ui,i=f.av;c.UNKNOWN_ERR=0;c.MEDIA_ERR_ABORTED=1;c.MEDIA_ERR_NETWORK=2;c.MEDIA_ERR_DECODE=3;c.MEDIA_ERR_SRC_NOT_SUPPORTED=4;c.prototype={delegate:null,_state:b.Task.STOPPED,__video_node:null,_src:"",_poster:"",_preload:"",_autoplay:!1,_loop:!1,_controls:!1,_volume:1,_muted:!1,_current_time:0,
play:function(){if(this._state===b.Task.STARTED)return!1;this.__video_node&&(this._state=b.Task.STARTED,this.__video_node.play())},start:function(){this.play()},pause:function(){if(this._state===b.Task.PAUSED)return!1;this.__video_node&&(this.__video_node.pause(),this._state=b.Task.PAUSED,this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this))},stop:function(){if(this._state===b.Task.STOPPED)return!1;this.__video_node&&(this.__video_node.stop?this.__video_node.stop():(this.__video_node.pause(),
this.__video_node.currentTime=0),this._state=b.Task.STOPPED,this.delegate&&this.delegate.taskDidStop&&this.delegate.taskDidStop(this))},destructor:function(){this.__i__&&(this.__video_node.removeEventListener("volumechange",this),this.__video_node.removeEventListener("ended",this),this.__video_node.removeEventListener("playing",this),this.__video_node.removeEventListener("play",this),this.__video_node.removeEventListener("pause",this),this.__video_node.removeEventListener("error",this),h.View.prototype.destructor.call(this))},
initComponent:function(){h.View.prototype.initComponent.call(this);if(this.__video_node=this.view.querySelector("video")){this.__video_node.addEventListener("volumechange",this);this.__video_node.addEventListener("ended",this);this.__video_node.addEventListener("playing",this);this.__video_node.addEventListener("play",this);this.__video_node.addEventListener("pause",this);this.__video_node.addEventListener("error",this);var a=this;this.__video_node.addEventListener("timeupdate",function(){a._current_time=
a.__video_node.currentTime;a.propertyChange("currentTime")},!1)}else console.error("Uncompatible video view")},handleEvent:function(a){switch(a.type){case "volumechange":this._volume=this.__video_node.getAttribute("volume");this.propertyChange("volume");this.propagate("volumechange",this._volume);break;case "ended":this._state=b.Task.STOPED;this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this);this.propagate(a.type);break;case "pause":this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this);
this._state=b.Task.PAUSED;this.propagate(a.type);break;case "playing":case "play":this._state=b.Task.STARTED;this.propagate(a.type);break;case "error":this.__video_node.error?this.propagate(a.type,this.__video_node.error.code):this.propagate(a.type,c.UNKNOWN_ERR)}}};e.extendClass(c,h.View);e.defineClassProperties(c,{controls:{set:function(a){this._controls=a?!0:!1;this.__video_node&&(this.__video_node.setAttribute("controls",this._controls),this.propertyChange("controls"))},get:function(){return this._controls}},
size:{set:function(a){if(a&&e.isArray(a)&&2===a.length&&e.isNumber(a[0])&&e.isNumber(a[1])&&(this._size[0]=a[0],this._size[1]=a[1],this.view)){this._updateSizeAndPos();if(!this.__video_node&&(this.__video_node=this.view.querySelector("video"),!this.__video_node)){console.error("Uncompatible video view");return}this.__video_node.setAttribute("width",this._size[0]);this.__video_node.setAttribute("height",this._size[1])}},get:function(){this.view&&this.view.parentNode&&(this._size[0]=this.view.offsetWidth,
this._size[1]=this.view.offsetHeight);return this._size.slice()}},src:{set:function(a){e.isString(a)&&(this._src=a,this.__video_node&&(this.__video_node.setAttribute("src",this._src),this.propertyChange("src")))},get:function(){return this._src}},poster:{set:function(a){e.isString(a)&&(this._poster=a,this.__video_node&&(this.__video_node.setAttribute("poster",this._poster),this.propertyChange("poster")))},get:function(){return this._poster}},loop:{set:function(a){this._loop=a?!0:!1;this.__video_node&&
(this.__video_node.setAttribute("loop",this._loop),this.propertyChange("loop"))},get:function(){return this._loop}},autoplay:{set:function(a){this._autoplay=a?!0:!1;this.__video_node&&(this.__video_node.setAttribute("autoplay",this._autoplay),this.propertyChange("autoplay"))},get:function(){return this._autoplay}},volume:{set:function(a){if(e.isNumber(a)&&!(0>a||1<a))this._volume=a,this.__video_node&&(this.__video_node.setAttribute("volume",this._volume),this.propertyChange("volume"))},get:function(){return this._volume}},
muted:{set:function(a){this._muted=a?!0:!1;this.propertyChange("muted")},get:function(){return this._muted}},currentTime:{get:function(){return this._current_time}},state:{get:function(){return this._state}}});i.Video=c;d.UNKNOWN_ERR=0;d.MEDIA_ERR_ABORTED=1;d.MEDIA_ERR_NETWORK=2;d.MEDIA_ERR_DECODE=3;d.MEDIA_ERR_SRC_NOT_SUPPORTED=4;d.prototype={delegate:null,_state:b.Task.STOPPED,__audio:null,_src:"",_autoplay:!1,_loop:!1,_volume:1,_muted:!1,_current_time:0,play:function(){if(this._state===b.Task.STARTED)return!1;
this.__audio&&(this._state=b.Task.STARTED,this.__audio.play())},start:function(){this.play()},pause:function(){if(this._state===b.Task.PAUSED)return!1;this.__audio&&(this.__audio.pause(),this._state=b.Task.PAUSED,this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this))},stop:function(){if(this._state===b.Task.STOPPED)return!1;this.__audio&&(g.Media?this.__audio.stop():this.__audio.pause(),this._state=b.Task.STOPPED,this.delegate&&this.delegate.taskDidStop&&this.delegate.taskDidStop(this))},
destructor:function(){this.__i__&&(this.__audio.removeEventListener("volumechange",this),this.__audio.removeEventListener("ended",this),this.__audio.removeEventListener("playing",this),this.__audio.removeEventListener("play",this),this.__audio.removeEventListener("pause",this),this.__audio.removeEventListener("error",this),delete this.__audio,this.__audio=null,b.EventSource.prototype.destructor.call(this))},initComponent:function(){b.EventSource.prototype.initComponent.call(this);this.__audio=new g.Audio;
this.__audio.preload="auto";this.__audio.autoplay=this._autoplay;this.__audio.addEventListener("volumechange",this);this.__audio.addEventListener("ended",this);this.__audio.addEventListener("playing",this);this.__audio.addEventListener("play",this);this.__audio.addEventListener("pause",this);this.__audio.addEventListener("error",this);var a=this;this.__audio.addEventListener("timeupdate",function(){a._current_time=a.__audio.currentTime;a.propertyChange("currentTime")},!1)},handleEvent:function(a){switch(a.type){case "volumechange":this._volume=
this.__audio.volume;this.propertyChange("volume");this.propagate("volumechange",this._volume);break;case "ended":this._state=b.Task.STOPED;this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this);this.propagate(a.type);break;case "pause":this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this);this._state=b.Task.PAUSED;this.propagate(a.type);break;case "playing":case "play":this._state=b.Task.STARTED;this.propagate(a.type);break;case "error":this.__audio.error?this.propagate(a.type,
this.__audio.error.code):this.propagate(a.type,d.UNKNOWN_ERR)}}};e.extendClass(d,b.EventSource);e.defineClassProperties(d,{src:{set:function(a){if(f.util.isString(a)){this._src=a;self=this;if(g.Media)this.__audio=new g.Media(this._src,function(){self._state=b.Task.STOPED;self.delegate&&self.delegate.taskDidEnd&&self.delegate.taskDidEnd(self);self.propagate(event.type)}),this._autoplay&&this.play();else{if(!this.__audio)return;this.__audio.src=this._src}this.propertyChange("src")}},get:function(){return this._src}},
loop:{set:function(a){this._loop=a?!0:!1;this.__audio&&(this.__audio.loop=this._loop,this.propertyChange("loop"))},get:function(){return this._loop}},autoplay:{set:function(a){this._autoplay=a?!0:!1;this.__audio&&(this.__audio.autoplay=this._autoplay,this.propertyChange("autoplay"))},get:function(){return this._autoplay}},volume:{set:function(a){if(f.util.isNumber(a)&&!(0>a||1<a))this._volume=a,this.__audio&&(this.__audio.volume=this._volume,this.propertyChange("volume"))},get:function(){return this._volume}},
muted:{set:function(a){this._muted=a?!0:!1;this.propertyChange("muted")},get:function(){return this._muted}},currentTime:{get:function(){return this._current_time}},state:{get:function(){return this._state}}});i.Audio=d;c.prototype.html_template="<div class='vs_av_video'><video class='video_inner'></video></div>"})(window);
