/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(o,u){function z(){return"vs_id_"+ca++}function T(){return"vs_id_"+(new Date).getTime()+""+Math.floor(1E6*Math.random())}function O(a,b){f.isNumber(a)&&(this.x=a);f.isNumber(b)&&(this.y=b)}function q(a){this.constructor=j.Object;this._id=f.isString(a)?a:a&&a.id?a.id:z();this.__df__=[];a&&(this.__config__=a)}function G(a){return a&&f.isFunction(a.clone)?a.clone():f.clone(a)}function da(a,b,c){var d=b.__lookupGetter__(a),e=b.__lookupSetter__(a),g=c.__lookupSetter__(a),i="_"+f.underscore(a);
if(e||d)g?c[a]=G(b[i]):c[i]=G(b[i])}function ea(a,b,c){var d=b.getPropertyDescriptor(a),e=c.getPropertyDescriptor(a),g="_"+f.underscore(a);if(d&&e&&(d.get||d.set))e.set?c[a]=G(b[g]):c[g]=G(b[g])}function fa(a,b){var c={},d,e,g,i;for(i in b){d=b[i];if(f.isNumber(d))e={},g="_"+f.underscore(i),d&k.core.Object.PROPERTY_IN&&(e.set=function(a,b){return function(c){this[b]=c;this.propertyChange(a)}}(i,g)),d&k.core.Object.PROPERTY_OUT&&(e.get=function(a){return function(){return this[a]}}(g));else if(f.isString(d)){g=
ga.exec(d);if(!g||3!=g.length)throw"Unvalid property path: "+d;e={};e.set=function(a,b){return function(c){for(var d=this,g=a.split(".");d&&g.length;)d=d[g.shift()];d&&(d[b]=c);this.propertyChange(b)}}(g[1],g[2]);e.get=function(a,b){return function(){for(var c=this,d=a.split(".");c&&d.length;)c=c[d.shift()];if(c)return c[b]}}(g[1],g[2])}else"object"==typeof d&&(e=d);c[i]=e}f.defineClassProperties(a,c)}function U(a,b){this.obj=a;f.isFunction(b)?this.func_ptr=b:f.isString(b)&&(this.func_name=b)}function P(a,
b){this.func_ptr=a;this.args=b}function V(a,b){a&&b&&(H={handler_list:b,event:a},Q())}function W(a,b){function c(){h--;0>=h&&(b?I=!1:J=!1)}function d(a){if(a)try{if(f.isFunction(a.func_ptr))a.func_ptr.call(a.obj,x);else if(f.isString(a.func_name)&&f.isFunction(a.obj[a.func_name]))a.obj[a.func_name](x);else f.isFunction(a.obj.notify)&&a.obj.notify(x)}catch(b){b.stack?console.error(b.stack):console.error(b)}c()}var e=a.handler_list,g=e.length,i,h=g,x=a.event;b?I=!0:J=!0;g||c();for(i=0;i<g;i++)b?d(e[i]):
function(a){k.setImmediate(function(){d(a)})}(e[i])}function X(){if(A.length){var a=A.shift();if(a)try{K=!0,a.run()}catch(b){b.stack?console.error(b.stack):console.error(b)}k.util.free(a);K=!1;A.length&&R()}}function ha(){function a(a){a.data===b&&X()}var b="vs.core.scheduler"+Math.random();o.addEventListener&&o.addEventListener("message",a,!1);return function(){o.postMessage(b,"*")}}function Q(){function a(){Y=!1;Q()}H&&(W(H,!0),H=null);0===L.length&&0===A.length||Y||(J||I?k.setImmediate(a):(!K&&
A.length&&R(),L.length&&!J&&!I&&W(L.shift())))}function r(a){this.parent=q;this.parent(a);this.constructor=j.EventSource;this.__bindings__={};this.__node_binds__={}}function B(a){this.parent=r;this.parent(a);this.constructor=k.core.Model;this.__links__=[]}function v(a){this.dataflow_node=[];this.dataflow_edges={};this.is_propagating=!1;this.__shouldnt_propagate__=0;this._list_node=[];this._edges_from={};a&&a.__df__&&a.__df__.push(this)}function m(a){this.parent=j.Object;this.parent(a);this.constructor=
m}function C(a){this.parent=j.Task;this.parent();this.constructor=C;this._tasksAndParams=[];this._state=m.STOPPED;arguments.length&&this.setTasks(arguments)}function D(a){this.parent=j.Task;this.parent();this.constructor=D;this._tasksAndParams=[];this._state=m.STOPPED;arguments.length&&this.setTasks(arguments)}function E(a){this.parent=j.Task;this.parent();this.constructor=E;this._state=m.STOPPED;this.time=a}function h(){this.deviceId=this.orientation=null;this.browserDetect();this.orientationDetect();
this.screenDetect()}function y(a){this.parent=k.core.Model;this.parent(a);this.constructor=k.core.Array}function t(a){this.parent=j.EventSource;this.parent(a);this.constructor=k.core.DataStorage;this.__models__={}}function S(a){this.parent=t;this.parent(a);this.constructor=k.core.LocalStorage}function s(a){this.parent=t;this.parent(a);this.constructor=s;this._xhrs={};this._headers={}}var Z=o.document,k=o.vs,f=k.util,j=k.core,ca=0;j.createId=z;j.createUniqueId=T;O.prototype={x:0,y:0,matrixTransform:function(a){var b=
new k.CSSMatrix,b=b.translate(this.x,this.y,this.z||0),a=a.multiply(b),c=new O(a.m41,a.m42);delete b;delete a;return c}};k.Point=O;q.prototype={_id:"",__i__:!1,__input_property__did__change__:!1,__config__:null,__df__:null,init:function(a){if(this.__i__)return this;this._id||(this._id=z());if(q._obs[this._id]){console.warn("Impossible to create an object with an already used id.");var b=this._id;this._id=T();console.warn('The id "'+b+'" is replaced by "'+this._id+'".')}q._obs[this._id]=this;a||this.initComponent();
this.__i__=!0;!a&&this.vsdInit&&this.vsdInit();this.__config__&&(this.configure(this.__config__),this.__config__=null);this.componentDidInitialize&&this.componentDidInitialize();this.initSkin&&(console.warn("Your application shouldn't use initSkin anymore.\n        You should rename by componentDidInitialize."),q.prototype.initSkin=function(){},this.initSkin(),q.prototype.initSkin=u);return this},initComponent:function(){},componentDidInitialize:function(){},createId:function(){console.warn("this.createId is deprecated, Use the static method vs.core.createId instead");
return z()},configure:function(a){if("object"===typeof a){var b,c,d,e=!1;this.__df__&&this.__df__.forEach(function(a){a.pausePropagation()});this.__configuration_process=!0;if(a instanceof B)if((b=this.getPropertyDescriptor("model"))&&b.set)this.model=a,e=!0;else{b=a.getModelProperties();for(d=0;d<b.length;d++)c=b[d],"id"!==c&&(this[c]=a[c],e=!0)}else if(a)for(c in a)"id"===c||"node"===c||"node_ref"===c||"view"===c||(this[c]=a[c],e=!0);this.__configuration_process=!1;this.__df__&&this.__df__.length?
this.__df__.forEach(function(a){a.restartPropagation();e&&a.propagate(this)}):e&&this.propertiesDidChange&&this.propertiesDidChange()}},propertiesDidChange:function(){return!1},toJSON:function(){return this._toJSON()},parseJSON:function(a){try{this.parseData(a&&f.parseJSON(a)||{})}catch(b){b.stack&&console.log(b.stack),console.error("vs.core.Object.parseJSON failed. "+b.toString())}},parseData:function(a){var b,c;for(b in a)c=a[b],this["_"+f.underscore(b)]=c;this.inPropertyDidChange()},_toJSON:function(){var a,
b,c={},d=this.getModelProperties();if(!d)return c;for(var e=0;e<d.length;e++)a=d[e],b=this["_"+f.underscore(a)],"undefined"!=typeof b&&(b=b instanceof Date?'"/Date('+b.getTime()+')/"':b&&b.toJSON?b.toJSON():b,c[a]=b);return c},destructor:function(){delete q._obs[this._id];this.__i__=!1},isDeleted:function(){return!this.__i__},propertyChange:function(){this.__input_property__did__change__=!0;self=this;this.__df__&&this.__df__.forEach(function(a){a.propagate(self)})},inPropertyDidChange:function(){this.__input_property__did__change__=
!0;0<v.__nb_propagation||this.__configuration_process||this.propertiesDidChange&&this.propertiesDidChange()},outPropertyChange:function(){this.__input_property__did__change__=!0;self=this;this.__df__&&this.__df__.forEach(function(a){a.propagate(self,!1,!0)})},propagateChange:function(a){this.propertyChange(a)},connect:function(a){return new M(this,a)},link:function(a){if(a instanceof k.core.Model)this.__model&&this.__model.unlinkTo(this),this.__model=a,this.__model.linkTo(this),this.configure(this.__model);
else throw"vs.core.Object.link; parameter is not a vs.core.Model";},unlink:function(){if(this.__model){if(this.__model){this.__model.unlinkTo(this);var a=this.__model.getModelProperties();for(l=a.length,config={};l--;)config[a[l]]=null;this.configure(config)}this.__model=u}},clone:function(a,b){function c(a,b,c){var d=b.__lookupGetter__(a),g=b.__lookupSetter__(a),e=c.__lookupGetter__(a),i=c.__lookupSetter__(a);d&&!e&&c.__defineGetter__(a,d);g&&!i&&c.__defineSetter__(a,g);!g&&!d?(d=b[a],c[a]=f.isArray(d)?
d.slice():b[a]):(c.__properties__||(c.__properties__=[]),c.__properties__.push(a))}function d(a,b,c){var d=b.getOwnPropertyDescriptor(a),g=c.getOwnPropertyDescriptor(a);d&&(d.get||d.set)?g||(f.defineProperty(c,a,d),c.__properties__||(c.__properties__=[]),c.__properties__.push(a)):(d=b[a],c[a]=f.isArray(d)?d.slice():b[a])}var e,g;b||(b={});if(b[this._id])return b[this._id];a||(a={});a.id||(a.id=z());if(f.isFunction(this.constructor))e=new this.constructor(a);else return console.warn("impossible to clone this object."),
null;b[this._id]=e;var i=Object.defineProperty?d:c;for(g in this)"parent"===g||"_id"===g||"constructor"===g||0===g.indexOf("__")||this.getPropertyDescriptor(g)&&(f.isFunction(this[g])&&!f.isFunction(e[g])?e[g]=this[g]:!e.isProperty(g)&&this.isProperty(g)&&i(g,this,e));e.__i__=!1;e.init();this._clone(e,b);this._clone_properties_value(e,b);this.__model&&(b&&b[this.__model._id]?e.link(b[this.__model._id]):e.link(this.__model));return e},_clone_properties_value:function(a){for(var b in this)"id"!=b&&
this.isProperty(b)&&$(b,this,a)},_clone:function(){},getModelProperties:function(){var a=[];this.__properties__&&(a=a.concat(this.__properties__));this.constructor.__properties__&&(a=a.concat(this.constructor.__properties__));return a},isProperty:function(a){return this.__properties__&&-1!==this.__properties__.indexOf(a)||-1!==this.constructor.__properties__.indexOf(a)?!0:!1},defineProperty:function(a,b){f.defineProperty(this,a,b);this.__properties__||(this.__properties__=[]);-1===this.__properties__.indexOf(a)&&
this.__properties__.push(a)},getOwnPropertyDescriptor:function(a){return Object.getOwnPropertyDescriptor(this,a)},getPropertyDescriptor:function(a){function b(a,c){if(!a)return null;var g=Object.getPrototypeOf(a);if(!g)return null;var i=Object.getOwnPropertyDescriptor(g,c);return i?i:b(g,c)}var c=Object.getOwnPropertyDescriptor(this,a);return c?c:b(this,a)},_super:function(){var a=this._super.caller._super_func_;a&&a.apply(this,arguments)}};f.defineClassProperty(q,"id",{get:function(){return this._id}});
var $=Object.defineProperty?ea:da;q._obs={};q.__propertyCloneValue=$;j.Object=q;var ia=Object.prototype.constructor;k.core.Object.PROPERTY_IN=1;k.core.Object.PROPERTY_OUT=2;k.core.Object.PROPERTY_IN_OUT=3;var ga=/(\w+[.\w+]*)#(\w+)/;j.createClass=function(a){var b=null,c={},d=k.core.Object,e={},b=function(){this.parent=b.__spec.parent;b.__spec&&b.__spec._constructor?b.__spec._constructor.apply(this,arguments):b.__spec&&b.__spec.parent&&this.parent.apply(this,arguments);this.constructor=b};a&&a.parent&&
(d=a.parent,delete a.parent);a&&a.properties&&(e=a.properties,delete a.properties);c.parent=d;a&&a.constructor&&a.constructor!==ia&&(c._constructor=a.constructor,c._constructor._super_func_=d);b.__spec=c;a&&(b.prototype=a,a.constructor=b);d.prototype&&f.extendClass(b,d);if(a)for(key in a)if(a.hasOwnProperty(key)){var c=a[key],g=d.prototype[key];f.isFunction(c)&&f.isFunction(g)&&(c._super_func_=g)}fa(b,e);return b};U.prototype.destructor=function(){delete this.obj;delete this.func_ptr;delete this.func_name};
P.prototype.run=function(){this.func_ptr.apply(u)};P.prototype.destructor=function(){delete this.args;delete this.func_ptr};var L=[],H=null,A=[],J=!1,I=!1,K=!1,Y=!1,R=o.postMessage?ha():function(){setTimeout(X,0)};k.setImmediate=(o.setImmediate||function(a){A.push(new P(a));K||R()}).bind(o);f.extend(k,{scheduleAction:function(a,b){f.isFunction(a)&&(b&&f.isNumber(b)?setTimeout(a,b):"__on_next_frame__"===b?k.requestAnimationFrame(a):k.setImmediate(a))},ON_NEXT_FRAME:"__on_next_frame__"});j.FORCE_EVENT_PROPAGATION_DELAY=
!1;j.POINTER_START=k.POINTER_START;j.POINTER_MOVE=k.POINTER_MOVE;j.POINTER_END=k.POINTER_END;j.POINTER_CANCEL=k.POINTER_CANCEL;j.GESTURE_START=k.GESTURE_START;j.GESTURE_CHANGE=k.GESTURE_CHANGE;j.GESTURE_END=k.GESTURE_END;var N=function(a,b,c){this.srcTarget=this.src=a;this.type=b;this.data=c};N.prototype={src:null,srcTarget:null,type:"",data:null,destructor:function(){delete this.src;delete this.srcTarget;delete this.type;delete this.data}};j.Event=N;j.EVENT_SUPPORT_GESTURE=!1;r.prototype={__bindings__:null,
__node_binds__:null,destructor:function(){var a,b,c;for(a in this.__bindings__){if(b=this.__bindings__[a]){c=void 0;for(var d=b.length;d--;)c=b[d],f.free(c)}delete this.__bindings__[a]}delete this.__bindings__;for(a in this.__node_binds__)if(c=this.__node_binds__[a],"undefined"===typeof c)console.warn("vs.core.Object.destructor, no bind <"+a+" exists.");else for(b=0;b<c.length;b++)data=c[b],data.n.removeEventListener(event,data.h);delete this.__node_binds__;q.prototype.destructor.call(this)},_clone:function(a,
b){q.prototype._clone.call(this,a,b);a.__bindings__={};a.__node_binds__={}},bind:function(a,b,c){if(a&&b)return b=new U(b,c),c=this.__bindings__[a],c||(c=[],this.__bindings__[a]=c),c.push(b),b},unbind:function(a,b,c){if(a=this.__bindings__[a])for(var d,e=0;e<a.length;)d=a[e],d.obj===b?f.isString(c)||f.isFunction(c)?d.func_name===c||d.func_ptr===c?(a.remove(e),f.free(d)):e++:(a.remove(e),f.free(d)):e++},propagate:function(a,b,c){var d=this.__bindings__[a];!d||0===d.length?this.__parent&&(c||(c=this),
this.__parent.propagate(a,b,c)):(a=new N(this,a,b),c&&(a.srcTarget=c),a&&d&&(L.push({handler_list:d,event:a}),Q()))},notify:function(a){this.propagate(a.type,a.data)},nodeBind:function(a,b,c,d){if(a&&f.isString(b)){var e=this,g=null,i=null,h,x;if("undefined"===typeof c)c="notify";else if(f.isString(c)){if(!f.isFunction(this[c])){console.warn("vs.core.Object.nodeBind, unknown function named: "+c);return}}else if(f.isFunction(c))g=c,c=g.name;else{console.error("vs.core.Object.nodeBind, invalid func parameter");
return}i=!d||d===n.ANY_MASK?function(a){try{a.src=a.currentTarget,a.data=a,g||(g=e[c]),g.call(e,a)}catch(b){b.stack&&console.log(b.stack),console.error(b)}}:function(a){try{if(d||!a.altKey&&!a.ctrlKey&&!a.shiftKey&&!a.metaKey)d===n.ALT&&!a.altKey||d===n.CTRL&&!a.ctrlKey||d===n.SHIFT&&!a.shiftKey||d===n.META&&!a.metaKey||(a.src=a.currentTarget,a.data=a,g||(g=e[c]),g.call(e,a))}catch(b){b.stack&&console.log(b.stack),console.error(b)}};x=b+c;this.__node_binds__?(h=this.__node_binds__[x],"undefined"===
typeof h&&(h=[],this.__node_binds__[x]=h),h.push({n:a,h:i}),k.addPointerListener(a,b,i,!1)):console.error("nodeBind impossible")}},nodeUnbind:function(a,b,c){if(a&&f.isString(b)){var d,e;if("undefined"===typeof c)c="notify";else if(f.isString(c)){if(!f.isFunction(this[c])){console.warn("vs.core.Object.nodeUnbind, unknown function named: "+c);return}}else if(f.isFunction(c))c=c.name;else{console.error("vs.core.Object.nodeBind, invalid func parameter");return}d=this.__node_binds__[b+c];if("undefined"===
typeof d)console.warn("vs.core.Object.nodeUnbind, no bind <"+b+","+c+"> exists.");else{for(c=0;c<d.length;)e=d[c],e.n===a?(k.removePointerListener(a,b,e.h,!1),d.remove(c)):c++;a._object_=u}}}};f.extendClass(r,q);j.EventSource=r;B.prototype={__links__:null,__should_propagate_changes__:!0,_sync_service_:null,bindChange:function(a,b,c){b&&this.bind(a?"change:"+a:"change",b,c)},unbindChange:function(a,b,c){this.unbind(a?"change:"+a:"change",b,c)},stopPropagation:function(){this.__should_propagate_changes__=
!1},hasToPropagateChange:function(){return this.__should_propagate_changes__},change:function(a,b,c){this.__should_propagate_changes__=!0;a=a?"change:"+a:"change";b=new N(this,a,b);try{if(!c)for(var d=this.__links__.length;d--;)this.__links__[d].configure(this);"change"!==a&&V(b,this.__bindings__[a]);V(b,this.__bindings__.change)}catch(e){e.stack&&console.error(e.stack),console.error(e)}},clear:function(a){var b,c=this;this.getModelProperties().forEach(function(d){b="_"+f.underscore(d);a&&k.util.free(c[b]);
c[b]=u})},propagate:function(a,b,c){this.__should_propagate_changes__=!0;r.prototype.propagate.call(this,a,b,c)},linkTo:function(a){a instanceof k.core.Object&&-1===this.__links__.indexOf(a)&&this.__links__.push(a)},unlinkTo:function(a){a instanceof k.core.Object&&this.__links__.remove(a)},propertyChange:function(a){k._default_df_&&k._default_df_.propagate(this,a);if(this.__should_propagate_changes__){var b=this.__links__.length;if(a)for(;b--;)this.__links__[b][a]=this[a];else for(;b--;)this.__links__[b].configure(this);
this.change(null,null,!0)}},parseData:function(a){var b;this.stopPropagation();for(b in a)this._parse_property(b,a[b]);this.change()},_parse_property:function(a,b){var c=this.getModelProperties(),d="_"+f.underscore(a),e;b&&b.data||f.isArray(b)?(e=(new y({id:b.id})).init(),e.parseData(b)):e=b;-1===c.indexOf(a)&&(c={},d="_"+f.underscore(a),c.set=function(a,b){return function(c){this[b]=c;this.propertyChange(a)}}(a,d),c.get=function(a){return function(){return this[a]}}(d),this.defineProperty(a,c));
this[d]=e}};f.extendClass(B,r);j.Model=B;var n=new r("__KEYBOARD__");n._handler_set_down=!1;n._handler_set_up=!1;n.managePrevent=function(a,b){var c=this.__bindings__[a],d,e;if(c)for(d=0;d<c.length;d++)if(e=c[d],e.prevent){b.preventDefault();break}};n.KEY_UP=1E3;n.ESC=27;n.ENTER=13;n.SPACE=32;n.BACKSPACE=8;n.SHIFT=16;n.CTRL=17;n.ALT=18;n.NUMLOCK=144;n.LEFT_ARROW=37;n.UP_ARROW=38;n.RIGHT_ARROW=39;n.DOWN_ARROW=40;n.L=76;n.S=83;n.Z=90;n.META=2E3;n.ANY_MASK=3E3;n.UNDO=256;n.REDO=257;n.SAVE=258;j.KEYBOARD=
n;j.KEYBOARD.bind=function(a,b,c,d){var b=r.prototype.bind.call(this,a,b,c),e=this;d&&(b.prevent=!0);a>n.KEY_UP?this._handler_set_up||(Z.documentElement.addEventListener("keyup",function(a){e.managePrevent(a.keyCode,a);e.propagate(a.keyCode+n.KEY_UP,a)},!1),this._handler_set_up=!0):this._handler_set_down||(Z.documentElement.addEventListener("keydown",function(a){(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode===n.Z?(e.propagate(n.UNDO),a.preventDefault()):(a.ctrlKey||a.metaKey)&&a.shiftKey&&a.keyCode===
n.Z?(e.propagate(n.REDO),a.preventDefault()):(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode===n.S?(e.propagate(n.SAVE),a.preventDefault()):(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode?(e.managePrevent(n.META+a.keyCode,a),e.propagate(n.META+a.keyCode)):(e.managePrevent(a.keyCode,a),e.propagate(a.keyCode,a))},!1),this._handler_set_down=!0);return b};var F=function(a){this.parent=j.EventSource;this.parent(z());this.constructor=F;this.owner=a;this._list_of_state={};this._list_input=[];this._list_output=
[];this._current_state=this._initial_state="";this._inputs={};this._output_action={}};F.prototype={destructor:function(){delete this._list_of_state;this.owner=u;delete this._list_of_state;delete this._list_input;delete this._list_output;delete this._inputs;delete this._output_action;j.EventSource.prototype.destructor.call(this)},_clone:function(a,b){r.prototype._clone.call(this,a,b);a.owner=a.__config__.owner;a._current_state="";a._inputs={};a._output_action={}},initWithData:function(a,b,c,d){if(a&&
b&&c&&d){for(var e=0;e<a.length;e++)this.addState(a[e]);for(e=0;e<b.length;e++)this.addInput(b[e]);for(e=0;e<c.length;e++)this.addOutput(c[e]);for(e=0;e<d.length;e++)this.addTransition(d[e].from,d[e].to,d[e].on,d[e].output)}},initWithMatrix:function(a){for(var b=1;b<a[0].length;b++)this.addState(a[0][b]);for(b=1;b<a.length;b++)for(var c=a[b][0],d=1;d<a[0].length;d++){var e=a[0][d],g=a[b][d];g&&(g=g.split("/"),g[0]&&this.addInput(g[0]),g[1]&&this.addOutput(g[1]),this.addTransition(c,e,g[0],g[1]))}},
addInput:function(a){a&&!this.existInput(a)&&this._list_input.push(a)},getInputs:function(){return this._list_input.slice()},existInput:function(a){return!a?void 0:-1<this._list_input.findItem(a)},addOutput:function(a){a&&!this.existOutput(a)&&this._list_output.push(a)},getOutputs:function(){return this._list_output.slice()},existOutput:function(a){return!a?void 0:-1<this._list_output.findItem(a)},addState:function(a){if(!a||this.existState(a))return!1;this._list_of_state[a]={transitionEvents:{}};
return!0},removeState:function(a){if(!a||!this.existState(a))return!1;delete this._list_of_state[a];return!0},renameState:function(a,b){if(!a||!this.existState(a)||!b||this.existState(b))return!1;this._list_of_state[b]=this._list_of_state[a];delete this._list_of_state[a];this._initial_state===a&&(this._initial_state=b);for(var c in this._list_of_state){var d=this._list_of_state[c];if(null!==d)for(var e in d.transitionEvents){var g=d.transitionEvents[e];g.to===a&&(g.to=b)}}return!0},getListState:function(){var a=
[],b;for(b in this._list_of_state)a.push(b);return a},existState:function(a){return!a?!1:this._list_of_state[a]?!0:!1},addTransition:function(a,b,c,d){a&&this.existState(a)&&b&&this.existState(b)&&c&&this.existInput(c)&&(this._list_of_state[a].transitionEvents[c]={on:c,to:b,output:d})},removeTransitionFrom:function(a,b){if(a&&this.existState(a)&&b&&this.existInput(b)){var c=this._list_of_state[a];c.transitionEvents[b]&&delete c.transitionEvents[b]}},removeTransitionTo:function(a,b){if(a&&this.existState(a)&&
b&&this.existInput(b))for(var c in this._list_of_state){var d=this._list_of_state[c],e=d.transitionEvents[b];e&&e.to===a&&delete d.transitionEvents[b]}},getTransionsToState:function(a){if(this.existState(a)){var b=[],c;for(c in this._list_of_state){var d=this._list_of_state[c];if(null!==d)for(var e in d.transitionEvents){var g=d.transitionEvents[e];g.to===a&&(g=f.clone(g),g.from=c,b.push(g))}}return b}},getTransionsFromState:function(a){if(this.existState(a)){var b=[],c=this._list_of_state[a];if(null===
c)return null;for(var d in c.transitionEvents){var e=f.clone(c.transitionEvents[d]);e.from=a;b.push(e)}return b}},switchStates:function(a,b){if(!(a===b||!this.existState(a)||!this.existState(b))){for(var c=this.getTransionsToState(a),d=this.getTransionsFromState(a),e=this.getTransionsToState(b),g=this.getTransionsFromState(b),i=0;i<c.length;){var f=c[i];f.from===b?c.remove(f):i++}for(i=0;i<d.length;)f=d[i],f.to===b?d.remove(f):i++;for(i=0;i<c.length;i++)f=c[i],this.removeTransitionFrom(f.from,f.on);
for(i=0;i<d.length;i++)f=d[i],this.removeTransitionFrom(f.from,f.on);for(i=0;i<e.length;i++)f=e[i],this.removeTransitionFrom(f.from,f.on);for(i=0;i<g.length;i++)f=g[i],this.removeTransitionFrom(f.from,f.on);for(i=0;i<c.length;i++){var f=c[i],h=f.from===b?a:f.from;this.addTransition(h,b,f.on,f.output)}for(i=0;i<d.length;i++)f=d[i],c=f.from===b?a:f.to,this.addTransition(b,c,f.on,f.output);for(i=0;i<e.length;i++)f=e[i],h=f.from===a?b:f.from,this.addTransition(h,a,f.on,f.output);for(i=0;i<g.length;i++)f=
g[i],c=f.to===a?b:f.to,this.addTransition(a,c,f.on,f.output);this._initial_state===a?this._initial_state=b:this._initial_state===b&&(this._initial_state=a)}},setInput:function(a,b,c){if(a&&b&&c){if(b.bind)b.bind(c,this);else if(b.addEventListener)this.nodeBind(b,c);else return;var d=this._inputs[b];d||(d=[],this._inputs[b]=d);d.push([c,a,b])}},setOutput:function(a,b){a&&b&&(this._output_action[a]=b)},activate:function(){if(!this._initial_state||!this._list_of_state[this._initial_state])return!1;this.goTo(this._initial_state);
return!0},goTo:function(a,b,c){if(!this.existState(a))return!1;this._current_state=a;if(b&&this._output_action[b])if(a=this._output_action[b],f.isFunction(a))a.call(this.owner,c);else if(f.isString(a))this.owner[this._output_action[b]](c);return!0},clear:function(){this._list_of_state={};delete this._list_input;delete this._list_output;this._list_input=[];this._list_output=[];this._initial_state="";for(var a in this._inputs)for(var b=this._inputs[a],c=0;c<b.length;c++){var d=b[c][2],e=b[c][0];d.bind?
d.unbind(e,this):d.addEventListener&&this.nodeUnbind(d,e)}this._current_state=""},notify:function(a){var b=this._inputs[a.src];if(b)for(var c=0;c<b.length;c++)a.type===b[c][0]&&this._list_of_state[this._current_state]&&this.fsmNotify(b[c][1],a.data)},getAccessibleStateOn:function(a){if(this._list_of_state[this._current_state])return a=this._list_of_state[this._current_state].transitionEvents[a],!a?void 0:this._list_of_state[a.to]},fsmNotify:function(a,b,c){if(this._list_of_state[this._current_state]){var d=
this._list_of_state[this._current_state].transitionEvents[a];if(!d)return!1;this.goTo(d.to,d.output,{on:a,data:b},c);return!0}}};f.extendClass(F,r);f.defineClassProperty(F,"initialState",{set:function(a){a?this.existState(a)&&(this._initial_state=a):this._initial_state=u},get:function(){return this._initial_state}});j.Fsm=F;var aa=1;v.__nb_propagation=0;v.prototype={propagate_values:function(a){var b=this.dataflow_edges[a._id],c,d=0,e=0,g=0,i,h,j,k=0,m=0,n=null,p;if(b){k=b.length;for(d=0;d<k;d++)if(c=
b[d])if(j=c[0])if((c=c[2])&&c.length)for(e=0;e<c.length;e++){i=c[e];n=i[3];p=[];h=i[1];m=h.length;for(g=0;g<m;g++)p.push(h[g].call(a));n&&(p=n.apply(o,p),f.isArray(p)||(p=[p]));h=i[2];m=h.length;if(p.length!==m){console.error("Dataflow, invalid parameters");return}for(g=0;g<m;g++)i=h[g],i.call(j,p[g]);j.__input_property__did__change__=!0}}},propagate:function(a,b,c){if(!this.is_propagating&&!this.__shouldnt_propagate__){this.is_propagating=!0;v.__nb_propagation++;var b=0,d=this.dataflow_node,e=d.length;
if(a){for(;b<e&&d[b]!==a;)b++;if(b<e-1){if(!c&&a.propertiesDidChange&&a.propertiesDidChange()){v.__nb_propagation--;this.is_propagating=!1;return}this.propagate_values(a);b++}else b=0}for(;b<e;b++)if((a=d[b])&&a.__input_property__did__change__)a.__input_property__did__change__=!1,(!a.propertiesDidChange||!a.propertiesDidChange())&&this.propagate_values(a);v.__nb_propagation--;this.is_propagating=!1}},connect:function(a,b,c,d,e){var g,i,h,j,k=aa++;g=f.isString(a)?a:a._id;if(a=q._obs[g]){-1===a.__df__.indexOf(this)&&
a.__df__.push(this);a=f.isString(c)?c:c._id;if(f.isString(b))b=[b];else if(!f.isArray(b)){console.warn("DataFlow.connect, error");return}if(f.isString(d))d=[d];else if(!f.isArray(d)){console.warn("DataFlow.connect, error");return}if(!e&&d.length!==b.length)console.warn("DataFlow.connect, error");else{-1===this._list_node.indexOf(g)&&this._list_node.push(g);-1===this._list_node.indexOf(a)&&this._list_node.push(a);c=this._edges_from[g];c||(c=[],this._edges_from[g]=c);i=c.length;for(g=0;g<i;g++)if(h=
c[g],h[0]===a){j=h[2];break}j||(j=[],c.push([a,1,j]));e=[k,b.slice(),d.slice(),e];j.push(e);return k}}},unconnect:function(){1===arguments.length?this._unconnect_by_id(arguments[0]):this._unconnect_by_params.apply(this,arguments)},_unconnect_by_params:function(a,b,c,d){function e(a,b){b.forEach(function(b){b=a.indexOf(b);-1!==b&&a.remove(b)})}var g,i;aa++;var h,a=f.isString(a)?a:a._id;if(g=this._edges_from[a])if((a=q._obs[a])&&-1!==a.__df__.indexOf(this)){c=f.isString(c)?c:c._id;if(f.isString(b))b=
[b];else if(!f.isArray(b)){console.warn("DataFlow.unconnect, error");return}if(f.isString(d))d=[d];else if(!f.isArray(d)){console.warn("DataFlow.unconnect, error");return}for(a=0;a<g.length;a++)if(i=g[a],i[0]===c){i=i[2];for(var j=0;j<i.length;)h=i[j],properties_out_s=h[1],properties_in_s=h[2],e(properties_out_s,b),e(properties_in_s,d),0===properties_out_s.length||0===d.length?i.remove(j):j++;0===i.length?g.remove(a):a++}else a++}},_unconnect_by_id:function(a){for(var b in this._edges_from){var c=
this._edges_from[b];if(c)for(var d=c.length,e=0;e<d;e++)for(var g=c[e][2],f=0,h=g.length,j;f<h;f++)if((j=g[f])&&j[0]===a){g.remove(f);return}}},_sort:function(){var a=this._list_node.length,b=[],c,d,e,g;for(c=0;c<a;c++)b[c]=0;for(e in this._edges_from){g=this._edges_from[e];for(d=0;d<g.length;d++)a=this._list_node.findItem(g[d][0]),b[a]++}a=this._list_node.slice();c=[];for(e=0;0!==a.length;){d=this._array_min(b);g=b[d];b.remove(d);var f=a[d];a.remove(d);0<g&&e++;c.push(f);if(g=this._edges_from[f])for(d=
0;d<g.length;d++)f=a.findItem(g[d][0]),-1!==f&&b[f]--}this._list_node=c;this.is_sorted=!0;this.is_cyclic=0<e;0<e&&(b=Object.keys(this._edges_from).length,console.warn("WARNING: Cycles detected during topological sort.%d dependencies out of %d have been violated.\n",e,b));return!this.is_cyclic},_array_min:function(a){var b=a.length;if(0===b)return-1;if(1===b)return 0;for(var b=0,c=a[b],d=1;d<a.length;d++)a[d]<c&&(c=a[d],b=d);return b},build:function(){this._sort();this._data_optimize(this._edges_from,
this._list_node)},pausePropagation:function(){this.__shouldnt_propagate__++},restartPropagation:function(){this.__shouldnt_propagate__--;0>this.__shouldnt_propagate__&&(this.__shouldnt_propagate__=0)},_data_optimize:function(a,b){if(b&&a){var c=[],d,e,g,h,j,k,m,n,o,p,r,u,s,t,v,w;for(d=0;d<b.length;d++)p=b[d],(u=q._obs[p])&&c.push(u);this.dataflow_node=c;c={};for(p in a)if(u=q._obs[p])if(h=a[p],j=[],c[p]=j,h)for(d=0;d<h.length;d++)if(k=h[d],e=[3],j.push(e),r=k[0],r=q._obs[r]){e[0]=r;e[1]=k[1];k=k[2];
m=[];e[2]=m;for(e=0;e<k.length;e++){n=k[e];o=[4];m.push(o);o[0]=n[0];f.isFunction(n[3])&&(o[3]=n[3]);v=n[1];w=[];for(g=0;g<v.length;g++)s=v[g],(t=u.getPropertyDescriptor(s))&&(t.get?w.push(t.get):w.push(function(a){return function(){return this[a]}}("_"+f.underscore(s))));o[1]=w;v=n[2];w=[];for(g=0;g<v.length;g++)s=v[g],(t=r.getPropertyDescriptor(s))&&(t.set?w.push(t.set):w.push(function(a){return function(b){this[a]=b}}("_"+f.underscore(s))));o[2]=w}}this.dataflow_edges=c}}};j.DataFlow=v;k._default_df_=
new v;var M=function(a,b){this._base_object=a;this._previous_object=u;this.property_out=b};M.prototype.to=function(a,b,c){k._default_df_.connect(this._base_object,this.property_out,a,b,c);this._previous_object=a;return this};M.prototype.connect=function(a){return new M(this._previous_object||this._base_object,a)};m.STARTED=1;m.STOPPED=0;m.PAUSED=2;m.prototype={delegate:null,_state:m.STOPPED,destructor:function(){this.stop();j.Object.prototype.destructor.call(this)},_clone:function(a,b){j.Object.prototype.destructor._clone.call(this,
a,b);a._state=this._state},start:function(){},stop:function(){},pause:function(){}};f.extendClass(m,j.Object);f.defineClassProperty(m,"state",{get:function(){return this._state}});k.par=function(){if(0!==arguments.length){var a=new C;a.setTasks(arguments);return a}};C.prototype={_tasksAndParams:null,_tasksWillEnded:null,setTasks:function(a){if(this._state!==m.STOPPED)return!1;var b,c,d,e;this._tasksAndParams=[];for(b=0;b<a.length;b++)if(c=a[b])d=e=null,f.isArray(c)?1===c.length?d=c[0]:2===c.length&&
(d=c[0],e=c[1]):(d=c,e=null),d?!d.start||!d.stop||!d.pause?console.warn("Invalid task: "+d.toString()):this._tasksAndParams.push([d,e]):console.warn("Undefined task")},start:function(a){if(this._state===m.STARTED)return!1;this._tasksWillEnded=this._tasksAndParams.length;this._state=m.STARTED;var b,c;for(c=0;c<this._tasksAndParams.length;c++)b=this._tasksAndParams[c],b[0].delegate=this,b[0].start(b[1]?b[1]:a);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;var a,
b;for(b=0;b<this._tasksAndParams.length;b++)a=this._tasksAndParams[b],a[0].stop();return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;var a,b;for(b=0;b<this._tasksAndParams.length;b++)a=this._tasksAndParams[b],a[0].pause();return!0},taskDidStop:function(){this._state=m.STOPPED;this._tasksWillEnded--;if(0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidStop)try{this.delegate.taskDidStop(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},taskDidPause:function(){this._state=
m.STOPPED;this._tasksWillEnded--;if(0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidPause)try{this.delegate.taskDidPause(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},taskDidEnd:function(){this._state=m.STOPPED;this._tasksWillEnded--;if(0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidEnd)try{this.delegate.taskDidEnd(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}}};f.extendClass(C,m);k.seq=function(){if(0!==arguments.length){var a=new D;
a.setTasks(arguments);return a}};D.prototype={_tasksAndParams:null,_nextTaskToStart:0,_startParam:null,setTasks:function(a){if(this._state!==m.STOPPED)return!1;var b,c,d,e;this._tasksAndParams=[];for(b=0;b<a.length;b++)if(c=a[b])d=e=null,f.isArray(c)?1===c.length?d=c[0]:2===c.length&&(d=c[0],e=c[1]):(d=c,e=null),d?!d.start||!d.stop||!d.pause?console.warn("Invalid task: "+d.toString()):this._tasksAndParams.push([d,e]):console.warn("Undefined task")},start:function(a){if(this._state===m.STARTED)return!1;
var b=this._tasksAndParams[this._nextTaskToStart];this._nextTaskToStart++;if(!b)return this._nextTaskToStart=0,this._state=m.STOPED,!1;this._state=m.STARTED;this._startParam=a;b[0].delegate=this;b[0].start(b[1]?b[1]:a);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;var a=this._tasksAndParams[this._nextTaskToStart-1];this._nextTaskToStart=0;if(!a)return!1;a[0].stop();return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;var a=this._tasksAndParams[this._nextTaskToStart-
1];if(!a)return!1;a[0].pause();return!0},taskDidStop:function(){this._state=m.STOPPED;this._nextTaskToStart=0;if(this.delegate&&this.delegate.taskDidStop)try{this.delegate.taskDidStop(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},taskDidPause:function(){this._state=m.PAUSED;this._nextTaskToStart-=1;if(this.delegate&&this.delegate.taskDidPause)try{this.delegate.taskDidPause(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},taskDidEnd:function(){this._state=m.STOPPED;
if(this._nextTaskToStart<this._tasksAndParams.length)this.start(this._startParam);else if(this._nextTaskToStart=0,this.delegate&&this.delegate.taskDidEnd)try{this.delegate.taskDidEnd(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}}};f.extendClass(D,m);E.prototype={_time:0,_left_time:0,_timer:null,_start_time:0,start:function(){var a=this,b=this._time;if(this._state===m.STARTED)return!1;this._state===m.PAUSED?b=this._left_time:this._left_time=b;this._state=m.STARTED;this._start_time=
(new Date).getTime();a=this;this._timer=setTimeout(function(){a._state=m.STOPPED;if(a.delegate&&a.delegate.taskDidEnd)try{a.delegate.taskDidEnd(a)}catch(b){b.stack&&console.log(b.stack),console.error(b)}},b);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;clearTimeout(this._timer);this._timer=null;this._left_time=this._time;if(this.delegate&&this.delegate.taskDidStop)try{this.delegate.taskDidStop(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}return!0},
pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;this._left_time=this._left_time-(new Date).getTime()+this._start_time;if(this.delegate&&this.delegate.taskDidPause)try{this.delegate.taskDidPause(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}return!0}};f.extendClass(E,m);f.defineClassProperty(E,"state",{set:function(a){f.isNumber(a)&&(this._time=a)}});f.extend(j,{Task:m,Task_PAR:C,Task_SEQ:D,TaskWait:E});h.OS_UNKNOWN=0;h.OS_WINDOWS=1;h.OS_MACOS=2;h.OS_LINUX=
4;h.OS_IOS=5;h.OS_WP7=6;h.OS_BLACK_BERRY=7;h.OS_SYMBIAN=8;h.OS_ANDROID=9;h.OS_MEEGO=10;h.OS_FIREFOX=11;h.SR_UNKNOWN=0;h.SR_QVGA=1;h.SR_WQVGA=2;h.SR_HVGA=4;h.SR_VGA=5;h.SR_WVGA=6;h.SR_FWVGA=7;h.SR_SVGA=8;h.SR_DVGA=9;h.SR_WDVGA=10;h.SR_XGA=11;h.SR_N_HD=12;h.SR_Q_HD=13;h.SR_WXGA=14;h.SR_QXGA=15;h.BROWSER_UNKNOWN=0;h.BROWSER_CHROME=1;h.BROWSER_SAFARI=2;h.BROWSER_OPERA=3;h.BROWSER_FIREFOX=4;h.BROWSER_MSIE=5;h.SS_UNKNOWN=0;h.SS_4_INCH=1;h.SS_7_INCH=2;h.SS_10_INCH=3;h.prototype={os:h.OS_UNKNOWN,browser:h.BROWSER_UNKNOWN,
screenResolution:h.SR_UNKNOWN,screenRatio:0,screenSize:h.SS_UNKNOWN,virtualScreenSize:null,browserDetect:function(){function a(a){for(var c=a.length;c--;){var d=a[c].string,e=a[c].prop;if(d){if(d.match(a[c].subString))return a[c].identity}else if(e)return a[c].identity}}this.browser=a(h._data_browser)||h.BROWSER_UNKNOWN;this.os=a(h._data_OS)||h.OS_UNKNOWN},orientationDetect:function(){this.orientation=o.orientation?o.orientation:o.outerWidth>o.outerHeight?90:0},_getScreenSize:function(){return o.device&&
o.device.width?[o.device.width,o.device.height]:this.os>=h.OS_IOS&&this.os<=h.OS_MEEGO?[o.screen.width,o.screen.height]:[o.outerWidth,o.outerHeight]},screenDetect:function(){var a=o.devicePixelRatio,b;a||(a=1);b=this._getScreenSize();if(b[0]>b[1]){var c=b[0];b[0]=b[1];b[1]=c}this.screenResolution=h._getScreenResolutionCode(b[0],b[1]);this.screenRatio=b[1]/b[0];a*=160;o.device&&o.device.dpi&&(a=device.dpi);b=Math.sqrt(b[0]*b[0]+b[1]*b[1])/a;6>b?this.screenSize=h.SS_4_INCH:9>b?this.screenSize=h.SS_7_INCH:
11>b&&(this.screenSize=h.SS_10_INCH)},getOrientation:function(){return this.orientation},setDeviceId:function(a){f.isString(a)&&(this.screenResolution=h.SR_UNKNOWN,this.deviceId=a,-1!=a.indexOf("wp7")?(this.os=h.OS_WP7,this.screenResolution=h.SR_WVGA,this.screenRatio=1.6,this.screenSize=h.SS_4_INCH):-1!=a.indexOf("iphone")?(this.os=h.OS_IOS,this.screenResolution=h.SR_HVGA,-1!=a.indexOf("_3_2")?this.screenRatio=1.5:-1!=a.indexOf("_16_9")&&(this.screenRatio=16/9),this.screenSize=h.SS_4_INCH):-1!=a.indexOf("ipad")?
(this.os=h.OS_IOS,this.screenResolution=h.SR_XGA,this.screenRatio=4/3,this.screenSize=h.SS_10_INCH):-1!=a.indexOf("ffos")?this.os=h.OS_FIREFOX:-1!=a.indexOf("android")&&(this.os=h.OS_ANDROID,-1!=a.indexOf("_3_2")?this.screenRatio=1.5:-1!=a.indexOf("_16_10")?this.screenRatio=1.6:-1!=a.indexOf("_16_9")&&(this.screenRatio=16/9),-1!=a.indexOf("android_4")?this.screenSize=h.SS_4_INCH:-1!=a.indexOf("android_7")?this.screenSize=h.SS_7_INCH:-1!=a.indexOf("android_10")&&(this.screenSize=h.SS_10_INCH)))},generateDeviceId:function(a){if(a&&
this.deviceId)return this.deviceId;this.orientationDetect();this.screenDetect();a="";switch(this.os){case h.OS_IOS:screenSize=this._getScreenSize();if(320===screenSize[0]||480===screenSize[0])a+="iphone";if(640===screenSize[0]||960===screenSize[0])a+="iphone";if(768===screenSize[0]||1024===screenSize[0])a+="ipad";if(1536===screenSize[0]||2048===screenSize[0])a+="ipad";break;case h.OS_ANDROID:a+="android";break;case h.OS_FIREFOX:a+="ffos";break;case h.OS_WP7:a+="wp7";break;case h.OS_BLACK_BERRY:a+=
"blackberry"}switch(this.screenSize){case h.SS_4_INCH:a+="_3";break;case h.SS_7_INCH:a+="_7";break;case h.SS_10_INCH:a+="_10"}0.1>Math.abs(o.deviceConfiguration.screenRatio-1.5)?a+="_3_2":0.1>Math.abs(o.deviceConfiguration.screenRatio-4/3)?a+="_4_3":0.1>Math.abs(o.deviceConfiguration.screenRatio-1.6)?a+="_16_10":0.1>Math.abs(o.deviceConfiguration.screenRatio-16/9)&&(a+="_16_9");switch(this.orientation){case 90:case -90:a+="_l";break;case 0:case 180:a+="_p"}return a},setOrientation:function(a,b){var c,
d;d=o.innerWidth;var e=o.innerHeight,g;d>e&&(g=e,e=d,d=g);for(c in j.Object._obs)if(d=j.Object._obs[c])d._orientationWillChange&&d._orientationWillChange(a),d.orientationWillChange&&d.orientationWillChange(a);this.targetId&&(c=this.targetId.replace("_p",""),c=c.replace("_l",""),this.targetId=0===a||180===a?c+"_p":c+"_l",this.setActiveStyleSheet(this.targetId));this.orientation=a;this.virtualScreenSize&&cordova&&cordova.exec&&cordova.exec(null,null,"VSD_Application","setAppSize",[{width:this.virtualScreenSize[0],
height:this.virtualScreenSize[1]}]);c=function(){var b,c;for(b in j.Object._obs)(c=j.Object._obs[b])&&c.orientationDidChange&&c.orientationDidChange(a)};b?c.call(this):setTimeout(c,100)},setActiveStyleSheet:function(a){f.setActiveStyleSheet(a)},registerTargetId:function(){}};h._getScreenResolutionCode=function(a,b){a*=o.devicePixelRatio;b*=o.devicePixelRatio;if(240===a&&320===b)return h.SR_QVGA;if(240===a&&400===b)return h.SR_WQVGA;if(320===a&&480===b)return h.SR_HVGA;if(480===a&&640===b)return h.SR_VGA;
if(480===a&&800===b)return h.SR_WVGA;if(320===a&&854===b)return h.SR_WFVGA;if(600===a&&800===b)return h.SR_SVGA;if(640===a&&960===b)return h.SR_DVGA;if(640===a&&1136===b)return h.SR_WDVGA;if(768===a&&1024===b)return h.SR_XGA;if(360===a&&640===b)return h.SR_N_HD;if(540===a&&960===b)return h.SR_Q_HD;if(720===a&&1280===b||768===a&&1280===b||800===a&&1280===b)return h.SR_WXGA;if(1536===a&&2048===b)return h.SR_QXGA};h._estimateScreenSize=function(a){var b=a.width/a.xdpi,a=a.height/a.ydpi,b=Math.sqrt(b*
b+a*a);return 5>b?3:8>b?7:10};h._data_browser="undefined"!=typeof navigator?[{string:navigator.userAgent,subString:"Chrome",identity:h.BROWSER_CHROME},{string:navigator.vendor,subString:"Apple",identity:h.BROWSER_SAFARI,versionSearch:"Version"},{prop:o.opera,identity:h.BROWSER_OPERA,versionSearch:"Version"},{string:navigator.userAgent,subString:"Firefox",identity:h.BROWSER_FIREFOX},{string:navigator.userAgent,subString:"MSIE",identity:h.BROWSER_MSIE,versionSearch:"MSIE"}]:[];h._data_OS="undefined"!=
typeof navigator?[{string:navigator.platform,subString:"Win",identity:h.OS_WINDOWS},{string:navigator.platform,subString:"Mac",identity:h.OS_MACOS},{string:navigator.platform,subString:"Linux",identity:h.OS_LINUX},{string:navigator.userAgent,subString:"iPad|iPhone|iPod",identity:h.OS_IOS},{string:navigator.userAgent,subString:"Android",identity:h.OS_ANDROID},{string:navigator.userAgent,subString:"Firefox",identity:h.OS_FIREFOX}]:[];"undefined"!=typeof o&&!o.deviceConfiguration&&(o.deviceConfiguration=
new h);j.DeviceConfiguration=h;HTTPRequest=function(a){this.parent=j.EventSource;this.parent(a);this.constructor=HTTPRequest;this._headers={};this.__xhrs=[]};HTTPRequest.prototype={_url:"",_method:"GET",_login:"",_password:"",_content_type:"",_headers:null,__xhrs:null,destructor:function(){this.__xhrs.forEach(function(a){if(a&&a.onload)a.onabort()});this._headers=this.__xhrs=null;r.prototype.destructor.call(this)},setHeaders:function(a){if(a)for(var b in a)this._headers[b]=a[b]},send:function(a){var b=
new XMLHttpRequest;try{this._response_xml=this._response_text=null;b.open(this._method,this._url,!0,this._login||null,this._password||null);b.setRequestHeader("Cache-Control","no-cache");b.setRequestHeader("Pragma","no-cache");for(var c in this._headers)b.setRequestHeader(c,this._headers[c]);this._headers={};this._content_type&&b.setRequestHeader("Content-Type",this._content_type);var d=this;b.onabort=function(){b.onload=b.onerror=b.onabort=null;delete b;d.propagate("loaderror",{status:"aborted"})};
b.onerror=function(a){b.onload=b.onerror=b.onabort=null;delete b;d.propagate("loaderror",{status:"failed",response:a})};b.onload=function(){function a(c){d.propagate("loaderror",c);delete b;return!1}b.onload=b.onerror=b.onabort=null;if(4!==b.readyState)return a(xkr.statusText);return 200===b.status?(d._response_text=b.responseText,d._response_xml=b.responseXML,d.propagateChange(),d.propagate("textload",d._response_text),d._response_xml&&d.propagate("xmlload",d._response_xml),delete b,!0):a({status:b.statusText,
response:b.response})};b.send(a);this.__xhrs.push(b)}catch(e){b.onload=b.onerror=b.onabort=null,delete b,this.propagate("loaderror",e)}}};f.extendClass(HTTPRequest,j.EventSource);f.defineClassProperties(HTTPRequest,{url:{set:function(a){f.isString(a)&&(this._url=a)}},method:{set:function(a){"GET"!=a&&"POST"!=a||(this._method=a)}},login:{set:function(a){f.isString(a)&&(this._login=a)}},password:{set:function(a){f.isString(a)&&(this._password=a)}},contentType:{set:function(a){f.isString(a)&&(this._content_type=
a)}},responseText:{get:function(){return this._response_text}},responseXML:{get:function(){return this._response_xml}}});j.HTTPRequest=HTTPRequest;var ba=j.createClass({parent:j.EventSource,_url:"",_clb_param_name:"callback",__index:0,properties:{url:{set:function(a){f.isString(a)&&(this._url=a)}},clbParamName:{set:function(a){f.isString(a)&&(this._clb_param_name=a)}},responseJson:{get:function(){return this._response_json}}},send:function(){var a=this,b="jsonp"+a._id+a.__index++,c=this._clb_param_name+
"="+b,d=a._url,e=d.length-1,d="?"===d[e]?d+c:"-1"!==d.indexOf("?")?d+("&"+c):"/"===d[e]?d.substr(0,e)+"?"+c:d+("?"+c),g=f.importFile(d,null,null,"js"),h=function(){g&&(g.parentElement.removeChild(g),g=u)},j=setTimeout(function(){h();b in o&&delete o[b];a.propagate("loaderror","Impossible to load data")},3E3);o[b]=function(c){clearTimeout(j);h();delete o[b];c&&(c.error?a.propagate("loaderror",c.error):(a._response_json=c,a.outPropertyChange(),a.propagate("jsonload",c)))}}});j.AjaxJSONP=ba;y.prototype=
{_data:null,_model_class:null,_index:null,_value:null,initComponent:function(){this._data=[];this.forEach=Array.prototype.forEach.bind(this._data)},forEach:function(){},item:function(a){if(f.isNumber(a)&&!(0>a||a>this._data.length))return this._data[a]},_instanciateModel:function(a){if(a instanceof k.core.Model)return a;if(a instanceof Object&&this._model_class)try{var b=new this._model_class(a);b.init();return b}catch(c){c.stack&&console.log(c.stack),console.error(c)}return a},add:function(){for(var a=
[],b=0;b<arguments.length;b++)a.push(this._instanciateModel(arguments[b]));this._data.push.apply(this._data,a);this.hasToPropagateChange()&&this.change("add");return this.length},addAtIndex:function(){if(!(2>arguments.length)){for(var a=[],b=1;b<arguments.length;b++)a.push(this._instanciateModel(arguments[b]));this._data.splice.apply(this._data,a);this.hasToPropagateChange()&&this.change("add",{from:a[0],to:a.length-2})}},remove:function(a,b){this._data.remove(a,b);this.hasToPropagateChange()&&this.change("remove",
{from:a,to:b})},removeAll:function(){this._data=[];this._index=-1;this._value=u;this.forEach=Array.prototype.forEach.bind(this._data);this.hasToPropagateChange()&&this.change("removeall")},clear:function(a){var b=0,c=this._data.length;if(a)for(;b<c;b++)k.util.free(this._data[b]);this.removeAll()},indexOf:function(){throw"method not yet implemented";},toJSON:function(){var a=this._toJSON(),b=0,c=this._data.length,d;for(a.data=[];b<c;b++)d=this._data[b],"undefined"!=typeof d&&(d instanceof Date?d='"/Date('+
d.getTime()+')/"':d&&d.toJSON&&(d=d.toJSON()),a.data.push(d));return a},parseData:function(a){function b(a){h._data=[];h.forEach=Array.prototype.forEach.bind(h._data);for(c=0;c<a.length;c++)g=a[c],(e=h._model_class?(new h._model_class).init():f.isArray(g)?(new y).init():f.isUndefined(g)||f.isString(g)||f.isNumber(g)||"boolean"==typeof g||null==g||g instanceof Date?null:(new B).init())?(e.parseData(g),h.add(e)):h.add(g)}var c,d,e,g,h=this;this.stopPropagation();if(f.isArray(a))b(a);else for(d in a)"data"==
d?b(a.data):this._parse_property(d,a[d]);this.change()}};f.extendClass(y,j.Model);f.defineClassProperties(y,{data:{set:function(a){if(!this.__i__)throw"Component not initialized";if(f.isArray(a))this._data=a.slice(),this.forEach=Array.prototype.forEach.bind(this._data);else if(a instanceof y)this._data=a._data.slice(),this.forEach=Array.prototype.forEach.bind(this._data);else return;this.hasToPropagateChange()&&this.change("add")},get:function(){if(!this.__i__)throw"Component not initialized";return this._data.slice()}},
length:{get:function(){if(!this.__i__)throw"Component not initialized";return this._data.length}},modelClass:{set:function(a){f.isFunction(a)&&(this._model_class=a)}},index:{set:function(a){f.isString(a)&&(a=parseInt(a,10));if(f.isNumber(a)&&!(0>a||a>this._data.length))this._index=a=Math.floor(a),this._value=this._data[a],this.propertyChange("value")},get:function(){return this._index}},value:{get:function(){return this._value}}});j.Array=y;t.prototype={__models__:null,registerModel:function(a,b){a&&
b&&(this.__models__[a]&&error.log("Model with the name already registered."),this.__models__[a]=b,b._sync_service_=this)},removeModel:function(a){a&&this.__models__[a]&&delete this.__models__[a]},save:function(){},load:function(){}};f.extendClass(t,j.EventSource);j.DataStorage=t;S.prototype={save:function(a){function b(a){var b,g=c.__models__[a];if(g){try{b=JSON.stringify(g)}catch(f){f.stack&&console.log(f.stack),error.log(f),c.propagate("error",f)}localStorage.setItem(a,b)}}var c=this;if(a)b(a);
else for(a in this.__models__)b(a);c.propagate("save")},load:function(a){function b(a){try{var b=c.__models__[a];if(b){var g=localStorage.getItem(a);b.parseJSON(g)}}catch(f){f.stack&&console.log(f.stack),console.error("LocalStorate.load failed. "+f.toString())}}var c=this;if(a)b(a);else for(a in this.__models__)b(a);c.propagate("load")}};f.extendClass(S,t);j.LocalStorage=S;s.XHR=0;s.JSONP=1;s.prototype={_xhrs:null,_mode:0,_headers:null,_url:"",initComponent:function(){t.prototype.initComponent.call(this)},
destructor:function(){t.prototype.destructor.call(this)},setHeaders:function(a){if(a){this._headers={};for(var b in a)this._headers[b]=a[b]}},save:function(a){function b(a){var b,f=c.__models__[a];if(f){try{b=JSON.stringify(f)}catch(h){h.stack&&console.log(h.stack),error.log(h),c.propagate("error",h)}s.setItem(a,b)}}var c=this;if(a)b(a);else for(a in this.__models__)b(a);c.propagate("save")},load:function(a){this._mode===s.XHR&&this._load_xhr(a);this._mode===s.JSONP&&this._load_jsonp(a)},_load_xhr:function(a){function b(a){try{var b=
c.__models__[a];if(b){var g=c._url+a,h=b.getModelProperties(),j=0;if(h&&h.length)for(var g=g+"?",k=0;k<h.length;k++){var m=h[k],n=b["_"+f.underscore(m)];if(!("id"===m||"modelClass"===m))if(f.isString(n)||f.isNumber(n))j++&&(g+="&"),g+=m+"="+escape(n)}var o=(new HTTPRequest).init();c._xhrs[o.id]=a;o.bind("textload",c,c._process_xhr_result);o.setHeaders(c._headers);o.url=g;o.method="GET";o.contentType="application/json";o.send()}}catch(p){p.stack&&console.log(p.stack),console.error("LocalStorate.load failed. "+
p.toString())}}var c=this;if(a)b(a);else for(a in this.__models__)b(a)},_load_jsonp:function(a){function b(a){try{var b=c.__models__[a];if(b){var g=c._url+a+".json",h=b.getModelProperties(),j=0;if(h&&h.length)for(var g=g+"?",k=0;k<h.length;k++){var m=h[k],o=b["_"+f.underscore(m)];if(!("id"===m||"modelClass"===m))if(f.isString(o)||f.isNumber(o))j++&&(g+="&"),g+=m+"="+escape(o)}var n=(new ba).init();c._xhrs[n.id]=a;n.bind("jsonload",c,c._process_json_result);n.url=g;n.send()}}catch(p){p.stack&&console.log(p.stack),
console.error("LocalStorate.load failed. "+p.toString())}}var c=this;if(a)b(a);else for(a in this.__models__)b(a)},_sync:function(){},_process_xhr_result:function(a){var b=a.data,a=a.src,c=this._xhrs[a.id];a.unbind("textload",this,this._process_xhr_result);k.util.free(a);delete this._xhrs[a.id];if(!b)return console.error("Failed to parse rss document that is null."),!1;if(a=this.__models__[c])a.parseJSON(b),a.change(),this.propagate("load",a)},_process_json_result:function(a){var b=a.data,a=a.src,
c=this._xhrs[a.id];a.unbind("textload",this,this._process_json_result);k.util.free(a);delete this._xhrs[a.id];if(a=this.__models__[c])a.parseData(b),a.change(),this.propagate("load",a)}};k.util.extendClass(s,t);k.util.defineClassProperties(s,{url:{set:function(a){k.util.isString(a)&&(this._url=a)},get:function(){return this._url}},mode:{set:function(a){if(0===a||1===a)this._mode=a}}});k.core.RestStorage=s})(window);
