/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(n,u){function t(){return"vs_id_"+H++}function q(a){this.constructor=j.Object;this._id=i.isString(a)?a:a&&a.id?a.id:t();a&&(this.__config__=i.clone(a))}function I(a,b){var c={},d,e,h,g;for(g in b){d=b[g];if(i.isNumber(d))e={},h="_"+i.underscore(g),d&o.core.Object.PROPERTY_IN&&(e.set=function(a,b){return function(c){this[b]=c;this.propertyChange(a)}}(g,h)),d&o.core.Object.PROPERTY_OUT&&(e.get=function(a){return function(){return this[a]}}(h));else if(i.isString(d)){h=J.exec(d);if(!h||3!=h.length)throw"Unvalid property path: "+
d;e={};e.set=function(a,b){return function(c){this[a][b]=c;this.propertyChange(b)}}(h[1],h[2]);e.get=function(a,b){return function(){return this[a][b]}}(h[1],h[2])}else"object"==typeof d&&(e=d);c[g]=e}i.defineClassProperties(a,c)}function y(a){this.parent=j.Object;this.parent(a);this.constructor=o.core.Model;this.__bindings__={};this.__links__=[]}function D(a,b,c,d){this.spec=a;this.obj=b;this.delay=FORCE_EVENT_PROPAGATION_DELAY?!0:d;i.isFunction(c)?this.func_ptr=c:this.func=c}function s(a){this.parent=
j.Object;this.parent(a);this.constructor=j.EventSource;this.__bindings__={};this.__node_binds__={}}function E(){this.dataflow_node=[];this.dataflow_edges={};this.is_propagating=!1;this._node_link={};this.__shouldnt_propagate__=0}function m(a){this.parent=j.Object;this.parent(a);this.constructor=m}function z(a){this.parent=j.Object;this.parent();this.constructor=z;this._tasksAndParams=[];arguments.length&&this.setTasks(arguments)}function A(a){this.parent=j.Object;this.parent();this.constructor=A;
this._tasksAndParams=[];arguments.length&&this.setTasks(arguments)}function v(a){this.parent=j.Object;this.parent();this.constructor=v;this.time=a}function f(){this.deviceId=this.orientation=null;this.targets={};this.os=f.OS_UNKNOWN;this.browser=f.BROWSER_UNKNOWN;this.screenResolution=f.SR_UNKNOWN;this.screenRatio=0;this.browserDetect()}function B(a){this.parent=o.core.Model;this.parent(a);this.constructor=o.core.Array}function w(a){this.parent=j.EventSource;this.parent(a);this.constructor=o.core.DataStorage;
this.__models__={}}function F(a){this.parent=w;this.parent(a);this.constructor=o.core.LocalStorage}var G=n.document,o=n.vs,i=o.util,j=o.core,H=0;j.createId=t;j.createUniqueId=function(){return"vs_id_"+(new Date).getTime()+""+Math.floor(1E6*Math.random())};q.prototype={_id:"",__i__:!1,__config__:null,init:function(a){if(this.__i__)return this;this._id||(this._id=t());q._obs[this._id]=this;a||this.initComponent();this.__i__=!0;!a&&this.vsdInit&&this.vsdInit();this.__config__&&(this.configure(this.__config__),
delete this.__config__);this.componentDidInitialize&&this.componentDidInitialize();this.initSkin&&(console.warn("Your application shouldn't use initSkin anymore.\nYou should rename by componentDidInitialize."),q.prototype.initSkin=function(){},this.initSkin(),q.prototype.initSkin=u);return this},initComponent:function(){},createId:function(){console.warn("this.createId is deprecated, Use the static method vs.core.createId instead");return t()},configure:function(a){if("object"===typeof a){var b,c,
d,e=!1,h=r[this._id];h&&h.pausePropagation();if(a instanceof y)if((b=this.getPropertyDescriptor("model"))&&b.set)this.model=a,e=!0;else{b=a.getProperties();for(d=0;d<b.length;d++)c=b[d],"id"!==c&&(this[c]=a[c],e=!0)}else if(a)for(c in a)"id"===c||"node"===c||"node_ref"===c||"view"===c||(this[c]=a[c],e=!0);h?(h.restartPropagation(),e&&(this.propertiesDidChange&&this.propertiesDidChange(),h.propagate(this._id))):e&&this.propertiesDidChange&&this.propertiesDidChange()}},getProperties:function(){return!this.constructor._properties_?
[]:this.constructor._properties_.slice()},toJSON:function(){return this._toJSON("{")+"}"},parseJSON:function(a){try{var b=a&&i.parseJSON(a)||{},c;for(c in b)this["_"+c]=void 0}catch(d){console.error("vs.core.Object.parseJSON failed. "+d.toString())}},_toJSON:function(a){var b,c,d,e=this.constructor._properties_,h=0;if(!e)return a;for(var g=0;g<e.length;g++)if(b=e[g],c=this["_"+b],"undefined"!=typeof c){if(null==c)d="null";else if(c instanceof Date)d='"/Date('+c.getTime()+')/"';else if(c.toJSON)d=
c.toJSON();else try{d=JSON.stringify(c)}catch(p){console.warn(p);continue}h++&&(a+=",");a+='"'+b+'":'+d}return a},destructor:function(){this.__i__=!1},propertyChange:function(a){var b=r[this._id];b&&b.propagate(this._id,a)},propagateChange:function(a){this.propertyChange(a)},link:function(a){if(a instanceof o.core.Model)this.__model&&this.__model.unlinkTo(this),this.__model=a,this.__model.linkTo(this),this.configure(this.__model);else throw"vs.core.Object.link; parameter is not a vs.core.Model";},
unlink:function(){if(this.__model){if(this.__model){this.__model.unlinkTo(this);var a=this.__model.getProperties();for(l=a.length,config={};l--;)config[a[l]]=null;this.configure(config)}this.__model=u}},clone:function(a,b){function c(a,b,c){var d=b.__lookupGetter__(a),e=b.__lookupSetter__(a),h=c.__lookupGetter__(a),g=c.__lookupSetter__(a);d&&!h&&c.__defineGetter__(a,d);e&&!g&&c.__defineSetter__(a,e);!e&&!d&&(d=b[a],c[a]=i.isArray(d)?d.slice():b[a])}function d(a,b,c){var d=b.getOwnPropertyDescriptor(a),
e=c.getOwnPropertyDescriptor(a);d&&(d.get||d.set)?e||i.defineProperty(c,a,d):(d=b[a],c[a]=i.isArray(d)?d.slice():b[a])}function e(a,b,c){var d=b.__lookupGetter__(a),e=b.__lookupSetter__(a),h=c.__lookupSetter__(a);if(e||d)h?c[a]=b["_"+a]:c["_"+a]=b["_"+a]}function h(a,b,c){var d=b.getOwnPropertyDescriptor(a),e=c.getOwnPropertyDescriptor(a);if(d&&e&&(d.get||d.set))e.set?c[a]=b["_"+a]:c["_"+a]=b["_"+a]}var g,p;b||(b={});if(b[this._id])return b[this._id];a||(a={});a.id||(a.id=t());if(i.isFunction(this.constructor))g=
new this.constructor(a);else return console.warn("impossible to clone this object."),null;b[this._id]=g;var f=Object.defineProperty?d:c,j=Object.defineProperty?h:e;for(p in this)this.hasOwnProperty(p)&&(i.isFunction(this[p])&&!i.isFunction(g[p])?g[p]=this[p]:f(p,this,g));g.__i__=!1;g.init();this._clone(g,a,b);for(p in this)"id"==p||"_id"==p||this.hasOwnProperty(p)&&j(p,this,g);this.__model&&(b&&b[this.__model._id]?g.link(b[this.__model._id]):g.link(this.__model));return g},_clone:function(){},getOwnPropertyDescriptor:function(a){return Object.getOwnPropertyDescriptor(this,
a)},getPropertyDescriptor:function(a){function b(a,c){if(!a)return null;var h=Object.getPrototypeOf(a);if(!h)return null;var g=Object.getOwnPropertyDescriptor(h,c);return g?g:b(h,c)}var c=Object.getOwnPropertyDescriptor(this,a);return c?c:b(this,a)},_super:function(){var a=this._super.caller._super_func_;a&&a.apply(this,arguments)}};i.defineClassProperty(q,"id",{get:function(){return this._id}});q._obs={};j.Object=q;var K=n.Object.prototype.constructor;o.core.Object.PROPERTY_IN=1;o.core.Object.PROPERTY_OUT=
2;o.core.Object.PROPERTY_IN_OUT=3;var J=/(\w+[.\w+]*)#(\w+)/;j.createClass=function(a){var b=null,c={},d=o.core.Object,e={},b=function(){this.parent=b.__spec.parent;b.__spec&&b.__spec._constructor?b.__spec._constructor.apply(this,arguments):b.__spec&&b.__spec.parent&&this.parent.apply(this,arguments);this.constructor=b};a&&a.parent&&(d=a.parent,delete a.parent);a&&a.properties&&(e=a.properties,delete a.properties);c.parent=d;a&&a.constructor&&a.constructor!==K&&(c._constructor=a.constructor,c._constructor._super_func_=
d);b.__spec=c;a&&(b.prototype=a,a.constructor=b);d.prototype&&i.extendClass(b,d);if(a)for(key in a)if(a.hasOwnProperty(key)){var c=a[key],h=d.prototype[key];i.isFunction(c)&&i.isFunction(h)&&(c._super_func_=h)}I(b,e);return b};y.prototype={__bindings__:null,__links__:null,__should_propagate_changes__:!0,_sync_service_:null,destructor:function(){j.Object.prototype.destructor.call(this);this._sync_service_&&this._sync_service_.removeModel(this);for(var a in this.__bindings__){var b=this.__bindings__[a];
if(b)for(var c=void 0,d=b.length;d--;)c=b[d],i.free(c);delete this.__bindings__[a]}delete this.__bindings__},bindChange:function(a,b,c){b&&(a=a||"change",c=new D(a,b,c,!1),b=this.__bindings__[a],b||(b=[],this.__bindings__[a]=b),b.push(c))},unbindChange:function(a,b,c){a||(a="change");var d=this.__bindings__[a];if(d)for(var e,h=0;h<d.length;)e=d[h],e.spec===a?e.obj===b?i.isString(c)||i.isFunction(c)?e.func===c||e.func_ptr===c?(d.remove(h),i.free(e)):h++:(d.remove(h),i.free(e)):h++:h++},stopPropagation:function(){this.__should_propagate_changes__=
!1},hasToPropagateChange:function(){return this.__should_propagate_changes__},change:function(a,b){var c;this.__should_propagate_changes__=!0;c=new C(this,a||"change:"+a);try{if(!b)for(var d=this.__links__.length;d--;)this.__links__[d].configure(this);d=function(a){if(a)for(var b=a.length,d;b--;)if(d=a[b],d.func_ptr)d.func_ptr.call(d.obj,c);else if(d.func)d.obj[d.func](c);else d.obj.notify(c)};a&&"change"!=a&&d(this.__bindings__[a]);d(this.__bindings__.change)}catch(e){console.error(e)}},linkTo:function(a){a instanceof
o.core.Object&&-1===this.__links__.indexOf(a)&&this.__links__.push(a)},unlinkTo:function(a){a instanceof o.core.Object&&this.__links__.remove(a)},propertyChange:function(a){var b=r[this._id];b&&b.propagate(this._id,a);if(this.__should_propagate_changes__){b=this.__links__.length;if(a)for(;b--;)this.__links__[b][a]=this[a];else for(;b--;)this.__links__[b].configure(this);this.change(null,!0)}}};i.extendClass(y,j.Object);j.Model=y;FORCE_EVENT_PROPAGATION_DELAY=!1;EVENT_SUPPORT_TOUCH="createTouch"in
G;if(!EVENT_SUPPORT_TOUCH&&(-1!==n.navigator.userAgent.indexOf("Android")||-1!==n.navigator.userAgent.indexOf("BlackBerry")))EVENT_SUPPORT_TOUCH=!0;EVENT_SUPPORT_TOUCH?(j.POINTER_START="touchstart",j.POINTER_MOVE="touchmove",j.POINTER_END="touchend",j.POINTER_CANCEL="touchcancel"):(j.POINTER_START="mousedown",j.POINTER_MOVE="mousemove",j.POINTER_END="mouseup",j.POINTER_CANCEL="mouseup");var C=function(a,b,c){this.srcTarget=this.src=a;this.type=b;this.data=c};C.prototype={src:null,srcTarget:null,type:"",
data:null,destructor:function(){delete this.src;delete this.srcTarget;delete this.type;delete this.data}};j.Event=C;j.FORCE_EVENT_PROPAGATION_DELAY=FORCE_EVENT_PROPAGATION_DELAY;j.EVENT_SUPPORT_TOUCH=EVENT_SUPPORT_TOUCH;D.prototype.destructor=function(){delete this.spec;delete this.obj;delete this.delay;delete this.func_ptr;delete this.func};s.prototype={__bindings__:null,__node_binds__:null,destructor:function(){var a,b,c;for(a in this.__bindings__)if(b=this.__bindings__[a]){for(;b.length;)c=b.pop(),
i.free(c);delete this.__bindings__[a]}delete this.__bindings__;for(a in this.__node_binds__)if(c=this.__node_binds__[a],"undefined"===typeof c)console.warn("vs.core.Object.destructor, no bind <"+a+" exists.");else for(b=0;b<c.length;b++)data=c[b],data.n.removeEventListener(event,data.h);delete this.__node_binds__;q.prototype.destructor.call(this)},_clone:function(a,b){q.prototype._clone.call(this,a,b);a.__bindings__={};a.__node_binds__={}},bind:function(a,b,c,d){if(a&&b)return b=new D(a,b,c,d),c=
this.__bindings__[a],c||(c=[],this.__bindings__[a]=c),c.push(b),b},unbind:function(a,b,c){var d=this.__bindings__[a],e=0,h;if(d)for(;e<d.length;)h=d[e],h.spec===a?h.obj===b?i.isString(c)||i.isFunction(c)?h.func===c||h.func_ptr===c?(d.remove(e),i.free(h)):e++:(d.remove(e),i.free(h)):e++:e++},propagate:function(a,b,c,d){var e=this.__bindings__[a],h,g,f;if(e){h=new C(this,a,b);c&&(h.srcTarget=c);a=e.length;try{for(f=function(){if(g.func_ptr)g.func_ptr.call(g.obj,h);else if(g.func)g.obj[g.func](h);else g.obj.notify(h)};a--;)g=
e[a],d||g.delay?n.setTimeout(f,0):f.call(this)}catch(i){console.error(i)}}else this.__parent&&(c||(c=this),this.__parent.propagate(a,b,c))},notify:function(a){this.propagate(a.type,a.data)},nodeBind:function(a,b,c,d){if(a&&i.isString(b)){var e=this,h=null,g=null,f,j;if("undefined"===typeof c)c="notify";else if(i.isString(c)){if(!i.isFunction(this[c])){console.warn("vs.core.Object.nodeBind, unknown function named: "+c);return}}else if(i.isFunction(c))h=c,c=h.name;else{console.error("vs.core.Object.nodeBind, invalid func parameter");
return}g=!d||d===k.ANY_MASK?function(a){try{a.src=a.currentTarget,a.data=a,h||(h=e[c]),h.call(e,a)}catch(b){console.error(b)}}:function(a){a.stopPropagation();try{if(d||!a.altKey&&!a.ctrlKey&&!a.shiftKey&&!a.metaKey)d===k.ALT&&!a.altKey||d===k.CTRL&&!a.ctrlKey||d===k.SHIFT&&!a.shiftKey||d===k.META&&!a.metaKey||(a.src=a.currentTarget,a.data=a,h||(h=e[c]),h.call(e,a))}catch(b){console.error(b)}};j=b+c;this.__node_binds__?(f=this.__node_binds__[j],"undefined"===typeof f&&(f=[],this.__node_binds__[j]=
f),f.push({n:a,h:g}),a.addEventListener(b,g,!1)):console.error("nodeBind impossible")}},nodeUnbind:function(a,b,c){if(a&&i.isString(b)){var d,e;if("undefined"===typeof c)c="notify";else if(i.isString(c)){if(!i.isFunction(this[c])){console.warn("vs.core.Object.nodeUnbind, unknown function named: "+c);return}}else if(i.isFunction(c))c=c.name;else{console.error("vs.core.Object.nodeBind, invalid func parameter");return}d=this.__node_binds__[b+c];if("undefined"===typeof d)console.warn("vs.core.Object.nodeUnbind, no bind <"+
b+","+c+" exists.");else{for(c=0;c<d.length;)e=d[c],e.n===a?(a.removeEventListener(b,e.h),d.remove(c)):c++;a._object_=u}}}};i.extendClass(s,q);j.EventSource=s;var k=new s("__KEYBOARD__");k._handler_set_down=!1;k._handler_set_up=!1;k.managePrevent=function(a,b){var c=this.__bindings__[a],d,e;if(c)for(d=0;d<c.length;d++)if(e=c[d],e.prevent){b.preventDefault();break}};k.KEY_UP=1E3;k.ESC=27;k.ENTER=13;k.SPACE=32;k.BACKSPACE=8;k.SHIFT=16;k.CTRL=17;k.ALT=18;k.NUMLOCK=144;k.LEFT_ARROW=37;k.UP_ARROW=38;k.RIGHT_ARROW=
39;k.DOWN_ARROW=40;k.L=76;k.S=83;k.Z=90;k.META=2E3;k.ANY_MASK=3E3;k.UNDO=256;k.REDO=257;k.SAVE=258;j.KEYBOARD=k;j.KEYBOARD.bind=function(a,b,c,d){var b=s.prototype.bind.call(this,a,b,c),e=this;d&&(b.prevent=!0);a>k.KEY_UP?this._handler_set_up||(G.documentElement.addEventListener("keyup",function(a){e.managePrevent(a.keyCode,a);e.propagate(a.keyCode+k.KEY_UP,a)},!1),this._handler_set_up=!0):this._handler_set_down||(G.documentElement.addEventListener("keydown",function(a){(a.ctrlKey||a.metaKey)&&!a.shiftKey&&
a.keyCode===k.Z?(e.propagate(k.UNDO),a.preventDefault()):(a.ctrlKey||a.metaKey)&&a.shiftKey&&a.keyCode===k.Z?(e.propagate(k.REDO),a.preventDefault()):(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode===k.S?(e.propagate(k.SAVE),a.preventDefault()):(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode?(e.managePrevent(k.META+a.keyCode,a),e.propagate(k.META+a.keyCode)):(e.managePrevent(a.keyCode,a),e.propagate(a.keyCode,a))},!1),this._handler_set_down=!0)};var x=function(a){this.parent=j.EventSource;this.parent(t());
this.constructor=x;this.owner=a;this._list_of_state={};this._list_input=[];this._list_output=[];this._current_state=this._initial_state="";this._inputs={};this._output_action={}};x.prototype={destructor:function(){delete this._list_of_state;this.owner=u;delete this._list_of_state;delete this._list_input;delete this._list_output;delete this._inputs;delete this._output_action;j.EventSource.prototype.destructor.call(this)},_clone:function(a,b){s.prototype._clone.call(this,a,b);a.owner=a.__config__.owner;
a._current_state="";a._inputs={};a._output_action={}},initWithData:function(a,b,c,d){if(a&&b&&c&&d){for(var e=0;e<a.length;e++)this.addState(a[e]);for(e=0;e<b.length;e++)this.addInput(b[e]);for(e=0;e<c.length;e++)this.addOutput(c[e]);for(e=0;e<d.length;e++)this.addTransition(d[e].from,d[e].to,d[e].on,d[e].output)}},initWithMatrix:function(a){for(var b=1;b<a[0].length;b++)this.addState(a[0][b]);for(b=1;b<a.length;b++)for(var c=a[b][0],d=1;d<a[0].length;d++){var e=a[0][d],h=a[b][d];h&&(h=h.split("/"),
h[0]&&this.addInput(h[0]),h[1]&&this.addOutput(h[1]),this.addTransition(c,e,h[0],h[1]))}},addInput:function(a){a&&!this.existInput(a)&&this._list_input.push(a)},getInputs:function(){return this._list_input.slice()},existInput:function(a){return!a?void 0:-1<this._list_input.findItem(a)},addOutput:function(a){a&&!this.existOutput(a)&&this._list_output.push(a)},getOutputs:function(){return this._list_output.slice()},existOutput:function(a){return!a?void 0:-1<this._list_output.findItem(a)},addState:function(a){if(!a||
this.existState(a))return!1;this._list_of_state[a]={transitionEvents:{}};return!0},removeState:function(a){if(!a||!this.existState(a))return!1;delete this._list_of_state[a];return!0},renameState:function(a,b){if(!a||!this.existState(a)||!b||this.existState(b))return!1;this._list_of_state[b]=this._list_of_state[a];delete this._list_of_state[a];this._initial_state===a&&(this._initial_state=b);for(var c in this._list_of_state){var d=this._list_of_state[c];if(null!==d)for(var e in d.transitionEvents){var h=
d.transitionEvents[e];h.to===a&&(h.to=b)}}return!0},getListState:function(){var a=[],b;for(b in this._list_of_state)a.push(b);return a},existState:function(a){return!a?!1:this._list_of_state[a]?!0:!1},addTransition:function(a,b,c,d){a&&this.existState(a)&&b&&this.existState(b)&&c&&this.existInput(c)&&(this._list_of_state[a].transitionEvents[c]={on:c,to:b,output:d})},removeTransitionFrom:function(a,b){if(a&&this.existState(a)&&b&&this.existInput(b)){var c=this._list_of_state[a];c.transitionEvents[b]&&
delete c.transitionEvents[b]}},removeTransitionTo:function(a,b){if(a&&this.existState(a)&&b&&this.existInput(b))for(var c in this._list_of_state){var d=this._list_of_state[c],e=d.transitionEvents[b];e&&e.to===a&&delete d.transitionEvents[b]}},getTransionsToState:function(a){if(this.existState(a)){var b=[],c;for(c in this._list_of_state){var d=this._list_of_state[c];if(null!==d)for(var e in d.transitionEvents){var h=d.transitionEvents[e];h.to===a&&(h=i.clone(h),h.from=c,b.push(h))}}return b}},getTransionsFromState:function(a){if(this.existState(a)){var b=
[],c=this._list_of_state[a];if(null===c)return null;for(var d in c.transitionEvents){var e=i.clone(c.transitionEvents[d]);e.from=a;b.push(e)}return b}},switchStates:function(a,b){if(!(a===b||!this.existState(a)||!this.existState(b))){for(var c=this.getTransionsToState(a),d=this.getTransionsFromState(a),e=this.getTransionsToState(b),h=this.getTransionsFromState(b),g=0;g<c.length;){var f=c[g];f.from===b?c.remove(f):g++}for(g=0;g<d.length;)f=d[g],f.to===b?d.remove(f):g++;for(g=0;g<c.length;g++)f=c[g],
this.removeTransitionFrom(f.from,f.on);for(g=0;g<d.length;g++)f=d[g],this.removeTransitionFrom(f.from,f.on);for(g=0;g<e.length;g++)f=e[g],this.removeTransitionFrom(f.from,f.on);for(g=0;g<h.length;g++)f=h[g],this.removeTransitionFrom(f.from,f.on);for(g=0;g<c.length;g++){var f=c[g],i=f.from===b?a:f.from;this.addTransition(i,b,f.on,f.output)}for(g=0;g<d.length;g++)f=d[g],c=f.from===b?a:f.to,this.addTransition(b,c,f.on,f.output);for(g=0;g<e.length;g++)f=e[g],i=f.from===a?b:f.from,this.addTransition(i,
a,f.on,f.output);for(g=0;g<h.length;g++)f=h[g],c=f.to===a?b:f.to,this.addTransition(a,c,f.on,f.output);this._initial_state===a?this._initial_state=b:this._initial_state===b&&(this._initial_state=a)}},setInput:function(a,b,c){if(a&&b&&c){if(b.bind)b.bind(c,this);else if(b.addEventListener)this.nodeBind(b,c);else return;var d=this._inputs[b];d||(d=[],this._inputs[b]=d);d.push([c,a,b])}},setOutput:function(a,b){a&&b&&(this._output_action[a]=b)},activate:function(){if(!this._initial_state||!this._list_of_state[this._initial_state])return!1;
this.goTo(this._initial_state);return!0},goTo:function(a,b,c){if(!this.existState(a))return!1;this._current_state=a;if(b&&this._output_action[b])if(a=this._output_action[b],a instanceof Function)a.call(this.owner,c);else if(i.isString(a))this.owner[this._output_action[b]](c);return!0},clear:function(){this._list_of_state={};delete this._list_input;delete this._list_output;this._list_input=[];this._list_output=[];this._initial_state="";for(var a in this._inputs)for(var b=this._inputs[a],c=0;c<b.length;c++){var d=
b[c][2],e=b[c][0];d.bind?d.unbind(e,this):d.addEventListener&&this.nodeUnbind(d,e)}this._current_state=""},notify:function(a){var b=this._inputs[a.src];if(b)for(var c=0;c<b.length;c++)a.type===b[c][0]&&this._list_of_state[this._current_state]&&this.fsmNotify(b[c][1],a.data)},fsmNotify:function(a,b,c){if(this._list_of_state[this._current_state]){var d=this._list_of_state[this._current_state].transitionEvents[a];if(!d)return!1;this.goTo(d.to,d.output,{on:a,data:b},c);return!0}}};i.extendClass(x,s);
i.defineClassProperty(x,"initialState",{set:function(a){a?this.existState(a)&&(this._initial_state=a):this._initial_state=u},get:function(){return this._initial_state}});j.Fsm=x;E.prototype={propagate_values:function(a){var b=this.dataflow_edges[a],c,d,e,f,g,j;if(b){d=q._obs[a];for(a=0;a<b.length;a++)if(g=q._obs[b[a][0]])if(j=b[a][2]){for(c=0;c<j.length;c++){e=j[c][0];f=j[c][1];var k=d.getPropertyDescriptor(e),m=g.getPropertyDescriptor(f);if(!k||!k.get)if(e="_"+i.underscore(e),!d.hasOwnProperty(e))continue;
if(!m||!m.set)if(f="_"+i.underscore(f),!g.hasOwnProperty(f))continue;g[f]=d[e]}g.__should__call__has__changed__=!0}}},propagate:function(a){if(!this.is_propagating&&!this.__shouldnt_propagate__){this.is_propagating=!0;var b=0;if(a){for(;b<this.dataflow_node.length&&this.dataflow_node[b]!==a;)b++;b<this.dataflow_node.length-1&&(this.propagate_values(a),b++)}for(;b<this.dataflow_node.length;b++)if(a=q._obs[this.dataflow_node[b]])a.__should__call__has__changed__&&a.propertiesDidChange&&(a.propertiesDidChange(),
a.__should__call__has__changed__=!1),this.propagate_values(a.id);this.is_propagating=!1}},build:function(){if(this._ref_node&&this._ref_edges){var a=[],b,c,d,e,f,g;for(b=0;b<this._ref_node.length;b++)c=this._ref_node[b],this._node_link[c]&&a.push(this._node_link[c]);this.dataflow_node=a;a={};for(c in this._ref_edges)if(this._node_link[c]){d=this._ref_edges[c];e=[];for(b=0;b<d.length;b++)f=d[b],g=[3],this._node_link[f[0]]&&(g[0]=this._node_link[f[0]],g[1]=f[1],g[2]=f[2].slice(),e.push(g));a[this._node_link[c]]=
e}this.dataflow_edges=a}},register_ref_node:function(a){a&&(this._ref_node=a)},register_ref_edges:function(a){a&&(this._ref_edges=a)},pausePropagation:function(){this.__shouldnt_propagate__++},restartPropagation:function(){this.__shouldnt_propagate__--;0>this.__shouldnt_propagate__&&(this.__shouldnt_propagate__=0)}};var r={};n._df_node_register=function(a,b,c){if(a&&b&&c&&(a=r[a]))a._node_link[b]=c,r[c]=a};n._df_create=function(a,b){var c=new E;c.ref=b;return r[a]=c};n._df_register_ref_node=function(a,
b){if(a&&b){var c=r[a];c&&c.register_ref_node(b)}};n._df_register_ref_edges=function(a,b){if(a&&b){var c=r[a];c&&c.register_ref_edges(b)}};n._df_build=function(a){a&&(a=r[a])&&a.build()};j.DataFlow=E;m.STARTED=1;m.STOPPED=0;m.PAUSED=2;m.prototype={delegate:null,_state:m.STOPPED,start:function(){},stop:function(){},pause:function(){}};i.extendClass(m,j.Object);i.defineClassProperty(m,"state",{get:function(){return this._state}});z.prototype={_tasksAndParams:null,_tasksWillEnded:null,setTasks:function(a){if(this._state!==
m.STOPPED)return!1;var b,c,d,e;this._tasksAndParams=[];for(b=0;b<a.length;b++)if(c=a[b])d=e=null,i.isArray(c)?1===c.length?d=c[0]:2===c.length&&(d=c[0],e=c[1]):(d=c,e=null),d?!d.start||!d.stop||!d.pause?console.warn("Invalid task: "+d.toString()):this._tasksAndParams.push([d,e]):console.warn("Undefined task")},start:function(a){if(this._state===m.STARTED)return!1;this._tasksWillEnded=this._tasksAndParams.length;this._state=m.STARTED;var b,c;for(c=0;c<this._tasksAndParams.length;c++)b=this._tasksAndParams[c],
b[0].delegate=this,b[0].start(b[1]?b[1]:a);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;var a,b;for(b=0;b<this._tasksAndParams.length;b++)a=this._tasksAndParams[b],a[0].stop();return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;var a,b;for(b=0;b<this._tasksAndParams.length;b++)a=this._tasksAndParams[b],a[0].pause();return!0},taskDidStop:function(){this._state=m.STOPPED;this._tasksWillEnded--;0===this._tasksWillEnded&&this.delegate&&
this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this)},taskDidPause:function(){this._state=m.STOPPED;this._tasksWillEnded--;0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this)},taskDidEnd:function(){this._state=m.STOPPED;this._tasksWillEnded--;0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this)}};i.extendClass(z,j.Object);A.prototype={_tasksAndParams:null,_nextTaskToStart:0,_startParam:null,setTasks:function(a){if(this._state!==
m.STOPPED)return!1;var b,c,d,e;this._tasksAndParams=[];for(b=0;b<a.length;b++)if(c=a[b])d=e=null,i.isArray(c)?1===c.length?d=c[0]:2===c.length&&(d=c[0],e=c[1]):(d=c,e=null),d?!d.start||!d.stop||!d.pause?console.warn("Invalid task: "+d.toString()):this._tasksAndParams.push([d,e]):console.warn("Undefined task")},start:function(a){if(this._state===m.STARTED)return!1;this._state=m.STARTED;this._startParam=a;var b=this._tasksAndParams[this._nextTaskToStart];if(!b)return!1;this._nextTaskToStart++;b[0].delegate=
this;b[0].start(b[1]?b[1]:a);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;var a=this._tasksAndParams[this._nextTaskToStart-1];if(!a)return!1;this._nextTaskToStart=0;a[0].stop();return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;var a=this._tasksAndParams[this._nextTaskToStart-1];if(!a)return!1;a[0].pause();return!0},taskDidStop:function(){this._state=m.STOPPED;0===this._nextTaskToStart&&(this._nextTaskToStart-=1);this.delegate&&
this.delegate.taskDidStop&&this.delegate.taskDidStop(this)},taskDidPause:function(){this._state=m.PAUSED;this._nextTaskToStart-=1;this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this)},taskDidEnd:function(){this._state=m.STOPPED;this._nextTaskToStart<this._tasksAndParams.length?this.start(this._startParam):(this._nextTaskToStart=0,this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this))}};i.extendClass(A,j.Object);v.prototype={_time:0,_left_time:0,_timer:null,
_start_time:0,start:function(){var a=this,b=this._time;if(this._state===m.STARTED)return!1;this._state===m.PAUSED?b=this._left_time:this._left_time=b;this._state=m.STARTED;this._start_time=(new Date).getTime();a=this;this._timer=setTimeout(function(){a._state=m.STOPPED;a.delegate&&a.delegate.taskDidEnd&&a.delegate.taskDidEnd(a)},b);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;clearTimeout(this._timer);this._timer=null;this._left_time=this._time;this.delegate&&
this.delegate.taskDidStop&&this.delegate.taskDidStop(this);return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;this._left_time=this._left_time-(new Date).getTime()+this._start_time;this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this);return!0}};i.extendClass(v,j.Object);i.defineClassProperty(v,"state",{set:function(a){i.isNumber(a)&&(this._time=a)}});i.extend(j,{Task:m,Task_PAR:z,Task_SEQ:A,TaskWait:v});f.OS_UNKNOWN=0;f.OS_WINDOWS=1;f.OS_MACOS=
2;f.OS_LINUX=4;f.OS_IOS=5;f.OS_WP7=6;f.OS_BLACK_BERRY=7;f.OS_SYMBIAN=8;f.OS_ANDROID=9;f.OS_MEEGO=10;f.SR_UNKNOWN=0;f.SR_QVGA=1;f.SR_WQVGA=2;f.SR_HVGA=4;f.SR_VGA=5;f.SR_WVGA=6;f.SR_FWVGA=7;f.SR_SVGA=8;f.SR_XGA=9;f.SR_N_HD=10;f.SR_Q_HD=11;f.SR_WXGA=12;f.BROWSER_UNKNOWN=0;f.BROWSER_CHROME=1;f.BROWSER_SAFARI=2;f.BROWSER_OPERA=3;f.BROWSER_FIREFOX=4;f.BROWSER_MSIE=5;f.prototype={browserDetect:function(){function a(a){for(var c=a.length;c--;){var d=a[c].string,e=a[c].prop;this.versionSearchString=a[c].versionSearch||
a[c].identity;if(d){if(d.match(a[c].subString))return a[c].identity}else if(e)return a[c].identity}}this.browser=a(f._data_browser)||f.BROWSER_UNKNOWN;this.os=a(f._data_OS)||f.OS_UNKNOWN},getOrientation:function(){return this.orientation},setDeviceId:function(a){if(i.isString(a))if(this.deviceId=a,-1!=a.indexOf("wp7"))this.os=f.OS_WP7,this.screenResolution=f.SR_WVGA,this.screenRatio=1.6;else if(-1!=a.indexOf("iphone"))this.os=f.OS_IOS,this.screenResolution=f.SR_HVGA,this.screenRatio=1.5;else if(-1!=
a.indexOf("ipad"))this.os=f.OS_IOS,this.screenResolution=f.SR_XGA,this.screenRatio=4/3;else if(-1!=a.indexOf("nokia_s3"))this.os=f.OS_SYMBIAN,this.screenResolution=f.SR_N_HD,this.screenRatio=4/3;else if(-1!=a.indexOf("android")){this.os=f.OS_ANDROID;-1!=a.indexOf("_3_2")?this.screenRatio=1.5:-1!=a.indexOf("_16_10")?this.screenRatio=1.6:-1!=a.indexOf("_16_9")&&(this.screenRatio=16/9);var a=n.screen.width,b=n.screen.height;a>b&&(a=n.screen.height,b=n.screen.width);this.screenResolution=f._getScreenResolutionCode(a,
b)}else-1!=a.indexOf("blackberry")&&(this.os=f.OS_BLACK_BERRY,a.indexOf("_4_3")?this.screenRatio=4/3:a.indexOf("_3_2")?this.screenRatio=1.5:a.indexOf("_16_10")&&(this.screenRatio=1.6),a=n.screen.width,b=n.screen.height,this.screenResolution=f._getScreenResolutionCode(a,b))},setOrientation:function(a,b){var c,d,e;e=n.innerWidth;var f=n.innerHeight,g;if(this.orientation!==a){e>f&&(g=f,f=e,e=g);for(d in j.Object._obs)if(e=j.Object._obs[d])e._orientationWillChange&&e._orientationWillChange(a),e.orientationWillChange&&
e.orientationWillChange(a);for(c in this.targets)if(d=this.targets[c],d.device===this.deviceId&&(!(0!==a&&180!==a||-1===c.indexOf("_p"))||!(90!==a&&-90!==a||-1===c.indexOf("_l"))))return this.setActiveStyleSheet(c),this.orientation=a,d=function(){var b,c;for(b in j.Object._obs)(c=j.Object._obs[b])&&c.orientationDidChange&&c.orientationDidChange(a)},b?d.call(this):setTimeout(d,100),c}},setActiveStyleSheet:function(a){i.setActiveStyleSheet(a);n._current_platform_id=a},registerTargetId:function(a,b){this.targets[a]=
b}};f._getScreenResolutionCode=function(a,b){if(240===a&&320===b)return f.SR_QVGA;if(240===a&&400===b)return f.SR_WQVGA;if(320===a&&480===b)return f.SR_HVGA;if(480===a&&640===b)return f.SR_VGA;if(480===a&&800===b)return f.SR_WVGA;if(320===a&&854===b)return f.SR_WFVGA;if(600===a&&800===b)return f.SR_SVGA;if(768===a&&1024===b)return f.SR_XGA;if(360===a&&640===b)return f.SR_N_HD;if(540===a&&960===b)return f.SR_Q_HD;if(800===a&&1280===b)return f.SR_WXGA};f._estimateScreenSize=function(a){var b=a.width/
a.xdpi,a=a.height/a.ydpi,b=Math.sqrt(b*b+a*a);return 5>b?3:8>b?7:10};f._data_browser=[{string:navigator.userAgent,subString:"Chrome",identity:f.BROWSER_CHROME},{string:navigator.vendor,subString:"Apple",identity:f.BROWSER_SAFARI,versionSearch:"Version"},{prop:n.opera,identity:f.BROWSER_OPERA,versionSearch:"Version"},{string:navigator.userAgent,subString:"Firefox",identity:f.BROWSER_FIREFOX},{string:navigator.userAgent,subString:"MSIE",identity:f.BROWSER_MSIE,versionSearch:"MSIE"}];f._data_OS=[{string:navigator.platform,
subString:"Win",identity:f.OS_WINDOWS},{string:navigator.platform,subString:"Mac",identity:f.OS_MACOS},{string:navigator.userAgent,subString:"iPad|iPhone|iPod",identity:f.OS_IOS},{string:navigator.userAgent,subString:"Android",identity:f.OS_ANDROID},{string:navigator.platform,subString:"Linux",identity:f.OS_LINUX}];"undefined"==typeof n.deviceConfiguration&&(n.deviceConfiguration=new f);j.DeviceConfiguration=f;HTTPRequest=function(a){this.parent=j.EventSource;this.parent(a);this.constructor=HTTPRequest};
HTTPRequest.prototype={_url:"",_method:"GET",_login:"",_password:"",_content_type:"",send:function(a){var b=new XMLHttpRequest;this._response_xml=this._response_text=null;b.open(this._method,this._url,!0,this._login||null,this._password||null);b.setRequestHeader("Cache-Control","no-cache");b.setRequestHeader("Pragma","no-cache");this._content_type&&b.setRequestHeader("Content-Type",this._content_type);var c=this;b.onreadystatechange=function(){if(4===b.readyState)if(200===b.status)if(b.responseText)c._response_text=
b.responseText,c._response_xml=b.responseXML,c.propagateChange(),c.propagate("textload",c._response_text),c.propagate("xmlload",c._response_xml);else return c.propagate("loaderror","file not found."),!1;else return c.propagate("loaderror",b.status),!1};b.send(a)}};i.extendClass(HTTPRequest,j.EventSource);i.defineClassProperties(HTTPRequest,{url:{set:function(a){i.isString(a)&&(this._url=a)}},method:{set:function(a){"GET"!=a||"POST"!=a||(this._method=a)}},login:{set:function(a){i.isString(a)&&(this._login=
a)}},password:{set:function(a){i.isString(a)&&(this._password=a)}},contentType:{set:function(a){i.isString(a)&&(this._content_type=a)}},responseText:{get:function(){return this._response_text}},responseXML:{get:function(){return this._response_xml}}});j.HTTPRequest=HTTPRequest;B.prototype={_data:null,_model_class:null,initComponent:function(){this._data=[]},item:function(a){return this._data[a]},_instanciateModel:function(a){if(a instanceof o.core.Model)return a;if(a instanceof Object&&this._model_class)try{var b=
new this._model_class(a);b.init();return b}catch(c){console.error(c.toString())}return a},add:function(){for(var a=[],b=0;b<arguments.length;b++)a.push(this._instanciateModel(arguments[b]));this._data.push.apply(this._data,a);this.hasToPropagateChange()&&this.change("add");return this.length},addAtIndex:function(){if(!(2>arguments.length)){for(var a=[],b=1;b<arguments.length;b++)a.push(this._instanciateModel(arguments[b]));this._data.splice.apply(this._data,a);this.hasToPropagateChange()&&this.change("add",
a[0],a.length-2)}},remove:function(a,b){this._data.remove(a,b);this.hasToPropagateChange()&&this.change("remove",a,b)},removeAll:function(){this._data=[];this.hasToPropagateChange()&&this.change("removeall")},indexOf:function(){throw"method not yet implemented";},toJSON:function(){for(var a=this._toJSON("{"),b=0,c,a=a+', "data": [';b<this._data.length;b++)if(c=this._data[b])a=c.toJSON?a+c.toJSON():a+JSON.stringify(c),b<this._data.length-1&&(a+=",");return a+"]}"},parseJSON:function(a){try{var b=a&&
i.parseJSON(a)||{},c,d,e,f;for(d in b)if(this._data=[],"data"==d)for(c=0;c<b.data.length;c++)if(f=b.data[c],this._model_class){e=new this._model_class;e.init();for(d in f)e["_"+d]=f[d];this.add(e)}else this.add(f);else this["_"+d]=b[d]}catch(g){console.error("vs.core.Array.parseJSON failed. "+g.toString())}}};i.extendClass(B,j.Model);i.defineClassProperties(B,{length:{get:function(){if(!this.__i__)throw"Component not initialized";return this._data.length}},modelClass:{set:function(a){a instanceof
Function&&(this._model_class=a)}}});j.Array=B;w.prototype={__models__:null,registerModel:function(a,b){a&&b&&(this.__models__[a]&&error.log("Model with the name already registered."),this.__models__[a]=b,b._sync_service_=this)},removeModel:function(a){a&&this.__models__[a]&&delete this.__models__[a]},save:function(){},load:function(){}};i.extendClass(w,j.EventSource);j.DataStorage=w;F.prototype={save:function(a){function b(a){var b,f=c.__models__[a];if(f){try{b=f.toJSON?f.toJSON():JSON.stringify(f)}catch(g){error.log(g),
c.propagate("error",g)}localStorage.setItem(a,b)}}var c=this;if(a)b(a);else for(a in this.__models__)b(a);c.propagate("save")},load:function(a){function b(a){try{var b=c.__models__[a];if(b){var f=localStorage.getItem(a);b.parseJSON(f)}}catch(g){console.error("LocalStorate.load failed. "+g.toString())}}var c=this;if(a)b(a);else for(a in this.__models__)b(a);c.propagate("load")}};i.extendClass(F,w);j.LocalStorage=F})(window);
