/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(o,u){function v(){return"vs_id_"+Y++}function K(a,b){h.isNumber(a)&&(this.x=a);h.isNumber(b)&&(this.y=b)}function p(a){this.constructor=j.Object;this._id=h.isString(a)?a:a&&a.id?a.id:v();a&&(this.__config__=a)}function E(a){return a&&h.isFunction(a.clone)?a.clone():h.clone(a)}function Z(a,b,c){var d=b.__lookupGetter__(a),f=b.__lookupSetter__(a),i=c.__lookupSetter__(a),g="_"+h.underscore(a);if(f||d)i?c[a]=E(b[g]):c[g]=E(b[g])}function $(a,b,c){var d=b.getPropertyDescriptor(a),f=c.getPropertyDescriptor(a),
i="_"+h.underscore(a);if(d&&f&&(d.get||d.set))f.set?c[a]=E(b[i]):c[i]=E(b[i])}function aa(a,b){var c={},d,f,i,g;for(g in b){d=b[g];if(h.isNumber(d))f={},i="_"+h.underscore(g),d&k.core.Object.PROPERTY_IN&&(f.set=function(a,b){return function(c){this[b]=c;this.propertyChange(a)}}(g,i)),d&k.core.Object.PROPERTY_OUT&&(f.get=function(a){return function(){return this[a]}}(i));else if(h.isString(d)){i=ba.exec(d);if(!i||3!=i.length)throw"Unvalid property path: "+d;f={};f.set=function(a,b){return function(c){for(var d=
this,f=a.split(".");d&&f.length;)d=d[f.shift()];d&&(d[b]=c);this.propertyChange(b)}}(i[1],i[2]);f.get=function(a,b){return function(){for(var c=this,d=a.split(".");c&&d.length;)c=c[d.shift()];if(c)return c[b]}}(i[1],i[2])}else"object"==typeof d&&(f=d);c[g]=f}h.defineClassProperties(a,c)}function Q(a,b){this.obj=a;h.isFunction(b)?this.func_ptr=b:h.isString(b)&&(this.func_name=b)}function L(a,b){this.func_ptr=a;this.args=b}function R(a,b){a&&b&&(F={handler_list:b,event:a},M())}function S(a,b){function c(a){if(a)try{if(h.isFunction(a.func_ptr))a.func_ptr.call(a.obj,
g);else if(h.isString(a.func_name)&&h.isFunction(a.obj[a.func_name]))a.obj[a.func_name](g);else h.isFunction(a.obj.notify)&&a.obj.notify(g)}catch(b){b.stack?console.error(b.stack):console.error(b)}f--;0>=f&&(y=!1)}var d=a.handler_list,f=d.length,i,g=a.event;y=!0;f||(f--,0>=f&&(y=!1));for(i=0;i<f;i++)b?c(d[i]):function(a){G(function(){c(a)})}(d[i])}function T(){if(w.length){var a=w.shift();if(a)try{H=!0,a.run()}catch(b){b.stack?console.error(b.stack):console.error(b)}k.util.free(a);H=!1;w.length&&
N()}}function ca(){function a(a){a.data===b&&T()}var b="vs.core.scheduler"+Math.random();o.addEventListener&&o.addEventListener("message",a,!1);return function(){o.postMessage(b,"*")}}function M(){function a(){U=!1;M()}F&&(S(F,!0),F=null);0===I.length&&0===w.length||U||(y?G(a):(!H&&w.length&&N(),I.length&&(y||S(I.shift()))))}function q(a){this.parent=p;this.parent(a);this.constructor=j.EventSource;this.__bindings__={};this.__node_binds__={}}function z(a){this.parent=q;this.parent(a);this.constructor=
k.core.Model;this.__links__=[]}function O(){this.dataflow_node=[];this.dataflow_edges={};this.is_propagating=!1;this._node_link={};this.__shouldnt_propagate__=0}function m(a){this.parent=j.Object;this.parent(a);this.constructor=m}function A(a){this.parent=j.Task;this.parent();this.constructor=A;this._tasksAndParams=[];this._state=m.STOPPED;arguments.length&&this.setTasks(arguments)}function B(a){this.parent=j.Task;this.parent();this.constructor=B;this._tasksAndParams=[];this._state=m.STOPPED;arguments.length&&
this.setTasks(arguments)}function C(a){this.parent=j.Task;this.parent();this.constructor=C;this._state=m.STOPPED;this.time=a}function e(){this.deviceId=this.orientation=null;this.targets={};this.browserDetect();this.orientationDetect();this.screenDetect()}function x(a){this.parent=k.core.Model;this.parent(a);this.constructor=k.core.Array}function s(a){this.parent=j.EventSource;this.parent(a);this.constructor=k.core.DataStorage;this.__models__={}}function P(a){this.parent=s;this.parent(a);this.constructor=
k.core.LocalStorage}function r(a){this.parent=s;this.parent(a);this.constructor=r;this._xhrs={};this._headers={}}var V=o.document,k=o.vs,h=k.util,j=k.core,Y=0;j.createId=v;j.createUniqueId=function(){return"vs_id_"+(new Date).getTime()+""+Math.floor(1E6*Math.random())};K.prototype={x:0,y:0,matrixTransform:function(a){var b=new k.CSSMatrix,b=b.translate(this.x,this.y,this.z||0),a=a.multiply(b),c=new K(a.m41,a.m42);delete b;delete a;return c}};k.Point=K;p.prototype={_id:"",__i__:!1,__config__:null,
init:function(a){if(this.__i__)return this;this._id||(this._id=v());p._obs[this._id]=this;a||this.initComponent();this.__i__=!0;!a&&this.vsdInit&&this.vsdInit();this.__config__&&(this.configure(this.__config__),this.__config__=null);this.componentDidInitialize&&this.componentDidInitialize();this.initSkin&&(console.warn("Your application shouldn't use initSkin anymore.\n        You should rename by componentDidInitialize."),p.prototype.initSkin=function(){},this.initSkin(),p.prototype.initSkin=u);
return this},initComponent:function(){},componentDidInitialize:function(){},createId:function(){console.warn("this.createId is deprecated, Use the static method vs.core.createId instead");return v()},configure:function(a){if("object"===typeof a){var b,c,d,f=!1,i=t[this._id];i&&i.pausePropagation();if(a instanceof z)if((b=this.getPropertyDescriptor("model"))&&b.set)this.model=a,f=!0;else{b=a.getModelProperties();for(d=0;d<b.length;d++)c=b[d],"id"!==c&&(this[c]=a[c],f=!0)}else if(a)for(c in a)"id"===
c||"node"===c||"node_ref"===c||"view"===c||(this[c]=a[c],f=!0);i?(i.restartPropagation(),f&&(this.propertiesDidChange&&this.propertiesDidChange(),i.propagate(this._id))):f&&this.propertiesDidChange&&this.propertiesDidChange()}},toJSON:function(){return this._toJSON("{")+"}"},parseJSON:function(a){try{this.parseData(a&&h.parseJSON(a)||{})}catch(b){console.error("vs.core.Object.parseJSON failed. "+b.toString())}},parseData:function(a){var b,c;for(b in a)c=a[b],this["_"+h.underscore(b)]=c},_toJSON:function(a){var b,
c,d,f=this.getModelProperties(),i=0;if(!f)return a;for(var g=0;g<f.length;g++)if(b=f[g],c=this["_"+b],"undefined"!=typeof c){if(null==c)d="null";else if(c instanceof Date)d='"/Date('+c.getTime()+')/"';else if(c.toJSON)d=c.toJSON();else try{d=JSON.stringify(c)}catch(e){console.warn(e);continue}i++&&(a+=",");a+='"'+b+'":'+d}return a},destructor:function(){this.__i__=!1},isDeleted:function(){return!this.__i__},propertyChange:function(a){var b=t[this._id];b&&b.propagate(this._id,a)},propagateChange:function(a){this.propertyChange(a)},
link:function(a){if(a instanceof k.core.Model)this.__model&&this.__model.unlinkTo(this),this.__model=a,this.__model.linkTo(this),this.configure(this.__model);else throw"vs.core.Object.link; parameter is not a vs.core.Model";},unlink:function(){if(this.__model){if(this.__model){this.__model.unlinkTo(this);var a=this.__model.getModelProperties();for(l=a.length,config={};l--;)config[a[l]]=null;this.configure(config)}this.__model=u}},clone:function(a,b){function c(a,b,c){var d=b.__lookupGetter__(a),f=
b.__lookupSetter__(a),i=c.__lookupGetter__(a),g=c.__lookupSetter__(a);d&&!i&&c.__defineGetter__(a,d);f&&!g&&c.__defineSetter__(a,f);!f&&!d?(d=b[a],c[a]=h.isArray(d)?d.slice():b[a]):(c.__properties__||(c.__properties__=[]),c.__properties__.push(a))}function d(a,b,c){var d=b.getOwnPropertyDescriptor(a),f=c.getOwnPropertyDescriptor(a);d&&(d.get||d.set)?f||(h.defineProperty(c,a,d),c.__properties__||(c.__properties__=[]),c.__properties__.push(a)):(d=b[a],c[a]=h.isArray(d)?d.slice():b[a])}var f,i;b||(b=
{});if(b[this._id])return b[this._id];a||(a={});a.id||(a.id=v());if(h.isFunction(this.constructor))f=new this.constructor(a);else return console.warn("impossible to clone this object."),null;b[this._id]=f;var g=Object.defineProperty?d:c;for(i in this)"parent"===i||"_id"===i||"constructor"===i||0===i.indexOf("__")||this.getPropertyDescriptor(i)&&(h.isFunction(this[i])&&!h.isFunction(f[i])?f[i]=this[i]:!f.isProperty(i)&&this.isProperty(i)&&g(i,this,f));f.__i__=!1;f.init();this._clone(f,b);this._clone_properties_value(f,
b);this.__model&&(b&&b[this.__model._id]?f.link(b[this.__model._id]):f.link(this.__model));return f},_clone_properties_value:function(a){for(var b in this)"_id"!==b&&this.isProperty(b)&&W(b,this,a)},_clone:function(){},getModelProperties:function(){var a=[];this.__properties__&&(a=a.concat(this.__properties__));this.constructor.__properties__&&(a=a.concat(this.constructor.__properties__));return a},isProperty:function(a){return this.__properties__&&-1!==this.__properties__.indexOf(a)||-1!==this.constructor.__properties__.indexOf(a)?
!0:!1},defineProperty:function(a,b){h.defineProperty(this,a,b);this.__properties__||(this.__properties__=[]);-1===this.__properties__.indexOf(a)&&this.__properties__.push(a)},getOwnPropertyDescriptor:function(a){return Object.getOwnPropertyDescriptor(this,a)},getPropertyDescriptor:function(a){function b(a,c){if(!a)return null;var i=Object.getPrototypeOf(a);if(!i)return null;var g=Object.getOwnPropertyDescriptor(i,c);return g?g:b(i,c)}var c=Object.getOwnPropertyDescriptor(this,a);return c?c:b(this,
a)},_super:function(){var a=this._super.caller._super_func_;a&&a.apply(this,arguments)}};h.defineClassProperty(p,"id",{get:function(){return this._id}});var W=Object.defineProperty?$:Z;p._obs={};p.__propertyCloneValue=W;j.Object=p;var da=Object.prototype.constructor;k.core.Object.PROPERTY_IN=1;k.core.Object.PROPERTY_OUT=2;k.core.Object.PROPERTY_IN_OUT=3;var ba=/(\w+[.\w+]*)#(\w+)/;j.createClass=function(a){var b=null,c={},d=k.core.Object,f={},b=function(){this.parent=b.__spec.parent;b.__spec&&b.__spec._constructor?
b.__spec._constructor.apply(this,arguments):b.__spec&&b.__spec.parent&&this.parent.apply(this,arguments);this.constructor=b};a&&a.parent&&(d=a.parent,delete a.parent);a&&a.properties&&(f=a.properties,delete a.properties);c.parent=d;a&&a.constructor&&a.constructor!==da&&(c._constructor=a.constructor,c._constructor._super_func_=d);b.__spec=c;a&&(b.prototype=a,a.constructor=b);d.prototype&&h.extendClass(b,d);if(a)for(key in a)if(a.hasOwnProperty(key)){var c=a[key],i=d.prototype[key];h.isFunction(c)&&
h.isFunction(i)&&(c._super_func_=i)}aa(b,f);return b};Q.prototype.destructor=function(){delete this.obj;delete this.func_ptr;delete this.func_name};L.prototype.run=function(){this.func_ptr.apply(u)};L.prototype.destructor=function(){delete this.args;delete this.func_ptr};var I=[],F=null,w=[],y=!1,H=!1,U=!1,N=o.postMessage?ca():function(){setTimeout(T,0)},G=o.setImmediate||function(a){w.push(new L(a));H||N()};k.setImmediate=G;h.extend(k,{scheduleAction:function(a,b){h.isFunction(a)&&(b&&h.isNumber(b)?
setTimeout(a,b):"__on_next_frame__"===b?k.requestAnimationFrame(a):G(a))},ON_NEXT_FRAME:"__on_next_frame__"});j.FORCE_EVENT_PROPAGATION_DELAY=!1;j.POINTER_START=k.POINTER_START;j.POINTER_MOVE=k.POINTER_MOVE;j.POINTER_END=k.POINTER_END;j.POINTER_CANCEL=k.POINTER_CANCEL;j.GESTURE_START=k.GESTURE_START;j.GESTURE_CHANGE=k.GESTURE_CHANGE;j.GESTURE_END=k.GESTURE_END;var J=function(a,b,c){this.srcTarget=this.src=a;this.type=b;this.data=c};J.prototype={src:null,srcTarget:null,type:"",data:null,destructor:function(){delete this.src;
delete this.srcTarget;delete this.type;delete this.data}};j.Event=J;j.EVENT_SUPPORT_GESTURE=!1;q.prototype={__bindings__:null,__node_binds__:null,destructor:function(){var a,b,c;for(a in this.__bindings__){if(b=this.__bindings__[a]){c=void 0;for(var d=b.length;d--;)c=b[d],h.free(c)}delete this.__bindings__[a]}delete this.__bindings__;for(a in this.__node_binds__)if(c=this.__node_binds__[a],"undefined"===typeof c)console.warn("vs.core.Object.destructor, no bind <"+a+" exists.");else for(b=0;b<c.length;b++)data=
c[b],data.n.removeEventListener(event,data.h);delete this.__node_binds__;p.prototype.destructor.call(this)},_clone:function(a,b){p.prototype._clone.call(this,a,b);a.__bindings__={};a.__node_binds__={}},bind:function(a,b,c){if(a&&b)return b=new Q(b,c),c=this.__bindings__[a],c||(c=[],this.__bindings__[a]=c),c.push(b),b},unbind:function(a,b,c){if(a=this.__bindings__[a])for(var d,f=0;f<a.length;)d=a[f],d.obj===b?h.isString(c)||h.isFunction(c)?d.func_name===c||d.func_ptr===c?(a.remove(f),h.free(d)):f++:
(a.remove(f),h.free(d)):f++},propagate:function(a,b,c){var d=this.__bindings__[a];!d||0===d.length?this.__parent&&(c||(c=this),this.__parent.propagate(a,b,c)):(a=new J(this,a,b),c&&(a.srcTarget=c),a&&d&&(I.push({handler_list:d,event:a}),M()))},notify:function(a){this.propagate(a.type,a.data)},nodeBind:function(a,b,c,d){if(a&&h.isString(b)){var f=this,i=null,g=null,e,j;if("undefined"===typeof c)c="notify";else if(h.isString(c)){if(!h.isFunction(this[c])){console.warn("vs.core.Object.nodeBind, unknown function named: "+
c);return}}else if(h.isFunction(c))i=c,c=i.name;else{console.error("vs.core.Object.nodeBind, invalid func parameter");return}g=!d||d===n.ANY_MASK?function(a){try{a.src=a.currentTarget,a.data=a,i||(i=f[c]),i.call(f,a)}catch(b){console.error(b)}}:function(a){try{if(d||!a.altKey&&!a.ctrlKey&&!a.shiftKey&&!a.metaKey)d===n.ALT&&!a.altKey||d===n.CTRL&&!a.ctrlKey||d===n.SHIFT&&!a.shiftKey||d===n.META&&!a.metaKey||(a.src=a.currentTarget,a.data=a,i||(i=f[c]),i.call(f,a))}catch(b){console.error(b)}};j=b+c;
this.__node_binds__?(e=this.__node_binds__[j],"undefined"===typeof e&&(e=[],this.__node_binds__[j]=e),e.push({n:a,h:g}),k.addPointerListener(a,b,g,!1)):console.error("nodeBind impossible")}},nodeUnbind:function(a,b,c){if(a&&h.isString(b)){var d,f;if("undefined"===typeof c)c="notify";else if(h.isString(c)){if(!h.isFunction(this[c])){console.warn("vs.core.Object.nodeUnbind, unknown function named: "+c);return}}else if(h.isFunction(c))c=c.name;else{console.error("vs.core.Object.nodeBind, invalid func parameter");
return}d=this.__node_binds__[b+c];if("undefined"===typeof d)console.warn("vs.core.Object.nodeUnbind, no bind <"+b+","+c+"> exists.");else{for(c=0;c<d.length;)f=d[c],f.n===a?(a.removeEventListener(b,f.h),d.remove(c)):c++;a._object_=u}}}};h.extendClass(q,p);j.EventSource=q;z.prototype={__links__:null,__should_propagate_changes__:!0,_sync_service_:null,bindChange:function(a,b,c){b&&this.bind(a?"change:"+a:"change",b,c)},unbindChange:function(a,b,c){this.unbind(a?"change:"+a:"change",b,c)},stopPropagation:function(){this.__should_propagate_changes__=
!1},hasToPropagateChange:function(){return this.__should_propagate_changes__},change:function(a,b,c){this.__should_propagate_changes__=!0;a=a?"change:"+a:"change";b=new J(this,a,b);try{if(!c)for(var d=this.__links__.length;d--;)this.__links__[d].configure(this);"change"!==a&&R(b,this.__bindings__[a]);R(b,this.__bindings__.change)}catch(f){f.stack&&console.error(f.stack),console.error(f)}},propagate:function(a,b,c){this.__should_propagate_changes__=!0;q.prototype.propagate.call(this,a,b,c)},linkTo:function(a){a instanceof
k.core.Object&&-1===this.__links__.indexOf(a)&&this.__links__.push(a)},unlinkTo:function(a){a instanceof k.core.Object&&this.__links__.remove(a)},propertyChange:function(a){var b=t[this._id];b&&b.propagate(this._id,a);if(this.__should_propagate_changes__){b=this.__links__.length;if(a)for(;b--;)this.__links__[b][a]=this[a];else for(;b--;)this.__links__[b].configure(this);this.change(null,null,!0)}},parseData:function(a){for(var b in a)this._parse_property(b,a[b])},_parse_property:function(a,b){var c=
this.getModelProperties(),d="_"+h.underscore(a),f;h.isArray(b)?(f=(new x({})).init(),f.parseData(b)):f=b;-1===c.indexOf(a)&&(c={},d="_"+h.underscore(a),c.set=function(a,b){return function(c){this[b]=c;this.propertyChange(a)}}(a,d),c.get=function(a){return function(){return this[a]}}(d),this.defineProperty(a,c));this[d]=f}};h.extendClass(z,q);j.Model=z;var n=new q("__KEYBOARD__");n._handler_set_down=!1;n._handler_set_up=!1;n.managePrevent=function(a,b){var c=this.__bindings__[a],d,f;if(c)for(d=0;d<
c.length;d++)if(f=c[d],f.prevent){b.preventDefault();break}};n.KEY_UP=1E3;n.ESC=27;n.ENTER=13;n.SPACE=32;n.BACKSPACE=8;n.SHIFT=16;n.CTRL=17;n.ALT=18;n.NUMLOCK=144;n.LEFT_ARROW=37;n.UP_ARROW=38;n.RIGHT_ARROW=39;n.DOWN_ARROW=40;n.L=76;n.S=83;n.Z=90;n.META=2E3;n.ANY_MASK=3E3;n.UNDO=256;n.REDO=257;n.SAVE=258;j.KEYBOARD=n;j.KEYBOARD.bind=function(a,b,c,d){var b=q.prototype.bind.call(this,a,b,c),f=this;d&&(b.prevent=!0);a>n.KEY_UP?this._handler_set_up||(V.documentElement.addEventListener("keyup",function(a){f.managePrevent(a.keyCode,
a);f.propagate(a.keyCode+n.KEY_UP,a)},!1),this._handler_set_up=!0):this._handler_set_down||(V.documentElement.addEventListener("keydown",function(a){(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode===n.Z?(f.propagate(n.UNDO),a.preventDefault()):(a.ctrlKey||a.metaKey)&&a.shiftKey&&a.keyCode===n.Z?(f.propagate(n.REDO),a.preventDefault()):(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode===n.S?(f.propagate(n.SAVE),a.preventDefault()):(a.ctrlKey||a.metaKey)&&!a.shiftKey&&a.keyCode?(f.managePrevent(n.META+
a.keyCode,a),f.propagate(n.META+a.keyCode)):(f.managePrevent(a.keyCode,a),f.propagate(a.keyCode,a))},!1),this._handler_set_down=!0)};var D=function(a){this.parent=j.EventSource;this.parent(v());this.constructor=D;this.owner=a;this._list_of_state={};this._list_input=[];this._list_output=[];this._current_state=this._initial_state="";this._inputs={};this._output_action={}};D.prototype={destructor:function(){delete this._list_of_state;this.owner=u;delete this._list_of_state;delete this._list_input;delete this._list_output;
delete this._inputs;delete this._output_action;j.EventSource.prototype.destructor.call(this)},_clone:function(a,b){q.prototype._clone.call(this,a,b);a.owner=a.__config__.owner;a._current_state="";a._inputs={};a._output_action={}},initWithData:function(a,b,c,d){if(a&&b&&c&&d){for(var f=0;f<a.length;f++)this.addState(a[f]);for(f=0;f<b.length;f++)this.addInput(b[f]);for(f=0;f<c.length;f++)this.addOutput(c[f]);for(f=0;f<d.length;f++)this.addTransition(d[f].from,d[f].to,d[f].on,d[f].output)}},initWithMatrix:function(a){for(var b=
1;b<a[0].length;b++)this.addState(a[0][b]);for(b=1;b<a.length;b++)for(var c=a[b][0],d=1;d<a[0].length;d++){var f=a[0][d],i=a[b][d];i&&(i=i.split("/"),i[0]&&this.addInput(i[0]),i[1]&&this.addOutput(i[1]),this.addTransition(c,f,i[0],i[1]))}},addInput:function(a){a&&!this.existInput(a)&&this._list_input.push(a)},getInputs:function(){return this._list_input.slice()},existInput:function(a){return!a?void 0:-1<this._list_input.findItem(a)},addOutput:function(a){a&&!this.existOutput(a)&&this._list_output.push(a)},
getOutputs:function(){return this._list_output.slice()},existOutput:function(a){return!a?void 0:-1<this._list_output.findItem(a)},addState:function(a){if(!a||this.existState(a))return!1;this._list_of_state[a]={transitionEvents:{}};return!0},removeState:function(a){if(!a||!this.existState(a))return!1;delete this._list_of_state[a];return!0},renameState:function(a,b){if(!a||!this.existState(a)||!b||this.existState(b))return!1;this._list_of_state[b]=this._list_of_state[a];delete this._list_of_state[a];
this._initial_state===a&&(this._initial_state=b);for(var c in this._list_of_state){var d=this._list_of_state[c];if(null!==d)for(var f in d.transitionEvents){var i=d.transitionEvents[f];i.to===a&&(i.to=b)}}return!0},getListState:function(){var a=[],b;for(b in this._list_of_state)a.push(b);return a},existState:function(a){return!a?!1:this._list_of_state[a]?!0:!1},addTransition:function(a,b,c,d){a&&this.existState(a)&&b&&this.existState(b)&&c&&this.existInput(c)&&(this._list_of_state[a].transitionEvents[c]=
{on:c,to:b,output:d})},removeTransitionFrom:function(a,b){if(a&&this.existState(a)&&b&&this.existInput(b)){var c=this._list_of_state[a];c.transitionEvents[b]&&delete c.transitionEvents[b]}},removeTransitionTo:function(a,b){if(a&&this.existState(a)&&b&&this.existInput(b))for(var c in this._list_of_state){var d=this._list_of_state[c],f=d.transitionEvents[b];f&&f.to===a&&delete d.transitionEvents[b]}},getTransionsToState:function(a){if(this.existState(a)){var b=[],c;for(c in this._list_of_state){var d=
this._list_of_state[c];if(null!==d)for(var f in d.transitionEvents){var i=d.transitionEvents[f];i.to===a&&(i=h.clone(i),i.from=c,b.push(i))}}return b}},getTransionsFromState:function(a){if(this.existState(a)){var b=[],c=this._list_of_state[a];if(null===c)return null;for(var d in c.transitionEvents){var f=h.clone(c.transitionEvents[d]);f.from=a;b.push(f)}return b}},switchStates:function(a,b){if(!(a===b||!this.existState(a)||!this.existState(b))){for(var c=this.getTransionsToState(a),d=this.getTransionsFromState(a),
f=this.getTransionsToState(b),i=this.getTransionsFromState(b),g=0;g<c.length;){var e=c[g];e.from===b?c.remove(e):g++}for(g=0;g<d.length;)e=d[g],e.to===b?d.remove(e):g++;for(g=0;g<c.length;g++)e=c[g],this.removeTransitionFrom(e.from,e.on);for(g=0;g<d.length;g++)e=d[g],this.removeTransitionFrom(e.from,e.on);for(g=0;g<f.length;g++)e=f[g],this.removeTransitionFrom(e.from,e.on);for(g=0;g<i.length;g++)e=i[g],this.removeTransitionFrom(e.from,e.on);for(g=0;g<c.length;g++){var e=c[g],h=e.from===b?a:e.from;
this.addTransition(h,b,e.on,e.output)}for(g=0;g<d.length;g++)e=d[g],c=e.from===b?a:e.to,this.addTransition(b,c,e.on,e.output);for(g=0;g<f.length;g++)e=f[g],h=e.from===a?b:e.from,this.addTransition(h,a,e.on,e.output);for(g=0;g<i.length;g++)e=i[g],c=e.to===a?b:e.to,this.addTransition(a,c,e.on,e.output);this._initial_state===a?this._initial_state=b:this._initial_state===b&&(this._initial_state=a)}},setInput:function(a,b,c){if(a&&b&&c){if(b.bind)b.bind(c,this);else if(b.addEventListener)this.nodeBind(b,
c);else return;var d=this._inputs[b];d||(d=[],this._inputs[b]=d);d.push([c,a,b])}},setOutput:function(a,b){a&&b&&(this._output_action[a]=b)},activate:function(){if(!this._initial_state||!this._list_of_state[this._initial_state])return!1;this.goTo(this._initial_state);return!0},goTo:function(a,b,c){if(!this.existState(a))return!1;this._current_state=a;if(b&&this._output_action[b])if(a=this._output_action[b],h.isFunction(a))a.call(this.owner,c);else if(h.isString(a))this.owner[this._output_action[b]](c);
return!0},clear:function(){this._list_of_state={};delete this._list_input;delete this._list_output;this._list_input=[];this._list_output=[];this._initial_state="";for(var a in this._inputs)for(var b=this._inputs[a],c=0;c<b.length;c++){var d=b[c][2],f=b[c][0];d.bind?d.unbind(f,this):d.addEventListener&&this.nodeUnbind(d,f)}this._current_state=""},notify:function(a){var b=this._inputs[a.src];if(b)for(var c=0;c<b.length;c++)a.type===b[c][0]&&this._list_of_state[this._current_state]&&this.fsmNotify(b[c][1],
a.data)},fsmNotify:function(a,b,c){if(this._list_of_state[this._current_state]){var d=this._list_of_state[this._current_state].transitionEvents[a];if(!d)return!1;this.goTo(d.to,d.output,{on:a,data:b},c);return!0}}};h.extendClass(D,q);h.defineClassProperty(D,"initialState",{set:function(a){a?this.existState(a)&&(this._initial_state=a):this._initial_state=u},get:function(){return this._initial_state}});j.Fsm=D;O.prototype={propagate_values:function(a){var b=this.dataflow_edges[a],c,d,f,i,e,j;if(b){d=
p._obs[a];for(a=0;a<b.length;a++)if(e=p._obs[b[a][0]])if(j=b[a][2]){for(c=0;c<j.length;c++){f=j[c][0];i=j[c][1];var k=d.getPropertyDescriptor(f),m=e.getPropertyDescriptor(i);if(!k||!k.get)if(f="_"+h.underscore(f),!d.hasOwnProperty(f))continue;if(!m||!m.set)if(i="_"+h.underscore(i),!e.hasOwnProperty(i))continue;e[i]=d[f]}e.__should__call__has__changed__=!0}}},propagate:function(a){if(!this.is_propagating&&!this.__shouldnt_propagate__){this.is_propagating=!0;var b=0;if(a){for(;b<this.dataflow_node.length&&
this.dataflow_node[b]!==a;)b++;b<this.dataflow_node.length-1&&(this.propagate_values(a),b++)}for(;b<this.dataflow_node.length;b++)if(a=p._obs[this.dataflow_node[b]])a.__should__call__has__changed__&&a.propertiesDidChange&&(a.propertiesDidChange(),a.__should__call__has__changed__=!1),this.propagate_values(a.id);this.is_propagating=!1}},build:function(){if(this._ref_node&&this._ref_edges){var a=[],b,c,d,f,e,g;for(b=0;b<this._ref_node.length;b++)c=this._ref_node[b],this._node_link[c]&&a.push(this._node_link[c]);
this.dataflow_node=a;a={};for(c in this._ref_edges)if(this._node_link[c]){d=this._ref_edges[c];f=[];for(b=0;b<d.length;b++)e=d[b],g=[3],this._node_link[e[0]]&&(g[0]=this._node_link[e[0]],g[1]=e[1],g[2]=e[2].slice(),f.push(g));a[this._node_link[c]]=f}this.dataflow_edges=a}},register_ref_node:function(a){a&&(this._ref_node=a)},register_ref_edges:function(a){a&&(this._ref_edges=a)},pausePropagation:function(){this.__shouldnt_propagate__++},restartPropagation:function(){this.__shouldnt_propagate__--;
0>this.__shouldnt_propagate__&&(this.__shouldnt_propagate__=0)}};var t={};k._df_node_register=function(a,b,c){if(a&&b&&c&&(a=t[a]))a._node_link[b]=c,t[c]=a};k._df_create=function(a,b){var c=new O;c.ref=b;return t[a]=c};k._df_register_ref_node=function(a,b){if(a&&b){var c=t[a];c&&c.register_ref_node(b)}};k._df_register_ref_edges=function(a,b){if(a&&b){var c=t[a];c&&c.register_ref_edges(b)}};k._df_build=function(a){a&&(a=t[a])&&a.build()};j.DataFlow=O;m.STARTED=1;m.STOPPED=0;m.PAUSED=2;m.prototype=
{delegate:null,_state:m.STOPPED,destructor:function(){this.stop();this._super()},start:function(){},stop:function(){},pause:function(){}};h.extendClass(m,j.Object);h.defineClassProperty(m,"state",{get:function(){return this._state}});k.par=function(){if(0!==arguments.length){var a=new A;a.setTasks(arguments);return a}};A.prototype={_tasksAndParams:null,_tasksWillEnded:null,setTasks:function(a){if(this._state!==m.STOPPED)return!1;var b,c,d,f;this._tasksAndParams=[];for(b=0;b<a.length;b++)if(c=a[b])d=
f=null,h.isArray(c)?1===c.length?d=c[0]:2===c.length&&(d=c[0],f=c[1]):(d=c,f=null),d?!d.start||!d.stop||!d.pause?console.warn("Invalid task: "+d.toString()):this._tasksAndParams.push([d,f]):console.warn("Undefined task")},start:function(a){if(this._state===m.STARTED)return!1;this._tasksWillEnded=this._tasksAndParams.length;this._state=m.STARTED;var b,c;for(c=0;c<this._tasksAndParams.length;c++)b=this._tasksAndParams[c],b[0].delegate=this,b[0].start(b[1]?b[1]:a);return!0},stop:function(){if(this._state===
m.STOPPED)return!1;this._state=m.STOPPED;var a,b;for(b=0;b<this._tasksAndParams.length;b++)a=this._tasksAndParams[b],a[0].stop();return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;var a,b;for(b=0;b<this._tasksAndParams.length;b++)a=this._tasksAndParams[b],a[0].pause();return!0},taskDidStop:function(){this._state=m.STOPPED;this._tasksWillEnded--;0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this)},taskDidPause:function(){this._state=
m.STOPPED;this._tasksWillEnded--;0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this)},taskDidEnd:function(){this._state=m.STOPPED;this._tasksWillEnded--;0===this._tasksWillEnded&&this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this)}};h.extendClass(A,m);k.seq=function(){if(0!==arguments.length){var a=new B;a.setTasks(arguments);return a}};B.prototype={_tasksAndParams:null,_nextTaskToStart:0,_startParam:null,setTasks:function(a){if(this._state!==
m.STOPPED)return!1;var b,c,d,f;this._tasksAndParams=[];for(b=0;b<a.length;b++)if(c=a[b])d=f=null,h.isArray(c)?1===c.length?d=c[0]:2===c.length&&(d=c[0],f=c[1]):(d=c,f=null),d?!d.start||!d.stop||!d.pause?console.warn("Invalid task: "+d.toString()):this._tasksAndParams.push([d,f]):console.warn("Undefined task")},start:function(a){if(this._state===m.STARTED)return!1;this._state=m.STARTED;this._startParam=a;var b=this._tasksAndParams[this._nextTaskToStart];if(!b)return!1;this._nextTaskToStart++;b[0].delegate=
this;b[0].start(b[1]?b[1]:a);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;var a=this._tasksAndParams[this._nextTaskToStart-1];if(!a)return!1;this._nextTaskToStart=0;a[0].stop();return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;var a=this._tasksAndParams[this._nextTaskToStart-1];if(!a)return!1;a[0].pause();return!0},taskDidStop:function(){this._state=m.STOPPED;0===this._nextTaskToStart&&(this._nextTaskToStart-=1);this.delegate&&
this.delegate.taskDidStop&&this.delegate.taskDidStop(this)},taskDidPause:function(){this._state=m.PAUSED;this._nextTaskToStart-=1;this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this)},taskDidEnd:function(){this._state=m.STOPPED;this._nextTaskToStart<this._tasksAndParams.length?this.start(this._startParam):(this._nextTaskToStart=0,this.delegate&&this.delegate.taskDidEnd&&this.delegate.taskDidEnd(this))}};h.extendClass(B,m);C.prototype={_time:0,_left_time:0,_timer:null,_start_time:0,
start:function(){var a=this,b=this._time;if(this._state===m.STARTED)return!1;this._state===m.PAUSED?b=this._left_time:this._left_time=b;this._state=m.STARTED;this._start_time=(new Date).getTime();a=this;this._timer=setTimeout(function(){a._state=m.STOPPED;a.delegate&&a.delegate.taskDidEnd&&a.delegate.taskDidEnd(a)},b);return!0},stop:function(){if(this._state===m.STOPPED)return!1;this._state=m.STOPPED;clearTimeout(this._timer);this._timer=null;this._left_time=this._time;this.delegate&&this.delegate.taskDidStop&&
this.delegate.taskDidStop(this);return!0},pause:function(){if(this._state===m.PAUSED)return!1;this._state=m.PAUSED;this._left_time=this._left_time-(new Date).getTime()+this._start_time;this.delegate&&this.delegate.taskDidPause&&this.delegate.taskDidPause(this);return!0}};h.extendClass(C,m);h.defineClassProperty(C,"state",{set:function(a){h.isNumber(a)&&(this._time=a)}});h.extend(j,{Task:m,Task_PAR:A,Task_SEQ:B,TaskWait:C});e.OS_UNKNOWN=0;e.OS_WINDOWS=1;e.OS_MACOS=2;e.OS_LINUX=4;e.OS_IOS=5;e.OS_WP7=
6;e.OS_BLACK_BERRY=7;e.OS_SYMBIAN=8;e.OS_ANDROID=9;e.OS_MEEGO=10;e.SR_UNKNOWN=0;e.SR_QVGA=1;e.SR_WQVGA=2;e.SR_HVGA=4;e.SR_VGA=5;e.SR_WVGA=6;e.SR_FWVGA=7;e.SR_SVGA=8;e.SR_DVGA=9;e.SR_WDVGA=10;e.SR_XGA=11;e.SR_N_HD=12;e.SR_Q_HD=13;e.SR_WXGA=14;e.SR_QXGA=15;e.BROWSER_UNKNOWN=0;e.BROWSER_CHROME=1;e.BROWSER_SAFARI=2;e.BROWSER_OPERA=3;e.BROWSER_FIREFOX=4;e.BROWSER_MSIE=5;e.SS_UNKNOWN=0;e.SS_4_INCH=1;e.SS_7_INCH=2;e.SS_10_INCH=3;e.prototype={os:e.OS_UNKNOWN,browser:e.BROWSER_UNKNOWN,screenResolution:e.SR_UNKNOWN,
screenRatio:0,screenSize:e.SS_UNKNOWN,browserDetect:function(){function a(a){for(var c=a.length;c--;){var d=a[c].string,f=a[c].prop;if(d){if(d.match(a[c].subString))return a[c].identity}else if(f)return a[c].identity}}this.browser=a(e._data_browser)||e.BROWSER_UNKNOWN;this.os=a(e._data_OS)||e.OS_UNKNOWN},orientationDetect:function(){this.orientation=o.orientation?o.orientation:o.outerWidth>o.outerHeight?90:0},screenDetect:function(){var a=o.devicePixelRatio,b,c;a||(a=1);this.os>=e.OS_IOS&&this.os<=
e.OS_MEEGO?(b=o.screen.width,c=o.screen.height):(b=o.outerWidth,c=o.outerHeight);if(b>c){var d=b;b=c;c=d}this.screenResolution=e._getScreenResolutionCode(b,c);this.screenRatio=c/b;a=Math.sqrt(b*b+c*c)/(160*a);6>a?this.screenSize=e.SS_4_INCH:9>a?this.screenSize=e.SS_7_INCH:11>a&&(this.screenSize=e.SS_10_INCH)},getOrientation:function(){return this.orientation},setDeviceId:function(a){if(h.isString(a))if(this.deviceId=a,-1!=a.indexOf("wp7"))this.os=e.OS_WP7,this.screenResolution=e.SR_WVGA,this.screenRatio=
1.6;else if(-1!=a.indexOf("iphone"))this.os=e.OS_IOS,this.screenResolution=e.SR_HVGA,-1!=a.indexOf("_3_2")?this.screenRatio=1.5:-1!=a.indexOf("_16_9")&&(this.screenRatio=16/9);else if(-1!=a.indexOf("ipad"))this.os=e.OS_IOS,this.screenResolution=e.SR_XGA,this.screenRatio=4/3;else if(-1!=a.indexOf("nokia_s3"))this.os=e.OS_SYMBIAN,this.screenResolution=e.SR_N_HD,this.screenRatio=4/3;else if(-1!=a.indexOf("android")){this.os=e.OS_ANDROID;-1!=a.indexOf("_3_2")?this.screenRatio=1.5:-1!=a.indexOf("_16_10")?
this.screenRatio=1.6:-1!=a.indexOf("_16_9")&&(this.screenRatio=16/9);var a=o.screen.width,b=o.screen.height;a>b&&(a=o.screen.height,b=o.screen.width);this.screenResolution=e._getScreenResolutionCode(a,b)}else-1!=a.indexOf("blackberry")&&(this.os=e.OS_BLACK_BERRY,a.indexOf("_4_3")?this.screenRatio=4/3:a.indexOf("_3_2")?this.screenRatio=1.5:a.indexOf("_16_10")&&(this.screenRatio=1.6),a=o.screen.width,b=o.screen.height,this.screenResolution=e._getScreenResolutionCode(a,b))},setOrientation:function(a,
b){var c,d,f;f=o.innerWidth;var e=o.innerHeight,g;if(this.orientation!==a){f>e&&(g=e,e=f,f=g);for(d in j.Object._obs)if(f=j.Object._obs[d])f._orientationWillChange&&f._orientationWillChange(a),f.orientationWillChange&&f.orientationWillChange(a);for(c in this.targets)if(d=this.targets[c],d.device===this.deviceId&&(!(0!==a&&180!==a||-1===c.indexOf("_p"))||!(90!==a&&-90!==a||-1===c.indexOf("_l")))){this.setActiveStyleSheet(c);break}this.orientation=a;d=function(){var b,c;for(b in j.Object._obs)(c=j.Object._obs[b])&&
c.orientationDidChange&&c.orientationDidChange(a)};b?d.call(this):setTimeout(d,100);return c}},setActiveStyleSheet:function(a){h.setActiveStyleSheet(a);k._current_platform_id=a},registerTargetId:function(a,b){this.targets[a]=b}};e._getScreenResolutionCode=function(a,b){if(240===a&&320===b)return e.SR_QVGA;if(240===a&&400===b)return e.SR_WQVGA;if(320===a&&480===b)return e.SR_HVGA;if(480===a&&640===b)return e.SR_VGA;if(480===a&&800===b)return e.SR_WVGA;if(320===a&&854===b)return e.SR_WFVGA;if(600===
a&&800===b)return e.SR_SVGA;if(640===a&&960===b)return e.SR_DVGA;if(640===a&&1136===b)return e.SR_WDVGA;if(768===a&&1024===b)return e.SR_XGA;if(360===a&&640===b)return e.SR_N_HD;if(540===a&&960===b)return e.SR_Q_HD;if(720===a&&1280===b||768===a&&1280===b||800===a&&1280===b)return e.SR_WXGA;if(1536===a&&2048===b)return e.SR_QXGA};e._estimateScreenSize=function(a){var b=a.width/a.xdpi,a=a.height/a.ydpi,b=Math.sqrt(b*b+a*a);return 5>b?3:8>b?7:10};e._data_browser="undefined"!=typeof navigator?[{string:navigator.userAgent,
subString:"Chrome",identity:e.BROWSER_CHROME},{string:navigator.vendor,subString:"Apple",identity:e.BROWSER_SAFARI,versionSearch:"Version"},{prop:o.opera,identity:e.BROWSER_OPERA,versionSearch:"Version"},{string:navigator.userAgent,subString:"Firefox",identity:e.BROWSER_FIREFOX},{string:navigator.userAgent,subString:"MSIE",identity:e.BROWSER_MSIE,versionSearch:"MSIE"}]:[];e._data_OS="undefined"!=typeof navigator?[{string:navigator.platform,subString:"Win",identity:e.OS_WINDOWS},{string:navigator.platform,
subString:"Mac",identity:e.OS_MACOS},{string:navigator.platform,subString:"Linux",identity:e.OS_LINUX},{string:navigator.userAgent,subString:"iPad|iPhone|iPod",identity:e.OS_IOS},{string:navigator.userAgent,subString:"Android",identity:e.OS_ANDROID}]:[];"undefined"!=typeof o&&!o.deviceConfiguration&&(o.deviceConfiguration=new e);j.DeviceConfiguration=e;HTTPRequest=function(a){this.parent=j.EventSource;this.parent(a);this.constructor=HTTPRequest;this._headers={}};HTTPRequest.prototype={_url:"",_method:"GET",
_login:"",_password:"",_content_type:"",_headers:null,setHeaders:function(a){if(a)for(var b in a)this._headers[b]=a[b]},send:function(a){var b=new XMLHttpRequest;try{this._response_xml=this._response_text=null;b.open(this._method,this._url,!0,this._login||null,this._password||null);b.setRequestHeader("Cache-Control","no-cache");b.setRequestHeader("Pragma","no-cache");for(var c in this._headers)b.setRequestHeader(c,this._headers[c]);this._headers={};this._content_type&&b.setRequestHeader("Content-Type",
this._content_type);var d=this;b.onabort=function(){b.onload=b.onerror=b.onabort=null;delete b;d.propagate("loaderror",{status:"aborted"})};b.onerror=function(a){b.onload=b.onerror=b.onabort=null;delete b;d.propagate("loaderror",{status:"failed",response:a})};b.onload=function(){function a(c){d.propagate("loaderror",c);delete b;return!1}b.onload=b.onerror=b.onabort=null;if(4!==b.readyState)return a(xkr.statusText);return 200===b.status?(d._response_text=b.responseText,d._response_xml=b.responseXML,
d.propagateChange(),d.propagate("textload",d._response_text),d._response_xml&&d.propagate("xmlload",d._response_xml),delete b,!0):a({status:b.statusText,response:b.response})};b.send(a)}catch(f){b.onload=b.onerror=b.onabort=null,delete b,this.propagate("loaderror",f)}}};h.extendClass(HTTPRequest,j.EventSource);h.defineClassProperties(HTTPRequest,{url:{set:function(a){h.isString(a)&&(this._url=a)}},method:{set:function(a){"GET"!=a&&"POST"!=a||(this._method=a)}},login:{set:function(a){h.isString(a)&&
(this._login=a)}},password:{set:function(a){h.isString(a)&&(this._password=a)}},contentType:{set:function(a){h.isString(a)&&(this._content_type=a)}},responseText:{get:function(){return this._response_text}},responseXML:{get:function(){return this._response_xml}}});j.HTTPRequest=HTTPRequest;var X=j.createClass({parent:j.EventSource,_url:"",_clb_param_name:"callback",__index:0,properties:{url:{set:function(a){h.isString(a)&&(this._url=a)}},clbParamName:{set:function(a){h.isString(a)&&(this._clb_param_name=
a)}},responseJson:{get:function(){return this._response_json}}},send:function(){var a=this,b="jsonp"+a._id+a.__index++,c=this._clb_param_name+"="+b,d=a._url,f=d.length-1,d="?"===d[f]?d+c:"-1"!==d.indexOf("?")?d+("&"+c):"/"===d[f]?d.substr(0,f)+"?"+c:d+("?"+c),e=h.importFile(d,null,null,"js"),g=function(){e&&(e.parentElement.removeChild(e),e=u)},j=setTimeout(function(){g();b in o&&delete o[b];a.propagate("loaderror","Impossible to load data")},3E3);o[b]=function(c){clearTimeout(j);g();delete o[b];
c&&(c.error?a.propagate("loaderror",c.error):(a._response_json=c,a.propertyChange(),a.propagate("jsonload",c)))}}});j.AjaxJSONP=X;x.prototype={_data:null,_model_class:null,initComponent:function(){this._data=[]},item:function(a){return this._data[a]},_instanciateModel:function(a){if(a instanceof k.core.Model)return a;if(a instanceof Object&&this._model_class)try{var b=new this._model_class(a);b.init();return b}catch(c){console.error(c.toString())}return a},add:function(){for(var a=[],b=0;b<arguments.length;b++)a.push(this._instanciateModel(arguments[b]));
this._data.push.apply(this._data,a);this.hasToPropagateChange()&&this.change("add");return this.length},addAtIndex:function(){if(!(2>arguments.length)){for(var a=[],b=1;b<arguments.length;b++)a.push(this._instanciateModel(arguments[b]));this._data.splice.apply(this._data,a);this.hasToPropagateChange()&&this.change("add",{from:a[0],to:a.length-2})}},remove:function(a,b){this._data.remove(a,b);this.hasToPropagateChange()&&this.change("remove",{from:a,to:b})},removeAll:function(){this._data=[];this.hasToPropagateChange()&&
this.change("removeall")},indexOf:function(){throw"method not yet implemented";},toJSON:function(){for(var a=this._toJSON("{"),b=0,c,a=a+', "data": [';b<this._data.length;b++)if(c=this._data[b])a=c.toJSON?a+c.toJSON():a+JSON.stringify(c),b<this._data.length-1&&(a+=",");return a+"]}"},parseData:function(a){function b(a){g._data=[];for(c=0;c<a.length;c++)e=a[c],f=g._model_class?(new g._model_class).init():(new z).init(),f.parseData(e),g.add(f)}var c,d,f,e,g=this;if(h.isArray(a))b(a);else for(d in a)this._data=
[],"data"==d?b(a.data):this._parse_property(d,a[d])}};h.extendClass(x,j.Model);h.defineClassProperties(x,{data:{set:function(a){if(!this.__i__)throw"Component not initialized";if(h.isArray(a))this._data=a.slice();else if(a instanceof x)this._data=a._data.slice();else return;this.hasToPropagateChange()&&this.change("add")},get:function(){if(!this.__i__)throw"Component not initialized";return this._data.slice()}},length:{get:function(){if(!this.__i__)throw"Component not initialized";return this._data.length}},
modelClass:{set:function(a){h.isFunction(a)&&(this._model_class=a)}}});j.Array=x;s.prototype={__models__:null,registerModel:function(a,b){a&&b&&(this.__models__[a]&&error.log("Model with the name already registered."),this.__models__[a]=b,b._sync_service_=this)},removeModel:function(a){a&&this.__models__[a]&&delete this.__models__[a]},save:function(){},load:function(){}};h.extendClass(s,j.EventSource);j.DataStorage=s;P.prototype={save:function(a){function b(a){var b,e=c.__models__[a];if(e){try{b=
e.toJSON?e.toJSON():JSON.stringify(e)}catch(g){error.log(g),c.propagate("error",g)}localStorage.setItem(a,b)}}var c=this;if(a)b(a);else for(a in this.__models__)b(a);c.propagate("save")},load:function(a){function b(a){try{var b=c.__models__[a];if(b){var e=localStorage.getItem(a);b.parseJSON(e)}}catch(g){console.error("LocalStorate.load failed. "+g.toString())}}var c=this;if(a)b(a);else for(a in this.__models__)b(a);c.propagate("load")}};h.extendClass(P,s);j.LocalStorage=P;r.XHR=0;r.JSONP=1;r.prototype=
{_xhrs:null,_mode:0,_headers:null,_url:"",initComponent:function(){s.prototype.initComponent.call(this)},destructor:function(){s.prototype.destructor.call(this)},setHeaders:function(a){if(a){this._headers={};for(var b in a)this._headers[b]=a[b]}},save:function(a){function b(a){var b,e=c.__models__[a];if(e){try{b=e.toJSON?e.toJSON():JSON.stringify(e)}catch(g){error.log(g),c.propagate("error",g)}r.setItem(a,b)}}var c=this;if(a)b(a);else for(a in this.__models__)b(a);c.propagate("save")},load:function(a){this._mode===
r.XHR&&this._load_xhr(a);this._mode===r.JSONP&&this._load_jsonp(a)},_load_xhr:function(a){function b(a){try{var b=c.__models__[a];if(b){var e=c._url+a+".json",g=b.getModelProperties(),j=0;if(g&&g.length)for(var e=e+"?",k=0;k<g.length;k++){var m=g[k],n=b["_"+m];if(!("id"===m||"modelClass"===m))if(h.isString(n)||h.isNumber(n))j++&&(e+="&"),e+=m+"="+escape(n)}var o=(new HTTPRequest).init();c._xhrs[o.id]=a;o.bind("textload",c,c._process_xhr_result);o.setHeaders(c._headers);o.url=e;o.method="GET";o.contentType=
"application/json";o.send()}}catch(p){console.error("LocalStorate.load failed. "+p.toString())}}var c=this;if(a)b(a);else for(a in this.__models__)b(a)},_load_jsonp:function(a){function b(a){try{var b=c.__models__[a];if(b){var e=c._url+a+".json",g=b.getModelProperties(),j=0;if(g&&g.length)for(var e=e+"?",k=0;k<g.length;k++){var m=g[k],n=b["_"+m];if(!("id"===m||"modelClass"===m))if(h.isString(n)||h.isNumber(n))j++&&(e+="&"),e+=m+"="+escape(n)}var o=(new X).init();c._xhrs[o.id]=a;o.bind("jsonload",
c,c._process_json_result);o.url=e;o.send()}}catch(p){console.error("LocalStorate.load failed. "+p.toString())}}var c=this;if(a)b(a);else for(a in this.__models__)b(a)},_sync:function(){},_process_xhr_result:function(a){var b=a.data,a=a.src,c=this._xhrs[a.id];a.unbind("textload",this,this._process_xhr_result);k.util.free(a);delete this._xhrs[a.id];if(!b)return console.error("Failed to parse rss document that is null."),!1;if(a=this.__models__[c])a.parseJSON(b),this.propagate("load",a)},_process_json_result:function(a){var b=
a.data,a=a.src,c=this._xhrs[a.id];a.unbind("textload",this,this._process_json_result);k.util.free(a);delete this._xhrs[a.id];if(a=this.__models__[c])a.parseData(b),a.change(),this.propagate("load",a)}};k.util.extendClass(r,s);k.util.defineClassProperties(r,{url:{set:function(a){k.util.isString(a)&&(this._url=a)},get:function(){return this._url}},mode:{set:function(a){if(0===a||1===a)this._mode=a}}});k.core.RestStorage=r})(window);
