/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(q,m){function j(a){this.parent=i.Object;this.parent(a);this.constructor=j}function r(a){a?(this.url=a.getAttribute("url"),this.length=a.getAttribute("length"),this.type=a.getAttribute("type")):this.type=this.length=this.url=null}function s(a){a?(this.isPermaLink=a.getAttribute("isPermaLink"),this.value=a.childNodes[0].nodeValue):this.value=this.isPermaLink=null}function t(a){a?(this.url=a.getAttribute("url"),this.value=a.childNodes[0].nodeValue):this.value=this.url=null}function n(a){for(var b=
"title,link,description,author,comments,pubDate".split(","),d="_title,_link,_description,_author,_comments,_pub_date".split(","),c=null,g=0;g<b.length;g++)if(c=a.getElementsByTagName(b[g])[0])this[d[g]]=c.childNodes[0].nodeValue;this._category=new o(a.getElementsByTagName("category")[0]);this._enclosure=new r(a.getElementsByTagName("enclosure")[0]);this._guid=new s(a.getElementsByTagName("guid")[0]);this._source=new t(a.getElementsByTagName("source")[0]);if(this._image=new p(a.getElementsByTagName("content")[0]))this._image_url=
this.image.url}function o(a){a?(this.domain=a.getAttribute("domain"),this.value=a.childNodes[0].nodeValue):this.value=this.domain=null}function p(a){if(a){imgAttribs="url,title,link,width,height,description".split(",");for(var b=0;b<imgAttribs.length;b++)a.getAttribute(imgAttribs[b])&&(this[imgAttribs[b]]=a.getAttribute(imgAttribs[b]))}else this.description=this.height=this.width=this.link=this.url=null}var k=q.vs,e=k.util,i=k.core,l=k.data;j.prototype={_src:"",_anchor:"",_query:"",_file:"",_directory:"",
_path:"",_relative:"",_port:0,_host:"",_password:"",_user:"",_authority:"",_protocol:"",_query_key:null,__options:{strictMode:!1,key:"_source,_protocol,_authority,_userInfo,_user,_password,_host,_port,_relative,_path,_directory,_file,_query,_anchor".split(","),q:{name:"_query_key",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}},
parse:function(a){if(e.isString(a)){this._src=a;for(var b=this.__options,a=b.parser[b.strictMode?"strict":"loose"].exec(a),d=14,c=this;d--;)this[b.key[d]]=a[d]||"";this[b.q.name]={};this[b.key[12]].replace(b.q.parser,function(a,d,e){d&&(c[b.q.name][d]=e)});this.propertyChange("src")}}};e.extendClass(j,i.Object);e.defineClassProperties(j,{src:{set:function(a){e.isString(a)&&this.parse(a)},get:function(){return this._src}},anchor:{get:function(){return this._anchor}},query:{get:function(){return this._query}},
queryKey:{get:function(){return this._query_key}},file:{get:function(){return this._file}},directory:{get:function(){return this._directory}},path:{get:function(){return this._path}},port:{get:function(){return this._port}},relative:{get:function(){return this._relative}},host:{get:function(){return this._host}},password:{get:function(){return this._password}},user:{get:function(){return this._user}},authority:{get:function(){return this._authority}},protocol:{get:function(){return this._protocol}}});
l.URL=j;n.prototype={_title:"",_link:"",_description:"",_author:"",_comments:"",_pub_date:"",_category:null,_enclosure:null,_guid:null,_source:null,_image:null,_image_url:"",_category:null,toString:function(){return this.title}};e.defineClassProperties(n,{title:{get:function(){return this._title}},link:{get:function(){return this._link}},description:{get:function(){return this._description}},author:{get:function(){return this._author}},comments:{get:function(){return this._comments}},pubDate:{get:function(){return this._pub_date}},
category:{get:function(){return this._category}},enclosure:{get:function(){return this._enclosure}},guid:{get:function(){return this._guid}},source:{get:function(){return this._source}},image:{get:function(){return this._image}},imageUrl:{get:function(){return this._image_url}}});RSSFeed=function(a){this.parent=k.core.EventSource;this.parent(a);this.constructor=RSSFeed};RSSFeed.prototype={_items:null,_title:null,_link:null,_description:null,_language:null,_copyright:null,_managing_editor:null,_web_master:null,
_pub_date:null,_last_build_date:null,_generator:null,_docs:null,_ttl:null,_rating:null};e.extendClass(RSSFeed,i.EventSource);e.defineClassProperties(RSSFeed,{items:{get:function(){return this._items}},title:{get:function(){return this._title}},link:{get:function(){return this._link}},description:{get:function(){return this._description}},language:{get:function(){return this._language}},copyright:{get:function(){return this._copyright}},managingEditor:{get:function(){return this._managing_editor}},
webMaster:{get:function(){return this._web_master}},pubDate:{get:function(){return this._pub_date}},lastBuildDate:{get:function(){return this._last_build_date}},generator:{get:function(){return this._generator}},docs:{get:function(){return this._docs}},rating:{get:function(){return this._rating}},image:{get:function(){return this._image}},imageUrl:{get:function(){return this._image_url}},category:{get:function(){return this._category}}});RSSRequester=function(a){this.parent=RSSFeed;this.parent(a);
this.constructor=RSSRequester;this._rss=this};RSSRequester.prototype={_url:"",_rss:null,initComponent:function(){RSSFeed.prototype.initComponent.call(this);this._xhr=new i.HTTPRequest;this._xhr.init();this._xhr.bind("xmlload",this,this.processRSS);this._xhr.bind("loaderror",this,this.processError)},destructor:function(){this._xhr.unbind("xmlload",this,this.processRSS);this._xhr.unbind("loaderror",this,this.processError);free(this._xhr);RSSFeed.prototype.destructor.call(this)},loadRSS:function(){this._xhr.send()},
processRSS:function(a){a=a.data;if(!a&&(a=(new DOMParser).parseFromString(this._xhr.responseText,"application/xml"),!a))return console.error("Failed to parse rss document that is null."),this.propagate("rssloaderror","document null."),!1;var b=a;this._items=[];if(b){for(var a=b.getElementsByTagName("channel")[0],d=b.getElementsByTagName("item"),b=0;b<d.length;b++)Item=new n(d[b]),this._items.push(Item);for(var d="_title,_link,_description,_language,_copyright,_managing_editor,_web_master,_pub_date,_last_build_date,_generator,_docs,_ttl,_rating".split(","),
c="title,link,description,language,copyright,managingEditor,webMaster,pubDate,lastBuildDate,generator,docs,ttl,rating".split(","),g=null,b=0;b<c.length;b++)if(g=a.getElementsByTagName(c[b])[0])this[d[b]]=g.childNodes[0].nodeValue;this._category=new o(a.getElementsByTagName("category")[0]);this._image=new p(a.getElementsByTagName("image")[0])}else console.error("Failed to parse rss document that is null.");this.propagate("rssload",this);this.propertyChange()},processError:function(a){a&&a.data&&"failed"===
a.data.status?this.performAlternateRequest?this.performAlternateRequest():this.propagate("rssloaderror"):this.propagate("rssloaderror")},propertiesDidChange:function(){this.loadRSS()},performAlternateRequest:function(){var a=(new i.AjaxJSONP).init();a.url="http://pipes.yahoo.com/pipes/pipe.run?_id=9oyONQzA2xGOkM4FqGIyXQ&_render=json&feed="+escape(this._url);a.clbParamName="_callback";a.bind("jsonload",this,function(a){a=a.data;if(!a||!a.value||!a.value.items)this.propagate("rssloaderror","document null.");
else{a=a.value;this._pub_date=a.pubDate;this._items=[];itemElements=a.items;for(a=0;a<itemElements.length;a++)this._items.push(itemElements[a]);this.propagate("rssload",this);this.propertyChange()}});a.bind("loaderror",this,function(){this.propagate("rssloaderror")});a.send()}};e.extendClass(RSSRequester,RSSFeed);e.defineClassProperties(RSSRequester,{url:{set:function(a){e.isString(a)&&(this._url=a,this._xhr.url=a)}},rss:{get:function(){return this._rss}}});l.RSSFeed=RSSFeed;l.RSSRequester=RSSRequester;
var c=function(a){this.parent=i.EventSource;this.parent(a);this.constructor=c;c.loadService(this);this.ERROR_CODE=0;this._addresses=[];this._position=[]};c.loadService=function(a){c.__google_loaded__||(c.__google_wait_loaded__||(c.__google_wait_loaded__=!0,e.importFile("http://www.google.com/jsapi?key="+c.key+"&callback=vs.data.GoogleSearch.__on_loaded",null,null,"js")),a&&c._to_finish_init.push(a))};c.key=" ABQIAAAAE4BGaIh0t-7l9PDR7PA0rRR6KW34AlT62yZeC298tyhOjAL-9hQQpk22pW6ZfaCFEr3zjz2Q8rjqAw";c.__google_wait_loaded__=
!1;c.__google_loaded__=!1;c._to_finish_init=[];c.LOCAL_SEARCH_ENGINE=1;c.VIDEO_SEARCH_ENGINE=2;c.__on_loaded=function(){google.load("search","1",{nocss:!0,callback:k.data.GoogleSearch.__on_search_loaded})};c.__on_search_loaded=function(){var a,b;c.__google_loaded__=!0;c.__google_wait_loaded__=!1;for(a=0,b=c._to_finish_init.length;a<b;a++)c._to_finish_init[a].finishInit();c._to_finish_init=null};c.ERROR_CODE_STR="No error,Unknown error,Unvalid parameters data,Error with google server,Connexion error,Unvalid google response".split(",");
c.prototype={__local_search:m,__video_search:m,__init_ok:!1,__engine_to_init:0,__end_init_clb:null,_engine_loaded:!1,_str_address:"",_addresses:null,_position:null,finishInit:function(){this.__init_ok=!0;this.__engine_to_init&&(this.setSearchEngine(this.__engine_to_init),this.__engine_to_init=0)},setSearchEngine:function(a){this.__init_ok?(a|c.LOCAL_SEARCH_ENGINE&&!this.__local_search&&(this.__local_search=new google.search.LocalSearch,this.__local_search.setResultSetSize(google.search.Search.SMALL_RESULTSET),
this.__local_search.setNoHtmlGeneration()),a|c.VIDEO_SEARCH_ENGINE&&!this.__video_search&&(this.__video_search=new google.search.VideoSearch,this.__video_search.setResultSetSize(google.search.Search.SMALL_RESULTSET),this.__video_search.setNoHtmlGeneration()),this._engine_loaded=!0,this.propagate("engineload"),this.propertyChange("engineLoaded")):this.__engine_to_init=a},_newGoogleLocalSearch:function(a,b){var d=this;this.__local_search.setSearchCompleteCallback(this,function(){b.call(d,d.__local_search.results)});
!a||"string"!==typeof a?(this.ERROR_CODE=2,b.call(d,null)):this.__local_search.execute(a)},_googleLocalSearch:function(a,b){if(this.__local_search)this._newGoogleLocalSearch(a,b);else if(!a||"string"!==typeof a)this.ERROR_CODE=2,b.call(this,null);else{var d=new XMLHttpRequest;d.open("GET","http://ajax.googleapis.com/ajax/services/search/local?v=1.0&q="+a,!1);d.send(null);4===d.readyState?(d=eval("("+d.responseText+")"),200!==d.responseStatus?(this.ERROR_CODE=3,b.call(this,null)):d.responseData?b.call(this,
d.responseData):(this.ERROR_CODE=5,b.call(this,null))):(this.ERROR_CODE=4,b.call(this,null))}},GPSCoordinateToAddress:function(a,b,d){if(this.__local_search)if(d||(d=this),!a||!a.length)this.ERROR_CODE=2,b.call(d,null);else{var c=this;this._googleLocalSearch(a[0]+","+a[1],function(a){if(a)if(0===a.length||!a[0])this.ERROR_CODE=5,b.call(d,null);else{c._addresses=[];var f={title:"",addressLine:"",streetAddress:"",city:"",region:"",country_code:"",postalCode:0};f.title=a[0].titleNoFormatting;f.addressLine=
a[0].addressLines.join(", ");f.streetAddress=a[0].streetAddress;f.city=a[0].city;f.region=a[0].region;f.country_code=a[0].country;f.postalCode=a[0].postalCode;f.locale=c.countryToLocal(f.country_code);c._addresses.push(f);b.call(d,f);c.propertyChange("addresses")}else this.ERROR_CODE=5,b.call(d,null)})}else console.error("The local search engine is not initialized")},countryToLocal:function(a){switch(a){case "US":return"en_US";case "GB":return"en_GB";case "FR":return"fr_FR";case "CA":return"fr_CA";
case m:return"en_US";default:return a.toLowerCase()}},addressToGPSCoordinate:function(a,b,d){if(this.__local_search){var c=[0,0];d||(d=this);if(!a||"string"!==typeof a)this.ERROR_CODE=2,b.call(d,null);else{var g=this;this._googleLocalSearch('"'+a+'"',function(a){a&&(a[0]?(c[0]=parseFloat(a[0].lat),c[1]=parseFloat(a[0].lng),g._position=c,b.call(d,c.slice()),g.propertyChange("position")):(this.ERROR_CODE=5,b.call(d,null)))})}}else console.error("The local search engine is not initialized")},searchAddress:function(a,
b,c){if(this.__local_search)if(c||(c=this),!a||"string"!==typeof a)this.ERROR_CODE=2,b.call(c,null);else{var e=this;this._googleLocalSearch('"'+a+'"',function(a){e._addresses=[];if(a){for(var f=0;f<a.length;f++){var h={};h.title=a[f].titleNoFormatting;h.addressLine=a[f].addressLines.join(", ");h.streetAddress=a[f].streetAddress;h.city=a[f].city;h.region=a[f].region;h.country_code=a[f].country;h.postalCode=a[f].postalCode;e._addresses.push(h)}b.call(c,e._addresses.slice())}else b.call(c,[]);e.propertyChange("addresses")})}else console.error("The local search engine is not initialized")}};
e.extendClass(c,i.EventSource);e.defineClassProperties(c,{strAddress:{set:function(a){if(e.isString(a)){this._str_address=a;var b=this;this.searchAddress(a,function(){b.addressToGPSCoordinate(a,function(){},this)},this)}}},addresses:{get:function(){return this._addresses}},position:{set:function(a){e.isArray(a)&&2===a.length&&e.isNumber(a[0])&&e.isNumber(a[1])&&this.GPSCoordinateToAddress(a,function(){},this)},get:function(){return this._position}},engineLoaded:{get:function(){return this._engine_loaded}}});
l.GoogleSearch=c})(window);
