/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(p,l){function i(a){this.parent=h.Object;this.parent(a);this.constructor=i}function q(a){a?(this.url=a.getAttribute("url"),this.length=a.getAttribute("length"),this.type=a.getAttribute("type")):this.type=this.length=this.url=null}function r(a){a?(this.isPermaLink=a.getAttribute("isPermaLink"),this.value=a.childNodes[0].nodeValue):this.value=this.isPermaLink=null}function s(a){a?(this.url=a.getAttribute("url"),this.value=a.childNodes[0].nodeValue):this.value=this.url=null}function m(a){for(var b=
"title,link,description,author,comments,pubDate".split(","),c="_title,_link,_description,_author,_comments,_pub_date".split(","),d=null,g=0;g<b.length;g++)if(d=a.getElementsByTagName(b[g])[0])this[c[g]]=d.childNodes[0].nodeValue;this._category=new n(a.getElementsByTagName("category")[0]);this._enclosure=new q(a.getElementsByTagName("enclosure")[0]);this._guid=new r(a.getElementsByTagName("guid")[0]);this._source=new s(a.getElementsByTagName("source")[0]);if(this._image=new o(a.getElementsByTagName("content")[0]))this._image_url=
this.image.url}function n(a){a?(this.domain=a.getAttribute("domain"),this.value=a.childNodes[0].nodeValue):this.value=this.domain=null}function o(a){if(a){imgAttribs="url,title,link,width,height,description".split(",");for(var b=0;b<imgAttribs.length;b++)a.getAttribute(imgAttribs[b])&&(this[imgAttribs[b]]=a.getAttribute(imgAttribs[b]))}else this.description=this.height=this.width=this.link=this.url=null}var j=p.vs,e=j.util,h=j.core,k=j.data;i.prototype={_src:"",_anchor:"",_query:"",_file:"",_directory:"",
_path:"",_relative:"",_port:0,_host:"",_password:"",_user:"",_authority:"",_protocol:"",_query_key:null,__options:{strictMode:!1,key:"_source,_protocol,_authority,_userInfo,_user,_password,_host,_port,_relative,_path,_directory,_file,_query,_anchor".split(","),q:{name:"_query_key",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}},
parse:function(a){if(e.isString(a)){this._src=a;for(var b=this.__options,a=b.parser[b.strictMode?"strict":"loose"].exec(a),c=14;c--;)this[b.key[c]]=a[c]||"";this[b.q.name]={};this[b.key[12]].replace(b.q.parser,function(a,c,d){c&&(this[b.q.name][c]=d)});this.propertyChange("src")}}};e.extendClass(i,h.Object);e.defineClassProperties(i,{src:{set:function(a){e.isString(a)&&this.parse(a)},get:function(){return this._src}},anchor:{get:function(){return this._anchor}},query:{get:function(){return this._query}},
queryKey:{get:function(){return this._query_key}},file:{get:function(){return this._file}},directory:{get:function(){return this._directory}},path:{get:function(){return this._path}},port:{get:function(){return this._port}},relative:{get:function(){return this._relative}},host:{get:function(){return this._host}},password:{get:function(){return this._password}},user:{get:function(){return this._user}},authority:{get:function(){return this._authority}},protocol:{get:function(){return this._protocol}}});
k.URL=i;m.prototype={_title:"",_link:"",_description:"",_author:"",_comments:"",_pub_date:"",_category:null,_enclosure:null,_guid:null,_source:null,_image:null,_image_url:"",_category:null,toString:function(){return this.title}};e.defineClassProperties(m,{title:{get:function(){return this._title}},link:{get:function(){return this._link}},description:{get:function(){return this._description}},author:{get:function(){return this._author}},comments:{get:function(){return this._comments}},pubDate:{get:function(){return this._pub_date}},
category:{get:function(){return this._category}},enclosure:{get:function(){return this._enclosure}},guid:{get:function(){return this._guid}},source:{get:function(){return this._source}},image:{get:function(){return this._image}},imageUrl:{get:function(){return this._image_url}}});RSSFeed=function(a){this.parent=j.core.EventSource;this.parent(a);this.constructor=RSSFeed};RSSFeed.prototype={_items:null,_title:null,_link:null,_description:null,_language:null,_copyright:null,_managing_editor:null,_web_master:null,
_pub_date:null,_last_build_date:null,_generator:null,_docs:null,_ttl:null,_rating:null};e.extendClass(RSSFeed,h.EventSource);e.defineClassProperties(RSSFeed,{items:{get:function(){return this._items}},title:{get:function(){return this._title}},link:{get:function(){return this._link}},description:{get:function(){return this._description}},language:{get:function(){return this._language}},copyright:{get:function(){return this._copyright}},managingEditor:{get:function(){return this._managing_editor}},
webMaster:{get:function(){return this._web_master}},pubDate:{get:function(){return this._pub_date}},lastBuildDate:{get:function(){return this._last_build_date}},generator:{get:function(){return this._generator}},docs:{get:function(){return this._docs}},rating:{get:function(){return this._rating}},image:{get:function(){return this._image}},imageUrl:{get:function(){return this._image_url}},category:{get:function(){return this._category}}});RSSRequester=function(a){this.parent=RSSFeed;this.parent(a);
this.constructor=RSSRequester;this._rss=this};RSSRequester.prototype={_url:"",_rss:null,initComponent:function(){RSSFeed.prototype.initComponent.call(this);this._xhr=new h.HTTPRequest;this._xhr.init();this._xhr.bind("xmlload",this,this.processRSS)},destructor:function(){this._xhr.unbind("xmlload",this,this.processRSS);free(this._xhr);RSSFeed.prototype.destructor.call(this)},loadRSS:function(){this._xhr.send()},processRSS:function(a){a=a.data;if(!a&&(a=(new DOMParser).parseFromString(this._xhr.responseText,
"application/xml"),!a))return console.error("Failed to parse rss document that is null."),this.propagate("rssloaderror","document null."),!1;var b=a;this._items=[];if(b){for(var a=b.getElementsByTagName("channel")[0],c=b.getElementsByTagName("item"),b=0;b<c.length;b++)Item=new m(c[b]),this._items.push(Item);for(var c="_title,_link,_description,_language,_copyright,_managing_editor,_web_master,_pub_date,_last_build_date,_generator,_docs,_ttl,_rating".split(","),d="title,link,description,language,copyright,managingEditor,webMaster,pubDate,lastBuildDate,generator,docs,ttl,rating".split(","),
g=null,b=0;b<d.length;b++)if(g=a.getElementsByTagName(d[b])[0])this[c[b]]=g.childNodes[0].nodeValue;this._category=new n(a.getElementsByTagName("category")[0]);this._image=new o(a.getElementsByTagName("image")[0])}else console.error("Failed to parse rss document that is null.");this.propagate("rssload",this);this.propertyChange()},propertiesDidChange:function(){this.loadRSS()}};e.extendClass(RSSRequester,RSSFeed);e.defineClassProperties(RSSRequester,{url:{set:function(a){e.isString(a)&&(this._url=
a,this._xhr.url=a)}},rss:{get:function(){return this._rss}}});k.RSSFeed=RSSFeed;k.RSSRequester=RSSRequester;var d=function(a){this.parent=h.EventSource;this.parent(a);this.constructor=d;d.loadService(this);this.ERROR_CODE=0};d.loadService=function(a){d.__google_loaded__||(d.__google_wait_loaded__||(d.__google_wait_loaded__=!0,e.importFile("http://www.google.com/jsapi?key="+d.key+"&callback=vs.data.GoogleSearch.__on_loaded",null,null,"js")),a&&d._to_finish_init.push(a))};d.key=" ABQIAAAAE4BGaIh0t-7l9PDR7PA0rRR6KW34AlT62yZeC298tyhOjAL-9hQQpk22pW6ZfaCFEr3zjz2Q8rjqAw";
d.__google_wait_loaded__=!1;d.__google_loaded__=!1;d._to_finish_init=[];d.LOCAL_SEARCH_ENGINE=1;d.VIDEO_SEARCH_ENGINE=2;d.__on_loaded=function(){google.load("search","1",{nocss:!0,callback:j.data.GoogleSearch.__on_search_loaded})};d.__on_search_loaded=function(){var a,b;d.__google_loaded__=!0;d.__google_wait_loaded__=!1;for(a=0,b=d._to_finish_init.length;a<b;a++)d._to_finish_init[a].finishInit();d._to_finish_init=null};d.ERROR_CODE_STR="No error,Unknown error,Unvalid parameters data,Error with google server,Connexion error,Unvalid google response".split(",");
d.prototype={__local_search:l,__video_search:l,__init_ok:!1,__engine_to_init:0,__end_init_clb:null,finishInit:function(){this.__init_ok=!0;this.__engine_to_init&&(this.setSearchEngine(this.__engine_to_init),this.__engine_to_init=0)},setSearchEngine:function(a){this.__init_ok?(a|d.LOCAL_SEARCH_ENGINE&&!this.__local_search&&(this.__local_search=new google.search.LocalSearch,this.__local_search.setResultSetSize(google.search.Search.SMALL_RESULTSET),this.__local_search.setNoHtmlGeneration()),a|d.VIDEO_SEARCH_ENGINE&&
!this.__video_search&&(this.__video_search=new google.search.VideoSearch,this.__video_search.setResultSetSize(google.search.Search.SMALL_RESULTSET),this.__video_search.setNoHtmlGeneration()),this.propagate("engineload")):this.__engine_to_init=a},_newGoogleLocalSearch:function(a,b){var c=this;this.__local_search.setSearchCompleteCallback(this,function(){b.call(c,c.__local_search.results)});!a||"string"!==typeof a?(this.ERROR_CODE=2,b.call(c,null)):this.__local_search.execute(a)},_googleLocalSearch:function(a,
b){if(this.__local_search)this._newGoogleLocalSearch(a,b);else if(!a||"string"!==typeof a)this.ERROR_CODE=2,b.call(this,null);else{var c=new XMLHttpRequest;c.open("GET","http://ajax.googleapis.com/ajax/services/search/local?v=1.0&q="+a,!1);c.send(null);4===c.readyState?(c=eval("("+c.responseText+")"),200!==c.responseStatus?(this.ERROR_CODE=3,b.call(this,null)):c.responseData?b.call(this,c.responseData):(this.ERROR_CODE=5,b.call(this,null))):(this.ERROR_CODE=4,b.call(this,null))}},GPSCoordinateToAddress:function(a,
b,c){if(this.__local_search)if(c||(c=this),!a||!a.length)this.ERROR_CODE=2,b.call(c,null);else{var d=this;this._googleLocalSearch(a[0]+","+a[1],function(a){if(a)if(0===a.length||!a[0])this.ERROR_CODE=5,b.call(c,null);else{var f={title:"",addressLine:"",streetAddress:"",city:"",region:"",country_code:"",postalCode:0};f.title=a[0].titleNoFormatting;f.addressLine=a[0].addressLines.join(", ");f.streetAddress=a[0].streetAddress;f.city=a[0].city;f.region=a[0].region;f.country_code=a[0].country;f.postalCode=
a[0].postalCode;f.locale=d.countryToLocal(f.country_code);b.call(c,f)}else this.ERROR_CODE=5,b.call(c,null)})}else console.error("The local search engine is not initialized")},countryToLocal:function(a){switch(a){case "US":return"en_US";case "GB":return"en_GB";case "FR":return"fr_FR";case "CA":return"fr_CA";case l:return"en_US";default:return a.toLowerCase()}},addressToGPSCoordinate:function(a,b,c){if(this.__local_search){var d=[0,0];c||(c=this);!a||"string"!==typeof a?(this.ERROR_CODE=2,b.call(c,
null)):this._googleLocalSearch('"'+a+'"',function(a){a&&(a[0]?(d[0]=parseFloat(a[0].lat),d[1]=parseFloat(a[0].lng),b.call(c,d)):(this.ERROR_CODE=5,b.call(c,null)))})}else console.error("The local search engine is not initialized")},searchAddress:function(a,b,c){this.__local_search?(c||(c=this),!a||"string"!==typeof a?(this.ERROR_CODE=2,b.call(c,null)):this._googleLocalSearch('"'+a+'"',function(a){var d=[];if(a)for(var f=0;f<a.length;f++){var e={};e.title=a[f].titleNoFormatting;e.addressLine=a[f].addressLines.join(", ");
e.streetAddress=a[f].streetAddress;e.city=a[f].city;e.region=a[f].region;e.country_code=a[f].country;e.postalCode=a[f].postalCode;d.push(e)}b.call(c,d)})):console.error("The local search engine is not initialized")}};e.extendClass(d,h.EventSource);k.GoogleSearch=d})(window);
