/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(n,l){function p(){b.InfoWindow=function(a,c,k,b,d){this.vs_map=a;this.id=c;this.type=k;this.setCoordinate(b,d);this.setValues({map:this.vs_map._gmap})};b.InfoWindow.prototype=new google.maps.OverlayView;b.InfoWindow.prototype.destructor=function(){this.setMap(null);this.vs_map=this.marker=l};b.InfoWindow.prototype.hide=function(){this.view&&(this.view.style.display="none")};b.InfoWindow.prototype.show=function(){this.view&&(this.view.style.display="block")};b.InfoWindow.prototype.setMarker=
function(a){this.marker&&this.unbind("position");this.marker=a;this.id=this.marker.id;this.type=this.marker.type;this.info=this.marker.info;this.bindTo("position",this.marker._gmarker,"position");this.instanciateView(this.type,this.info)};b.InfoWindow.prototype.setCoordinate=function(a,c){this.position&&delete this.position;this.position=new google.maps.LatLng(a,c)};b.InfoWindow.prototype.setType=function(a){this.type=a;this.instanciateView(this.type,this.info)};b.InfoWindow.prototype.setInfo=function(a){this.info=
a;this.instanciateView(this.type,this.info)};b.InfoWindow.prototype.instanciateView=function(a,c){var k=h.createElement("div"),i=b._anotation_templates_[a];i||(i=b._anotation_templates_["default"]);i=i.infoWindow;if(c)for(key in c)var d=c[key],d=d?d:"",i=i.replace("{"+key+"}",d);k.innerHTML=i;this.view||this.createView();this.view.innerHTML=k.firstElementChild.innerHTML;this.view.className=k.firstElementChild.className};b.InfoWindow.prototype.createView=function(){this.view||(this.view=h.createElement("div"),
this.view.addEventListener(f.POINTER_START,this))};b.InfoWindow.prototype.handleEvent=function(a){var c=this;switch(a.type){case f.POINTER_START:if(f.EVENT_SUPPORT_TOUCH&&1<a.touches.length)break;h.addEventListener(f.POINTER_END,this);h.addEventListener(f.POINTER_MOVE,this);this.__start_x=f.EVENT_SUPPORT_TOUCH?a.touches[0].pageX:a.pageX;this.__start_y=f.EVENT_SUPPORT_TOUCH?a.touches[0].pageY:a.pageY;this.marker&&this.removeMapEvent();d.addClassName(this.view,"selected");return!1;case f.POINTER_MOVE:var b=
(f.EVENT_SUPPORT_TOUCH?a.touches[0].pageY:a.pageY)-this.__start_y;if(10>Math.abs((f.EVENT_SUPPORT_TOUCH?a.touches[0].pageX:a.pageX)-this.__start_x)+Math.abs(b))return a.preventDefault(),!1;h.removeEventListener(f.POINTER_END,this);h.removeEventListener(f.POINTER_MOVE,this);this.marker&&setTimeout(function(){c.initMapEvent()},0);d.removeClassName(this.view,"selected");return!1;case f.POINTER_END:return a.stopPropagation(),a.preventDefault(),h.removeEventListener(f.POINTER_END,this),h.removeEventListener(f.POINTER_MOVE,
this),this.marker&&setTimeout(function(){c.initMapEvent()},0),d.removeClassName(this.view,"selected"),this.vs_map.annotationSelect(this.id),!1}};b.InfoWindow.prototype.onAdd=function(){this.view||this.createView();this.getPanes().floatPane.appendChild(this.view);var a=this;this.listeners_=[google.maps.event.addListener(this,"position_changed",function(){a.draw()})]};b.InfoWindow.prototype.onRemove=function(){this.view.parentNode.removeChild(this.view);for(var a=0,c=this.listeners_.length;a<c;++a)google.maps.event.removeListener(this.listeners_[a])};
b.InfoWindow.prototype.draw=function(){var a=this.getProjection().fromLatLngToDivPixel(this.get("position")),c=this.view;c.style.display="block";c.style.visibility="hidden";var b=0;if(this.marker){var b=10,d=this.marker._gmarker.getIcon();d&&(b+=d.size.height)}setTimeout(function(){var d=c.offsetHeight;c.style.left=a.x-Math.ceil(c.offsetWidth/2)+"px";c.style.top=a.y-d-b+"px";c.style.visibility="visible"},0)};b.InfoWindow.prototype.initMapEvent=function(){if(!this.map_listener){var a=this;this.map_listener=
google.maps.event.addListener(this.vs_map._gmap,"click",function(){a.hide()})}};b.InfoWindow.prototype.removeMapEvent=function(){this.map_listener&&(google.maps.event.removeListener(this.map_listener),this.map_listener=l)};b.InfoWindowWithMarker=function(a){this.vs_map=a;this.setValues({map:this.vs_map._gmap});this.initMapEvent()};d.extendClass(b.InfoWindowWithMarker,b.InfoWindow)}function j(a){this.parent=e.ui.View;this.parent(a);this.constructor=j;this.__indicators_list={}}var h=n.document,e=n.vs,
d=e.util,f=e.core,m=e.ui,o=e.ext.ui,b=function(a){this.parent=e.ui.View;this.parent(a);this.constructor=b;this._center=[];this._center[0]=48.83763339660763;this._center[1]=2.3397827148437544;b.__google_loaded__||(b.__google_wait_loaded__||(b.__google_wait_loaded__=!0,e.util.importFile("http://maps.google.com/maps/api/js?sensor=true&callback=vs.ext.ui.GMap.__on_laoded",null,null,"js")),b._to_finish_init.push(this));this.__annotations={}};b.NO_MARKER=0;b.DEVICE_IMAGE_MARKER=1;b.IMAGE_MARKER=2;b._anotation_templates_=
{};b._anotation_templates_["default"]={marker:{type:b.DEVICE_IMAGE_MARKER},infoWindow:'<div class="vs_ext_ui_gmap_info">    <div>{title}</div>    <div>{subtitle}</div>  </div>'};b.__google_wait_loaded__=!1;b.__google_loaded__=!1;b._to_finish_init=[];b.__on_laoded=function(){var a,c;b.__google_loaded__=!0;b.__google_wait_loaded__=!1;p();for(a=0,c=b._to_finish_init.length;a<c;a++)b._to_finish_init[a].finishInit();b._to_finish_init=null};b.prototype={_zoom:10,_tilt:-1,_scroll:!0,_tap_to_zoom:!0,_max_zoom:20,
_min_zoom:1,_zoom_control:!1,_street_view_control:!1,_center:null,_gmap:null,__init_finished:!1,__annotations:null,destructor:function(){delete this._gmap;e.ui.View.prototype.destructor.call(this)},initComponent:function(){e.ui.View.prototype.initComponent.call(this);b.__google_loaded__&&this.finishInit()},finishInit:function(){var a={zoom:this._zoom,center:new google.maps.LatLng(this._center[0],this._center[1]),disableDefaultUI:!0,draggable:this._scroll,maxZoom:this._max_zoom,minZoom:this._min_zoom,
disableDoubleClickZoom:!this._tap_to_zoom,streetViewControl:this._street_view_control,streetViewControlOptions:{position:google.maps.ControlPosition.LEFT_TOP},zoomControl:this._zoom_control,zoomControlOptions:{position:google.maps.ControlPosition.LEFT_BOTTOM,style:google.maps.ZoomControlStyle.SMALL},mapTypeControlOptions:{style:google.maps.ControlPosition.HORIZONTAL_BAR},mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.DROPDOWN_MENU}};this._gmap=
new google.maps.Map(this.view,a);var c=this;setTimeout(function(){c.__init_did_finish()},0)},__init_did_finish:function(){this.__init_finished=!0;this.streetViewControl=this._street_view_control;this.zoomControl=this._zoom_control;this.propagate("mapload")},isReady:function(){return this.__init_finished},getGoogleMapObject:function(){return this._gmap},showCenterMark:function(){this._center_mark||(this._center_mark=new google.maps.Marker({position:new google.maps.LatLng(this._center[0],this._center[1]),
icon:"mapCenter.png"}));this._center_mark.setGMap(this._gmap)},hideCenterMark:function(){this._center_mark&&this._center_mark.setGMap(null)},addAnnotation:function(a,c,k,i,e){if(this.__init_finished){if(!d.isString(a)||!a)a=f.createId();c=new b.Annotation(this,a,c,k,i,e);return this.__annotations[a]=c}},setAnnotationTemplate:function(a,c,k){if(d.isString(a)||a){var i=b._anotation_templates_["default"];b._anotation_templates_[a]={marker:d.clone(c?c:i.marker),infoWindow:d.clone(k?k:i.infoWindow)}}},
removeAnnotation:function(a){!d.isString(a)&&a.id&&(a=a.id);var c=this.__annotations[a];c&&(d.free(c),delete this.__annotations[a])},removeAnnotations:function(){for(var a in this.__annotations)this.removeAnnotation(a)},annotationSelect:function(a){this.propagate("annotationselect",a)}};d.extendClass(b,e.ui.View);d.defineClassProperties(b,{scroll:{set:function(a){this._scroll=a?!0:!1;this.__init_finished&&this._gmap.setOptions({draggable:this._scroll})},get:function(){return this._scroll}},tapToZoom:{set:function(a){this._tap_to_zoom=
a?!0:!1;this.__init_finished&&this._gmap.setOptions({disableDoubleClickZoom:!this._tap_to_zoom})},get:function(){return this._tap_to_zoom}},maxZoom:{set:function(a){e.util.isNumber(a)&&(this._max_zoom=a,this.__init_finished&&this._gmap.setOptions({maxZoom:this._max_zoom}))},get:function(){return this._max_zoom}},minZoom:{set:function(a){e.util.isNumber(a)&&(this._min_zoom=a,this.__init_finished&&this._gmap.setOptions({maxZoom:this._min_zoom}))},get:function(){return this._min_zoom}},zoomControl:{set:function(a){this._zoom_control=
a?!0:!1;this.__init_finished&&this._gmap.setOptions({zoomControl:this._zoom_control})},get:function(){return this._zoom_control}},zoom:{set:function(a){e.util.isNumber(a)&&this.__init_finished&&(a=Math.floor(a),a!==this._zoom&&(this._zoom=a,this._gmap.setZoom(this._zoom)))},get:function(){return!this._gmap?-1:this._zoom=this._gmap.getZoom()}},tilt:{set:function(a){e.util.isNumber(a)&&this.__init_finished&&(this._tilt=a,this._gmap.setTilt(a))},get:function(){return!this._gmap?-1:this._tilt=this._gmap.getTilt()}},
streetViewControl:{set:function(a){this._street_view_control=a?!0:!1;this.__init_finished&&this._gmap.setOptions({streetViewControl:this._street_view_control})},get:function(){return this._street_view_control}},center:{set:function(a){this.__init_finished&&a&&e.util.isArray(a)&&2===a.length&&e.util.isNumber(a[0])&&e.util.isNumber(a[1])&&(this._center[0]=a[0],this._center[1]=a[1],a=new google.maps.LatLng(a[0],a[1]),this._gmap.setCenter(a),this._center_mark&&this._center_mark.setPosition(a))},get:function(){if(!this._gmap)return[0,
0];var a=this._gmap.getCenter();this._center[0]=a.lat();this._center[1]=a.lng();return this._center.slice()}}});b.Annotation=function(a,c,d,i,f,h){this.map=a;this.id=c;this.info=f;this.type=h?h:"default";this._coordinate=new google.maps.LatLng(d,i);var g=b._anotation_templates_[this.type];g||(g=b._anotation_templates_["default"]);this.image=null;g.marker.type==b.DEVICE_IMAGE_MARKER?(g=n.deviceConfiguration.os,this.image=g==e.core.DeviceConfiguration.OS_SYMBIAN?new google.maps.MarkerImage("css/kit/symbian_marker.png",
new google.maps.Size(48,51),new google.maps.Point(0,0),new google.maps.Point(24,48)):g==e.core.DeviceConfiguration.OS_WP7?new google.maps.MarkerImage("css/kit/wp7_marker.png",new google.maps.Size(15,31),new google.maps.Point(0,0),new google.maps.Point(0,31)):new google.maps.MarkerImage("css/kit/ios_marker.png",new google.maps.Size(32,41),new google.maps.Point(0,0),new google.maps.Point(8,36))):g.marker.type==b.IMAGE_MARKER&&(this.image=new google.maps.MarkerImage(g.marker.url));if(this.image){this._gmarker=
new google.maps.Marker({position:this._coordinate,icon:this.image,map:a._gmap,animation:google.maps.Animation.DROP});var j=this;google.maps.event.addListener(this._gmarker,"click",function(){j.onselect()})}else this._infoWindow=new b.InfoWindow(this.map,c,d,i,h),this._infoWindow.setCoordinate(d,i),this._infoWindow.setInfo(f)};b.Annotation.prototype={destructor:function(){this._gmarker&&(this._gmarker.setMap(null),delete this._gmarker);this._infoWindow&&free(this._infoWindow);this.image&&delete this.image;
delete this._coordinate;this.map=l},onselect:function(){this.showInfoWindow()},showInfoWindow:function(){this.map._infoWindow||(this.map._infoWindow=new b.InfoWindowWithMarker(this.map));this.map._infoWindow.setMarker(this)}};d.defineClassProperties(b.Annotation,{coordinate:{set:function(a){if(d.isArray(a)||2==a.length)delete this._coordinate,this._coordinate=new google.maps.LatLng(a[0],a[1]),this._gmarker&&this._gmarker.setPosition(this._coordinate)},get:function(){return[this._coordinate.lat(),
this._coordinate.lng()]}},info:{set:function(a){this._info=a;this._infoWindow&&this._infoWindow.setInfo(a)},get:function(){return this._info}}});o.GMap=b;j.HORIZONTAL=e.fx.SlideController.HORIZONTAL;j.VERTICAL=e.fx.SlideController.VERTICAL;j.prototype={_indicators_visibility:!0,_delegate:null,_orientation:j.HORIZONTAL,_slideController:null,__indicators:null,__selected_indicator:null,__indicators_list:null,__indicators_timer:0,destructor:function(){d.free(this._slideController);e.ui.View.prototype.destructor.call(this)},
initComponent:function(){e.ui.View.prototype.initComponent.call(this);this.__indicators=this.view.querySelector(".vs_ext_ui_carousel >.indicators");e.util.addClassName(this.__indicators,"horizontal");this._slideController=new e.fx.SlideController(this);this._slideController.delegate=this;this._slideController.isTactile=!0;this._slideController.init()},refresh:function(){this._slideController&&this._slideController.refresh&&this._slideController.refresh();e.ui.View.prototype.refresh.call(this)},controllerViewWillChange:function(a,
c){this.__indicators_timer&&(clearTimeout(this.__indicators_timer),__indicators_timer=0);var b=c.id,d=this;this.__indicators_timer=setTimeout(function(){d.__selected_indicator&&e.util.removeClassName(d.__selected_indicator,"selected");d.__selected_indicator=d.__indicators_list[b];e.util.addClassName(d.__selected_indicator,"selected")},500);this._delegate&&this._delegate.carouselViewWillChange&&this._delegate.carouselViewWillChange(c)},add:function(a){e.ui.View.prototype.add.call(this,a,"children");
this.push(a)},push:function(a,c){if(!this.isChild(a)||!this._slideController.isStateExit(a.id)){var b,d=this._slideController.push(a,c);b=h.createElement("span");this.__indicators.appendChild(b);this.__indicators_list[d]=b}},remove:function(a){a&&a.id&&(this.__indicators.removeChild(this.__indicators_list[a.id]),delete this.__indicators_list[a.id],e.ui.View.prototype.remove.call(this,a))},removeAllChildren:function(){for(var a in this.__indicators_list)this.remove(e.core.Object._obs[a])},goToNextView:function(){this._slideController.goToNextView()},
goToPreviousView:function(){this._slideController.goToPreviousView()},goToView:function(a){this._slideController.goToViewId(a)},goToViewAt:function(a){this._slideController.goToViewAt(a)}};d.extendClass(j,e.ui.View);d.defineClassProperties(j,{size:{set:function(a){a&&d.isArray(a)&&2===a.length&&d.isNumber(a[0])&&d.isNumber(a[1])&&(this._size[0]=a[0],this._size[1]=a[1],this.view&&(this._updateSize(),this._slideController&&this._slideController.refresh&&this._slideController.refresh()))},get:function(){var a=
this.view;a&&a.parentNode&&(this._size[0]=a.offsetWidth,this._size[1]=a.offsetHeight);return this._size.slice()}},delegate:{set:function(a){this._delegate=a}},indicatorsVisibility:{set:function(a){a?(this._indicators_visibility=!0,__setVisible(this.__indicators,!0)):(this._indicators_visibility=!1,__setVisible(this.__indicators,!1))}},orientation:{set:function(a){a!==j.HORIZONTAL&&a!==j.VERTICAL||this._orientation===a||(a===j.HORIZONTAL?(e.util.removeClassName(this.__indicators,"vertical"),e.util.addClassName(this.__indicators,
"horizontal")):(e.util.removeClassName(this.__indicators,"horizontal"),e.util.addClassName(this.__indicators,"vertical")),this._orientation=a,this._slideController.orientation=a)},get:function(){return this._orientation}}});o.Carousel=j;var g=function(a){this.parent=m.View;this.parent(a);this.constructor=g;this.__ab_a_items=[]};g.STRETCH_NONE=0;g.STRETCH_FILL=1;g.prototype={_stretch:g.STRETCH_NONE,__ab_a_items:l,__ab_a_current_index:l,__ab_a_head_height:33,push:function(a,c){a&&(this.add(a),this.setPanelTitle(this._getIndexForChild(a),
c))},add:function(a){if(a){var c;a.id||(a.id=e.core.createId());c=this.__ab_a_items.length;c=this._createView(a,"Section "+(c+1),c);this.view.appendChild(c.dt);m.View.prototype.add.call(this,a,"children",c.dd);this.__ab_a_items.push(c);this._updateSizePanel()}},remove:function(a){var c=this._getIndexForChild(a),b;-1!==c&&(m.View.prototype.remove.call(this,a),b=this.__ab_a_items[c],b.dd.removeChild(a.view),this.view.removeChild(b.dt),b.dt.removeEventListener(f.POINTER_START,this),delete b.dt,delete b.dd,
delete b,this.__ab_a_items.remove(c),c===this.__ab_a_current_index?(this.__ab_a_current_index=null,this.expandPanel(0)):this._updateSizePanel())},_getIndexForChild:function(a){if(!a)return-1;var c,b;for(c=0;c<this.__ab_a_items.length;c++)if((b=this.__ab_a_items[c])&&b.dd&&b.dd.__child===a)return c;return-1},_createView:function(a,c,b){var e={};e.dt=h.createElement("dt");d.setElementInnerText(e.dt,c);e.title=c;e.dd=h.createElement("dd");this._stretch===g.STRETCH_FILL&&(a.position=[0,0]);e.dd.appendChild(a.view);
c=b?"collapsed":"expanded";e.dd.setAttribute("class",c);e.dt.setAttribute("class",c);e.dd.__child=a;e.child=a;"collapsed"===c?(e.dd.style.width="100%",e.dd.style.height="0px"):(e.dd.style.width="100%",e.dd.style.height=a._size[1]+"px",this.__ab_a_current_index=b);this._stretch===g.STRETCH_FILL&&(a.size=[this._size[0]-2,this._size[1]]);e.dt.__dd=e.dd;e.dt.__index=b;e.dt.addEventListener(f.POINTER_START,this);return e},expandPanel:function(a){var c,b;if(d.isNumber(a)&&0<=a&&a<this.__ab_a_items.length){if(a!==
this.__ab_a_current_index){if(c=this.__ab_a_items[this.__ab_a_current_index])d.removeClassName(c.dt,"expanded"),d.addClassName(c.dt,"collapsed"),d.removeClassName(c.dd,"expanded"),d.addClassName(c.dd,"collapsed"),c.dd.style.height="0px";c=this.__ab_a_items[a];d.removeClassName(c.dt,"collapsed");d.addClassName(c.dt,"expanded");d.removeClassName(c.dd,"collapsed");d.addClassName(c.dd,"expanded");this.__ab_a_current_index=a;this._updateSizePanel();this.propagate("panel_select",a)}}else if(d.isString(a))for(b=
0;b<this.__ab_a_items.length;b++)if(c=this.__ab_a_items[b],c.title===a){this.expandPanel(b);break}},setPanelTitle:function(a,c){var b,e;if(d.isNumber(a)&&0<=a&&a<this.__ab_a_items.length)b=this.__ab_a_items[a],b.title=c,d.setElementInnerText(b.dt,c);else if(d.isString(a))for(e=0;e<this.__ab_a_items.length;e++)if(b=this.__ab_a_items[e],b.title===a){this.setPanelTitle(e,c);break}},show:function(){e.ui.View.prototype.show.call(this);this._updateSizePanel()},refresh:function(){e.ui.View.prototype.refresh.call(this);
this._updateSizePanel()},_updateSize:function(){e.ui.View.prototype._updateSize.call(this);this._updateSizePanel()},_updateSizePanel:function(){var a,c;if(c=this.__ab_a_items[this.__ab_a_current_index])a=this._size[1],this.__ab_a_head_height=c.dt.offsetHeight,a-=this.__ab_a_items.length*this.__ab_a_head_height+2,c.dd.style.height=a+"px",this._stretch===g.STRETCH_FILL&&(c.child.size=[this._size[0]-2,a])},handleEvent:function(a){var c=a.target,b=this;1!==c.nodeType&&(c=c.parentElement);if(a.type===
f.POINTER_START){if(EVENT_SUPPORT_TOUCH&&1<a.touches.length)return;a.stopPropagation();a.preventDefault();if(d.hasClassName(c,"expanded"))return!1;h.addEventListener(f.POINTER_MOVE,this,!1);h.addEventListener(f.POINTER_END,this,!1);this.__touch_start_x=EVENT_SUPPORT_TOUCH?a.touches[0].pageY:a.pageY;this.__touch_start_y=EVENT_SUPPORT_TOUCH?a.touches[0].pageY:a.pageY;this.__elem=c;this.__elem_to_unselect&&(d.removeClassName(this.__elem_to_unselect,"selected"),this.__elem_to_unselect=null);this.__list_time_out=
setTimeout(function(){d.addClassName(b.__elem,"selected");b.__list_time_out=0},0)}else a.type===f.POINTER_MOVE?(a.stopPropagation(),a.preventDefault(),c=EVENT_SUPPORT_TOUCH?a.touches[0].pageX:a.pageX,a=EVENT_SUPPORT_TOUCH?a.touches[0].pageY:a.pageY,a=Math.abs(a-this.__touch_start_y)+Math.abs(c-this.__touch_start_x),this.__elem&&a>2*m.View.MOVE_THRESHOLD&&(this.__list_time_out?(clearTimeout(this.__list_time_out),this.__list_time_out=0):d.removeClassName(this.__elem,"selected"),this.__elem=null)):a.type===
f.POINTER_END&&(a.stopPropagation(),a.preventDefault(),h.removeEventListener(f.POINTER_MOVE,this),h.removeEventListener(f.POINTER_END,this),this.__elem&&(this.__list_time_out&&(clearTimeout(this.__list_time_out),d.addClassName(b.__elem,"selected")),this.__elem_to_unselect=this.__elem,this.__list_time_out=setTimeout(function(){d.removeClassName(b.__elem_to_unselect,"selected");b.__elem_to_unselect=null;b.__list_time_out=0},m.View.UNSELECT_DELAY),d.isNumber(c.__index)&&this.expandPanel(c.__index)),
this.__elem=null);return!1}};d.extendClass(g,e.ui.View);d.defineClassProperty(g,"stretch",{set:function(a){d.isNumber(a)&&!(a!==g.STRETCH_FILL&&a!==g.STRETCH_NONE)&&(this._stretch=a,this._stretch===g.STRETCH_FILL?d.addClassName(this.view,"fill"):d.removeClassName(this.view,"fill"),this._updateSizePanel())},get:function(){return this._stretch}});o.Accordion=g;b.prototype.html_template="<div class='vs_ext_ui_gmap'></div>";j.prototype.html_template="<div class='vs_ext_ui_carousel' x-hag-hole='children'><div class='indicators'></div></div>";
g.prototype.html_template="<dl class='vs_ext_ui_accordion' x-hag-hole='children'></dl>"})(window);
