/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(u){function F(a,b,c,e,f){var s=0,i=0,l=0,h=0,g=0,j=0,l=3*b,i=3*(e-b)-l,s=1-l-i,j=3*c,g=3*(f-c)-j,h=1-j-g;return function(a){return((h*a+g)*a+j)*a}(function(a){var b,c,d,e;for(d=a,c=0;8>c;c++){e=((s*d+i)*d+l)*d-a;if(0.005>(0<=e?e:0-e))return d;b=(3*s*d+2*i)*d+l;if(1.0E-6>(0<=b?b:0-b))break;d-=e/b}b=0;c=1;d=a;if(d<b)return b;if(d>c)return c;for(;b<c;){e=((s*d+i)*d+l)*d;if(0.005>(0<=e-a?e-a:0-(e-a)))break;a>e?b=d:c=d;d=0.5*(c-b)+b}return d}(a))}function o(a,b,c,e){return function(f){return F(f,
a,b,c,e)}}function D(a,b){var c=a.getPropertyDescriptor("__trans_anim_"+b);c&&(Object.defineProperty(a,b,c),delete a["__trans_anim_"+b])}var b=u.vs,n=b.util,f=b.fx,u=b.ext.fx,E={},m=new f.Animation(["translateY","0px"]);m.addKeyFrame(0,["0px"]);m.addKeyFrame(20,["0px"]);m.addKeyFrame(40,["-30px"]);m.addKeyFrame(50,["0px"]);m.addKeyFrame(60,["-15px"]);m.addKeyFrame(80,["0px"]);m.duration="1s";var h=new f.Animation(["translateX","0px"]);h.addKeyFrame(0,["0px"]);h.addKeyFrame(10,["-10px"]);h.addKeyFrame(20,
["10px"]);h.addKeyFrame(30,["-10px"]);h.addKeyFrame(40,["10px"]);h.addKeyFrame(50,["-10px"]);h.addKeyFrame(60,["10px"]);h.addKeyFrame(70,["-10px"]);h.addKeyFrame(80,["10px"]);h.addKeyFrame(90,["0px"]);h.duration="1s";var k=new f.Animation(["rotate","0deg"]);k.addKeyFrame(0,["0deg"]);k.addKeyFrame(20,["15deg"]);k.addKeyFrame(40,["-10deg"]);k.addKeyFrame(60,["5deg"]);k.addKeyFrame(80,["-5deg"]);k.duration="1s";k.origin=[50,0];var p=new f.Animation(["scale","1"]);p.addKeyFrame(0,["1"]);p.addKeyFrame(50,
["1.1"]);p.addKeyFrame(80,["0.97"]);p.duration="1s";var q=new f.Animation(["perspective","400px"],["rotateX","0deg"],["opacity","1"]);q.addKeyFrame(0,["400px","90deg","0"]);q.addKeyFrame(40,["400px","-10deg"]);q.addKeyFrame(70,["400px","10deg"]);q.duration="1s";var v=new f.Animation(["perspective","400px"],["rotateX","90deg"],["opacity","0"]);v.addKeyFrame(0,["400px","0deg","1"]);v.duration="1s";var r=new f.Animation(["perspective","400px"],["rotateY","0deg"],["opacity","1"]);r.addKeyFrame(0,["400px",
"90deg","0"]);r.addKeyFrame(40,["400px","-10deg"]);r.addKeyFrame(70,["400px","10deg"]);r.duration="1s";var w=new f.Animation(["perspective","400px"],["rotateY","90deg"],["opacity","0"]);w.addKeyFrame(0,["400px","0deg","1"]);w.duration="1s";var x=new f.Animation(["translateY","0px"],["opacity","1"]);x.addKeyFrame(0,["20px","0"]);x.duration="1s";var y=new f.Animation(["translateY","-20px"],["opacity","0"]);y.addKeyFrame(0,["0px","1"]);y.duration="1s";var z=new f.Animation(["translateY","0px"],["opacity",
"1"]);z.addKeyFrame(0,["-20px","0"]);z.duration="1s";var A=new f.Animation(["translateY","20px"],["opacity","0"]);A.addKeyFrame(0,["0px","1"]);A.duration="1s";var B=new f.Animation(["translateX","0px"],["opacity","1"]);B.addKeyFrame(0,["-20px","0"]);B.duration="1s";f=new f.Animation(["translateX","20px"],["opacity","0"]);f.addKeyFrame(0,["0px","1"]);f.duration="1s";n.extend(E,{Bounce:m,Shake:h,Swing:k,Pulse:p,FlipInX:q,FlipOutX:v,FlipInY:r,FlipOutY:w,FadeInUp:x,FadeOutUp:y,FadeInDown:z,FadeOutDown:A,
FadeInLeft:B,FadeOutLeft:f});var t=b.core.createClass({parent:b.core.Task,_duration:300,_begin:0,_steps:0,_repeat:1,_pace:null,_tick:0,__time_decl:0,__pause_time:0,__end_time:0,properties:{duration:b.core.Object.PROPERTY_IN,begin:b.core.Object.PROPERTY_IN,steps:{set:function(a){a?b.util.isNumber(a)&&!(2>a)&&(this._steps=parseInt(a,10)):this._step=0}},repeat:b.core.Object.PROPERTY_IN,pace:b.core.Object.PROPERTY_IN,tick:b.core.Object.PROPERTY_OUT},initComponent:function(){this._state=b.core.Task.STOPPED;
this._super()},start:function(a){function d(){0===this._steps?this._start_clock():this._start_steps()}if(this._state!==b.core.Task.STARTED){if(this._state===b.core.Task.STOPPED){var c=this._begin||0;this.__pause_time=this.__time_decl=0;if(0<c){b.scheduleAction(d.bind(this),c);return}if(-c>this._repeat*this._duration){this.__setTick(1);this.propagateChange("tick");this.__clb&&this.__clb(this._tick);if(this.delegate&&this.delegate.taskDidEnd)try{this.delegate.taskDidEnd(this)}catch(e){e.stack&&console.log(e.stack),
console.error(e)}return}this.__time_decl=-c%this._duration;this.__repeat_dur=this._repeat-Math.floor(-c/this._duration);this.__param=a}d.call(this);if(this.delegate&&this.delegate.taskDidStart)try{this.delegate.taskDidStart(this)}catch(f){f.stack&&console.log(f.stack),console.error(f)}}},__setTick:function(a){this._tick=this._pace&&this._pace._timing?this._pace._timing(a):a},_clock:function(){if(this._state===b.core.Task.STARTED){var a=Date.now();if(a>=this.__end_time)if(this.__setTick(1),this.propagateChange("tick"),
this.__clb&&this.__clb(this._tick),1<this.__repeat_dur)this.__repeat_dur--,b.scheduleAction(this._start_clock.bind(this),b.ON_NEXT_FRAME);else{if(this._state=b.core.Task.STOPPED,this.delegate&&this.delegate.taskDidEnd)try{this.delegate.taskDidEnd(this)}catch(d){d.stack&&console.log(d.stack),console.error(d)}}else b.scheduleAction(this._clock.bind(this),b.ON_NEXT_FRAME),this.__setTick((a-this.__start_time)/this._duration),this.propagateChange("tick"),this.__clb&&this.__clb(this._tick)}},_start_clock:function(){if(this._state===
b.core.Task.PAUSED){var a=Date.now()-this.__pause_time;this.__start_time+=a;this.__end_time+=a;this._state=b.core.Task.STARTED}else this.__start_time=Date.now()-this.__time_decl,this.__time_decl=0,this.__end_time=this.__start_time+this._duration,b.util.isFunction(this.__param)&&(this.__clb=this.__param),this._state=b.core.Task.STARTED,this.__setTick(0),this.propagateChange("tick"),this.__clb&&this.__clb(this._tick);b.scheduleAction(this._clock.bind(this))},_step:function(){if(this._state===b.core.Task.STARTED){var a=
this._steps-this.__steps;this.__steps--;if(a===this._steps)if(this.__setTick(1),this.propagateChange("tick"),this.__clb&&this.__clb(this._tick),1<this.__repeat_dur)this.__repeat_dur--,b.scheduleAction(this._start_steps.bind(this),b.ON_NEXT_FRAME);else{if(this._state=b.core.Task.STOPPED,this.delegate&&this.delegate.taskDidEnd)try{this.delegate.taskDidEnd(this)}catch(d){d.stack&&console.log(d.stack),console.error(d)}}else this.__setTick(a/(this._steps-1)),this.propagateChange("tick"),this.__clb&&this.__clb(this._tick),
a=this._duration/this._steps,b.scheduleAction(this._step.bind(this),a)}},_start_steps:function(){if(this._state===b.core.Task.PAUSED)this._state=b.core.Task.STARTED,b.scheduleAction(this._step.bind(this));else{b.util.isFunction(this.__param)&&(this.__clb=this.__param);this._state=b.core.Task.STARTED;this.__setTick(0);this.propagateChange("tick");this.__clb&&this.__clb(this._tick);var a=this._duration/this._steps;this.__steps=this._steps-1-Math.floor(this.__time_decl/a);this.__time_decl=0;b.scheduleAction(this._step.bind(this),
a)}},stop:function(){this._state=b.core.Task.STOPPED;this.__pause_time=0;this.__setTick(0);this.propagateChange("tick");this.__clb&&this.__clb(this._tick);if(this.delegate&&this.delegate.taskDidStop)try{this.delegate.taskDidStop(this)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},pause:function(){if(!this._state!==b.core.Task.STARTED&&(this._state=b.core.Task.PAUSED,this.__pause_time=Date.now(),this.delegate&&this.delegate.taskDidPause))try{this.delegate.taskDidPause(this)}catch(a){a.stack&&
console.log(a.stack),console.error(a)}}}),g=b.core.createClass({_timing:function(a){return a},_tick_in:0,_tick_out:0,properties:{timing:b.core.Object.PROPERTY_IN,tickIn:b.core.Object.PROPERTY_IN,tickOut:b.core.Object.PROPERTY_OUT},initComponent:function(){this._super();this._tick_out=this._timing?this._timing(this._tick_in):this._tick_in},propertiesDidChange:function(){this._tick_out=this._timing?this._timing(this._tick_in):this._tick_in;this.propagateChange("tickOut")}});g.getEaseInPace=function(){return(new g({timing:o(0.42,
0,1,1)})).init()};g.getEaseOutPace=function(){return(new g({timing:o(0,0,0.58,1)})).init()};g.getEaseInOutPace=function(){return(new g({timing:o(0.42,0,0.58,1)})).init()};g.getEaseOutInPace=function(){return(new g({timing:o(0,0.42,1,0.58)})).init()};g.getLinearPace=function(){return(new g).init()};g.getInvertLinearPace=function(){return(new g({timing:function(a){return 1-a}})).init()};var n=b.core.createClass({_calcule_mode:0,properties:{calculeMode:b.core.Object.PROPERTY_IN,tick:b.core.Object.PROPERTY_IN},
initComponent:function(){this._super();this.propertiesDidChange()},compute:function(){return!1},propertiesDidChange:function(){this.compute()&&this.propagateChange("out")}}),m=b.core.createClass({parent:n,_values:null,_out:0,properties:{values:{set:function(a){b.util.isArray(a)&&!(1>a.length)&&(this._values=a.slice())}},out:b.core.Object.PROPERTY_OUT},constructor:function(a){this._super(a);this._values=[]},compute:function(){if(!b.util.isNumber(this._tick))return!1;var a=this._values.length-1,d=this._tick*
a,c=Math.floor(d);0===this._tick?this._out=this._values[0]:1===this._tick?this._out=this._values[a]:(a=this._values[c],this._out=a+(this._values[c+1]-a)*(d-c));return!0}}),h=b.core.createClass({parent:n,_values:null,_out:0,properties:{values:{set:function(a){b.util.isArray(a)&&!(1>a.length)&&(this._values=a.slice())}},out:b.core.Object.PROPERTY_OUT},constructor:function(a){this._super(a);this._values=[]},compute:function(){if(!b.util.isNumber(this._tick))return!1;var a=this._values.length-1,d=this._tick*
a,c=Math.floor(d),d=d-c;0===this._tick?this._out=this._values[0]:1===this._tick?this._out=this._values[a]:(a=this._values[c],c=this._values[c+1],this._out=[a[0]+(c[0]-a[0])*d,a[1]+(c[1]-a[1])*d]);return!0}}),k=b.core.createClass({parent:n,_center:null,_values:null,_out:0,properties:{center:{set:function(a){b.util.isArray(a)&&2===a.length&&(this._center=a.slice())}},values:{set:function(a){b.util.isArray(a)&&!(1>a.length)&&(this._values=a.slice())}},out:b.core.Object.PROPERTY_OUT},constructor:function(a){this._super(a);
this._values=[0,0];this._center=[0,0]},compute:function(){if(!b.util.isNumber(this._tick))return!1;var a;a=this._values;var d=a.length-1,c=this._tick*d,e=Math.floor(c),c=c-e;0===this._tick?a=a[0]:1===this._tick?a=a[d]:(d=a[e],a=d+(a[e+1]-d)*c);c=this._center[0];e=this._center[1];d=Math.sqrt(c*c+e*e);a=2*Math.PI*a/180;c=d*Math.cos(a)+c;c=Math.round(1E3*c)/1E3;a=d*Math.sin(a)+e;a=Math.round(1E3*a)/1E3;this._out=[c,a];return!0}}),C={duration:300,begin:0,pace:g.getLinearPace(),steps:0,repeat:1,startClb:null,
endClb:null};b.util.extend(u,{Animation:E,Trajectory:n,Vector1D:m,Vector2D:h,Circular2D:k,Pace:g,Chronometer:t,generateCubicBezierFunction:o,createTransition:function(a,d,c){var e=b.util.clone(C);if(c)for(var f in c)e[f]=c[f];var c=(new t(e)).init(),g=e.pace,i=e.trajectory;c.__clb=function(b){g._tick_i=b;g._tick_out=g._timing?g._timing(b):g._tick_in;i._tick=g._tick_out;i.compute()&&(a[d]=i._out,a.propertyChange())};c.__data_to_delete=[c,g,i];return c},freeTransition:function(a){a&&(a.__data_to_delete&&
a.__data_to_delete.forEach(function(a){b.util.free(a)}),b.util.free(a))},animateTransitionBis:function(a,d,c,e){if(!(!b.util.isArray(d)||!b.util.isArray(c)||d.length!==c.length)){var f=b.util.clone(C);if(e)for(var g in e)f[g]=e[g];var e=(new t(f)).init(),i=f.pace,h=f.trajectory;e.__clb=function(b){i.tickIn=b;i.propertiesDidChange();h.tick=i.tickOut;h.propertiesDidChange();for(b=0;b<d.length;b++)a[c[b]]=h[d[b]];a.propertyChange()};return e}},attachTransition:function(a,d,c){var e=b.util.clone(C);if(c)for(var f in c)e[f]=
c[f];var g=(new t(e)).init(),h=e.pace,l=e.trajectory,m="_"+b.util.underscore(d),k;if(!l)throw Error("Error StringTrajectory");g.__clb=function(b){h._tick_i=b;h._tick_out=h._timing?h._timing(b):h._tick_in;l._tick=h._tick_out;l.compute()&&(k.call(a,l._out),a.propertyChange())};var j=a.getPropertyDescriptor(d);if(!j||!j.set)throw Error("Error StringTrajectory");k=j.set;D(a,d);(function(){var b={};j.get&&(b.get=j.get);b.set=function(a){l.values=[this[m],a];g.start()};b.configurable=j.configurable;b.enumerable=
j.enumerable;Object.defineProperty(a,"__trans_anim_"+d,j);Object.defineProperty(a,d,b)})()},removeTransition:D})})(window);
