/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(m,k){function o(){b.InfoWindow=function(a,c,p,b,d){this.vs_map=a;this.id=c;this.type=p;a&&(this.setCoordinate(b,d),this.setValues({map:this.vs_map._gmap}))};b.InfoWindow.prototype=new google.maps.OverlayView;b.InfoWindow.prototype.destructor=function(){this.setMap(null);this.vs_map=this.marker=k};b.InfoWindow.prototype.hide=function(){this.view&&(this.view.style.display="none")};b.InfoWindow.prototype.show=function(){this.view&&(this.view.style.display="block")};b.InfoWindow.prototype.setMarker=
function(a){this.marker&&this.unbind("position");this.marker=a;this.id=this.marker.id;this.type=this.marker.type;this.info=this.marker.info;this.bindTo("position",this.marker._gmarker,"position");this.instanciateView(this.type,this.info)};b.InfoWindow.prototype.setCoordinate=function(a,c){this.position&&delete this.position;this.position=new google.maps.LatLng(a,c)};b.InfoWindow.prototype.setType=function(a){this.type=a;this.instanciateView(this.type,this.info)};b.InfoWindow.prototype.setInfo=function(a){this.info=
a;this.instanciateView(this.type,this.info)};b.InfoWindow.prototype.instanciateView=function(a,c){var d=i.createElement("div"),f=b._anotation_templates_[a];f||(f=b._anotation_templates_["default"]);f=f.infoWindow;if(c)for(key in c)var g=c[key],g=g?g:"",f=f.replace("{"+key+"}",g);e.safeInnerHTML(d,f);this.view||this.createView();e.safeInnerHTML(this.view,d.firstElementChild.innerHTML);this.view.className=d.firstElementChild.className};b.InfoWindow.prototype.createView=function(){this.view||(this.view=
i.createElement("div"),d.addPointerListener(this.view,g.POINTER_START,this))};b.InfoWindow.prototype.handleEvent=function(a){var c=this;switch(a.type){case g.POINTER_START:if(1<a.nbPointers)break;d.addPointerListener(i,g.POINTER_END,this);d.addPointerListener(i,g.POINTER_MOVE,this);this.__start_x=a.pointerList[0].pageX;this.__start_y=a.pointerList[0].pageY;this.marker&&this.removeMapEvent();e.addClassName(this.view,"selected");return!1;case g.POINTER_MOVE:var b=a.pointerList[0].pageY-this.__start_y;
if(10>Math.abs(a.pointerList[0].pageX-this.__start_x)+Math.abs(b))return a.preventDefault(),!1;d.removePointerListener(i,g.POINTER_END,this);d.removePointerListener(i,g.POINTER_MOVE,this);this.marker&&d.scheduleAction(function(){c.initMapEvent()});e.removeClassName(this.view,"selected");return!1;case g.POINTER_END:return a.stopPropagation(),a.preventDefault(),d.removePointerListener(i,g.POINTER_END,this),d.removePointerListener(i,g.POINTER_MOVE,this),this.marker&&d.scheduleAction(function(){c.initMapEvent()}),
e.removeClassName(this.view,"selected"),this.vs_map.annotationSelect(this.id),!1}};b.InfoWindow.prototype.onAdd=function(){this.view||this.createView();this.getPanes().floatPane.appendChild(this.view);var a=this;this.listeners_=[google.maps.event.addListener(this,"position_changed",function(){a.draw()})]};b.InfoWindow.prototype.onRemove=function(){this.view.parentNode.removeChild(this.view);for(var a=0,c=this.listeners_.length;a<c;++a)google.maps.event.removeListener(this.listeners_[a])};b.InfoWindow.prototype.draw=
function(){var a=this.getProjection().fromLatLngToDivPixel(this.get("position")),c=this.view;c.style.display="block";c.style.visibility="hidden";var b=0;if(this.marker){var b=10,f=this.marker._gmarker.getIcon();f&&(b+=f.size.height)}d.scheduleAction(function(){var d=c.offsetHeight;c.style.left=a.x-Math.ceil(c.offsetWidth/2)+"px";c.style.top=a.y-d-b+"px";c.style.visibility="visible"})};b.InfoWindow.prototype.initMapEvent=function(){if(!this.map_listener){var a=this;this.map_listener=google.maps.event.addListener(this.vs_map._gmap,
"click",function(){a.hide()})}};b.InfoWindow.prototype.removeMapEvent=function(){this.map_listener&&(google.maps.event.removeListener(this.map_listener),this.map_listener=k)};b.InfoWindowWithMarker=function(a){this.vs_map=a;this.setValues({map:this.vs_map._gmap});this.initMapEvent()};e.extendClass(b.InfoWindowWithMarker,b.InfoWindow)}function j(a){this.parent=d.ui.View;this.parent(a);this.constructor=j;this.__indicators_list={}}var i=m.document,d=m.vs,e=d.util,g=d.core,l=d.ui,n=d.ext.ui,b=function(a){this.parent=
d.ui.View;this.parent(a);this.constructor=b;this._center=[];this._center[0]=48.83763339660763;this._center[1]=2.3397827148437544;b.__google_loaded__||(b.__google_wait_loaded__||(b.__google_wait_loaded__=!0,d.util.importFile("http://maps.google.com/maps/api/js?sensor=true&callback=vs.ext.ui.GMap.__on_laoded",null,null,"js")),b._to_finish_init.push(this));this.__annotations={}};b.NO_MARKER=0;b.DEVICE_IMAGE_MARKER=1;b.IMAGE_MARKER=2;b._anotation_templates_={};b._anotation_templates_["default"]={marker:{type:b.DEVICE_IMAGE_MARKER},
infoWindow:'<div class="vs_ext_ui_gmap_info">    <div>{title}</div>    <div>{subtitle}</div>  </div>'};b.__google_wait_loaded__=!1;b.__google_loaded__=!1;b._to_finish_init=[];b.__on_laoded=function(){var a,c;b.__google_loaded__=!0;b.__google_wait_loaded__=!1;o();for(a=0,c=b._to_finish_init.length;a<c;a++)b._to_finish_init[a].finishInit();b._to_finish_init=null};b.prototype={_zoom:10,_tilt:-1,_scroll:!0,_tap_to_zoom:!0,_max_zoom:20,_min_zoom:1,_zoom_control:!1,_street_view_control:!1,_center:null,
_gmap:null,__init_finished:!1,__annotations:null,destructor:function(){delete this._gmap;d.ui.View.prototype.destructor.call(this)},initComponent:function(){d.ui.View.prototype.initComponent.call(this);b.__google_loaded__&&this.finishInit()},finishInit:function(){var a={zoom:this._zoom,center:new google.maps.LatLng(this._center[0],this._center[1]),disableDefaultUI:!0,draggable:this._scroll,maxZoom:this._max_zoom,minZoom:this._min_zoom,disableDoubleClickZoom:!this._tap_to_zoom,streetViewControl:this._street_view_control,
streetViewControlOptions:{position:google.maps.ControlPosition.LEFT_TOP},zoomControl:this._zoom_control,zoomControlOptions:{position:google.maps.ControlPosition.LEFT_BOTTOM,style:google.maps.ZoomControlStyle.SMALL},mapTypeControlOptions:{style:google.maps.ControlPosition.HORIZONTAL_BAR},mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.DROPDOWN_MENU}};this._gmap=new google.maps.Map(this.view,a);var c=this;d.scheduleAction(function(){c.__init_did_finish()})},
__init_did_finish:function(){this.__init_finished=!0;this.streetViewControl=this._street_view_control;this.zoomControl=this._zoom_control;this.propagate("mapload")},isReady:function(){return this.__init_finished},getGoogleMapObject:function(){return this._gmap},showCenterMark:function(){this._center_mark||(this._center_mark=new google.maps.Marker({position:new google.maps.LatLng(this._center[0],this._center[1]),icon:"css/kit/mapCenter.png"}));this._center_mark.setMap(this._gmap)},hideCenterMark:function(){this._center_mark&&
this._center_mark.setMap(null)},refresh:function(){this._gmap&&(google.maps.event.trigger(this._gmap,"resize"),d.ui.View.prototype.refresh.call(this))},addAnnotation:function(a,c,d,f,i){if(this.__init_finished){if(!e.isString(a)||!a)a=g.createId();c=new b.Annotation(this,a,c,d,f,i);return this.__annotations[a]=c}},setAnnotationTemplate:function(a,c,d){if(e.isString(a)||a){var f=b._anotation_templates_["default"];b._anotation_templates_[a]={marker:e.clone(c?c:f.marker),infoWindow:e.clone(d?d:f.infoWindow)}}},
removeAnnotation:function(a){!e.isString(a)&&a.id&&(a=a.id);var c=this.__annotations[a];c&&(e.free(c),delete this.__annotations[a])},removeAnnotations:function(){for(var a in this.__annotations)this.removeAnnotation(a)},annotationSelect:function(a){this.propagate("annotationselect",a)}};e.extendClass(b,d.ui.View);e.defineClassProperties(b,{scroll:{set:function(a){this._scroll=a?!0:!1;this.__init_finished&&this._gmap.setOptions({draggable:this._scroll})},get:function(){return this._scroll}},tapToZoom:{set:function(a){this._tap_to_zoom=
a?!0:!1;this.__init_finished&&this._gmap.setOptions({disableDoubleClickZoom:!this._tap_to_zoom})},get:function(){return this._tap_to_zoom}},maxZoom:{set:function(a){d.util.isNumber(a)&&(this._max_zoom=a,this.__init_finished&&this._gmap.setOptions({maxZoom:this._max_zoom}))},get:function(){return this._max_zoom}},minZoom:{set:function(a){d.util.isNumber(a)&&(this._min_zoom=a,this.__init_finished&&this._gmap.setOptions({maxZoom:this._min_zoom}))},get:function(){return this._min_zoom}},zoomControl:{set:function(a){this._zoom_control=
a?!0:!1;this.__init_finished&&this._gmap.setOptions({zoomControl:this._zoom_control})},get:function(){return this._zoom_control}},zoom:{set:function(a){d.util.isNumber(a)&&this.__init_finished&&(a=Math.floor(a),a!==this._zoom&&(this._zoom=a,this._gmap.setZoom(this._zoom)))},get:function(){return!this._gmap?-1:this._zoom=this._gmap.getZoom()}},tilt:{set:function(a){d.util.isNumber(a)&&this.__init_finished&&(this._tilt=a,this._gmap.setTilt(a))},get:function(){return!this._gmap?-1:this._tilt=this._gmap.getTilt()}},
streetViewControl:{set:function(a){this._street_view_control=a?!0:!1;this.__init_finished&&this._gmap.setOptions({streetViewControl:this._street_view_control})},get:function(){return this._street_view_control}},center:{set:function(a){this.__init_finished&&a&&d.util.isArray(a)&&2===a.length&&d.util.isNumber(a[0])&&d.util.isNumber(a[1])&&(this._center[0]=a[0],this._center[1]=a[1],a=new google.maps.LatLng(a[0],a[1]),this._gmap.setCenter(a),this._center_mark&&this._center_mark.setPosition(a))},get:function(){if(!this._gmap)return[0,
0];var a=this._gmap.getCenter();this._center[0]=a.lat();this._center[1]=a.lng();return this._center.slice()}}});b.Annotation=function(a,c,e,f,g,i){this.map=a;this.id=c;this.info=g;this.type=i?i:"default";this._coordinate=new google.maps.LatLng(e,f);var h=b._anotation_templates_[this.type];h||(h=b._anotation_templates_["default"]);this.image=null;h.marker.type==b.DEVICE_IMAGE_MARKER?(h=m.deviceConfiguration.os,this.image=h==d.core.DeviceConfiguration.OS_SYMBIAN?new google.maps.MarkerImage("css/kit/symbian_marker.png",
new google.maps.Size(48,51),new google.maps.Point(0,0),new google.maps.Point(24,48)):h==d.core.DeviceConfiguration.OS_WP7?new google.maps.MarkerImage("css/kit/wp7_marker.png",new google.maps.Size(15,31),new google.maps.Point(0,0),new google.maps.Point(0,31)):new google.maps.MarkerImage("css/kit/ios_marker.png",new google.maps.Size(32,41),new google.maps.Point(0,0),new google.maps.Point(8,36))):h.marker.type==b.IMAGE_MARKER&&(this.image=new google.maps.MarkerImage(h.marker.url));if(this.image){this._gmarker=
new google.maps.Marker({position:this._coordinate,icon:this.image,map:a._gmap,animation:google.maps.Animation.DROP});var j=this;google.maps.event.addListener(this._gmarker,"click",function(){j.onselect()})}else this._infoWindow=new b.InfoWindow(this.map,c,e,f,i),this._infoWindow.setCoordinate(e,f),this._infoWindow.setInfo(g)};b.Annotation.prototype={destructor:function(){this._gmarker&&(this._gmarker.setMap(null),delete this._gmarker);this._infoWindow&&free(this._infoWindow);this.image&&delete this.image;
delete this._coordinate;this.map=k},onselect:function(){this.showInfoWindow()},showInfoWindow:function(){this.map._infoWindow||(this.map._infoWindow=new b.InfoWindowWithMarker(this.map));this.map._infoWindow.setMarker(this)}};e.defineClassProperties(b.Annotation,{coordinate:{set:function(a){if(e.isArray(a)||2==a.length)delete this._coordinate,this._coordinate=new google.maps.LatLng(a[0],a[1]),this._gmarker&&this._gmarker.setPosition(this._coordinate)},get:function(){return[this._coordinate.lat(),
this._coordinate.lng()]}},info:{set:function(a){this._info=a;this._infoWindow&&this._infoWindow.setInfo(a)},get:function(){return this._info}}});n.GMap=b;j.HORIZONTAL=d.fx.SlideController.HORIZONTAL;j.VERTICAL=d.fx.SlideController.VERTICAL;j.prototype={_indicators_visibility:!0,_delegate:null,_orientation:j.HORIZONTAL,_slideController:null,__indicators:null,__selected_indicator:null,__indicators_list:null,__indicators_timer:0,destructor:function(){e.free(this._slideController);d.ui.View.prototype.destructor.call(this)},
initComponent:function(){d.ui.View.prototype.initComponent.call(this);this.__indicators=this.view.querySelector(".vs_ext_ui_carousel >.indicators");d.util.addClassName(this.__indicators,"horizontal");this._slideController=new d.fx.SlideController(this);this._slideController.delegate=this;this._slideController.isTactile=!0;this._slideController.animationMode=d.fx.SlideController.PIXEL;this._slideController.init()},refresh:function(){this._slideController&&this._slideController.refresh&&this._slideController.refresh();
d.ui.View.prototype.refresh.call(this)},controllerViewWillChange:function(a,c){this.__indicators_timer&&(clearTimeout(this.__indicators_timer),__indicators_timer=0);var b=c.id,e=this;this.__indicators_timer=setTimeout(function(){e.__selected_indicator&&d.util.removeClassName(e.__selected_indicator,"selected");e.__selected_indicator=e.__indicators_list[b];d.util.addClassName(e.__selected_indicator,"selected")},500);this._delegate&&this._delegate.carouselViewWillChange&&this._delegate.carouselViewWillChange(c)},
add:function(a){d.ui.View.prototype.add.call(this,a,"children");this.push(a)},push:function(a,c){if(!this.isChild(a)||!this._slideController.isStateExit(a.id)){var d,b=this._slideController.push(a,c);d=i.createElement("span");this.__indicators.appendChild(d);this.__indicators_list[b]=d}},remove:function(a){a&&a.id&&(this.__indicators.removeChild(this.__indicators_list[a.id]),delete this.__indicators_list[a.id],d.ui.View.prototype.remove.call(this,a))},removeAllChildren:function(){for(var a in this.__indicators_list)this.remove(d.core.Object._obs[a])},
goToNextView:function(){this._slideController.goToNextView()},goToPreviousView:function(){this._slideController.goToPreviousView()},goToView:function(a){this._slideController.goToViewId(a)},goToViewAt:function(a){this._slideController.goToViewAt(a)}};e.extendClass(j,d.ui.View);e.defineClassProperties(j,{size:{set:function(a){a&&e.isArray(a)&&2===a.length&&e.isNumber(a[0])&&e.isNumber(a[1])&&(this._size[0]=a[0],this._size[1]=a[1],this.view&&(this._updateSize(),this._slideController&&this._slideController.refresh&&
this._slideController.refresh()))},get:function(){var a=this.view;a&&a.parentNode&&(this._size[0]=a.offsetWidth,this._size[1]=a.offsetHeight);return this._size.slice()}},delegate:{set:function(a){this._delegate=a}},indicatorsVisibility:{set:function(a){a?(this._indicators_visibility=!0,__setVisible(this.__indicators,!0)):(this._indicators_visibility=!1,__setVisible(this.__indicators,!1))}},orientation:{set:function(a){a!==j.HORIZONTAL&&a!==j.VERTICAL||this._orientation===a||(a===j.HORIZONTAL?(d.util.removeClassName(this.__indicators,
"vertical"),d.util.addClassName(this.__indicators,"horizontal")):(d.util.removeClassName(this.__indicators,"horizontal"),d.util.addClassName(this.__indicators,"vertical")),this._orientation=a,this._slideController.orientation=a)},get:function(){return this._orientation}}});n.Carousel=j;var h=function(a){this.parent=l.View;this.parent(a);this.constructor=h;this.__ab_a_items=[]};h.STRETCH_NONE=0;h.STRETCH_FILL=1;h.prototype={_stretch:h.STRETCH_NONE,__ab_a_items:k,__ab_a_current_index:k,__ab_a_head_height:33,
push:function(a,c){a&&(this.add(a),this.setPanelTitle(this._getIndexForChild(a),c))},add:function(a){if(a){var c;a.id||(a.id=d.core.createId());c=this.__ab_a_items.length;c=this._createView(a,"Section "+(c+1),c);this.view.appendChild(c.dt);l.View.prototype.add.call(this,a,"children",c.dd);this.__ab_a_items.push(c);this._updateSizePanel()}},remove:function(a){var c=this._getIndexForChild(a),b;-1!==c&&(l.View.prototype.remove.call(this,a),b=this.__ab_a_items[c],b.dd.removeChild(a.view),this.view.removeChild(b.dt),
d.removePointerListener(b.dt,g.POINTER_START,this),delete b.dt,delete b.dd,delete b,this.__ab_a_items.remove(c),c===this.__ab_a_current_index?(this.__ab_a_current_index=null,this.expandPanel(0)):this._updateSizePanel())},_getIndexForChild:function(a){if(!a)return-1;var c,b;for(c=0;c<this.__ab_a_items.length;c++)if((b=this.__ab_a_items[c])&&b.dd&&b.dd.__child===a)return c;return-1},_createView:function(a,c,b){var f={};f.dt=i.createElement("dt");e.setElementInnerText(f.dt,c);f.title=c;f.dd=i.createElement("dd");
this._stretch===h.STRETCH_FILL&&(a.position=[0,0]);f.dd.appendChild(a.view);c=b?"collapsed":"expanded";f.dd.setAttribute("class",c);f.dt.setAttribute("class",c);f.dd.__child=a;f.child=a;"collapsed"===c?(f.dd.style.width="100%",f.dd.style.height="0px"):(f.dd.style.width="100%",f.dd.style.height=a._size[1]+"px",this.__ab_a_current_index=b);this._stretch===h.STRETCH_FILL&&(a.size=[this._size[0]-2,this._size[1]]);f.dt.__dd=f.dd;f.dt.__index=b;d.addPointerListener(f.dt,g.POINTER_START,this);return f},
expandPanel:function(a){var c,b;if(e.isNumber(a)&&0<=a&&a<this.__ab_a_items.length){if(a!==this.__ab_a_current_index){if(c=this.__ab_a_items[this.__ab_a_current_index])e.removeClassName(c.dt,"expanded"),e.addClassName(c.dt,"collapsed"),e.removeClassName(c.dd,"expanded"),e.addClassName(c.dd,"collapsed"),c.dd.style.height="0px";c=this.__ab_a_items[a];e.removeClassName(c.dt,"collapsed");e.addClassName(c.dt,"expanded");e.removeClassName(c.dd,"collapsed");e.addClassName(c.dd,"expanded");this.__ab_a_current_index=
a;this._updateSizePanel();this.propagate("panel_select",a)}}else if(e.isString(a))for(b=0;b<this.__ab_a_items.length;b++)if(c=this.__ab_a_items[b],c.title===a){this.expandPanel(b);break}},setPanelTitle:function(a,c){var b,d;if(e.isNumber(a)&&0<=a&&a<this.__ab_a_items.length)b=this.__ab_a_items[a],b.title=c,e.setElementInnerText(b.dt,c);else if(e.isString(a))for(d=0;d<this.__ab_a_items.length;d++)if(b=this.__ab_a_items[d],b.title===a){this.setPanelTitle(d,c);break}},show:function(){d.ui.View.prototype.show.call(this);
this._updateSizePanel()},refresh:function(){d.ui.View.prototype.refresh.call(this);this._updateSizePanel()},_updateSize:function(){d.ui.View.prototype._updateSize.call(this);this._updateSizePanel()},_updateSizePanel:function(){var a,c;if(c=this.__ab_a_items[this.__ab_a_current_index])a=this._size[1],this.__ab_a_head_height=c.dt.offsetHeight,a-=this.__ab_a_items.length*this.__ab_a_head_height+2,c.dd.style.height=a+"px",this._stretch===h.STRETCH_FILL&&(c.child.size=[this._size[0]-2,a])},handleEvent:function(a){var c=
a.target,b=this;1!==c.nodeType&&(c=c.parentElement);if(a.type===g.POINTER_START){if(1<a.nbPointers)return;a.stopPropagation();a.preventDefault();if(e.hasClassName(c,"expanded"))return!1;d.addPointerListener(i,g.POINTER_MOVE,this,!1);d.addPointerListener(i,g.POINTER_END,this,!1);this.__touch_start_x=a.pointerList[0].pageX;this.__touch_start_y=a.pointerList[0].pageY;this.__elem=c;this.__elem_to_unselect&&(e.removeClassName(this.__elem_to_unselect,"selected"),this.__elem_to_unselect=null);this.__list_time_out=
setTimeout(function(){e.addClassName(b.__elem,"selected");b.__list_time_out=0},0)}else a.type===g.POINTER_MOVE?(a.stopPropagation(),a.preventDefault(),c=a.pointerList[0].pageX,a=a.pointerList[0].pageY,a=Math.abs(a-this.__touch_start_y)+Math.abs(c-this.__touch_start_x),this.__elem&&a>2*l.View.MOVE_THRESHOLD&&(this.__list_time_out?(clearTimeout(this.__list_time_out),this.__list_time_out=0):e.removeClassName(this.__elem,"selected"),this.__elem=null)):a.type===g.POINTER_END&&(a.stopPropagation(),a.preventDefault(),
d.removePointerListener(i,g.POINTER_MOVE,this),d.removePointerListener(i,g.POINTER_END,this),this.__elem&&(this.__list_time_out&&(clearTimeout(this.__list_time_out),e.addClassName(b.__elem,"selected")),this.__elem_to_unselect=this.__elem,this.__list_time_out=setTimeout(function(){e.removeClassName(b.__elem_to_unselect,"selected");b.__elem_to_unselect=null;b.__list_time_out=0},l.View.UNSELECT_DELAY),e.isNumber(c.__index)&&this.expandPanel(c.__index)),this.__elem=null);return!1}};e.extendClass(h,d.ui.View);
e.defineClassProperty(h,"stretch",{set:function(a){e.isNumber(a)&&!(a!==h.STRETCH_FILL&&a!==h.STRETCH_NONE)&&(this._stretch=a,this._stretch===h.STRETCH_FILL?e.addClassName(this.view,"fill"):e.removeClassName(this.view,"fill"),this._updateSizePanel())},get:function(){return this._stretch}});n.Accordion=h;b.prototype.html_template="<div class='vs_ext_ui_gmap'></div>";j.prototype.html_template="<div class='vs_ext_ui_carousel' x-hag-hole='children'>  <div class='indicators'></div></div>";h.prototype.html_template=
"<dl class='vs_ext_ui_accordion' x-hag-hole='children'></dl>"})(window);
