/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(L,B){function z(a){return!l.CSS_VENDOR?a:"-"+l.CSS_VENDOR.toLowerCase()+"-"+a}function g(a){this.parent=o.Task;this.parent();this.constructor=g;arguments.length&&(this.setAnimations(arguments),this.keyFrames["100%"]=this)}function s(a){this.parent=o.EventSource;this.parent();this.constructor=s;a&&(this._fsm=new o.Fsm(this),this._fsm.goTo=this.goTo,this._owner=a)}function f(a){this.parent=s;this.parent(a);this.constructor=f;arguments.length&&(this._fsm.addInput(f.NEXT),this._fsm.addInput(f.PRED),
this._fsm.addInput(f.FIRST),this._states_array=[])}function p(a,c,b){this.parent=s;this.parent(a);this.constructor=p;arguments.length&&(this._animation_type=b==p.NO_ANIMATION||b==p.CARD_ANIMATION||b==p.SLIDE_ANIMATION?b:p.DEFAULT_ANIMATION,this.setNavigationBar(c),this.__nav_bar_states={})}function t(a,c){this.parent=f;this.parent(a,c);this.constructor=t;a&&a.setStyle("-webkit-transform-style","preserve-3d")}function y(a,c){this.parent=f;this.parent(a,c);this.constructor=y;this.animationDuration=
y.ANIMATION_DURATION}var x=L.document,l=L.vs,e=l.util,o=l.core,I=l.ui,w=l.fx,v=e.setElementTransform,u=l.SUPPORT_3D_TRANSFORM;l.CSS_VENDOR;var F=z("animation-duration"),J=z("animation-delay"),C=z("animation-name"),M=z("animation-timing-function"),N=z("animation-fill-mode"),G=z("transition-duration"),K=z("transition-delay"),O=z("transition-timing-function"),P=z("transition-property"),Q=z("transform-origin"),H=z("animation-iteration-count"),A=z("transform"),R=z("keyframes"),D="animationend",E="transitionend";
"webkit"===l.CSS_VENDOR?(D="webkitAnimationEnd",E="webkitTransitionEnd"):"ms"===l.CSS_VENDOR?(D="msAnimationEnd",E="msTransitionEnd"):"moz"===l.CSS_VENDOR&&(D="Mozanimationend",E="Moztransitionend");e.extend(l,{ANIMATION_DURATION:F,ANIMATION_DELAY:J,ANIMATION_NAME:C,ANIMATION_TIMING_FUNC:M,ANIMATION_FILL_MODE:N,TRANSITION_DURATION:G,TRANSITION_PROPERTY:P,TRANSITION_DELAY:K,TRANSITION_TIMING_FUNC:O,TRANSFORM_ORIGIN:Q,ITERATION_COUNT:H,TRANSFORM:A,KEY_FRAMES:R,ANIMATION_END:D,TRANSITION_END:E});var T=
RegExp(/\$width/g),U=RegExp(/\$height/g),V=RegExp(/\$x/g),W=RegExp(/\$y/g),S=RegExp(/\$\{([\w]+)\}/g),Y=function(a,c,b,d,h){function g(b,d){var h,n=[],f;if(e.isNumber(b))return b;if(e.isString(b)){b=b.replace(T,a.size[0]+"px");b=b.replace(U,a.size[1]+"px");b=b.replace(V,a.position[0]+"px");b=b.replace(W,a.position[1]+"px");for(h=S.exec(b);h&&2===h.length;)n.push(h[1]),h=S.exec(b);for(h=0;h<n.length;h++)f=n[h],"undefined"!==typeof d[f]?b=b.replace("${"+f+"}",d[f]):"undefined"!==typeof c[f]&&(b=b.replace("${"+
f+"}",c[f]));return b}console.warn("vs.fx.Animation._parseValue. Unknown value's type: "+b);return 0}if(!c||!a||!a.view)console.error("procesAnimation: invalid component parameter!");else{var f=function(a){var b={},c,d;b.properties=a.properties?a.properties.slice():[];b.values=a.values?a.values.slice():[];a.durations&&(b.durations=a.durations);b.timings=a.timings?a.timings.slice():[];a.origin&&(b.origin=a.origin.slice());b.iterationCount=a.iterationCount;b.delay=a.delay;b.additive=a.additive;b.keyFrames=
{};a.keyFrames["100%"]||(a.keyFrames["100%"]=a);var h;for(c in a.keyFrames)if(d=a.keyFrames[c],e.isArray(d)){h=[];for(var f=0;f<d.length;f++)value=d[f],null==value||"undefined"==typeof value||(h[f]=g(value,a));b.keyFrames[c]=h}else{for(f=0;f<a.properties.length;f++)b.values[f]=g(a.values[f],d);b.keyFrames[c]={}}return b}(c);return X(a,c,f,b,d,h)}},X=function(a,c,b,d,h,f){function q(){var c;c=r?F:G;e.isArray(b.origin)&&2===b.origin.length&&a.setStyle(Q,b.origin[0]+"% "+b.origin[1]+"%");f?a.setStyle(c,
0):e.isString(b.durations)?a.setStyle(c,b.durations):e.isArray(b.durations)?a.setStyle(c,b.durations.join(", ")):a.setStyle(c,g.DEFAULT_DURATION);c=r?J:K;!f&&e.isNumber(b.delay)?a.setStyle(c,b.delay+"ms"):a.setStyle(c,"0");c=r?M:O;e.isString(b.timings)?a.setStyle(c,b.timings):e.isArray(b.timings)?a.setStyle(c,b.timings.join(", ")):a.setStyle(c,g.EASE);r&&("infinite"===b.iterationCount?a.setStyle(H,"infinite"):!b.iterationCount||!e.isNumber(b.iterationCount)?a.setStyle(H,"1"):a.setStyle(H,b.iterationCount),
a.setStyle(N,"forwards"))}function j(){q();var e,g;e=function(g){g.currentTarget===a.view&&(s||a.view.removeEventListener(E,e,!1),a.view.style.removeProperty(G),a.view.style.removeProperty(K),c.delegate&&c.delegate.taskDidEnd&&c.delegate.taskDidEnd(b),d&&d.call(h?h:w))};g=parseFloat(a.view.style.getPropertyValue(G));if(f||0===g)s=!0;s?l.scheduleAction(function(){e({currentTarget:a.view})}):a.view.addEventListener(E,e,!1);k()}function k(){var c="",d,h=[],e;for(i=0;i<b.properties.length;i++)d=b.properties[i],
e=b.values[i],"rotate"===d?(c+="rotate("+e+") ",d=A):"skew"===d?(c+="skew("+e+") ",d=A):u&&"translate"===d?(c+="translate3d("+e+") ",d=A):"translate"===d?(c+="translate("+e+") ",d=A):"translateX"===d?(c+="translateX("+e+") ",d=A):"translateY"===d?(c+="translateY("+e+") ",d=A):"rotateX"===d?(c+="rotateX("+e+") ",d=A):"rotateY"===d?(c+="rotateY("+e+") ",d=A):"scale"===d?(c+="scale("+e+") ",d=A):a.setStyle(d,e),-1==h.indexOf(d)&&h.push(d);c&&(b.additive&&(c=a.getCTM().toString()+" "+c),v(a.view,c));
a.setStyle(P,h.join(","))}function m(){q();var b,e,j;b=function(f){if(f.currentTarget===a.view){s||a.view.removeEventListener(D,b,!1);r&&k();a.view.style.removeProperty(F);a.view.style.removeProperty(J);if(e=a.getStyle(C))e=e.replace(p,""),a.setStyle(C,e);try{if((data=g.__css_animations[p])&&2===data.length)x.getElementsByTagName("head")[0].removeChild(data[0]),delete g.__css_animations[p]}catch(n){return n.stack&&console.log(n.stack),console.error(n),!1}c.delegate&&c.delegate.taskDidStop&&c.delegate.taskDidEnd(c);
d&&d.call(h?h:w)}};j=parseFloat(a.view.style.getPropertyValue(F));if(f||0===j)s=!0;s?l.scheduleAction(function(){b({currentTarget:a.view})}):a.view.addEventListener(D,b,!1);e=(e=a.getStyle(C))?e+(", "+p):p;a.setStyle(C,e)}function t(){var c,d,h,f,n,j,q,l=x.createElement("style");l.type="text/css";var k="";for(d in b.keyFrames){j="";c=b.keyFrames[d];h="";if(e.isArray(c))for(f=0;f<c.length;f++)q=c[f],null==q||"undefined"==typeof q||(n=b.properties[f])&&("rotate"===n?j+="rotate("+q+") ":"skew"===n?j+=
"skew("+q+") ":u&&"translate"===n?j+="translate3d("+q+") ":"translate"===n?j+="translate("+q+") ":"translateX"===n?j+="translateX("+q+") ":"translateY"===n?j+="translateY("+q+") ":"rotateX"===n?j+="rotateX("+q+") ":"rotateY"===n?j+="rotateY("+q+") ":"scale"===n?j+="scale("+q+") ":"perspective"===n?j+="perspective("+q+") ":h+=n+":"+q+";");else for(f=0;f<b.properties.length;f++)q=b.values[f],(n=b.properties[f])&&("rotate"===n?j+="rotate("+q+") ":"skew"===n?j+="skew("+q+") ":u&&"translate"===n?j+="translate3d("+
q+") ":"translate"===n?j+="translate("+q+") ":"translateX"===n?j+="translateX("+q+") ":"translateY"===n?j+="translateY("+q+") ":"rotateX"===n?j+="rotateX("+q+") ":"rotateY"===n?j+="rotateY("+q+") ":"scale"===n?j+="scale("+q+") ":"perspective"===n?j+="perspective("+q+") ":h+=n+":"+q+";");j&&(b.additive&&(j=a.getCTM().toString()+" "+j),h+=A+": "+j+";");k+=d+" { "+h+" } "}c=x.createTextNode("@"+R+" "+p+" { "+k+" }");l.appendChild(c);x.getElementsByTagName("head")[0].appendChild(l);g.__css_animations[p]=
[l,a];m()}if(!b||!a||!a.view)console.error("procesAnimation: invalid component parameter!");else{var p=o.createId(),r=b.keyFrames["0%"]?!0:!1,s=!1,w=this;r?l.scheduleAction(t):l.scheduleAction(j);return p}};g.__css_animations={};g.DEFAULT_DURATION="0.3s";g.DEFAULT_TIMING=g.EASE;g.prototype={properties:null,values:null,durations:null,timings:null,origin:null,iterationCount:1,delay:0,keyFrames:null,additive:!0,setAnimations:function(a){var c,b,d;this.properties=[];this.values=[];this.timings=[];this.keyFrames=
{};this.timings=this.durations=this.origin=null;for(c=0;c<a.length;c++)d=a[c],!e.isArray(d)||2!==d.length?console.warn("vs.fx.Animation, invalid animations"):(b=d[0],d=d[1],!e.isString(b)||!e.isString(d)?console.warn("vs.fx.Animation, invalid constructor argument option: ["+b+", "+d+"]"):(this.properties.push(b),this.values.push(d)))},addKeyFrame:function(a,c){if(c)if("from"===a)this.keyFrames["0%"]=c;else if("to"===a)this.keyFrames["100%"]=c;else if(e.isNumber(a)&&!(0>a||100<a))this.keyFrames[a+
"%"]=c},process:function(a,c,b,d){return Y(a,this,c,b,d)},clone:function(){var a=new g,c,b;a.keyFrames={};a.keyFrames["100%"]=a;a.properties=this.properties?this.properties.slice():[];a.values=this.values?this.values.slice():[];this.durations&&(a.durations=this.durations);a.timings=this.timings?this.timings.slice():[];this.origin&&(a.origin=this.origin.slice());if(this.keyFrames)for(c in this.keyFrames)"100%"!==c&&(b=this.keyFrames[c],a.keyFrames[c]=e.isArray(b)?b.slice():l.util.clone(b));a.iterationCount=
this.iterationCount;a.delay=this.delay;return a},start:function(a){return this.process(a)}};e.extendClass(g,o.Task);e.defineClassProperties(g,{duration:{set:function(a){a&&(this.durations=[a])},get:function(){return this.durations&&this.durations.length?this.durations[0]:g.DEFAULT_DURATION}},timing:{set:function(a){a&&(this.timings=[a])},get:function(){return this.timings&&this.timings.length?this.timings[0]:g.EASE}}});g.EASE="ease";g.LINEAR="linear";g.EASE_IN="ease-in";g.EASE_OUT="ease-out";g.EASE_IN_OUT=
"ease-in-out";TranslateAnimation=function(a,c,b){this.parent=g;arguments.length?(u?this.parent(["translate","${x}px,${y}px,${z}px"]):this.parent(["translate","${x}px,${y}px"]),e.isNumber(a)&&(this.x=a),e.isNumber(c)&&(this.y=c),e.isNumber(b)&&(this.z=b)):this.parent();this.constructor=TranslateAnimation};TranslateAnimation.prototype={x:0,y:0,z:0};e.extendClass(TranslateAnimation,g);RotateAnimation=function(a){this.parent=g;arguments.length?(this.parent(["rotate","${deg}deg"]),e.isNumber(a)&&(this.deg=
a)):this.parent();this.constructor=RotateAnimation};RotateAnimation.prototype={deg:0};e.extendClass(RotateAnimation,g);RotateXYZAnimation=function(a,c,b){this.parent=g;arguments.length?(this.parent(["rotateX","${degX}deg"],["rotateY","${degY}deg"],["rotate","${degZ}deg"]),e.isNumber(a)&&(this.degX=a),e.isNumber(c)&&(this.degY=c),e.isNumber(b)&&(this.degZ=b)):this.parent();this.constructor=RotateXYZAnimation};RotateXYZAnimation.prototype={degX:0,degY:0,degZ:0};e.extendClass(RotateXYZAnimation,g);ScaleAnimation=
function(a,c,b){this.parent=g;arguments.length?!e.isNumber(c)&&!e.isNumber(c)?(this.parent(["scale","${sx}"]),this.sy=this.sx=a):(this.parent(["scaleX","${sx}"],["scaleY","${sy}"],["scaleZ","${sz}"]),e.isNumber(a)&&(this.sx=a),e.isNumber(c)&&(this.sy=c),e.isNumber(b)&&(this.sz=b)):this.parent();this.constructor=ScaleAnimation};ScaleAnimation.prototype={sx:1,sy:1,sz:1};e.extendClass(ScaleAnimation,g);SkewAnimation=function(a,c){this.parent=g;arguments.length?(this.parent(["skew","${ax}deg,${ay}deg"]),
e.isNumber(a)&&(this.ax=a),e.isNumber(c)&&(this.ay=c)):this.parent();this.constructor=SkewAnimation};SkewAnimation.prototype={ax:0,ay:0};e.extendClass(SkewAnimation,g);OpacityAnimation=function(a){this.parent=g;arguments.length?(this.parent(["opacity","${value}"]),e.isNumber(a)&&(this.value=a)):this.parent();this.constructor=OpacityAnimation};OpacityAnimation.prototype={value:1};e.extendClass(OpacityAnimation,g);g.SlideOutRight=new g(["translateX","$width"]);g.SlideOutRight.addKeyFrame(0,["0px"]);
g.SlideOutLeft=new g(["translateX","-$width"]);g.SlideOutLeft.addKeyFrame(0,["0px"]);g.SlideOutTop=new g(["translateY","-$height"]);g.SlideOutTop.addKeyFrame(0,["0px"]);g.SlideOutBottom=new g(["translateY","$height"]);g.SlideOutBottom.addKeyFrame(0,["0px"]);g.SlideInRight=new g(["translateX","0px"]);g.SlideInRight.addKeyFrame(0,["$width"]);g.SlideInLeft=new g(["translateX","0px"]);g.SlideInLeft.addKeyFrame(0,["-$width"]);g.SlideInTop=new g(["translateY","0px"]);g.SlideInTop.addKeyFrame(0,["-$height"]);
g.SlideInBottom=new g(["translateY","0px"]);g.SlideInBottom.addKeyFrame(0,["$height"]);g.FadeIn=new g(["opacity","1"]);g.FadeIn.addKeyFrame(0,["0"]);g.FadeOut=new g(["opacity","0"]);g.FadeOut.addKeyFrame(0,["1"]);w.Animation=g;w.cancelAnimation=function(a){if(!a)return!1;var c,b;if((b=g.__css_animations[a])&&2===b.length){if(!b[1]||!b[1].getStyle||!b[0])return!1;c=b[1].getStyle(C);if(!c)return!1;c=c.replace(a,"");b[1].setStyle(C,c);try{x.getElementsByTagName("head")[0].removeChild(b[0])}catch(d){return d.stack&&
console.log(d.stack),console.error(d),!1}delete g.__css_animations[a]}else return!1;return!0};w.TranslateAnimation=TranslateAnimation;w.RotateAnimation=RotateAnimation;w.RotateXYZAnimation=RotateXYZAnimation;w.ScaleAnimation=ScaleAnimation;w.SkewAnimation=SkewAnimation;w.OpacityAnimation=OpacityAnimation;s.prototype={_delegate:null,_owner:null,_fsm:null,_initial_component:null,destructor:function(){this._owner&&(this._owner.__controller__=B,this._owner.remove=this._owner._ab_controller_remove,this._owner._ab_controller_remove=
B);this._delegate=B;e.free(this._fsm);o.EventSource.prototype.destructor.call(this)},initComponent:function(){o.EventSource.prototype.initComponent.call(this);this._fsm&&this._fsm.init();this._owner?this._owner.__controller__?console.error("The owner already use a controller"):(this._owner.__controller__=this,this._owner._ab_controller_remove=this._owner.remove,this._owner.remove=this.ab_controller_remove):console.error("Invalid vs.fx.Controller, owner is null vs.fx.Controller.id = '"+this._id+"'")},
ab_controller_remove:function(a){a&&((state=this.__controller__._fsm._list_of_state[a.id])?this.__controller__.remove(a):this._ab_controller_remove(a))},isStateExit:function(a){return!this._fsm?!1:this._fsm._list_of_state[a]?!0:!1},add:function(a,c,b,d){console.warn("vs.fx.Controller.add is deprecated. Use vs.fx.Controller.push");return this.push(a,c,b,d)},push:function(a,c,b,d){if(a&&this._fsm){c||(c={});var h=null,n,f,h=e.isString(a)&&c.id?c.id:!e.isString(a)&&a.id?a.id:o.createId();if(!this.isStateExit(h)){this._fsm.addState(h);
this._fsm._list_of_state[h].bindings={};if(d&&d.length)for(f=0;f<d.length;f++)n=d[f],!n||3!==n.length?console.warn("vs.fx.Controller.push: invalid binding information"):this.componentBind(h,n[0],n[1],n[2]);this.setStateComponentInformation(h,a,b,c);return h}}},remove:function(a){if(a&&this._owner&&this._fsm){var c=null;e.isString(a)?c=a:e.isString(a)||(c=a.id);(a=this._fsm._list_of_state[c])&&a.comp&&this._owner._ab_controller_remove(a.comp);this._fsm.removeState(c)}},setStateComponentInformation:function(a,
c,b,d){a&&this._fsm&&this._fsm.existState(a)&&c&&this._owner&&(d=d?e.clone(d):{},a=this._fsm._list_of_state[a],a.init_data=d,e.isString(c)?(a.comp_name=c,a.comp=B):(a.comp_name="",a.comp=c,this._owner.isChild(c)||this._owner.add(c,b)))},addTransition:function(a,c,b,d,h){var e;if(a&&this._fsm&&this._fsm.existState(a)&&c&&this._fsm.existState(c)&&b)for(e in this._fsm.existInput(b)||this._fsm.addInput(b),this._fsm.addTransition(a,c,b),this._fsm._list_of_state[a].transitionEvents)b=this._fsm._list_of_state[a].transitionEvents[e],
b.to===c&&(b.animation_out=d,b.animation_in=h)},_animateComponents:function(a,c,b,d,h,e){var f=this,j=function(){try{h&&h.call(f._owner),f._delegate&&f._delegate.animationDidEnd&&(console.warn("animationDidEnd is deprecated. Please use 'controllerAnimationDidEnd'."),f._delegate.animationDidEnd(f)),f._delegate&&f._delegate.controllerAnimationDidEnd&&f._delegate.controllerAnimationDidEnd(a,c,f)}catch(b){b.stack&&console.log(b.stack),console.error(b)}};l.scheduleAction(function(){try{if(c.show(),!d&&
!b)j.call(f);else{if(e){if(d){var h=d.durations;d.durations="0s"}if(b){var g=b.durations;b.durations="0s"}}d&&!b?d.process(c,j,f):!d&&b?b.process(a,j,f):(d&&d.process(c,j,f),b&&b.process(a));e&&(d&&(d.durations=h),b&&(b.durations=g))}}catch(l){l.stack&&console.log(l.stack),console.error(l)}})},componentBind:function(a,c,b,d){if(this._fsm){var h=this._fsm._list_of_state[a],e;h&&(e=h.bindings[c],e||(e=[],h.bindings[c]=e),e.push([b,d]),a===this._current_state&&h.comp.bind(c,b,d))}},refresh:function(){},
getCurrentState:function(){return!this._fsm?void 0:this._fsm._current_state},configureNewComponent:function(){},_beforeStateEnter:function(a,c){if(a&&(a.comp_name||a.comp)){var b,d,h,e;a.comp||(a.comp=this._owner.createAndAddComponent(a.comp_name,a.init_data,a.extension),a.comp.configure(a.init_data),a.comp&&a.comp.propertiesDidChange&&a.comp.propertiesDidChange(),a.comp.propertyChange(),this.configureNewComponent(a.comp));h=c;a.data_adaptation_func&&(h=a.data_adaptation_func(c));if(h){for(d in h)if(a.comp.__lookupSetter__(d)||
a.comp.hasOwnProperty(d))a.comp[d]=h[d];a.comp.propertyChange()}for(b in a.bindings)if(d=a.bindings[b])for(h=0;h<d.length;h++)(e=d[h])&&(e[1]?a.comp.bind(b,e[0],e[1]):a.comp.bind(b,e[0]))}},_beforeStateExit:function(a){if(a&&a.comp){var c,b,d,e;for(c in a.bindings)if(b=a.bindings[c])for(d=0;d<b.length;d++)(e=b[d])&&(e[1]?a.comp.unbind(c,e[0],e[1]):a.comp.bind(c,e[0]))}},goTo:function(a,c,b,d){var h,f=null;if(!a||!this._list_of_state[a])return console.warn("vs.fx.Controller.goTo unknown State id:"+
a),!1;this._current_state&&(b&&(f=this._list_of_state[this._current_state].transitionEvents[b.on]),h=this._list_of_state[this._current_state],this.owner._beforeStateExit(h));this._current_state=a;a=this._list_of_state[this._current_state];this.owner._beforeStateEnter(a,b?b.data:null);h&&h.comp&&h.comp.viewWillDisappear&&h.comp.viewWillDisappear();a.comp.viewWillAppear&&a.comp.viewWillAppear();this.owner._delegate&&this.owner._delegate.controllerViewWillChange&&(h?this.owner._delegate.controllerViewWillChange(h.comp,
a.comp,this.owner):this.owner._delegate.controllerViewWillChange(null,a.comp,this.owner));f?this.owner._animateComponents(h.comp,a.comp,f.animation_out,f.animation_in,null,d):a.comp.show();if(c&&this._output_action[c])if(d=this._output_action[c],e.isFunction(d))d.call(this._owner,b);else if(e.isString(d))this._owner[this._output_action[c]](b);return!0},notify:function(a,c){this._fsm&&a&&a.type&&this._fsm.fsmNotify(a.type,a.data,c)},clear:function(){this._fsm&&this._fsm.clear()}};e.extendClass(s,o.EventSource);
e.defineClassProperties(s,{initialComponent:{set:function(a){!this._fsm||!a?this._initial_component=B:this._fsm.existState(a)&&(this._initial_component=a,this._fsm.initialState=a,this._fsm.goTo(a))},get:function(){return this._initial_component}},delegate:{set:function(a){this._delegate=a}}});w.Controller=s;f.ANIMATION_DURATION=350;f.NEXT="next";f.PRED="pred";f.FIRST="first";f.LAST="last";f.prototype={_is_tactile:!1,_owner_handler_event_extended:!1,_owner_handler_event:null,_animation_duration:f.ANIMATION_DURATION,
_last_comp_id:null,_states_array:null,__nb_panels:0,_view_size:null,destructor:function(){delete this._states_array;s.prototype.destructor.call(this)},initComponent:function(){s.prototype.initComponent.call(this);this.isTactile=this._is_tactile;this._updateViewSize()},push:function(a,c,b,d){if(a&&(c||(c={}),a=s.prototype.push.call(this,a,c,b,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,
a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);this.addTransition(a,this._initial_component,f.FIRST);this._last_state=a;if(this._last_comp_id===this._initial_state){state=this._fsm._list_of_state[a];if(!state){console.error("Unknown error in vs.fx.StackController.push");return}state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,b),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&
state.comp.propertiesDidChange(),state.comp.propertyChange());state.comp.show()}return this._last_comp_id=a}},_updateViewSize:function(){},remove:function(a){if(a){var c=null;e.isString(a)?c=a:e.isString(a)||(c=a.id);var b=this._states_array.findItem(c);if(-1!==b){this._fsm.removeTransitionTo(c,f.NEXT);this._fsm.removeTransitionFrom(c,f.PRED);this._fsm.removeTransitionFrom(c,f.FIRST);this._states_array.remove(b);this.__nb_panels--;if(0===b&&0<this.__nb_panels){this._initial_component=this._states_array[0];
for(var d in this._states_array)d!==c&&d!==this._initial_component&&(this._fsm.removeTransitionFrom(d,f.FIRST),this.addTransition(d,this._initial_component,f.FIRST))}0===this.__nb_panels&&(this._initial_component=B,this._fsm._current_state=B);this._initial_component&&(this._fsm._current_state===c?0===b?this._fsm.goTo(this._initial_component):(b===this._states_array.length&&b--,this._fsm.goTo(this._states_array[b])):this._fsm.goTo(this._fsm._current_state));s.prototype.remove.call(this,a)}}},orientationDidChange:function(){this._updateViewSize()},
goToViewId:function(a,c,b){a=this._states_array.findItem(a);if(-1===a)return!1;this.goToViewAt(a,c,b)},goToViewAt:function(a,c,b){if(0>a||a>this._states_array.length)return!1;var d=this._states_array.findItem(this._fsm._current_state);if(d===a)return!0;var e=this._fsm._list_of_state[this._fsm._current_state];if(a>d){for(;d<a-1;)this._fsm.fsmNotify(f.NEXT,null,!0),d++;this._fsm.fsmNotify(f.NEXT,null,!0);a=this._fsm._list_of_state[this._fsm._current_state];this._stackAnimateComponents(1,e.comp,a.comp,
c,b)}else{for(;a+1<d;)this._fsm.fsmNotify(f.PRED,null,!0),d--;this._fsm.fsmNotify(f.PRED,null,!0);a=this._fsm._list_of_state[this._fsm._current_state];this._stackAnimateComponents(-1,e.comp,a.comp,c,b)}},_stackAnimateComponents:function(){},_animateComponents:function(){},goToNextView:function(a,c){var b=this._fsm._list_of_state[this._fsm._current_state],d=this._fsm.fsmNotify(f.NEXT,null,!0),e=this._fsm._list_of_state[this._fsm._current_state];d&&this._stackAnimateComponents(1,b.comp,e.comp,a,c);
return d},goToPreviousView:function(a,c){var b=this._fsm._list_of_state[this._fsm._current_state],d=this._fsm.fsmNotify(f.PRED,null,!0),e=this._fsm._list_of_state[this._fsm._current_state];d&&this._stackAnimateComponents(-1,b.comp,e.comp,a,c);return d},goToFirstView:function(a,c,b){var d=this._fsm._list_of_state[this._fsm._current_state],e=this._fsm.fsmNotify(f.FIRST,null,!0),g=this._fsm._list_of_state[this._fsm._current_state];e&&this._stackAnimateComponents(b?b:-1,d.comp,g.comp,a,c);return e},goToLastView:function(a,
c,b){var d=this._fsm._list_of_state[this._fsm._current_state],e=this._fsm.goTo(this._last_state,null,{on:f.LAST,data:null},c),g=this._fsm._list_of_state[this._fsm._current_state];e&&this._stackAnimateComponents(b?b:1,d.comp,g.comp,a,c);return e},handleEvent:function(){}};e.extendClass(f,s);e.defineClassProperties(f,{viewSize:{set:function(a){a&&e.isArray(a)&&2===a.length&&e.isNumber(a[0])&&e.isNumber(a[1])&&(this._view_size||(this._view_size=[]),this._view_size[0]=a[0],this._view_size[1]=a[1],this._updateViewSize())},
get:function(){return!this._view_size?this._owner.size:this._view_size.slice()}},isTactile:{set:function(a){a?(this._is_tactile=!0,this._owner&&this._owner.view&&(this._owner_handler_event_extended||(this._owner_handler_event=this._owner.handleEvent,this._owner.handleEvent=this.handleEvent,l.addPointerListener(this._owner.view,o.POINTER_START,this._owner,!1)),this._owner_handler_event_extended=!0)):(this._is_tactile=!1,this._owner&&this._owner.view&&this._owner_handler_event_extended&&(l.removePointerListener(this._owner.view,
o.POINTER_START,this._owner,!1),this._owner.handleEvent=this._owner_handler_event,this._owner_handler_event_extended=!1))},get:function(){return this._is_tactile}},animationDuration:{set:function(a){a||(a=0);e.isNumber(a)&&(this._animation_duration=a)}}});w.StackController=f;var m=l.core.createClass({parent:l.fx.StackController,_delta:0,_orientation:0,_transition_out_left:null,_transition_out_right:null,_transition_in:null,_animation_mode:0,properties:{orientation:{set:function(a){a!==m.HORIZONTAL&&
a!==m.VERTICAL||(this._orientation=a,this._updateViewSize())},get:function(){return this._orientation}},animationDuration:{set:function(a){a||(a=0);e.isNumber(a)&&(this._animation_duration=a,this._transition_out_left.duration=this._animation_duration+"ms",this._transition_out_right.duration=this._animation_duration+"ms",this._transition_in.duration=this._animation_duration+"ms")}},animationMode:{set:function(a){a||(a=0);a!==m.POURCENTAGE&&a!==m.PIXEL||this._animation_mode===a||(this._animation_mode=
a,e.free(this._transition_out_right),e.free(this._transition_out_left),this._setUpAnimations(),this._updateViewSize())}}},constructor:function(a){this._super(a);this._orientation=m.HORIZONTAL;arguments.length&&(this._setUpAnimations(),this._transition_in=new g(["translate","0,0,0"]),this.animationDuration=m.ANIMATION_DURATION)},_setUpAnimations:function(){switch(this._animation_mode){case m.POURCENTAGE:this._transition_out_left=new g(["translate","${x}%,${y}%,0"]);this._transition_out_right=new g(["translate",
"${x}%,${y}%,0"]);break;case m.PIXEL:this._transition_out_left=new g(["translate","${x}px,${y}px,0"]),this._transition_out_right=new g(["translate","${x}px,${y}px,0"])}this._transition_out_left.x=0;this._transition_out_left.y=0;this._transition_out_left.duration=this._animation_duration+"ms";this._transition_out_right.duration=this._animation_duration+"ms"},_updateViewSize:function(){var a,c,b,d;switch(this._animation_mode){case m.POURCENTAGE:a=100;delta_str=a+"%";break;case m.PIXEL:c=this._owner.size,
this._orientation===m.HORIZONTAL?a=c[0]:this._orientation===m.VERTICAL&&(a=c[1]),delta_str=a+"px"}this._orientation===m.HORIZONTAL?(this._transition_out_left.x=-a,this._transition_out_left.y=0,this._transition_out_right.x=a,this._transition_out_right.y=0):this._orientation===m.VERTICAL&&(this._transition_out_left.x=0,this._transition_out_left.y=-a,this._transition_out_right.x=0,this._transition_out_right.y=a);this._orientation===m.HORIZONTAL?d="translate3D(-"+delta_str+",0,0)":this._orientation===
m.VERTICAL&&(d="translate3D(0,-"+delta_str+",0)");for(a=0;a<this._states_array.length;a++)if(c=this._states_array[a],(b=this._fsm._list_of_state[c])&&b.comp)this._fsm._current_state===c?(this._orientation===m.HORIZONTAL?d="translate3D("+delta_str+",0,0)":this._orientation===m.VERTICAL&&(d="translate3D(0,"+delta_str+",0)"),b.comp.view.style.webkitTransitionDuration="0",v(b.comp.view,"translate3D(0,0,0)")):(b.comp.view.style.webkitTransitionDuration="0",v(b.comp.view,d))},push:function(a,c,b,d){if(a&&
(c||(c={}),a=s.prototype.push.call(this,a,c,b,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,b),state.comp.configure(state.init_data),state.comp.setStyle("position",
"absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.StackController.push")}},configureNewComponent:function(a){var c,b,d;switch(this._animation_mode){case m.POURCENTAGE:b=
"100%";break;case m.PIXEL:d=this._owner.size,this._orientation===m.HORIZONTAL?b=d[0]+"px":this._orientation===m.VERTICAL&&(b=d[1]+"px")}this._orientation===m.HORIZONTAL?c="translate3D("+b+",0,0)":this._orientation===m.VERTICAL&&(c="translate3D(0,"+b+",0)");a.view.style.webkitTransitionDuration="0";v(a.view,c);a.hide()},handleEvent:function(a){var c=!1,b=this.size,d=this.__controller__._animation_duration;a.type===o.POINTER_START?(this.__pos=this.__controller__._orientation===m.HORIZONTAL?a.changedTouches?
a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,l.addPointerListener(x,o.POINTER_END,this,!0),l.addPointerListener(x,o.POINTER_MOVE,this,!0),this.__delta=this.animationDuration=0):a.type===o.POINTER_MOVE?(a.preventDefault(),this.__delta=this.__controller__._orientation===m.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos:a.changedTouches?a.changedTouches[0].clientY-this.__pos:a.clientY-this.__pos):a.type===o.POINTER_END&&
(50<this.__delta?c=this.__controller__.goToPreviousView():-50>this.__delta&&(c=this.__controller__.goToNextView()),c||(this.animationDuration=d=this.__controller__._orientation===m.HORIZONTAL?Math.floor(d*this.__delta/b[0]):Math.floor(d*this.__delta/b[1])),l.removePointerListener(x,o.POINTER_END,this,!0),l.removePointerListener(x,o.POINTER_MOVE,this,!0))},refresh:function(){f.prototype.refresh.call(this);this._updateViewSize()},_stackAnimateComponents:function(a,c,b,d,e){var f=this._transition_in,
g,j,k;0<a?(j=this._transition_out_right,g=this._transition_out_left):(j=this._transition_out_left,g=this._transition_out_right);k=j.durations;j.durations="0s";var m=this,o=function(){c.hide();try{m._delegate&&m._delegate.controllerAnimationDidEnd&&m._delegate.controllerAnimationDidEnd(c,b,m),d&&d.call(m._owner)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},p=function(){j.durations=k;try{b.show(),b.refresh(),l.scheduleAction(function(){if(e){var a=f.durations;f.durations="0s";var d=g.durations;
g.durations="0s"}f.process(b,o,m);g.process(c);e&&(f.durations=a,g.durations=d)})}catch(a){a.stack&&console.log(a.stack),console.error(a)}};j.process(b,function(){l.scheduleAction(function(){p()})})}});m.ANIMATION_DURATION=300;m.HORIZONTAL=0;m.VERTICAL=1;m.POURCENTAGE=0;m.PIXEL=1;w.SlideController=m;var r=l.core.createClass({parent:l.fx.StackController,_is_circular:!1,_is_continuous_swipe:!1,__delta:0,__current_pos:0,_orientation:0,properties:{orientation:{set:function(a){a!==r.HORIZONTAL&&a!==r.VERTICAL||
(this._orientation=a,this._updateViewSize())},get:function(){return this._orientation}},isTactile:{set:function(a){a?(this._is_tactile=!0,this._owner&&this._owner.view&&(!this._owner_handler_event_extended&&!this.__drag_recognizer&&(this.__drag_recognizer=new I.DragRecognizer(this),this._owner.addPointerRecognizer(this.__drag_recognizer)),this._owner_handler_event_extended=!0)):(this._is_tactile=!1,this._owner&&this._owner.view&&this._owner_handler_event_extended&&(this.__drag_recognizer&&(this._owner.removePointerRecognizer(this.__drag_recognizer),
this.__drag_recognizer=null),this._owner_handler_event_extended=!1))},get:function(){return this._is_tactile}},isCircular:{set:function(a){this._is_circular=a?!0:!1},get:function(){return this._is_circular}},isContinuousSwipe:{set:function(a){this._is_continuous_swipe=a?!0:!1},get:function(){return this._is_continuous_swipe}}},constructor:function(a){this._super(a);this._orientation=r.HORIZONTAL;arguments.length&&(this.animationDuration=r.ANIMATION_DURATION)},_updateViewSize:function(){var a,c,b;
a=this._owner.size;this._orientation===r.HORIZONTAL?b=a[0]:this._orientation===r.VERTICAL&&(b=a[1]);for(a=0;a<this._states_array.length;a++)c=this._states_array[a],(c=this._fsm._list_of_state[c])&&c.comp&&(this._orientation===r.HORIZONTAL?c.comp.translate(b*a,0,0):this._orientation===r.VERTICAL&&c.comp.translate(0,b*a,0))},push:function(a,c,b,d){if(a&&(c||(c={}),a=s.prototype.push.call(this,a,c,b,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=
this.initialComponent=a;this.addTransition(this._last_comp_id,a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);this.addTransition(a,this._initial_component,f.FIRST);this._last_state=a;if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,b),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&
state.comp.propertiesDidChange(),state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.StackController.push")}},configureNewComponent:function(){var a=this._owner.size;this._orientation===r.HORIZONTAL?state.comp.translate(a[0]*(this.__nb_panels-1),0,0):this._orientation===
r.VERTICAL&&state.comp.translate(0,a[1]*(this.__nb_panels-1),0)},didDrag:function(a){this.__delta=this._orientation===r.HORIZONTAL?a.dx:a.dy;this._is_continuous_swipe&&(a=this._owner._holes.children,a.style.webkitTransitionDuration="0ms",v(a,"translate3D("+(this.__delta+this.__current_pos)+"px,0,0)"))},didDragEnd:function(){function a(){var a=b._owner._holes.children;a.style.webkitTransitionDuration=b._animation_duration+"ms";b._orientation===r.HORIZONTAL?v(a,"translate3D("+b.__current_pos+"px,0,0)"):
v(a,"translate3D(0,"+b.__current_pos+"px,0)")}var c,b=this;50<this.__delta?(c=this._fsm.getAccessibleStateOn(f.PRED),(c=!c&&this._is_circular?this.goToLastView(null,null,-1):this.goToPreviousView())||a()):-50>this.__delta?(c=this._fsm.getAccessibleStateOn(f.NEXT),(c=!c&&this._is_circular?this.goToFirstView(null,null,1):this.goToNextView())||a()):this._is_continuous_swipe&&a()},refresh:function(){f.prototype.refresh.call(this);this._updateViewSize()},_stackAnimateComponents:function(a,c,b,d,e){var a=
this._owner.size,f=this._owner._holes.children,c=this._states_array.indexOf(b.id);f.style.webkitTransitionDuration="0ms";this.__current_pos=this._orientation===r.HORIZONTAL?c*-a[0]:c*-a[1];var g=this;(function(){try{b.show(),b.refresh(),l.scheduleAction(function(){f.style.webkitTransitionDuration=e?"0ms":g._animation_duration+"ms";g._orientation===r.HORIZONTAL?v(f,"translate3D("+g.__current_pos+"px,0,0)"):v(f,"translate3D(0,"+g.__current_pos+"px,0)")})}catch(a){a.stack&&console.log(a.stack),console.error(a)}})()}});
e.extend(r.prototype,I.RecognizerManager);r.ANIMATION_DURATION=300;r.HORIZONTAL=0;r.VERTICAL=1;r.PIXEL=1;w.SwipeController=r;p.NO_ANIMATION=0;p.CARD_ANIMATION=1;p.SLIDE_ANIMATION=2;p.DEFAULT_ANIMATION=p.SLIDE_ANIMATION;p.BACK="back";p.prototype={_nav_bar:null,__nav_bar_states:null,_animation_type:p.DEFAULT_ANIMATION,destructor:function(){s.prototype.destructor.call(this)},initComponent:function(){s.prototype.initComponent.call(this);this.__translate_in_right=new TranslateAnimation(0);this.__translate_out_right=
new g(["translate","100%,0,0"]);this.__translate_out_left=new g(["translate","-100%,0,0"]);this.__translate_in_left=new TranslateAnimation(0)},setNavigationBar:function(a){a&&!(!a instanceof I.NavigationBar)&&(this._nav_bar=a)},_updateViewSize:function(){},push:function(a,c,b){if(a&&(c||(c={}),a=s.prototype.push.call(this,a,c,null,b)))return(c=this._fsm._list_of_state[a])&&c.comp&&this.configureNewComponent(c.comp),a},configureNavigationBarState:function(a,c){var b,d,f,g,k=[],j={};if(this._fsm._list_of_state[a]&&
c){for(d=0,f=c.length;d<f;d++)if(g=c[d])if(b=g.comp)e.isString(b)&&(b=o.Object._obs[b]),!b instanceof l.ui.View||(k.push(b),g.properties&&(j[b.id]=g.properties));this.__nav_bar_states[a]=j;this._nav_bar&&this._nav_bar.setStateItems(a,k)}},configureTransition:function(a,c,b){a&&this._fsm.existState(a)&&c&&this._fsm.existState(c)&&b&&(this._fsm.existInput(b)||this._fsm.addInput(b),this._animation_type===p.SLIDE_ANIMATION?(this.addTransition(a,c,b,this.__translate_out_left,this.__translate_in_right),
this.addTransition(c,a,p.BACK,this.__translate_out_right,this.__translate_in_left),this.__translate_in_left.duration="300ms",this.__translate_out_left.duration="300ms",this.__translate_in_right.duration="300ms",this.__translate_out_right.duration="300ms"):this._animation_type===p.CARD_ANIMATION?(this.addTransition(a,c,b,null,this.__translate_in_right),this.addTransition(c,a,p.BACK,this.__translate_out_right,null),this.__translate_in_right.duration="300ms",this.__translate_out_right.duration="300ms"):
(this.addTransition(a,c,b,null,this.__translate_in_right),this.addTransition(c,a,p.BACK,this.__translate_out_right,null),this.__translate_in_right.duration="0",this.__translate_out_right.duration="0"))},configureNewComponent:function(a){this.__translate_out_right.process(a,null,null,!0)},goTo:function(a,c,b,d){s.prototype.goTo.call(this,a,c,b,d)&&this.owner._nav_bar&&this.owner._nav_bar.changeState(a,this.owner.__nav_bar_states[a])},_animateComponents:w.Controller.prototype._animateComponents};e.extendClass(p,
f);e.defineClassProperties(p,{viewSize:{set:function(a){a&&e.isArray(a)&&2===a.length&&e.isNumber(a[0])&&e.isNumber(a[1])&&(this._view_size||(this._view_size=[]),this._view_size[0]=a[0],this._view_size[1]=a[1],this._updateViewSize())},get:function(){return!this._view_size?this._owner.size:this._view_size.slice()}},initialComponent:{set:function(a){if(a){if(this._fsm.existState(a)){this._initial_component=a;this._fsm.initialState=a;this._fsm.goTo(a);var a=this._fsm._list_of_state[a],c=this.__translate_in_right;
a&&a.comp&&c.process(a.comp,null,null,!0)}}else this._initial_component=B},get:function(){return this._initial_component}}});w.NavigationController=p;var k=l.core.createClass({parent:l.fx.StackController,_direction:0,_transition_out:null,_transition_in:null,properties:{direction:{set:function(a){a!==k.LEFT_OUT&&a!==k.RIGHT_OUT&&a!==k.BOTTOM_OUT&&a!==k.TOP_OUT||(this._direction=a,this._updateViewSize())},get:function(){return this._direction}},animationDuration:{set:function(a){a||(a=0);e.isNumber(a)&&
(this._animation_duration=a,this._transition_out&&(this._transition_out.duration=this._animation_duration+"ms"),this._transition_in&&(this._transition_in.duration=this._animation_duration+"ms"))}}},constructor:function(a){this._super(a);a&&(this._transition_out=new g(["translate","${x}%,${y}%,0"]),this._transition_out.x=0,this._transition_out.y=0,this._transition_in=new g(["translate","${x}%,${y}%,0"]),this._transition_in.x=0,this._transition_in.y=0,this.animationDuration=k.ANIMATION_DURATION);this._direction=
k.RIGHT_OUT},_updateViewSize:function(){this._transition_out&&(this._direction===k.LEFT_OUT?(this._transition_out.x=-100,this._transition_out.y=0):this._direction===k.RIGHT_OUT?(this._transition_out.x=100,this._transition_out.y=0):this._direction===k.BOTTOM_OUT?(this._transition_out.x=0,this._transition_out.y=100):(this._transition_out.x=0,this._transition_out.y=-100))},push:function(a,c,b,d){if(a&&(c||(c={}),a=s.prototype.push.call(this,a,c,b,d))){this._states_array.push(a);this.__nb_panels++;if(1===
this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,b),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),
state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.CardController.push")}},configureNewComponent:function(a){var c;c=u?"translate3d":"translate";c=this._direction===k.LEFT_OUT?c+"(-100%,0":this._direction===k.RIGHT_OUT?c+"(100%,0":this._direction===k.BOTTOM_OUT?
c+"(0,100%":c+"(0,-100%";c=u?c+",0)":c+")";a.view.style.webkitTransitionDuration="0";v(a.view,c)},handleEvent:function(a){var c=!1,b,d;if(a.type===o.POINTER_START)this.__pos=this.__controller__._direction===k.LEFT_OUT||this.__controller__._direction===k.RIGHT_OUT?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,l.addPointerListener(x,o.POINTER_END,this,!0),l.addPointerListener(x,o.POINTER_MOVE,this,!0);else if(a.type===o.POINTER_MOVE)if(a.preventDefault(),
b=this.__controller__._fsm._list_of_state[this.__controller__._fsm._current_state],c=this.__controller__._states_array.indexOf(this.__controller__._fsm._current_state),0<c&&(d=this.__controller__._states_array[c-1]),this.__controller__._direction===k.LEFT_OUT||this.__controller__._direction===k.RIGHT_OUT?(this.__delta=a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos,a=u?"translate3d("+this.__delta+"px,0px,0)":"translate("+this.__delta+"px,0px)"):(this.__delta=a.changedTouches?
a.changedTouches[0].clientY-this.__pos:a.clientY-this.__pos,a=u?"translate3d(0px,"+this.__delta+"px,0)":"translate(0px,"+this.__delta+"px)"),this.__controller__._direction===k.LEFT_OUT||this.__controller__._direction===k.TOP_OUT)if(0>this.__delta)b.comp.view.style.webkitTransitionDuration=0,v(b.comp.view,a);else{if(d&&(b=this.__controller__._fsm._list_of_state[d])&&b.comp)a=this.__controller__._direction===k.LEFT_OUT||this.__controller__._direction===k.RIGHT_OUT?u?"translate3d("+(this.__delta-this._size[0])+
"px,0px,0)":"translate("+(this.__delta-this._size[0])+"px,0px)":u?"translate3d(0px,"+(this.__delta-this._size[1])+"px,0)":"translate(0px,"+(this.__delta-this._size[1])+"px)",b.comp.view.style.webkitTransitionDuration=0,v(b.comp.view,a)}else if(0<this.__delta)b.comp.view.style.webkitTransitionDuration=0,v(b.comp.view,a);else{if(d&&(b=this.__controller__._fsm._list_of_state[d])&&b.comp)a=this.__controller__._direction===k.LEFT_OUT||this.__controller__._direction===k.RIGHT_OUT?u?"translate3d("+(this._size[0]+
this.__delta)+"px,0px,0)":"translate("+(this._size[0]+this.__delta)+"px,0px)":u?"translate3d(0px,"+(this._size[1]+this.__delta)+"px,0)":"translate(0px,"+(this._size[1]+this.__delta)+"px)",b.comp.view.style.webkitTransitionDuration=0,v(b.comp.view,a)}else if(a.type===o.POINTER_END){b=this.__controller__._fsm._list_of_state[this.__controller__._fsm._current_state];this.__controller__._direction===k.LEFT_OUT||this.__controller__._direction===k.TOP_OUT?50<this.__delta?c=this.__controller__.goToPreviousView():
-50>this.__delta&&(c=this.__controller__.goToNextView()):50<this.__delta?c=this.__controller__.goToNextView():-50>this.__delta&&(c=this.__controller__.goToPreviousView());if(!c)if(c=this.__controller__._states_array.indexOf(this.__controller__._fsm._current_state),0<c&&(d=this.__controller__._states_array[c-1]),(this.__controller__._direction===k.LEFT_OUT||this.__controller__._direction===k.TOP_OUT)&&0>this.__delta)a=u?"translate3d(0,0,0)":"translate(0,0)",b.comp.view.style.webkitTransitionDuration=
this.__controller__._animation_duration+"ms",v(b.comp.view,a);else if((this.__controller__._direction===k.RIGHT_OUT||this.__controller__._direction===k.BOTTOM_OUT)&&0<this.__delta)a=u?"translate3d(0,0,0)":"translate(0,0)",b.comp.view.style.webkitTransitionDuration=this.__controller__._animation_duration+"ms",v(b.comp.view,a);else if(d&&(b=this.__controller__._fsm._list_of_state[d])&&b.comp)a=this.__controller__._direction===k.LEFT_OUT?"(-100%,0px":this.__controller__._direction===k.RIGHT_OUT?"(100%,0px":
this.__controller__._direction===k.BOTTOM_OUT?"(0px,100%":"(0px,-100%",a=u?a+",0)":a+")",b.comp.view.style.webkitTransitionDuration=this.__controller__._animation_duration+"ms",v(b.comp.view,a);l.removePointerListener(x,o.POINTER_END,this,!0);l.removePointerListener(x,o.POINTER_MOVE,this,!0)}},_stackAnimateComponents:function(a,c,b,d,e){var f,g,j,k;0<a?(f=this._transition_in,k=b):(f=this._transition_out,g=this._transition_in,k=c);g&&(j=g.durations,g.durations="0s");var m=this,o=function(){c.hide();
try{m._delegate&&m._delegate.controllerAnimationDidEnd&&m._delegate.controllerAnimationDidEnd(c,b,m),d&&d.call(this.owner)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},p=function(){g&&(g.durations=j);try{b.show();if(e){var a=f.durations;f.durations="0s"}f.process(k,o,m);e&&(f.durations=a)}catch(c){c.stack&&console.log(c.stack),console.error(c)}};g?g.process(b,function(){l.scheduleAction(function(){p()})}):p()}});k.ANIMATION_DURATION=300;k.LEFT_OUT=0;k.RIGHT_OUT=1;k.TOP_OUT=2;k.BOTTOM_OUT=
3;w.CardController=k;t._translate_animation=new RotateXYZAnimation(-90,0,0);t._translate_animation.init();t._translate_animation.addKeyFrame("from",{degX:0});t._translate_animation.addKeyFrame(50,{degX:-92});t._translate_animation.addKeyFrame(70,{degX:-84});t._translate_animation.addKeyFrame(80,{degX:-90});t._translate_animation.addKeyFrame(95,{degX:-88});t._translate_animation.durations="2s";t.HORIZONTAL=0;t.VERTICAL=1;t.prototype={_orientation:t.HORIZONTAL,push:function(a,c,b){if(a){if(!e.isString(a)){var d=
this._states_array.length;a.position=[0,0];a.setStyle("z-index",1E3-d)}return f.prototype.push.call(this,a,c,b)}},handleEvent:function(a){var c=!1,b,d;if(a.type===o.POINTER_START)this.__pos=this.__layer._orientation===t.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,l.addPointerListener(x,o.POINTER_END,this,!0),l.addPointerListener(x,o.POINTER_MOVE,this,!0),this.animationDuration=0;else if(a.type===o.POINTER_MOVE)if(a.preventDefault(),
b=this.__layer._list_of_state[this.__layer._current_state],c=this.__layer._states_array.indexOf(this.__layer._current_state),0<c&&(d=this.__layer._states_array[c-1]),this.__layer._orientation===t.HORIZONTAL?(this.__delta=a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos,a=u?"translate3d("+this.__delta+"px,0px,0)":"translate("+this.__delta+"px,0px)"):(this.__delta=a.changedTouches?a.changedTouches[0].clientY-this.__pos:a.clientY-this.__pos,a=u?"translate3d(0px,"+this.__delta+
"px,0)":"translate(0px,"+this.__delta+"px)"),0>this.__delta)b.comp.view.style.webkitTransitionDuration=0,v(b.comp.view,a);else{if(d&&(b=this.__layer._list_of_state[d])&&b.comp)a=this.__layer._orientation===t.HORIZONTAL?u?"translate3d("+(this.__delta-this._size[0])+"px,0px,0)":"translate("+(this.__delta-this._size[0])+"px,0px)":u?"translate3d(0px,"+(this.__delta-this._size[1])+"px,0)":"translate(0px,"+(this.__delta-this._size[1])+"px)",b.comp.view.style.webkitTransitionDuration=0,v(b.comp.view,a)}else if(a.type===
o.POINTER_END){b=this.__layer._list_of_state[this.__layer._current_state];50<this.__delta?c=this.__layer.goToPreviousView():-50>this.__delta&&(c=this.__layer.goToNextView());if(!c)if(c=this.__layer._states_array.indexOf(this.__layer._current_state),0<c&&(d=this.__layer._states_array[c-1]),0>this.__delta)a=u?"translate3d(0,0,0)":"translate(0,0)",b.comp.view.style.webkitTransitionDuration=this.__layer._animation_duration+"ms",v(b.comp.view,a);else if(d&&(b=this.__layer._list_of_state[d])&&b.comp)a=
this.__layer._orientation===t.HORIZONTAL?u?"translate3d("+this._size[0]+"px,0px,0)":"translate("+this._size[0]+"px,0px)":u?"translate3d(0px,-"+this._size[1]+"px,0)":"translate(0px,-"+this._size[1]+"px)",b.comp.view.style.webkitTransitionDuration=this.__layer._animation_duration+"ms",v(b.comp.view,a);l.removePointerListener(x,o.POINTER_END,this,!0);l.removePointerListener(x,o.POINTER_MOVE,this,!0)}},goTo:function(a,c,b){function d(a){var b=this._list_of_state[this._states_array[a]];b&&(b.comp||(b.comp=
this.owner.createAndAddComponent(b.comp_name,b.init_data,b.extension),b.comp.configure(b.init_data),b.comp.style("position","absolute"),b.comp&&b.comp.propertiesDidChange&&b.comp.propertiesDidChange(),b.comp.propertyChange()),b.view?__setPos(b.view,0,0):b.comp.position=[0,0],b.comp.show(),b.comp.style("z-index",1E3-a))}var g=this._states_array.indexOf(a),k=this._list_of_state[this._current_state];f.prototype.goTo.call(this,a,c,b);if(a&&(this.owner.animationDuration=this._animation_duration,a=this._list_of_state[this._current_state],
a.comp.setStyle("position","absolute"),a.comp.position=[0,0],a.comp.setStyle("z-index",1E3-g),k&&a&&(k.comp.setStyle("-webkit-transform","scale3d(.835,.835,.835) translateZ(200px)"),a.comp.setStyle("-webkit-transform","scale3d(.835,.835,.835) rotateX(90deg) translateZ(200px)")),0<g&&d.call(this,g-1),g<this._states_array.length-1&&d.call(this,g+1),b&&b.on===f.NEXT&&k?t._translate_animation.process(this.owner):b&&b.on===f.PRED&&a&&(t._translate_animation.x=0,t._translate_animation.y=0,t._translate_animation.process(a.comp)),
c&&this._output_action[c]))if(g=this._output_action[c],e.isFunction(g))g.call(this.owner,b);else if(e.isString(g))this.owner[this._output_action[c]](b)}};e.extendClass(t,f);w.CubicController=t;y._opacity_animation=new OpacityAnimation(1);y._opacity_animation.init();y._opacity_animation.durations="0.2s";y.ANIMATION_DURATION=500;y.prototype={push:function(a,c,b){if(a){if(!e.isString(a)){var d=this._states_array.length;a.position=[0,0];a.setStyle("z-index",1E3-d)}f.prototype.push.call(this,a,c,b)}},
goTo:function(a,c,b){function d(a){var b=this._list_of_state[this._states_array[a]];b&&(b.comp||(b.comp=this.owner.createAndAddComponent(b.comp_name,b.init_data,b.extension),b.comp.configure(b.init_data),b.comp.setStyle("position","absolute"),b.comp&&b.comp.propertiesDidChange&&b.comp.propertiesDidChange(),b.comp.propertyChange()),b.view?__setPos(b.view,0,0):b.comp.position=[0,0],b.comp.show(),b.comp.setStyle("z-index",1E3-a))}var g=this._states_array.indexOf(a),k=this._list_of_state[this._current_state];
f.prototype.goTo.call(this,a,c,b);if(a&&(a=this._list_of_state[this._current_state],a.comp.setStyle("position","absolute"),a.comp.position=[0,0],a.comp.setStyle("z-index",1E3-g),0<g&&d.call(this,g-1),g<this._states_array.length-1&&d.call(this,g+1),b&&b.on===f.NEXT&&k?(y._opacity_animation.value=0,y._opacity_animation.process(k.comp)):b&&b.on===f.PRED&&a&&(y._opacity_animation.value=1,y._opacity_animation.process(a.comp)),c&&this._output_action[c]))if(g=this._output_action[c],e.isFunction(g))g.call(this.owner,
b);else if(e.isString(g))this.owner[this._output_action[c]](b)}};e.extendClass(y,f);e.defineClassProperty(y,"animationDuration",{set:function(a){a||(a=0);e.isNumber(a)&&(this._animation_duration=a,y._opacity_animation.durations=a/1E3+"s")}});w.OpacityController=y})(window);
