/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(L,B){function z(a){return!k.CSS_VENDOR?a:"-"+k.CSS_VENDOR.toLowerCase()+"-"+a}function e(a){this.parent=m.Task;this.parent();this.constructor=e;arguments.length&&(this.setAnimations(arguments),this.keyFrames["100%"]=this)}function s(a){this.parent=m.EventSource;this.parent();this.constructor=s;a&&(this._fsm=new m.Fsm(this),this._fsm.goTo=this.goTo,this._owner=a)}function f(a){this.parent=s;this.parent(a);this.constructor=f;arguments.length&&(this._fsm.addInput(f.NEXT),this._fsm.addInput(f.PRED),
this._fsm.addInput(f.FIRST),this._states_array=[])}function p(a,b,c){this.parent=s;this.parent(a);this.constructor=p;arguments.length&&(this._animation_type=c==p.NO_ANIMATION||c==p.CARD_ANIMATION||c==p.SLIDE_ANIMATION?c:p.DEFAULT_ANIMATION,this.setNavigationBar(b),this.__nav_bar_states={})}function t(a,b){this.parent=f;this.parent(a,b);this.constructor=t;a&&a.setStyle("-webkit-transform-style","preserve-3d")}function y(a,b){this.parent=f;this.parent(a,b);this.constructor=y;this.animationDuration=
y.ANIMATION_DURATION}var x=L.document,k=L.vs,g=k.util,m=k.core,I=k.ui,w=k.fx,v=g.setElementTransform,u=k.SUPPORT_3D_TRANSFORM;k.CSS_VENDOR;var F=z("animation-duration"),J=z("animation-delay"),C=z("animation-name"),M=z("animation-timing-function"),N=z("animation-fill-mode"),G=z("transition-duration"),K=z("transition-delay"),O=z("transition-timing-function"),P=z("transition-property"),Q=z("transform-origin"),H=z("animation-iteration-count"),A=z("transform"),R=z("keyframes"),D="animationend",E="transitionend";
"webkit"===k.CSS_VENDOR?(D="webkitAnimationEnd",E="webkitTransitionEnd"):"ms"===k.CSS_VENDOR?(D="msAnimationEnd",E="msTransitionEnd"):"moz"===k.CSS_VENDOR&&(D="Mozanimationend",E="Moztransitionend");g.extend(k,{ANIMATION_DURATION:F,ANIMATION_DELAY:J,ANIMATION_NAME:C,ANIMATION_TIMING_FUNC:M,ANIMATION_FILL_MODE:N,TRANSITION_DURATION:G,TRANSITION_PROPERTY:P,TRANSITION_DELAY:K,TRANSITION_TIMING_FUNC:O,TRANSFORM_ORIGIN:Q,ITERATION_COUNT:H,TRANSFORM:A,KEY_FRAMES:R,ANIMATION_END:D,TRANSITION_END:E});var T=
RegExp(/\$width/g),U=RegExp(/\$height/g),V=RegExp(/\$x/g),W=RegExp(/\$y/g),S=RegExp(/\$\{([\w]+)\}/g),Y=function(a,b,c,d,j){function e(c,d){var j,q=[],f;if(g.isNumber(c))return c;if(g.isString(c)){c=c.replace(T,a.size[0]+"px");c=c.replace(U,a.size[1]+"px");c=c.replace(V,a.position[0]+"px");c=c.replace(W,a.position[1]+"px");for(j=S.exec(c);j&&2===j.length;)q.push(j[1]),j=S.exec(c);for(j=0;j<q.length;j++)f=q[j],"undefined"!==typeof d[f]?c=c.replace("${"+f+"}",d[f]):"undefined"!==typeof b[f]&&(c=c.replace("${"+
f+"}",b[f]));return c}console.warn("vs.fx.Animation._parseValue. Unknown value's type: "+c);return 0}if(!b||!a||!a.view)console.error("procesAnimation: invalid component parameter!");else{var f=function(a){var c={},b,d;c.properties=a.properties?a.properties.slice():[];c.values=a.values?a.values.slice():[];a.durations&&(c.durations=a.durations);c.timings=a.timings?a.timings.slice():[];a.origin&&(c.origin=a.origin.slice());c.iterationCount=a.iterationCount;c.delay=a.delay;c.additive=a.additive;c.keyFrames=
{};a.keyFrames["100%"]||(a.keyFrames["100%"]=a);var j;for(b in a.keyFrames)if(d=a.keyFrames[b],g.isArray(d)){j=[];for(var f=0;f<d.length;f++)value=d[f],null==value||"undefined"==typeof value||(j[f]=e(value,a));c.keyFrames[b]=j}else{for(f=0;f<a.properties.length;f++)c.values[f]=e(a.values[f],d);c.keyFrames[b]={}}return c}(b);return X(a,b,f,c,d,j)}},X=function(a,b,c,d,j,f){function o(){var b;b=r?F:G;g.isArray(c.origin)&&2===c.origin.length&&a.setStyle(Q,c.origin[0]+"% "+c.origin[1]+"%");f?a.setStyle(b,
0):g.isString(c.durations)?a.setStyle(b,c.durations):g.isArray(c.durations)?a.setStyle(b,c.durations.join(", ")):a.setStyle(b,e.DEFAULT_DURATION);b=r?J:K;!f&&g.isNumber(c.delay)?a.setStyle(b,c.delay+"ms"):a.setStyle(b,"0");b=r?M:O;g.isString(c.timings)?a.setStyle(b,c.timings):g.isArray(c.timings)?a.setStyle(b,c.timings.join(", ")):a.setStyle(b,e.EASE);r&&("infinite"===c.iterationCount?a.setStyle(H,"infinite"):!c.iterationCount||!g.isNumber(c.iterationCount)?a.setStyle(H,"1"):a.setStyle(H,c.iterationCount),
a.setStyle(N,"forwards"))}function h(){o();var e,g;e=function(g){if(g.currentTarget===a.view){s||a.view.removeEventListener(E,e,!1);a.view.style.removeProperty(G);a.view.style.removeProperty(K);if(b.delegate&&b.delegate.taskDidEnd)try{b.delegate.taskDidEnd(c)}catch(f){f.stack&&console.log(f.stack),console.error(f)}d&&d.call(j?j:w)}};g=parseFloat(a.view.style.getPropertyValue(G));if(f||0===g)s=!0;s?k.scheduleAction(function(){e({currentTarget:a.view})}):a.view.addEventListener(E,e,!1);l()}function l(){var b=
"",d,j=[],e;for(i=0;i<c.properties.length;i++)d=c.properties[i],e=c.values[i],"rotate"===d?(b+="rotate("+e+") ",d=A):"skew"===d?(b+="skew("+e+") ",d=A):u&&"translate"===d?(b+="translate3d("+e+") ",d=A):"translate"===d?(b+="translate("+e+") ",d=A):"translateX"===d?(b+="translateX("+e+") ",d=A):"translateY"===d?(b+="translateY("+e+") ",d=A):"rotateX"===d?(b+="rotateX("+e+") ",d=A):"rotateY"===d?(b+="rotateY("+e+") ",d=A):"scale"===d?(b+="scale("+e+") ",d=A):a.setStyle(d,e),-1==j.indexOf(d)&&j.push(d);
b&&(c.additive&&(b=a.getCTM().toString()+" "+b),v(a.view,b));a.setStyle(P,j.join(","))}function n(){o();var g,h,m;g=function(f){if(f.currentTarget===a.view){s||a.view.removeEventListener(D,g,!1);r&&l();a.view.style.removeProperty(F);a.view.style.removeProperty(J);if(h=a.getStyle(C))h=h.replace(p,""),a.setStyle(C,h);try{if((data=e.__css_animations[p])&&2===data.length)x.getElementsByTagName("head")[0].removeChild(data[0]),delete e.__css_animations[p]}catch(q){return q.stack&&console.log(q.stack),console.error(q),
!1}if(b.delegate&&b.delegate.taskDidEnd)try{b.delegate.taskDidEnd(c)}catch(o){o.stack&&console.log(o.stack),console.error(o)}d&&d.call(j?j:w)}};m=parseFloat(a.view.style.getPropertyValue(F));if(f||0===m)s=!0;s?k.scheduleAction(function(){g({currentTarget:a.view})}):a.view.addEventListener(D,g,!1);h=(h=a.getStyle(C))?h+(", "+p):p;a.setStyle(C,h)}function t(){var b,d,j,f,q,h,o,k=x.createElement("style");k.type="text/css";var l="";for(d in c.keyFrames){h="";b=c.keyFrames[d];j="";if(g.isArray(b))for(f=
0;f<b.length;f++)o=b[f],null==o||"undefined"==typeof o||(q=c.properties[f])&&("rotate"===q?h+="rotate("+o+") ":"skew"===q?h+="skew("+o+") ":u&&"translate"===q?h+="translate3d("+o+") ":"translate"===q?h+="translate("+o+") ":"translateX"===q?h+="translateX("+o+") ":"translateY"===q?h+="translateY("+o+") ":"rotateX"===q?h+="rotateX("+o+") ":"rotateY"===q?h+="rotateY("+o+") ":"scale"===q?h+="scale("+o+") ":"perspective"===q?h+="perspective("+o+") ":j+=q+":"+o+";");else for(f=0;f<c.properties.length;f++)o=
c.values[f],(q=c.properties[f])&&("rotate"===q?h+="rotate("+o+") ":"skew"===q?h+="skew("+o+") ":u&&"translate"===q?h+="translate3d("+o+") ":"translate"===q?h+="translate("+o+") ":"translateX"===q?h+="translateX("+o+") ":"translateY"===q?h+="translateY("+o+") ":"rotateX"===q?h+="rotateX("+o+") ":"rotateY"===q?h+="rotateY("+o+") ":"scale"===q?h+="scale("+o+") ":"perspective"===q?h+="perspective("+o+") ":j+=q+":"+o+";");h&&(c.additive&&(h=a.getCTM().toString()+" "+h),j+=A+": "+h+";");l+=d+" { "+j+" } "}b=
x.createTextNode("@"+R+" "+p+" { "+l+" }");k.appendChild(b);x.getElementsByTagName("head")[0].appendChild(k);e.__css_animations[p]=[k,a];n()}if(!c||!a||!a.view)console.error("procesAnimation: invalid component parameter!");else{var p=m.createId(),r=c.keyFrames["0%"]?!0:!1,s=!1,w=this;r?k.scheduleAction(t):k.scheduleAction(h);return p}};e.__css_animations={};e.DEFAULT_DURATION="0.3s";e.DEFAULT_TIMING=e.EASE;e.prototype={properties:null,values:null,durations:null,timings:null,origin:null,iterationCount:1,
delay:0,keyFrames:null,additive:!0,setAnimations:function(a){var b,c,d;this.properties=[];this.values=[];this.timings=[];this.keyFrames={};this.timings=this.durations=this.origin=null;for(b=0;b<a.length;b++)d=a[b],!g.isArray(d)||2!==d.length?console.warn("vs.fx.Animation, invalid animations"):(c=d[0],d=d[1],!g.isString(c)||!g.isString(d)?console.warn("vs.fx.Animation, invalid constructor argument option: ["+c+", "+d+"]"):(this.properties.push(c),this.values.push(d)))},addKeyFrame:function(a,b){if(b)if("from"===
a)this.keyFrames["0%"]=b;else if("to"===a)this.keyFrames["100%"]=b;else if(g.isNumber(a)&&!(0>a||100<a))this.keyFrames[a+"%"]=b},process:function(a,b,c,d){return Y(a,this,b,c,d)},_clone:function(a,b){m.Object.prototype._clone.call(this,a,b);var c,d;a.keyFrames={};a.keyFrames["100%"]=a;a.properties=this.properties?this.properties.slice():[];a.values=this.values?this.values.slice():[];this.durations&&(a.durations=this.durations);a.timings=this.timings?this.timings.slice():[];this.origin&&(a.origin=
this.origin.slice());if(this.keyFrames)for(c in this.keyFrames)"100%"!==c&&(d=this.keyFrames[c],a.keyFrames[c]=g.isArray(d)?d.slice():k.util.clone(d));a.iterationCount=this.iterationCount;a.delay=this.delay},start:function(a){return this.process(a)}};g.extendClass(e,m.Task);g.defineClassProperties(e,{duration:{set:function(a){a&&(this.durations=[a])},get:function(){return this.durations&&this.durations.length?this.durations[0]:e.DEFAULT_DURATION}},timing:{set:function(a){a&&(this.timings=[a])},get:function(){return this.timings&&
this.timings.length?this.timings[0]:e.EASE}}});e.EASE="ease";e.LINEAR="linear";e.EASE_IN="ease-in";e.EASE_OUT="ease-out";e.EASE_IN_OUT="ease-in-out";TranslateAnimation=function(a,b,c){this.parent=e;arguments.length?(u?this.parent(["translate","${x}px,${y}px,${z}px"]):this.parent(["translate","${x}px,${y}px"]),g.isNumber(a)&&(this.x=a),g.isNumber(b)&&(this.y=b),g.isNumber(c)&&(this.z=c)):this.parent();this.constructor=TranslateAnimation};TranslateAnimation.prototype={x:0,y:0,z:0,_clone:function(a,
b){e.prototype._clone.call(this,a,b);a.x=this.x;a.y=this.y;a.z=this.z}};g.extendClass(TranslateAnimation,e);RotateAnimation=function(a){this.parent=e;arguments.length?(this.parent(["rotate","${deg}deg"]),g.isNumber(a)&&(this.deg=a)):this.parent();this.constructor=RotateAnimation};RotateAnimation.prototype={deg:0,_clone:function(a,b){e.prototype._clone.call(this,a,b);a.deg=this.deg}};g.extendClass(RotateAnimation,e);RotateXYZAnimation=function(a,b,c){this.parent=e;arguments.length?(this.parent(["rotateX",
"${degX}deg"],["rotateY","${degY}deg"],["rotate","${degZ}deg"]),g.isNumber(a)&&(this.degX=a),g.isNumber(b)&&(this.degY=b),g.isNumber(c)&&(this.degZ=c)):this.parent();this.constructor=RotateXYZAnimation};RotateXYZAnimation.prototype={degX:0,degY:0,degZ:0,_clone:function(a,b){e.prototype._clone.call(this,a,b);a.degX=this.degX;a.degY=this.degY;a.degZ=this.degZ}};g.extendClass(RotateXYZAnimation,e);ScaleAnimation=function(a,b,c){this.parent=e;arguments.length?!g.isNumber(b)&&!g.isNumber(b)?(this.parent(["scale",
"${sx}"]),this.sy=this.sx=a):(this.parent(["scaleX","${sx}"],["scaleY","${sy}"],["scaleZ","${sz}"]),g.isNumber(a)&&(this.sx=a),g.isNumber(b)&&(this.sy=b),g.isNumber(c)&&(this.sz=c)):this.parent();this.constructor=ScaleAnimation};ScaleAnimation.prototype={sx:1,sy:1,sz:1,_clone:function(a,b){e.prototype._clone.call(this,a,b);a.sx=this.sx;a.sy=this.sy;a.sz=this.sz}};g.extendClass(ScaleAnimation,e);SkewAnimation=function(a,b){this.parent=e;arguments.length?(this.parent(["skew","${ax}deg,${ay}deg"]),g.isNumber(a)&&
(this.ax=a),g.isNumber(b)&&(this.ay=b)):this.parent();this.constructor=SkewAnimation};SkewAnimation.prototype={ax:0,ay:0,_clone:function(a,b){e.prototype._clone.call(this,a,b);a.ax=this.ax;a.ay=this.ay}};g.extendClass(SkewAnimation,e);OpacityAnimation=function(a){this.parent=e;arguments.length?(this.parent(["opacity","${value}"]),g.isNumber(a)&&(this.value=a)):this.parent();this.constructor=OpacityAnimation};OpacityAnimation.prototype={value:1,_clone:function(a,b){e.prototype._clone.call(this,a,b);
a.value=this.value}};g.extendClass(OpacityAnimation,e);e.SlideOutRight=new e(["translateX","$width"]);e.SlideOutRight.addKeyFrame(0,["0px"]);e.SlideOutLeft=new e(["translateX","-$width"]);e.SlideOutLeft.addKeyFrame(0,["0px"]);e.SlideOutTop=new e(["translateY","-$height"]);e.SlideOutTop.addKeyFrame(0,["0px"]);e.SlideOutBottom=new e(["translateY","$height"]);e.SlideOutBottom.addKeyFrame(0,["0px"]);e.SlideInRight=new e(["translateX","0px"]);e.SlideInRight.addKeyFrame(0,["$width"]);e.SlideInLeft=new e(["translateX",
"0px"]);e.SlideInLeft.addKeyFrame(0,["-$width"]);e.SlideInTop=new e(["translateY","0px"]);e.SlideInTop.addKeyFrame(0,["-$height"]);e.SlideInBottom=new e(["translateY","0px"]);e.SlideInBottom.addKeyFrame(0,["$height"]);e.FadeIn=new e(["opacity","1"]);e.FadeIn.addKeyFrame(0,["0"]);e.FadeOut=new e(["opacity","0"]);e.FadeOut.addKeyFrame(0,["1"]);w.Animation=e;w.cancelAnimation=function(a){if(!a)return!1;var b,c;if((c=e.__css_animations[a])&&2===c.length){if(!c[1]||!c[1].getStyle||!c[0])return!1;b=c[1].getStyle(C);
if(!b)return!1;b=b.replace(a,"");c[1].setStyle(C,b);try{x.getElementsByTagName("head")[0].removeChild(c[0])}catch(d){return d.stack&&console.log(d.stack),console.error(d),!1}delete e.__css_animations[a]}else return!1;return!0};w.TranslateAnimation=TranslateAnimation;w.RotateAnimation=RotateAnimation;w.RotateXYZAnimation=RotateXYZAnimation;w.ScaleAnimation=ScaleAnimation;w.SkewAnimation=SkewAnimation;w.OpacityAnimation=OpacityAnimation;s.prototype={_delegate:null,_owner:null,_fsm:null,_initial_component:null,
destructor:function(){this._owner&&(this._owner.__controller__=B,this._owner.remove=this._owner._ab_controller_remove,this._owner._ab_controller_remove=B);this._delegate=B;g.free(this._fsm);m.EventSource.prototype.destructor.call(this)},initComponent:function(){m.EventSource.prototype.initComponent.call(this);this._fsm&&this._fsm.init();this._owner?this._owner.__controller__?console.error("The owner already use a controller"):(this._owner.__controller__=this,this._owner._ab_controller_remove=this._owner.remove,
this._owner.remove=this.ab_controller_remove):console.error("Invalid vs.fx.Controller, owner is null vs.fx.Controller.id = '"+this._id+"'")},ab_controller_remove:function(a){a&&((state=this.__controller__._fsm._list_of_state[a.id])?this.__controller__.remove(a):this._ab_controller_remove(a))},isStateExit:function(a){return!this._fsm?!1:this._fsm._list_of_state[a]?!0:!1},add:function(a,b,c,d){console.warn("vs.fx.Controller.add is deprecated. Use vs.fx.Controller.push");return this.push(a,b,c,d)},push:function(a,
b,c,d){if(a&&this._fsm){b||(b={});var j=null,e,f,j=g.isString(a)&&b.id?b.id:!g.isString(a)&&a.id?a.id:m.createId();if(!this.isStateExit(j)){this._fsm.addState(j);this._fsm._list_of_state[j].bindings={};if(d&&d.length)for(f=0;f<d.length;f++)e=d[f],!e||3!==e.length?console.warn("vs.fx.Controller.push: invalid binding information"):this.componentBind(j,e[0],e[1],e[2]);this.setStateComponentInformation(j,a,c,b);return j}}},remove:function(a){if(a&&this._owner&&this._fsm){var b=null;g.isString(a)?b=a:
g.isString(a)||(b=a.id);(a=this._fsm._list_of_state[b])&&a.comp&&this._owner._ab_controller_remove(a.comp);this._fsm.removeState(b)}},setStateComponentInformation:function(a,b,c,d){a&&this._fsm&&this._fsm.existState(a)&&b&&this._owner&&(d=d?g.clone(d):{},a=this._fsm._list_of_state[a],a.init_data=d,g.isString(b)?(a.comp_name=b,a.comp=B):(a.comp_name="",a.comp=b,this._owner.isChild(b)||this._owner.add(b,c)))},addTransition:function(a,b,c,d,j){var e;if(a&&this._fsm&&this._fsm.existState(a)&&b&&this._fsm.existState(b)&&
c)for(e in this._fsm.existInput(c)||this._fsm.addInput(c),this._fsm.addTransition(a,b,c),this._fsm._list_of_state[a].transitionEvents)c=this._fsm._list_of_state[a].transitionEvents[e],c.to===b&&(c.animation_out=d,c.animation_in=j)},_animateComponents:function(a,b,c,d,j,e){var f=this,h=function(){try{j&&j.call(f._owner),f._delegate&&f._delegate.animationDidEnd&&(console.warn("animationDidEnd is deprecated. Please use 'controllerAnimationDidEnd'."),f._delegate.animationDidEnd(f)),f._delegate&&f._delegate.controllerAnimationDidEnd&&
f._delegate.controllerAnimationDidEnd(a,b,f)}catch(c){c.stack&&console.log(c.stack),console.error(c)}};k.scheduleAction(function(){try{if(b.show(),!d&&!c)h.call(f);else{if(e){if(d){var j=d.durations;d.durations="0s"}if(c){var g=c.durations;c.durations="0s"}}d&&!c?d.process(b,h,f):!d&&c?c.process(a,h,f):(d&&d.process(b,h,f),c&&c.process(a));e&&(d&&(d.durations=j),c&&(c.durations=g))}}catch(k){k.stack&&console.log(k.stack),console.error(k)}})},componentBind:function(a,b,c,d){if(this._fsm){var j=this._fsm._list_of_state[a],
f;j&&(f=j.bindings[b],f||(f=[],j.bindings[b]=f),f.push([c,d]),a===this._current_state&&j.comp.bind(b,c,d))}},refresh:function(){},getCurrentState:function(){return!this._fsm?void 0:this._fsm._current_state},configureNewComponent:function(){},_beforeStateEnter:function(a,b){if(a&&(a.comp_name||a.comp)){var c,d,j,f;a.comp||(a.comp=this._owner.createAndAddComponent(a.comp_name,a.init_data,a.extension),a.comp.configure(a.init_data),a.comp&&a.comp.propertiesDidChange&&a.comp.propertiesDidChange(),a.comp.propertyChange(),
this.configureNewComponent(a.comp));j=b;a.data_adaptation_func&&(j=a.data_adaptation_func(b));if(j){for(d in j)if(a.comp.__lookupSetter__(d)||a.comp.hasOwnProperty(d))a.comp[d]=j[d];a.comp.propertyChange()}for(c in a.bindings)if(d=a.bindings[c])for(j=0;j<d.length;j++)(f=d[j])&&(f[1]?a.comp.bind(c,f[0],f[1]):a.comp.bind(c,f[0]))}},_beforeStateExit:function(a){if(a&&a.comp){var b,c,d,f;for(b in a.bindings)if(c=a.bindings[b])for(d=0;d<c.length;d++)(f=c[d])&&(f[1]?a.comp.unbind(b,f[0],f[1]):a.comp.bind(b,
f[0]))}},goTo:function(a,b,c,d){var f,e=null;if(!a||!this._list_of_state[a])return console.warn("vs.fx.Controller.goTo unknown State id:"+a),!1;this._current_state&&(c&&(e=this._list_of_state[this._current_state].transitionEvents[c.on]),f=this._list_of_state[this._current_state],this.owner._beforeStateExit(f));this._current_state=a;a=this._list_of_state[this._current_state];this.owner._beforeStateEnter(a,c?c.data:null);f&&f.comp&&f.comp.viewWillDisappear&&f.comp.viewWillDisappear();a.comp.viewWillAppear&&
a.comp.viewWillAppear();e?this.owner._animateComponents(f.comp,a.comp,e.animation_out,e.animation_in,null,d):a.comp.show();this.owner._delegate&&this.owner._delegate.controllerViewWillChange&&(f?this.owner._delegate.controllerViewWillChange(f.comp,a.comp,this.owner):this.owner._delegate.controllerViewWillChange(null,a.comp,this.owner));if(b&&this._output_action[b])if(d=this._output_action[b],g.isFunction(d))d.call(this._owner,c);else if(g.isString(d))this._owner[this._output_action[b]](c);return!0},
notify:function(a,b){this._fsm&&a&&a.type&&this._fsm.fsmNotify(a.type,a.data,b)},clear:function(){this._fsm&&this._fsm.clear()}};g.extendClass(s,m.EventSource);g.defineClassProperties(s,{initialComponent:{set:function(a){!this._fsm||!a?this._initial_component=B:this._fsm.existState(a)&&(this._initial_component=a,this._fsm.initialState=a,this._fsm.goTo(a))},get:function(){return this._initial_component}},delegate:{set:function(a){this._delegate=a}}});w.Controller=s;f.ANIMATION_DURATION=350;f.NEXT=
"next";f.PRED="pred";f.FIRST="first";f.LAST="last";f.prototype={_is_tactile:!1,_owner_handler_event_extended:!1,_owner_handler_event:null,_animation_duration:f.ANIMATION_DURATION,_last_comp_id:null,_states_array:null,__nb_panels:0,_view_size:null,destructor:function(){delete this._states_array;s.prototype.destructor.call(this)},initComponent:function(){s.prototype.initComponent.call(this);this.isTactile=this._is_tactile;this._updateViewSize()},push:function(a,b,c,d){if(a&&(b||(b={}),a=s.prototype.push.call(this,
a,b,c,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);this.addTransition(a,this._initial_component,f.FIRST);this._last_state=a;if(this._last_comp_id===this._initial_state){state=this._fsm._list_of_state[a];if(!state){console.error("Unknown error in vs.fx.StackController.push");return}state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,
state.init_data,c),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),state.comp.propertyChange());state.comp.show()}return this._last_comp_id=a}},_updateViewSize:function(){},remove:function(a){if(a){var b=null;g.isString(a)?b=a:g.isString(a)||(b=a.id);var c=this._states_array.findItem(b);if(-1!==c){this._fsm.removeTransitionTo(b,f.NEXT);this._fsm.removeTransitionFrom(b,f.PRED);this._fsm.removeTransitionFrom(b,
f.FIRST);this._states_array.remove(c);this.__nb_panels--;if(0===c&&0<this.__nb_panels){this._initial_component=this._states_array[0];for(var d in this._states_array)d!==b&&d!==this._initial_component&&(this._fsm.removeTransitionFrom(d,f.FIRST),this.addTransition(d,this._initial_component,f.FIRST))}0===this.__nb_panels&&(this._initial_component=B,this._fsm._current_state=B);this._initial_component&&(this._fsm._current_state===b?0===c?this._fsm.goTo(this._initial_component):(c===this._states_array.length&&
c--,this._fsm.goTo(this._states_array[c])):this._fsm.goTo(this._fsm._current_state));s.prototype.remove.call(this,a)}}},orientationDidChange:function(){this._updateViewSize()},goToViewId:function(a,b,c){a=this._states_array.findItem(a);if(-1===a)return!1;this.goToViewAt(a,b,c)},goToViewAt:function(a,b,c){if(0>a||a>this._states_array.length)return!1;var d=this._states_array.findItem(this._fsm._current_state);if(d===a)return!0;var e=this._fsm._list_of_state[this._fsm._current_state];if(a>d){for(;d<
a-1;)this._fsm.fsmNotify(f.NEXT,null,!0),d++;this._fsm.fsmNotify(f.NEXT,null,!0);a=this._fsm._list_of_state[this._fsm._current_state];this._stackAnimateComponents(1,e.comp,a.comp,b,c)}else{for(;a+1<d;)this._fsm.fsmNotify(f.PRED,null,!0),d--;this._fsm.fsmNotify(f.PRED,null,!0);a=this._fsm._list_of_state[this._fsm._current_state];this._stackAnimateComponents(-1,e.comp,a.comp,b,c)}},_stackAnimateComponents:function(){},_animateComponents:function(){},goToNextView:function(a,b){var c=this._fsm._list_of_state[this._fsm._current_state],
d=this._fsm.fsmNotify(f.NEXT,null,!0),e=this._fsm._list_of_state[this._fsm._current_state];d&&this._stackAnimateComponents(1,c.comp,e.comp,a,b);return d},goToPreviousView:function(a,b){var c=this._fsm._list_of_state[this._fsm._current_state],d=this._fsm.fsmNotify(f.PRED,null,!0),e=this._fsm._list_of_state[this._fsm._current_state];d&&this._stackAnimateComponents(-1,c.comp,e.comp,a,b);return d},goToFirstView:function(a,b,c){var d=this._fsm._list_of_state[this._fsm._current_state],e=this._fsm.fsmNotify(f.FIRST,
null,!0),g=this._fsm._list_of_state[this._fsm._current_state];e&&this._stackAnimateComponents(c?c:-1,d.comp,g.comp,a,b);return e},goToLastView:function(a,b,c){var d=this._fsm._list_of_state[this._fsm._current_state],e=this._fsm.goTo(this._last_state,null,{on:f.LAST,data:null},b),g=this._fsm._list_of_state[this._fsm._current_state];e&&this._stackAnimateComponents(c?c:1,d.comp,g.comp,a,b);return e},handleEvent:function(){}};g.extendClass(f,s);g.defineClassProperties(f,{viewSize:{set:function(a){a&&
g.isArray(a)&&2===a.length&&g.isNumber(a[0])&&g.isNumber(a[1])&&(this._view_size||(this._view_size=[]),this._view_size[0]=a[0],this._view_size[1]=a[1],this._updateViewSize())},get:function(){return!this._view_size?this._owner.size:this._view_size.slice()}},isTactile:{set:function(a){a?(this._is_tactile=!0,this._owner&&this._owner.view&&(this._owner_handler_event_extended||(this._owner_handler_event=this._owner.handleEvent,this._owner.handleEvent=this.handleEvent,k.addPointerListener(this._owner.view,
m.POINTER_START,this._owner,!1)),this._owner_handler_event_extended=!0)):(this._is_tactile=!1,this._owner&&this._owner.view&&this._owner_handler_event_extended&&(k.removePointerListener(this._owner.view,m.POINTER_START,this._owner,!1),this._owner.handleEvent=this._owner_handler_event,this._owner_handler_event_extended=!1))},get:function(){return this._is_tactile}},animationDuration:{set:function(a){a||(a=0);g.isNumber(a)&&(this._animation_duration=a)}}});w.StackController=f;var n=k.core.createClass({parent:k.fx.StackController,
_delta:0,_orientation:0,_transition_out_left:null,_transition_out_right:null,_transition_in:null,_animation_mode:0,properties:{orientation:{set:function(a){a!==n.HORIZONTAL&&a!==n.VERTICAL||(this._orientation=a,this._updateViewSize())},get:function(){return this._orientation}},animationDuration:{set:function(a){a||(a=0);g.isNumber(a)&&(this._animation_duration=a,this._transition_out_left.duration=this._animation_duration+"ms",this._transition_out_right.duration=this._animation_duration+"ms",this._transition_in.duration=
this._animation_duration+"ms")}},animationMode:{set:function(a){a||(a=0);a!==n.POURCENTAGE&&a!==n.PIXEL||this._animation_mode===a||(this._animation_mode=a,g.free(this._transition_out_right),g.free(this._transition_out_left),this._setUpAnimations(),this._updateViewSize())}}},constructor:function(a){this._super(a);this._orientation=n.HORIZONTAL;arguments.length&&(this._setUpAnimations(),this._transition_in=new e(["translate","0,0,0"]),this.animationDuration=n.ANIMATION_DURATION)},_setUpAnimations:function(){switch(this._animation_mode){case n.POURCENTAGE:this._transition_out_left=
new e(["translate","${x}%,${y}%,0"]);this._transition_out_right=new e(["translate","${x}%,${y}%,0"]);break;case n.PIXEL:this._transition_out_left=new e(["translate","${x}px,${y}px,0"]),this._transition_out_right=new e(["translate","${x}px,${y}px,0"])}this._transition_out_left.x=0;this._transition_out_left.y=0;this._transition_out_left.duration=this._animation_duration+"ms";this._transition_out_right.duration=this._animation_duration+"ms"},_updateViewSize:function(){var a,b,c,d;switch(this._animation_mode){case n.POURCENTAGE:a=
100;delta_str=a+"%";break;case n.PIXEL:b=this._owner.size,this._orientation===n.HORIZONTAL?a=b[0]:this._orientation===n.VERTICAL&&(a=b[1]),delta_str=a+"px"}this._orientation===n.HORIZONTAL?(this._transition_out_left.x=-a,this._transition_out_left.y=0,this._transition_out_right.x=a,this._transition_out_right.y=0):this._orientation===n.VERTICAL&&(this._transition_out_left.x=0,this._transition_out_left.y=-a,this._transition_out_right.x=0,this._transition_out_right.y=a);this._orientation===n.HORIZONTAL?
d="translate3D(-"+delta_str+",0,0)":this._orientation===n.VERTICAL&&(d="translate3D(0,-"+delta_str+",0)");for(a=0;a<this._states_array.length;a++)if(b=this._states_array[a],(c=this._fsm._list_of_state[b])&&c.comp)this._fsm._current_state===b?(this._orientation===n.HORIZONTAL?d="translate3D("+delta_str+",0,0)":this._orientation===n.VERTICAL&&(d="translate3D(0,"+delta_str+",0)"),c.comp.view.style.webkitTransitionDuration="0",v(c.comp.view,"translate3D(0,0,0)")):(c.comp.view.style.webkitTransitionDuration=
"0",v(c.comp.view,d))},push:function(a,b,c,d){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,c,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,c),
state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.StackController.push")}},configureNewComponent:function(a){var b,
c,d;switch(this._animation_mode){case n.POURCENTAGE:c="100%";break;case n.PIXEL:d=this._owner.size,this._orientation===n.HORIZONTAL?c=d[0]+"px":this._orientation===n.VERTICAL&&(c=d[1]+"px")}this._orientation===n.HORIZONTAL?b="translate3D("+c+",0,0)":this._orientation===n.VERTICAL&&(b="translate3D(0,"+c+",0)");a.view.style.webkitTransitionDuration="0";v(a.view,b);a.hide()},handleEvent:function(a){var b=!1,c=this.size,d=this.__controller__._animation_duration;a.type===m.POINTER_START?(this.__pos=this.__controller__._orientation===
n.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,k.addPointerListener(x,m.POINTER_END,this,!0),k.addPointerListener(x,m.POINTER_MOVE,this,!0),this.__delta=this.animationDuration=0):a.type===m.POINTER_MOVE?(a.preventDefault(),this.__delta=this.__controller__._orientation===n.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos:a.changedTouches?a.changedTouches[0].clientY-this.__pos:a.clientY-
this.__pos):a.type===m.POINTER_END&&(50<this.__delta?b=this.__controller__.goToPreviousView():-50>this.__delta&&(b=this.__controller__.goToNextView()),b||(this.animationDuration=d=this.__controller__._orientation===n.HORIZONTAL?Math.floor(d*this.__delta/c[0]):Math.floor(d*this.__delta/c[1])),k.removePointerListener(x,m.POINTER_END,this,!0),k.removePointerListener(x,m.POINTER_MOVE,this,!0))},refresh:function(){f.prototype.refresh.call(this);this._updateViewSize()},_stackAnimateComponents:function(a,
b,c,d,f){var e=this._transition_in,g,h,l;0<a?(h=this._transition_out_right,g=this._transition_out_left):(h=this._transition_out_left,g=this._transition_out_right);l=h.durations;h.durations="0s";var m=this,n=function(){b.hide();try{m._delegate&&m._delegate.controllerAnimationDidEnd&&m._delegate.controllerAnimationDidEnd(b,c,m),d&&d.call(m._owner)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},p=function(){h.durations=l;try{c.show(),c.refresh(),k.scheduleAction(function(){if(f){var a=e.durations;
e.durations="0s";var d=g.durations;g.durations="0s"}e.process(c,n,m);g.process(b);f&&(e.durations=a,g.durations=d)})}catch(a){a.stack&&console.log(a.stack),console.error(a)}};h.process(c,function(){k.scheduleAction(function(){p()})})}});n.ANIMATION_DURATION=300;n.HORIZONTAL=0;n.VERTICAL=1;n.POURCENTAGE=0;n.PIXEL=1;w.SlideController=n;var r=k.core.createClass({parent:k.fx.StackController,_is_circular:!1,_is_continuous_swipe:!1,__delta:0,__current_pos:0,_orientation:0,properties:{orientation:{set:function(a){a!==
r.HORIZONTAL&&a!==r.VERTICAL||(this._orientation=a,this._updateViewSize())},get:function(){return this._orientation}},isTactile:{set:function(a){a?(this._is_tactile=!0,this._owner&&this._owner.view&&(!this._owner_handler_event_extended&&!this.__drag_recognizer&&(this.__drag_recognizer=new I.DragRecognizer(this),this._owner.addPointerRecognizer(this.__drag_recognizer)),this._owner_handler_event_extended=!0)):(this._is_tactile=!1,this._owner&&this._owner.view&&this._owner_handler_event_extended&&(this.__drag_recognizer&&
(this._owner.removePointerRecognizer(this.__drag_recognizer),this.__drag_recognizer=null),this._owner_handler_event_extended=!1))},get:function(){return this._is_tactile}},isCircular:{set:function(a){this._is_circular=a?!0:!1},get:function(){return this._is_circular}},isContinuousSwipe:{set:function(a){this._is_continuous_swipe=a?!0:!1},get:function(){return this._is_continuous_swipe}}},constructor:function(a){this._super(a);this._orientation=r.HORIZONTAL;arguments.length&&(this.animationDuration=
r.ANIMATION_DURATION)},_updateViewSize:function(){var a,b,c;a=this._owner.size;this._orientation===r.HORIZONTAL?c=a[0]:this._orientation===r.VERTICAL&&(c=a[1]);for(a=0;a<this._states_array.length;a++)b=this._states_array[a],(b=this._fsm._list_of_state[b])&&b.comp&&(this._orientation===r.HORIZONTAL?b.comp.translate(c*a,0,0):this._orientation===r.VERTICAL&&b.comp.translate(0,c*a,0))},push:function(a,b,c,d){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,c,d))){this._states_array.push(a);this.__nb_panels++;
if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);this.addTransition(a,this._initial_component,f.FIRST);this._last_state=a;if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,c),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),
state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.StackController.push")}},configureNewComponent:function(){var a=this._owner.size;this._orientation===r.HORIZONTAL?state.comp.translate(a[0]*
(this.__nb_panels-1),0,0):this._orientation===r.VERTICAL&&state.comp.translate(0,a[1]*(this.__nb_panels-1),0)},didDrag:function(a){this.__delta=this._orientation===r.HORIZONTAL?a.dx:a.dy;this._is_continuous_swipe&&(a=this._owner._holes.children,a.style.webkitTransitionDuration="0ms",v(a,"translate3D("+(this.__delta+this.__current_pos)+"px,0,0)"))},didDragEnd:function(){function a(){var a=c._owner._holes.children;a.style.webkitTransitionDuration=c._animation_duration+"ms";c._orientation===r.HORIZONTAL?
v(a,"translate3D("+c.__current_pos+"px,0,0)"):v(a,"translate3D(0,"+c.__current_pos+"px,0)")}var b,c=this;50<this.__delta?(b=this._fsm.getAccessibleStateOn(f.PRED),(b=!b&&this._is_circular?this.goToLastView(null,null,-1):this.goToPreviousView())||a()):-50>this.__delta?(b=this._fsm.getAccessibleStateOn(f.NEXT),(b=!b&&this._is_circular?this.goToFirstView(null,null,1):this.goToNextView())||a()):this._is_continuous_swipe&&a()},refresh:function(){f.prototype.refresh.call(this);this._updateViewSize()},_stackAnimateComponents:function(a,
b,c,d,f){var a=this._owner.size,e=this._owner._holes.children,b=this._states_array.indexOf(c.id);e.style.webkitTransitionDuration="0ms";this.__current_pos=this._orientation===r.HORIZONTAL?b*-a[0]:b*-a[1];var g=this;(function(){try{c.show(),c.refresh(),k.scheduleAction(function(){e.style.webkitTransitionDuration=f?"0ms":g._animation_duration+"ms";g._orientation===r.HORIZONTAL?v(e,"translate3D("+g.__current_pos+"px,0,0)"):v(e,"translate3D(0,"+g.__current_pos+"px,0)")})}catch(a){a.stack&&console.log(a.stack),
console.error(a)}})()}});g.extend(r.prototype,I.RecognizerManager);r.ANIMATION_DURATION=300;r.HORIZONTAL=0;r.VERTICAL=1;r.PIXEL=1;w.SwipeController=r;p.NO_ANIMATION=0;p.CARD_ANIMATION=1;p.SLIDE_ANIMATION=2;p.DEFAULT_ANIMATION=p.SLIDE_ANIMATION;p.BACK="back";p.prototype={_nav_bar:null,__nav_bar_states:null,_animation_type:p.DEFAULT_ANIMATION,destructor:function(){s.prototype.destructor.call(this)},initComponent:function(){s.prototype.initComponent.call(this);this.__translate_in_right=new TranslateAnimation(0);
this.__translate_out_right=new e(["translate","100%,0,0"]);this.__translate_out_left=new e(["translate","-100%,0,0"]);this.__translate_in_left=new TranslateAnimation(0)},setNavigationBar:function(a){a&&!(!a instanceof I.NavigationBar)&&(this._nav_bar=a)},_updateViewSize:function(){},push:function(a,b,c){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,null,c)))return(b=this._fsm._list_of_state[a])&&b.comp&&this.configureNewComponent(b.comp),a},configureNavigationBarState:function(a,b){var c,d,f,
e,o=[],h={};if(this._fsm._list_of_state[a]&&b){for(d=0,f=b.length;d<f;d++)if(e=b[d])if(c=e.comp)g.isString(c)&&(c=m.Object._obs[c]),!c instanceof k.ui.View||(o.push(c),e.properties&&(h[c.id]=e.properties));this.__nav_bar_states[a]=h;this._nav_bar&&this._nav_bar.setStateItems(a,o)}},configureTransition:function(a,b,c){a&&this._fsm.existState(a)&&b&&this._fsm.existState(b)&&c&&(this._fsm.existInput(c)||this._fsm.addInput(c),this._animation_type===p.SLIDE_ANIMATION?(this.addTransition(a,b,c,this.__translate_out_left,
this.__translate_in_right),this.addTransition(b,a,p.BACK,this.__translate_out_right,this.__translate_in_left),this.__translate_in_left.duration="300ms",this.__translate_out_left.duration="300ms",this.__translate_in_right.duration="300ms",this.__translate_out_right.duration="300ms"):this._animation_type===p.CARD_ANIMATION?(this.addTransition(a,b,c,null,this.__translate_in_right),this.addTransition(b,a,p.BACK,this.__translate_out_right,null),this.__translate_in_right.duration="300ms",this.__translate_out_right.duration=
"300ms"):(this.addTransition(a,b,c,null,this.__translate_in_right),this.addTransition(b,a,p.BACK,this.__translate_out_right,null),this.__translate_in_right.duration="0",this.__translate_out_right.duration="0"))},configureNewComponent:function(a){this.__translate_out_right.process(a,null,null,!0)},goTo:function(a,b,c,d){s.prototype.goTo.call(this,a,b,c,d)&&this.owner._nav_bar&&this.owner._nav_bar.changeState(a,this.owner.__nav_bar_states[a])},_animateComponents:w.Controller.prototype._animateComponents};
g.extendClass(p,f);g.defineClassProperties(p,{viewSize:{set:function(a){a&&g.isArray(a)&&2===a.length&&g.isNumber(a[0])&&g.isNumber(a[1])&&(this._view_size||(this._view_size=[]),this._view_size[0]=a[0],this._view_size[1]=a[1],this._updateViewSize())},get:function(){return!this._view_size?this._owner.size:this._view_size.slice()}},initialComponent:{set:function(a){if(a){if(this._fsm.existState(a)){this._initial_component=a;this._fsm.initialState=a;this._fsm.goTo(a);var a=this._fsm._list_of_state[a],
b=this.__translate_in_right;a&&a.comp&&b.process(a.comp,null,null,!0)}}else this._initial_component=B},get:function(){return this._initial_component}}});w.NavigationController=p;var l=k.core.createClass({parent:k.fx.StackController,_direction:0,_transition_out:null,_transition_in:null,properties:{direction:{set:function(a){a!==l.LEFT_OUT&&a!==l.RIGHT_OUT&&a!==l.BOTTOM_OUT&&a!==l.TOP_OUT||(this._direction=a,this._updateViewSize())},get:function(){return this._direction}},animationDuration:{set:function(a){a||
(a=0);g.isNumber(a)&&(this._animation_duration=a,this._transition_out&&(this._transition_out.duration=this._animation_duration+"ms"),this._transition_in&&(this._transition_in.duration=this._animation_duration+"ms"))}}},constructor:function(a){this._super(a);a&&(this._transition_out=new e(["translate","${x}%,${y}%,0"]),this._transition_out.x=0,this._transition_out.y=0,this._transition_in=new e(["translate","${x}%,${y}%,0"]),this._transition_in.x=0,this._transition_in.y=0,this.animationDuration=l.ANIMATION_DURATION);
this._direction=l.RIGHT_OUT},_updateViewSize:function(){this._transition_out&&(this._direction===l.LEFT_OUT?(this._transition_out.x=-100,this._transition_out.y=0):this._direction===l.RIGHT_OUT?(this._transition_out.x=100,this._transition_out.y=0):this._direction===l.BOTTOM_OUT?(this._transition_out.x=0,this._transition_out.y=100):(this._transition_out.x=0,this._transition_out.y=-100))},push:function(a,b,c,d){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,c,d))){this._states_array.push(a);this.__nb_panels++;
if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,f.NEXT);this.addTransition(a,this._last_comp_id,f.PRED);if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,c),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),
state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.CardController.push")}},configureNewComponent:function(a){var b;b=u?"translate3d":"translate";b=this._direction===l.LEFT_OUT?b+"(-100%,0":this._direction===l.RIGHT_OUT?b+"(100%,0":this._direction===l.BOTTOM_OUT?
b+"(0,100%":b+"(0,-100%";b=u?b+",0)":b+")";a.view.style.webkitTransitionDuration="0";v(a.view,b)},handleEvent:function(a){var b=!1,c,d;if(a.type===m.POINTER_START)this.__pos=this.__controller__._direction===l.LEFT_OUT||this.__controller__._direction===l.RIGHT_OUT?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,k.addPointerListener(x,m.POINTER_END,this,!0),k.addPointerListener(x,m.POINTER_MOVE,this,!0);else if(a.type===m.POINTER_MOVE)if(a.preventDefault(),
c=this.__controller__._fsm._list_of_state[this.__controller__._fsm._current_state],b=this.__controller__._states_array.indexOf(this.__controller__._fsm._current_state),0<b&&(d=this.__controller__._states_array[b-1]),this.__controller__._direction===l.LEFT_OUT||this.__controller__._direction===l.RIGHT_OUT?(this.__delta=a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos,a=u?"translate3d("+this.__delta+"px,0px,0)":"translate("+this.__delta+"px,0px)"):(this.__delta=a.changedTouches?
a.changedTouches[0].clientY-this.__pos:a.clientY-this.__pos,a=u?"translate3d(0px,"+this.__delta+"px,0)":"translate(0px,"+this.__delta+"px)"),this.__controller__._direction===l.LEFT_OUT||this.__controller__._direction===l.TOP_OUT)if(0>this.__delta)c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a);else{if(d&&(c=this.__controller__._fsm._list_of_state[d])&&c.comp)a=this.__controller__._direction===l.LEFT_OUT||this.__controller__._direction===l.RIGHT_OUT?u?"translate3d("+(this.__delta-this._size[0])+
"px,0px,0)":"translate("+(this.__delta-this._size[0])+"px,0px)":u?"translate3d(0px,"+(this.__delta-this._size[1])+"px,0)":"translate(0px,"+(this.__delta-this._size[1])+"px)",c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a)}else if(0<this.__delta)c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a);else{if(d&&(c=this.__controller__._fsm._list_of_state[d])&&c.comp)a=this.__controller__._direction===l.LEFT_OUT||this.__controller__._direction===l.RIGHT_OUT?u?"translate3d("+(this._size[0]+
this.__delta)+"px,0px,0)":"translate("+(this._size[0]+this.__delta)+"px,0px)":u?"translate3d(0px,"+(this._size[1]+this.__delta)+"px,0)":"translate(0px,"+(this._size[1]+this.__delta)+"px)",c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a)}else if(a.type===m.POINTER_END){c=this.__controller__._fsm._list_of_state[this.__controller__._fsm._current_state];this.__controller__._direction===l.LEFT_OUT||this.__controller__._direction===l.TOP_OUT?50<this.__delta?b=this.__controller__.goToPreviousView():
-50>this.__delta&&(b=this.__controller__.goToNextView()):50<this.__delta?b=this.__controller__.goToNextView():-50>this.__delta&&(b=this.__controller__.goToPreviousView());if(!b)if(b=this.__controller__._states_array.indexOf(this.__controller__._fsm._current_state),0<b&&(d=this.__controller__._states_array[b-1]),(this.__controller__._direction===l.LEFT_OUT||this.__controller__._direction===l.TOP_OUT)&&0>this.__delta)a=u?"translate3d(0,0,0)":"translate(0,0)",c.comp.view.style.webkitTransitionDuration=
this.__controller__._animation_duration+"ms",v(c.comp.view,a);else if((this.__controller__._direction===l.RIGHT_OUT||this.__controller__._direction===l.BOTTOM_OUT)&&0<this.__delta)a=u?"translate3d(0,0,0)":"translate(0,0)",c.comp.view.style.webkitTransitionDuration=this.__controller__._animation_duration+"ms",v(c.comp.view,a);else if(d&&(c=this.__controller__._fsm._list_of_state[d])&&c.comp)a=this.__controller__._direction===l.LEFT_OUT?"(-100%,0px":this.__controller__._direction===l.RIGHT_OUT?"(100%,0px":
this.__controller__._direction===l.BOTTOM_OUT?"(0px,100%":"(0px,-100%",a=u?a+",0)":a+")",c.comp.view.style.webkitTransitionDuration=this.__controller__._animation_duration+"ms",v(c.comp.view,a);k.removePointerListener(x,m.POINTER_END,this,!0);k.removePointerListener(x,m.POINTER_MOVE,this,!0)}},_stackAnimateComponents:function(a,b,c,d,f){var e,g,h,l;0<a?(e=this._transition_in,l=c):(e=this._transition_out,g=this._transition_in,l=b);g&&(h=g.durations,g.durations="0s");var m=this,n=function(){b.hide();
try{m._delegate&&m._delegate.controllerAnimationDidEnd&&m._delegate.controllerAnimationDidEnd(b,c,m),d&&d.call(this.owner)}catch(a){a.stack&&console.log(a.stack),console.error(a)}},p=function(){g&&(g.durations=h);try{c.show();if(f){var a=e.durations;e.durations="0s"}e.process(l,n,m);f&&(e.durations=a)}catch(b){b.stack&&console.log(b.stack),console.error(b)}};g?g.process(c,function(){k.scheduleAction(function(){p()})}):p()}});l.ANIMATION_DURATION=300;l.LEFT_OUT=0;l.RIGHT_OUT=1;l.TOP_OUT=2;l.BOTTOM_OUT=
3;w.CardController=l;t._translate_animation=new RotateXYZAnimation(-90,0,0);t._translate_animation.init();t._translate_animation.addKeyFrame("from",{degX:0});t._translate_animation.addKeyFrame(50,{degX:-92});t._translate_animation.addKeyFrame(70,{degX:-84});t._translate_animation.addKeyFrame(80,{degX:-90});t._translate_animation.addKeyFrame(95,{degX:-88});t._translate_animation.durations="2s";t.HORIZONTAL=0;t.VERTICAL=1;t.prototype={_orientation:t.HORIZONTAL,push:function(a,b,c){if(a){if(!g.isString(a)){var d=
this._states_array.length;a.position=[0,0];a.setStyle("z-index",1E3-d)}return f.prototype.push.call(this,a,b,c)}},handleEvent:function(a){var b=!1,c,d;if(a.type===m.POINTER_START)this.__pos=this.__layer._orientation===t.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,k.addPointerListener(x,m.POINTER_END,this,!0),k.addPointerListener(x,m.POINTER_MOVE,this,!0),this.animationDuration=0;else if(a.type===m.POINTER_MOVE)if(a.preventDefault(),
c=this.__layer._list_of_state[this.__layer._current_state],b=this.__layer._states_array.indexOf(this.__layer._current_state),0<b&&(d=this.__layer._states_array[b-1]),this.__layer._orientation===t.HORIZONTAL?(this.__delta=a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos,a=u?"translate3d("+this.__delta+"px,0px,0)":"translate("+this.__delta+"px,0px)"):(this.__delta=a.changedTouches?a.changedTouches[0].clientY-this.__pos:a.clientY-this.__pos,a=u?"translate3d(0px,"+this.__delta+
"px,0)":"translate(0px,"+this.__delta+"px)"),0>this.__delta)c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a);else{if(d&&(c=this.__layer._list_of_state[d])&&c.comp)a=this.__layer._orientation===t.HORIZONTAL?u?"translate3d("+(this.__delta-this._size[0])+"px,0px,0)":"translate("+(this.__delta-this._size[0])+"px,0px)":u?"translate3d(0px,"+(this.__delta-this._size[1])+"px,0)":"translate(0px,"+(this.__delta-this._size[1])+"px)",c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a)}else if(a.type===
m.POINTER_END){c=this.__layer._list_of_state[this.__layer._current_state];50<this.__delta?b=this.__layer.goToPreviousView():-50>this.__delta&&(b=this.__layer.goToNextView());if(!b)if(b=this.__layer._states_array.indexOf(this.__layer._current_state),0<b&&(d=this.__layer._states_array[b-1]),0>this.__delta)a=u?"translate3d(0,0,0)":"translate(0,0)",c.comp.view.style.webkitTransitionDuration=this.__layer._animation_duration+"ms",v(c.comp.view,a);else if(d&&(c=this.__layer._list_of_state[d])&&c.comp)a=
this.__layer._orientation===t.HORIZONTAL?u?"translate3d("+this._size[0]+"px,0px,0)":"translate("+this._size[0]+"px,0px)":u?"translate3d(0px,-"+this._size[1]+"px,0)":"translate(0px,-"+this._size[1]+"px)",c.comp.view.style.webkitTransitionDuration=this.__layer._animation_duration+"ms",v(c.comp.view,a);k.removePointerListener(x,m.POINTER_END,this,!0);k.removePointerListener(x,m.POINTER_MOVE,this,!0)}},goTo:function(a,b,c){function d(a){var b=this._list_of_state[this._states_array[a]];b&&(b.comp||(b.comp=
this.owner.createAndAddComponent(b.comp_name,b.init_data,b.extension),b.comp.configure(b.init_data),b.comp.style("position","absolute"),b.comp&&b.comp.propertiesDidChange&&b.comp.propertiesDidChange(),b.comp.propertyChange()),b.view?__setPos(b.view,0,0):b.comp.position=[0,0],b.comp.show(),b.comp.style("z-index",1E3-a))}var e=this._states_array.indexOf(a),k=this._list_of_state[this._current_state];f.prototype.goTo.call(this,a,b,c);if(a&&(this.owner.animationDuration=this._animation_duration,a=this._list_of_state[this._current_state],
a.comp.setStyle("position","absolute"),a.comp.position=[0,0],a.comp.setStyle("z-index",1E3-e),k&&a&&(k.comp.setStyle("-webkit-transform","scale3d(.835,.835,.835) translateZ(200px)"),a.comp.setStyle("-webkit-transform","scale3d(.835,.835,.835) rotateX(90deg) translateZ(200px)")),0<e&&d.call(this,e-1),e<this._states_array.length-1&&d.call(this,e+1),c&&c.on===f.NEXT&&k?t._translate_animation.process(this.owner):c&&c.on===f.PRED&&a&&(t._translate_animation.x=0,t._translate_animation.y=0,t._translate_animation.process(a.comp)),
b&&this._output_action[b]))if(e=this._output_action[b],g.isFunction(e))e.call(this.owner,c);else if(g.isString(e))this.owner[this._output_action[b]](c)}};g.extendClass(t,f);w.CubicController=t;y._opacity_animation=new OpacityAnimation(1);y._opacity_animation.init();y._opacity_animation.durations="0.2s";y.ANIMATION_DURATION=500;y.prototype={push:function(a,b,c){if(a){if(!g.isString(a)){var d=this._states_array.length;a.position=[0,0];a.setStyle("z-index",1E3-d)}f.prototype.push.call(this,a,b,c)}},
goTo:function(a,b,c){function d(a){var b=this._list_of_state[this._states_array[a]];b&&(b.comp||(b.comp=this.owner.createAndAddComponent(b.comp_name,b.init_data,b.extension),b.comp.configure(b.init_data),b.comp.setStyle("position","absolute"),b.comp&&b.comp.propertiesDidChange&&b.comp.propertiesDidChange(),b.comp.propertyChange()),b.view?__setPos(b.view,0,0):b.comp.position=[0,0],b.comp.show(),b.comp.setStyle("z-index",1E3-a))}var e=this._states_array.indexOf(a),k=this._list_of_state[this._current_state];
f.prototype.goTo.call(this,a,b,c);if(a&&(a=this._list_of_state[this._current_state],a.comp.setStyle("position","absolute"),a.comp.position=[0,0],a.comp.setStyle("z-index",1E3-e),0<e&&d.call(this,e-1),e<this._states_array.length-1&&d.call(this,e+1),c&&c.on===f.NEXT&&k?(y._opacity_animation.value=0,y._opacity_animation.process(k.comp)):c&&c.on===f.PRED&&a&&(y._opacity_animation.value=1,y._opacity_animation.process(a.comp)),b&&this._output_action[b]))if(e=this._output_action[b],g.isFunction(e))e.call(this.owner,
c);else if(g.isString(e))this.owner[this._output_action[b]](c)}};g.extendClass(y,f);g.defineClassProperty(y,"animationDuration",{set:function(a){a||(a=0);g.isNumber(a)&&(this._animation_duration=a,y._opacity_animation.durations=a/1E3+"s")}});w.OpacityController=y})(window);
