/*

 Copyright (C) 2009-2012. David Thevenin, ViniSketch SARL (c), and 
 contributors. All rights reserved

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
(function(J,A){function y(a){return!j.CSS_VENDOR?a:"-"+j.CSS_VENDOR.toLowerCase()+"-"+a}function e(a){this.parent=n.Task;this.parent();this.constructor=e;arguments.length&&(this.setAnimations(arguments),this.keyFrames["100%"]=this)}function s(a){this.parent=n.EventSource;this.parent();this.constructor=s;a&&(this._fsm=new n.Fsm(this),this._fsm.goTo=this.goTo,this._owner=a)}function h(a){this.parent=s;this.parent(a);this.constructor=h;arguments.length&&(this._fsm.addInput(h.NEXT),this._fsm.addInput(h.PRED),
this._fsm.addInput(h.FIRST),this._states_array=[])}function r(a,b,c){this.parent=s;this.parent(a);this.constructor=r;arguments.length&&(this._animation_type=c==r.NO_ANIMATION||c==r.CARD_ANIMATION||c==r.SLIDE_ANIMATION?c:r.DEFAULT_ANIMATION,this.setNavigationBar(b),this.__nav_bar_states={})}function o(a,b){this.parent=h;this.parent(a,b);this.constructor=o;a&&a.setStyle("-webkit-transform-style","preserve-3d")}function w(a,b){this.parent=h;this.parent(a,b);this.constructor=w;this.animationDuration=
w.ANIMATION_DURATION}var t=J.document,j=J.vs,g=j.util,n=j.core,Q=j.ui,u=j.fx,v=g.setElementTransform,q=j.SUPPORT_3D_TRANSFORM;j.CSS_VENDOR;var E=y("animation-duration"),H=y("animation-delay"),B=y("animation-name"),K=y("animation-timing-function"),F=y("transition-duration"),I=y("transition-delay"),L=y("transition-timing-function"),M=y("transition-property"),N=y("transform-origin"),G=y("animation-iteration-count"),z=y("transform"),O=y("keyframes"),C="animationend",D="transitionend";"webkit"===j.CSS_VENDOR?
(C="webkitAnimationEnd",D="webkitTransitionEnd"):"ms"===j.CSS_VENDOR?(C="msAnimationEnd",D="msTransitionEnd"):"moz"===j.CSS_VENDOR&&(C="Mozanimationend",D="Moztransitionend");g.extend(j,{ANIMATION_DURATION:E,ANIMATION_DELAY:H,ANIMATION_NAME:B,ANIMATION_TIMING_FUNC:K,TRANSITION_DURATION:F,TRANSITION_PROPERTY:M,TRANSITION_DELAY:I,TRANSITION_TIMING_FUNC:L,TRANSFORM_ORIGIN:N,ITERATION_COUNT:G,TRANSFORM:z,KEY_FRAMES:O,ANIMATION_END:C,TRANSITION_END:D});var R=RegExp(/\$width/g),S=RegExp(/\$height/g),T=
RegExp(/\$x/g),U=RegExp(/\$y/g),P=RegExp(/\$\{([\w]+)\}/g),V=function(a,b,c,d){if(!b||!a||!a.view)console.error("procesAnimation: invalid component parameter!");else{var f,x,h,p,m,k=n.createId(),j=b.keyFrames["0%"]?!0:!1,o=!1;f=function(){var c;c=j?E:F;g.isArray(b.origin)&&2===b.origin.length&&a.setStyle(N,b.origin[0]+"% "+b.origin[1]+"%");g.isString(b.durations)?a.setStyle(c,b.durations):g.isArray(b.durations)?a.setStyle(c,b.durations.join(", ")):a.setStyle(c,e.DEFAULT_DURATION);c=j?H:I;g.isNumber(b.delay)?
a.setStyle(c,b.delay+"ms"):a.setStyle(c,"0");c=j?K:L;g.isString(b.timings)?a.setStyle(c,b.timings):g.isArray(b.timings)?a.setStyle(c,b.timings.join(", ")):a.setStyle(c,e.EASE);j&&("infinite"===b.iterationCount?a.setStyle(G,"infinite"):!b.iterationCount||!g.isNumber(b.iterationCount)?a.setStyle(G,"1"):a.setStyle(G,b.iterationCount))};x=function(c,d){var f,e=[],p;if(g.isNumber(c))return c;if(g.isString(c)){c=c.replace(R,a.size[0]+"px");c=c.replace(S,a.size[1]+"px");c=c.replace(T,a.position[0]+"px");
c=c.replace(U,a.position[1]+"px");for(f=P.exec(c);f&&2===f.length;)e.push(f[1]),f=P.exec(c);for(f=0;f<e.length;f++)p=e[f],"undefined"!==typeof d[p]?c=c.replace("${"+p+"}",d[p]):"undefined"!==typeof b[p]&&(c=c.replace("${"+p+"}",b[p]));return c}console.warn("vs.fx.Animation._parseValue. Unknown value's type: "+c);return 0};h=function(){f();var e,g=this;e=function(f){f.currentTarget===a.view&&(o||a.view.removeEventListener(D,e,!1),a.view.style.removeProperty(F),a.view.style.removeProperty(I),b.delegate&&
b.delegate.taskDidEnd&&b.delegate.taskDidEnd(b),c&&c.call(d?d:g))};0===parseFloat(a.view.style.getPropertyValue(F))&&(o=!0);o?setTimeout(function(){e({currentTarget:a.view})},0):a.view.addEventListener(D,e,!1);p()};p=function(){var c=b.keyFrames["100%"]?b.keyFrames["100%"]:b,d="",f,e=[],g;if(c)for(i=0;i<b.properties.length;i++)f=b.properties[i],g=x(b.values[i],c),"rotate"===f?(d+="rotate("+g+") ",f=z):"skew"===f?(d+="skew("+g+") ",f=z):q&&"translate"===f?(d+="translate3d("+g+") ",f=z):"translate"===
f?(d+="translate("+g+") ",f=z):"translateX"===f?(d+="translateX("+g+") ",f=z):"translateY"===f?(d+="translateY("+g+") ",f=z):"rotateX"===f?(d+="rotateX("+g+") ",f=z):"rotateY"===f?(d+="rotateY("+g+") ",f=z):"scale"===f?(d+="scale("+g+") ",f=z):a.setStyle(f,g),-1==e.indexOf(f)&&e.push(f);d&&v(a.view,d);a.setStyle(M,e.join(","))};m=function(){f();var g,x;g=function(f){if(f.currentTarget===a.view){o||a.view.removeEventListener(C,g,!1);j&&p();a.view.style.removeProperty(E);a.view.style.removeProperty(H);
if(x=a.getStyle(B))x=x.replace(k,""),a.setStyle(B,x);try{if((data=e.__css_animations[k])&&2===data.length)t.getElementsByTagName("head")[0].removeChild(data[0]),delete e.__css_animations[k]}catch(h){return console.error(h),!1}b.delegate&&b.delegate.taskDidStop&&b.delegate.taskDidEnd(b);c&&c.call(d?d:self)}};0===parseFloat(a.view.style.getPropertyValue(E))&&(o=!0);o?setTimeout(function(){g({currentTarget:a.view})},0):a.view.addEventListener(C,g,!1);x=(x=a.getStyle(B))?x+(", "+k):k;a.setStyle(B,x)};
j?function(){var c,d,f,p,h,l,j,n=t.createElement("style");n.type="text/css";var o="";for(d in b.keyFrames){l="";c=b.keyFrames[d];f="";if(g.isArray(c))for(p=0;p<c.length;p++)j=c[p],null==j||"undefined"==typeof j||(j=x(j,b),(h=b.properties[p])&&("rotate"===h?l+="rotate("+j+") ":"skew"===h?l+="skew("+j+") ":q&&"translate"===h?l+="translate3d("+j+") ":"translate"===h?l+="translate("+j+") ":"translateX"===h?l+="translateX("+j+") ":"translateY"===h?l+="translateY("+j+") ":"rotateX"===h?l+="rotateX("+j+
") ":"rotateY"===h?l+="rotateY("+j+") ":"scale"===h?l+="scale("+j+") ":"perspective"===h?l+="perspective("+j+") ":f+=h+":"+j+";"));else for(p=0;p<b.properties.length;p++)j=x(b.values[p],c),(h=b.properties[p])&&("rotate"===h?l+="rotate("+j+") ":"skew"===h?l+="skew("+j+") ":q&&"translate"===h?l+="translate3d("+j+") ":"translate"===h?l+="translate("+j+") ":"translateX"===h?l+="translateX("+j+") ":"translateY"===h?l+="translateY("+j+") ":"rotateX"===h?l+="rotateX("+j+") ":"rotateY"===h?l+="rotateY("+
j+") ":"scale"===h?l+="scale("+j+") ":"perspective"===h?l+="perspective("+j+") ":f+=h+":"+j+";");l&&(f+=z+": "+l+";");o+=d+" { "+f+" } "}c=t.createTextNode("@"+O+" "+k+" { "+o+" }");n.appendChild(c);t.getElementsByTagName("head")[0].appendChild(n);e.__css_animations[k]=[n,a];m()}():h();return k}};e.__css_animations={};e.DEFAULT_DURATION="0.3s";e.DEFAULT_TIMING=e.EASE;e.prototype={properties:null,values:null,durations:null,timings:null,origin:null,iterationCount:1,delay:0,keyFrames:null,setAnimations:function(a){var b,
c,d;this.properties=[];this.values=[];this.timings=[];this.keyFrames={};this.timings=this.durations=this.origin=null;for(b=0;b<a.length;b++)d=a[b],!g.isArray(d)||2!==d.length?console.warn("vs.fx.Animation, invalid animations"):(c=d[0],d=d[1],!g.isString(c)||!g.isString(d)?console.warn("vs.fx.Animation, invalid constructor argument option: ["+c+", "+d+"]"):(this.properties.push(c),this.values.push(d)))},addKeyFrame:function(a,b){if(b)if("from"===a)this.keyFrames["0%"]=b;else if("to"===a)this.keyFrames["100%"]=
b;else if(g.isNumber(a)&&!(0>a||100<a))this.keyFrames[a+"%"]=b},process:function(a,b,c){return V(a,this,b,c)},clone:function(){var a=new e,b,c;a.keyFrames={};a.keyFrames["100%"]=a;a.properties=this.properties?this.properties.slice():[];a.values=this.values?this.values.slice():[];this.durations&&(a.durations=this.durations);a.timings=this.timings?this.timings.slice():[];this.origin&&(a.origin=this.origin.slice());if(this.keyFrames)for(b in this.keyFrames)"100%"!==b&&(c=this.keyFrames[b],a.keyFrames[b]=
g.isArray(c)?c.slice():j.util.clone(c));a.iterationCount=this.iterationCount;a.delay=this.delay;return a},start:function(a){this.process(a)}};g.extendClass(e,n.Task);g.defineClassProperties(e,{duration:{set:function(a){a&&(this.durations=[a])},get:function(){return this.durations&&this.durations.length?this.durations[0]:e.DEFAULT_DURATION}},timing:{set:function(a){a&&(this.timings=[a])},get:function(){return this.timings&&this.timings.length?this.timings[0]:e.EASE}}});e.EASE="ease";e.LINEAR="linear";
e.EASE_IN="ease-in";e.EASE_OUT="ease-out";e.EASE_IN_OUT="ease-in-out";TranslateAnimation=function(a,b,c){this.parent=e;arguments.length?(q?this.parent(["translate","${x}px,${y}px,${z}px"]):this.parent(["translate","${x}px,${y}px"]),g.isNumber(a)&&(this.x=a),g.isNumber(b)&&(this.y=b),g.isNumber(c)&&(this.z=c)):this.parent();this.constructor=TranslateAnimation};TranslateAnimation.prototype={x:0,y:0,z:0};g.extendClass(TranslateAnimation,e);RotateAnimation=function(a){this.parent=e;arguments.length?(this.parent(["rotate",
"${deg}deg"]),g.isNumber(a)&&(this.deg=a)):this.parent();this.constructor=RotateAnimation};RotateAnimation.prototype={deg:0};g.extendClass(RotateAnimation,e);RotateXYZAnimation=function(a,b,c){this.parent=e;arguments.length?(this.parent(["rotateX","${degX}deg"],["rotateY","${degY}deg"],["rotate","${degZ}deg"]),g.isNumber(a)&&(this.degX=a),g.isNumber(b)&&(this.degY=b),g.isNumber(c)&&(this.degZ=c)):this.parent();this.constructor=RotateXYZAnimation};RotateXYZAnimation.prototype={degX:0,degY:0,degZ:0};
g.extendClass(RotateXYZAnimation,e);ScaleAnimation=function(a,b){this.parent=e;arguments.length?(this.parent(["scale","${sx},${sy}"]),g.isNumber(a)&&(this.sx=a),g.isNumber(b)&&(this.sy=b),g.isNumber(b)||(this.sy=this.sx)):this.parent();this.constructor=ScaleAnimation};ScaleAnimation.prototype={sx:1,sy:1};g.extendClass(ScaleAnimation,e);SkewAnimation=function(a,b){this.parent=e;arguments.length?(this.parent(["skew","${ax}deg,${ay}deg"]),g.isNumber(a)&&(this.ax=a),g.isNumber(b)&&(this.ay=b)):this.parent();
this.constructor=SkewAnimation};SkewAnimation.prototype={ax:0,ay:0};g.extendClass(SkewAnimation,e);OpacityAnimation=function(a){this.parent=e;arguments.length?(this.parent(["opacity","${value}"]),g.isNumber(a)&&(this.value=a)):this.parent();this.constructor=OpacityAnimation};OpacityAnimation.prototype={value:1};g.extendClass(OpacityAnimation,e);e.SlideOutRight=new e(["translateX","$width"]);e.SlideOutRight.addKeyFrame(0,["0px"]);e.SlideOutLeft=new e(["translateX","-$width"]);e.SlideOutLeft.addKeyFrame(0,
["0px"]);e.SlideOutTop=new e(["translateY","-$height"]);e.SlideOutTop.addKeyFrame(0,["0px"]);e.SlideOutBottom=new e(["translateY","$height"]);e.SlideOutBottom.addKeyFrame(0,["0px"]);e.SlideInRight=new e(["translateX","0px"]);e.SlideInRight.addKeyFrame(0,["$width"]);e.SlideInLeft=new e(["translateX","0px"]);e.SlideInLeft.addKeyFrame(0,["-$width"]);e.SlideInTop=new e(["translateY","0px"]);e.SlideInTop.addKeyFrame(0,["-$height"]);e.SlideInBottom=new e(["translateY","0px"]);e.SlideInBottom.addKeyFrame(0,
["$height"]);e.FadeIn=new e(["opacity","1"]);e.FadeIn.addKeyFrame(0,["0"]);e.FadeOut=new e(["opacity","0"]);e.FadeOut.addKeyFrame(0,["1"]);u.Animation=e;u.cancelAnimation=function(a){if(!a)return!1;var b,c;if((c=e.__css_animations[a])&&2===c.length){if(!c[1]||!c[1].getStyle||!c[0])return!1;b=c[1].getStyle(B);if(!b)return!1;b=b.replace(a,"");c[1].setStyle(B,b);try{t.getElementsByTagName("head")[0].removeChild(c[0])}catch(d){return console.error(d),!1}delete e.__css_animations[a]}else return!1;return!0};
u.TranslateAnimation=TranslateAnimation;u.RotateAnimation=RotateAnimation;u.RotateXYZAnimation=RotateXYZAnimation;u.ScaleAnimation=ScaleAnimation;u.SkewAnimation=SkewAnimation;u.OpacityAnimation=OpacityAnimation;s.prototype={_delegate:null,_owner:null,_fsm:null,_initial_component:null,destructor:function(){this._owner&&(this._owner.__controller__=A,this._owner.remove=this._owner._ab_controller_remove,this._owner._ab_controller_remove=A);this._delegate=A;g.free(this._fsm);n.EventSource.prototype.destructor.call(this)},
initComponent:function(){n.EventSource.prototype.initComponent.call(this);this._fsm&&this._fsm.init();this._owner?this._owner.__controller__?console.error("The owner already use a controller"):(this._owner.__controller__=this,this._owner._ab_controller_remove=this._owner.remove,this._owner.remove=this.ab_controller_remove):console.error("Invalid vs.fx.Controller, owner is null vs.fx.Controller.id = '"+this._id+"'")},ab_controller_remove:function(a){a&&((state=this.__controller__._fsm._list_of_state[a.id])?
this.__controller__.remove(a):this._ab_controller_remove(a))},isStateExit:function(a){return!this._fsm?!1:this._fsm._list_of_state[a]?!0:!1},add:function(a,b,c,d){console.warn("vs.fx.Controller.add is deprecated. Use vs.fx.Controller.push");return this.push(a,b,c,d)},push:function(a,b,c,d){if(a&&this._fsm){b||(b={});var f=null,e,l,f=g.isString(a)&&b.id?b.id:!g.isString(a)&&a.id?a.id:n.createId();if(!this.isStateExit(f)){this._fsm.addState(f);this._fsm._list_of_state[f].bindings={};if(d&&d.length)for(l=
0;l<d.length;l++)e=d[l],!e||3!==e.length?console.warn("vs.fx.Controller.push: invalid binding information"):this.componentBind(f,e[0],e[1],e[2]);this.setStateComponentInformation(f,a,c,b);return f}}},remove:function(a){if(a&&this._owner&&this._fsm){var b=null;g.isString(a)?b=a:g.isString(a)||(b=a.id);(a=this._fsm._list_of_state[b])&&a.comp&&this._owner._ab_controller_remove(a.comp);this._fsm.removeState(b)}},setStateComponentInformation:function(a,b,c,d){a&&this._fsm&&this._fsm.existState(a)&&b&&
this._owner&&(d=d?g.clone(d):{},a=this._fsm._list_of_state[a],a.init_data=d,g.isString(b)?(a.comp_name=b,a.comp=A):(a.comp_name="",a.comp=b,this._owner.isChild(b)||this._owner.add(b,c)))},addTransition:function(a,b,c,d,f){var e;if(a&&this._fsm&&this._fsm.existState(a)&&b&&this._fsm.existState(b)&&c)for(e in this._fsm.existInput(c)||this._fsm.addInput(c),this._fsm.addTransition(a,b,c),this._fsm._list_of_state[a].transitionEvents)c=this._fsm._list_of_state[a].transitionEvents[e],c.to===b&&(c.animation_out=
d,c.animation_in=f)},_animateComponents:function(a,b,c,d,f,e){var g=this,p=function(){try{f&&f.call(g._owner),g._delegate&&g._delegate.animationDidEnd&&(console.warn("animationDidEnd is deprecated. Please use 'controllerAnimationDidEnd'."),g._delegate.animationDidEnd(g)),g._delegate&&g._delegate.controllerAnimationDidEnd&&g._delegate.controllerAnimationDidEnd(a,b,g)}catch(c){console.error(c)}};setTimeout(function(){try{if(b.show(),!d&&!c)p.call(g);else{if(e){if(d){var f=d.durations;d.durations="0s"}if(c){var h=
c.durations;c.durations="0s"}}d&&!c?d.process(b,p,g):!d&&c?c.process(a,p,g):(d&&d.process(b,p,g),c&&c.process(a));e&&(d&&(d.durations=f),c&&(c.durations=h))}}catch(j){console.error(j)}},0)},componentBind:function(a,b,c,d){if(this._fsm){var f=this._fsm._list_of_state[a],g;f&&(g=f.bindings[b],g||(g=[],f.bindings[b]=g),g.push([c,d]),a===this._current_state&&f.comp.bind(b,c,d))}},refresh:function(){},getCurrentState:function(){return!this._fsm?void 0:this._fsm._current_state},configureNewComponent:function(){},
_beforeStateEnter:function(a,b){if(a&&(a.comp_name||a.comp)){var c,d,f,g;a.comp||(a.comp=this._owner.createAndAddComponent(a.comp_name,a.init_data,a.extension),a.comp.configure(a.init_data),a.comp&&a.comp.propertiesDidChange&&a.comp.propertiesDidChange(),a.comp.propertyChange(),this.configureNewComponent(a.comp));f=b;a.data_adaptation_func&&(f=a.data_adaptation_func(b));if(f){for(d in f)if(a.comp.__lookupSetter__(d)||a.comp.hasOwnProperty(d))a.comp[d]=f[d];a.comp.propertyChange()}for(c in a.bindings)if(d=
a.bindings[c])for(f=0;f<d.length;f++)(g=d[f])&&(g[1]?a.comp.bind(c,g[0],g[1]):a.comp.bind(c,g[0]))}},_beforeStateExit:function(a){if(a&&a.comp){var b,c,d,f;for(b in a.bindings)if(c=a.bindings[b])for(d=0;d<c.length;d++)(f=c[d])&&(f[1]?a.comp.unbind(b,f[0],f[1]):a.comp.bind(b,f[0]))}},goTo:function(a,b,c,d){var f,e=null;if(!a||!this._list_of_state[a])return console.warn("vs.fx.Controller.goTo unknown State id:"+a),!1;this._current_state&&(c&&(e=this._list_of_state[this._current_state].transitionEvents[c.on]),
f=this._list_of_state[this._current_state],this.owner._beforeStateExit(f));this._current_state=a;a=this._list_of_state[this._current_state];this.owner._beforeStateEnter(a,c?c.data:null);f&&f.comp&&f.comp.viewWillDisappear&&f.comp.viewWillDisappear();a.comp.viewWillAppear&&a.comp.viewWillAppear();this.owner._delegate&&this.owner._delegate.controllerViewWillChange&&(f?this.owner._delegate.controllerViewWillChange(f.comp,a.comp,this.owner):this.owner._delegate.controllerViewWillChange(null,a.comp,this.owner));
e?this.owner._animateComponents(f.comp,a.comp,e.animation_out,e.animation_in,null,d):a.comp.show();if(b&&this._output_action[b])if(d=this._output_action[b],d instanceof Function)d.call(this._owner,c);else if(g.isString(d))this._owner[this._output_action[b]](c);return!0},notify:function(a,b){this._fsm&&a&&a.type&&this._fsm.fsmNotify(a.type,a.data,b)},clear:function(){this._fsm&&this._fsm.clear()}};g.extendClass(s,n.EventSource);g.defineClassProperties(s,{initialComponent:{set:function(a){!this._fsm||
!a?this._initial_component=A:this._fsm.existState(a)&&(this._initial_component=a,this._fsm.initialState=a,this._fsm.goTo(a))},get:function(){return this._initial_component}},delegate:{set:function(a){this._delegate=a}}});u.Controller=s;h.ANIMATION_DURATION=350;h.NEXT="next";h.PRED="pred";h.FIRST="first";h.prototype={_is_tactile:!1,_owner_handler_event_extended:!1,_owner_handler_event:null,_animation_duration:h.ANIMATION_DURATION,_last_comp_id:null,_states_array:null,__nb_panels:0,_view_size:null,
destructor:function(){delete this._states_array;s.prototype.destructor.call(this)},initComponent:function(){s.prototype.initComponent.call(this);this.isTactile=this._is_tactile;this._updateViewSize()},push:function(a,b,c,d){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,c,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,h.NEXT);this.addTransition(a,this._last_comp_id,h.PRED);this.addTransition(a,
this._initial_component,h.FIRST);if(this._last_comp_id===this._initial_state){state=this._fsm._list_of_state[a];if(!state){console.error("Unknown error in vs.fx.StackController.push");return}state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,c),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),state.comp.propertyChange());state.comp.show()}return this._last_comp_id=
a}},_updateViewSize:function(){},remove:function(a){if(a){var b=null;g.isString(a)?b=a:g.isString(a)||(b=a.id);var c=this._states_array.findItem(b);if(-1!==c){this._fsm.removeTransitionTo(b,h.NEXT);this._fsm.removeTransitionFrom(b,h.PRED);this._fsm.removeTransitionFrom(b,h.FIRST);this._states_array.remove(c);this.__nb_panels--;if(0===c&&0<this.__nb_panels){this._initial_component=this._states_array[0];for(var d in this._states_array)d!==b&&d!==this._initial_component&&(this._fsm.removeTransitionFrom(d,
h.FIRST),this.addTransition(d,this._initial_component,h.FIRST))}0===this.__nb_panels&&(this._initial_component=A,this._fsm._current_state=A);this._initial_component&&(this._fsm._current_state===b?0===c?this._fsm.goTo(this._initial_component):(c===this._states_array.length&&c--,this._fsm.goTo(this._states_array[c])):this._fsm.goTo(this._fsm._current_state));s.prototype.remove.call(this,a)}}},orientationDidChange:function(){this._updateViewSize()},goToViewId:function(a,b,c){a=this._states_array.findItem(a);
if(-1===a)return!1;this.goToViewAt(a,b,c)},goToViewAt:function(a,b,c){if(0>a||a>this._states_array.length)return!1;var d=this._states_array.findItem(this._fsm._current_state);if(d===a)return!0;var f=this._fsm._list_of_state[this._fsm._current_state];if(a>d){for(;d<a-1;)this._fsm.fsmNotify(h.NEXT,null,!0),d++;this._fsm.fsmNotify(h.NEXT,null,!0);a=this._fsm._list_of_state[this._fsm._current_state];this._stackAnimateComponents(1,f.comp,a.comp,b,c)}else{for(;a+1<d;)this._fsm.fsmNotify(h.PRED,null,!0),
d--;this._fsm.fsmNotify(h.PRED,null,!0);a=this._fsm._list_of_state[this._fsm._current_state];this._stackAnimateComponents(-1,f.comp,a.comp,b,c)}},_stackAnimateComponents:function(){},_animateComponents:function(){},goToNextView:function(a,b){var c=this._fsm._list_of_state[this._fsm._current_state],d=this._fsm.fsmNotify(h.NEXT,null,!0),f=this._fsm._list_of_state[this._fsm._current_state];d&&this._stackAnimateComponents(1,c.comp,f.comp,a,b);return d},goToPreviousView:function(a,b){var c=this._fsm._list_of_state[this._fsm._current_state],
d=this._fsm.fsmNotify(h.PRED,null,!0),f=this._fsm._list_of_state[this._fsm._current_state];d&&this._stackAnimateComponents(-1,c.comp,f.comp,a,b);return d},goToFirstView:function(a,b){var c=this._fsm._list_of_state[this._fsm._current_state],d=this._fsm.fsmNotify(h.FIRST,null,!0),f=this._fsm._list_of_state[this._fsm._current_state];d&&this._stackAnimateComponents(-1,c.comp,f.comp,a,b);return d},handleEvent:function(){}};g.extendClass(h,s);g.defineClassProperties(h,{viewSize:{set:function(a){a&&g.isArray(a)&&
2===a.length&&g.isNumber(a[0])&&g.isNumber(a[1])&&(this._view_size||(this._view_size=[]),this._view_size[0]=a[0],this._view_size[1]=a[1],this._updateViewSize())},get:function(){return!this._view_size?this._owner.size:this._view_size.slice()}},isTactile:{set:function(a){a?(this._is_tactile=!0,this._owner&&this._owner.view&&(this._owner_handler_event_extended||(j.addPointerListener(this._owner.view,n.POINTER_START,this._owner,!1),this._owner_handler_event=this._owner.handleEvent,this._owner.handleEvent=
this.handleEvent),this._owner_handler_event_extended=!0)):(this._is_tactile=!1,this._owner&&this._owner.view&&this._owner_handler_event_extended&&(j.removePointerListener(this._owner.view,n.POINTER_START,this._owner,!1),this._owner.handleEvent=this._owner_handler_event,this._owner_handler_event_extended=!1))},get:function(){return this._is_tactile}},animationDuration:{set:function(a){a||(a=0);g.isNumber(a)&&(this._animation_duration=a)}}});u.StackController=h;var k=j.core.createClass({parent:j.fx.StackController,
_delta:0,_orientation:0,_transition_out_left:null,_transition_out_right:null,_transition_in:null,_animation_mode:0,properties:{orientation:{set:function(a){a!==k.HORIZONTAL&&a!==k.VERTICAL||(this._orientation=a,this._updateViewSize())},get:function(){return this._orientation}},animationDuration:{set:function(a){a||(a=0);g.isNumber(a)&&(this._animation_duration=a,this._transition_out_left.duration=this._animation_duration+"ms",this._transition_out_right.duration=this._animation_duration+"ms",this._transition_in.duration=
this._animation_duration+"ms")}},animationMode:{set:function(a){a||(a=0);a!==k.POURCENTAGE&&a!==k.PIXEL||this._animation_mode===a||(this._animation_mode=a,g.free(this._transition_out_right),g.free(this._transition_out_left),this._setUpAnimations(),this._updateViewSize())}}},constructor:function(a){this._super(a);this._orientation=k.HORIZONTAL;arguments.length&&(this._setUpAnimations(),this._transition_in=new e(["translate","0,0,0"]),this.animationDuration=k.ANIMATION_DURATION)},_setUpAnimations:function(){switch(this._animation_mode){case k.POURCENTAGE:this._transition_out_left=
new e(["translate","${x}%,${y}%,0"]);this._transition_out_right=new e(["translate","${x}%,${y}%,0"]);break;case k.PIXEL:this._transition_out_left=new e(["translate","${x}px,${y}px,0"]),this._transition_out_right=new e(["translate","${x}px,${y}px,0"])}this._transition_out_left.x=0;this._transition_out_left.y=0;this._transition_out_left.duration=this._animation_duration+"ms";this._transition_out_right.duration=this._animation_duration+"ms"},_updateViewSize:function(){var a,b,c,d;switch(this._animation_mode){case k.POURCENTAGE:a=
100;delta_str=a+"%";break;case k.PIXEL:b=this._owner.size,this._orientation===k.HORIZONTAL?a=b[0]:this._orientation===k.VERTICAL&&(a=b[1]),delta_str=a+"px"}this._orientation===k.HORIZONTAL?(this._transition_out_left.x=-a,this._transition_out_left.y=0,this._transition_out_right.x=a,this._transition_out_right.y=0):this._orientation===k.VERTICAL&&(this._transition_out_left.x=0,this._transition_out_left.y=-a,this._transition_out_right.x=0,this._transition_out_right.y=a);this._orientation===k.HORIZONTAL?
d="translate3D(-"+delta_str+",0,0)":this._orientation===k.VERTICAL&&(d="translate3D(0,-"+delta_str+",0)");for(a=0;a<this._states_array.length;a++)if(b=this._states_array[a],(c=this._fsm._list_of_state[b])&&c.comp)this._fsm._current_state===b?(this._orientation===k.HORIZONTAL?d="translate3D("+delta_str+",0,0)":this._orientation===k.VERTICAL&&(d="translate3D(0,"+delta_str+",0)"),c.comp.view.style.webkitTransitionDuration="0",v(c.comp.view,"translate3D(0,0,0)")):(c.comp.view.style.webkitTransitionDuration=
"0",v(c.comp.view,d))},push:function(a,b,c,d){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,c,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,h.NEXT);this.addTransition(a,this._last_comp_id,h.PRED);if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,c),
state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.StackController.push")}},configureNewComponent:function(a){var b,
c,d;switch(this._animation_mode){case k.POURCENTAGE:c="100%";break;case k.PIXEL:d=this._owner.size,this._orientation===k.HORIZONTAL?c=d[0]+"px":this._orientation===k.VERTICAL&&(c=d[1]+"px")}this._orientation===k.HORIZONTAL?b="translate3D("+c+",0,0)":this._orientation===k.VERTICAL&&(b="translate3D(0,"+c+",0)");a.view.style.webkitTransitionDuration="0";v(a.view,b)},handleEvent:function(a){var b=!1,c=this.size,d=this.__controller__._animation_duration;a.type===n.POINTER_START?(this.__pos=this.__controller__._orientation===
k.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,j.addPointerListener(t,n.POINTER_END,this,!0),j.addPointerListener(t,n.POINTER_MOVE,this,!0),this.__delta=this.animationDuration=0):a.type===n.POINTER_MOVE?(a.preventDefault(),this.__delta=this.__controller__._orientation===k.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos:a.changedTouches?a.changedTouches[0].clientY-this.__pos:a.clientY-
this.__pos):a.type===n.POINTER_END&&(50<this.__delta?b=this.__controller__.goToPreviousView():-50>this.__delta&&(b=this.__controller__.goToNextView()),b||(this.animationDuration=d=this.__controller__._orientation===k.HORIZONTAL?Math.floor(d*this.__delta/c[0]):Math.floor(d*this.__delta/c[1])),j.removePointerListener(t,n.POINTER_END,this,!0),j.removePointerListener(t,n.POINTER_MOVE,this,!0))},refresh:function(){h.prototype.refresh.call(this);this._updateViewSize()},_stackAnimateComponents:function(a,
b,c,d,f){var g=this._transition_in,e,h,j;0<a?(h=this._transition_out_right,e=this._transition_out_left):(h=this._transition_out_left,e=this._transition_out_right);j=h.durations;h.durations="0s";var k=this,m=function(){try{k._delegate&&k._delegate.controllerAnimationDidEnd&&k._delegate.controllerAnimationDidEnd(b,c,k),d&&d.call(k._owner)}catch(a){console.error(a)}};h.process(c,function(){setTimeout(function(){h.durations=j;try{c.show();if(f){var a=g.durations;g.durations="0s";var d=e.durations;e.durations=
"0s"}g.process(c,m,k);e.process(b);f&&(g.durations=a,e.durations=d)}catch(n){console.error(n)}},0)})}});k.ANIMATION_DURATION=300;k.HORIZONTAL=0;k.VERTICAL=1;k.POURCENTAGE=0;k.PIXEL=1;u.SlideController=k;r.NO_ANIMATION=0;r.CARD_ANIMATION=1;r.SLIDE_ANIMATION=2;r.DEFAULT_ANIMATION=r.SLIDE_ANIMATION;r.BACK="back";r.prototype={_nav_bar:null,__nav_bar_states:null,_animation_type:r.DEFAULT_ANIMATION,destructor:function(){s.prototype.destructor.call(this)},initComponent:function(){s.prototype.initComponent.call(this);
this.__translate_in_right=new TranslateAnimation(0);this.__translate_out_right=new e(["translate","100%,0,0"]);this.__translate_out_left=new e(["translate","-100%,0,0"]);this.__translate_in_left=new TranslateAnimation(0)},setNavigationBar:function(a){a&&!(!a instanceof Q.NavigationBar)&&(this._nav_bar=a)},_updateViewSize:function(){},push:function(a,b,c){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,null,c)))return(b=this._fsm._list_of_state[a])&&b.comp&&this.configureNewComponent(b.comp),a},
configureNavigationBarState:function(a,b){var c,d,f,e,h=[],p={};if(this._fsm._list_of_state[a]&&b){for(d=0,f=b.length;d<f;d++)if(e=b[d])if(c=e.comp)g.isString(c)&&(c=n.Object._obs[c]),!c instanceof j.ui.View||(h.push(c),e.properties&&(p[c.id]=e.properties));this.__nav_bar_states[a]=p;this._nav_bar&&this._nav_bar.setStateItems(a,h)}},configureTransition:function(a,b,c){a&&this._fsm.existState(a)&&b&&this._fsm.existState(b)&&c&&(this._fsm.existInput(c)||this._fsm.addInput(c),this._animation_type===
r.SLIDE_ANIMATION?(this.addTransition(a,b,c,this.__translate_out_left,this.__translate_in_right),this.addTransition(b,a,r.BACK,this.__translate_out_right,this.__translate_in_left),this.__translate_in_left.duration="300ms",this.__translate_out_left.duration="300ms",this.__translate_in_right.duration="300ms",this.__translate_out_right.duration="300ms"):this._animation_type===r.CARD_ANIMATION?(this.addTransition(a,b,c,null,this.__translate_in_right),this.addTransition(b,a,r.BACK,this.__translate_out_right,
null),this.__translate_in_right.duration="300ms",this.__translate_out_right.duration="300ms"):(this.addTransition(a,b,c,null,this.__translate_in_right),this.addTransition(b,a,r.BACK,this.__translate_out_right,null),this.__translate_in_right.duration="0",this.__translate_out_right.duration="0"))},configureNewComponent:function(a){var b=this.__translate_out_right,c=b.duration;b.duration="0s";b.process(a,function(){b.duration=c})},goTo:function(a,b,c,d){s.prototype.goTo.call(this,a,b,c,d)&&this.owner._nav_bar&&
this.owner._nav_bar.changeState(a,this.owner.__nav_bar_states[a])},_animateComponents:u.Controller.prototype._animateComponents};g.extendClass(r,h);g.defineClassProperties(r,{viewSize:{set:function(a){a&&g.isArray(a)&&2===a.length&&g.isNumber(a[0])&&g.isNumber(a[1])&&(this._view_size||(this._view_size=[]),this._view_size[0]=a[0],this._view_size[1]=a[1],this._updateViewSize())},get:function(){return!this._view_size?this._owner.size:this._view_size.slice()}},initialComponent:{set:function(a){if(a){if(this._fsm.existState(a)){this._initial_component=
a;this._fsm.initialState=a;this._fsm.goTo(a);var a=this._fsm._list_of_state[a],b=this.__translate_in_right,c=b.duration;a&&a.comp&&(b.duration="0s",b.process(a.comp,function(){b.duration=c}))}}else this._initial_component=A},get:function(){return this._initial_component}}});u.NavigationController=r;var m=j.core.createClass({parent:j.fx.StackController,_direction:0,_transition_out:null,_transition_in:null,properties:{direction:{set:function(a){a!==m.LEFT_OUT&&a!==m.RIGHT_OUT&&a!==m.BOTTOM_OUT&&a!==
m.TOP_OUT||(this._direction=a,this._updateViewSize())},get:function(){return this._direction}},animationDuration:{set:function(a){a||(a=0);g.isNumber(a)&&(this._animation_duration=a,this._transition_out&&(this._transition_out.duration=this._animation_duration+"ms"),this._transition_in&&(this._transition_in.duration=this._animation_duration+"ms"))}}},constructor:function(a){this._super(a);a&&(this._transition_out=new e(["translate","${x}%,${y}%,0"]),this._transition_out.x=0,this._transition_out.y=
0,this._transition_in=new e(["translate","${x}%,${y}%,0"]),this._transition_in.x=0,this._transition_in.y=0,this.animationDuration=m.ANIMATION_DURATION);this._direction=m.RIGHT_OUT},_updateViewSize:function(){this._transition_out&&(this._direction===m.LEFT_OUT?(this._transition_out.x=-100,this._transition_out.y=0):this._direction===m.RIGHT_OUT?(this._transition_out.x=100,this._transition_out.y=0):this._direction===m.BOTTOM_OUT?(this._transition_out.x=0,this._transition_out.y=100):(this._transition_out.x=
0,this._transition_out.y=-100))},push:function(a,b,c,d){if(a&&(b||(b={}),a=s.prototype.push.call(this,a,b,c,d))){this._states_array.push(a);this.__nb_panels++;if(1===this.__nb_panels)return this._last_comp_id=this.initialComponent=a;this.addTransition(this._last_comp_id,a,h.NEXT);this.addTransition(a,this._last_comp_id,h.PRED);if(state=this._fsm._list_of_state[a])return this._last_comp_id===this._initial_component?(state.comp||(state.comp=this._owner.createAndAddComponent(state.comp_name,state.init_data,
c),state.comp.configure(state.init_data),state.comp.setStyle("position","absolute"),state.comp&&state.comp.propertiesDidChange&&state.comp.propertiesDidChange(),state.comp.propertyChange()),state.comp.show(),state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)):state.comp&&(state.comp.setStyle("z-index",this.__nb_panels),this.configureNewComponent(state.comp)),this._last_comp_id=a;console.error("Unknown error in vs.fx.CardController.push")}},configureNewComponent:function(a){var b;
b=q?"translate3d":"translate";b=this._direction===m.LEFT_OUT?b+"(-100%,0":this._direction===m.RIGHT_OUT?b+"(100%,0":this._direction===m.BOTTOM_OUT?b+"(0,100%":b+"(0,-100%";b=q?b+",0)":b+")";a.view.style.webkitTransitionDuration="0";v(a.view,b)},handleEvent:function(a){var b=!1,c,d;if(a.type===n.POINTER_START)this.__pos=this.__controller__._direction===m.LEFT_OUT||this.__controller__._direction===m.RIGHT_OUT?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:
a.clientY,j.addPointerListener(t,n.POINTER_END,this,!0),j.addPointerListener(t,n.POINTER_MOVE,this,!0);else if(a.type===n.POINTER_MOVE)if(a.preventDefault(),c=this.__controller__._fsm._list_of_state[this.__controller__._fsm._current_state],b=this.__controller__._states_array.indexOf(this.__controller__._fsm._current_state),0<b&&(d=this.__controller__._states_array[b-1]),this.__controller__._direction===m.LEFT_OUT||this.__controller__._direction===m.RIGHT_OUT?(this.__delta=a.changedTouches?a.changedTouches[0].clientX-
this.__pos:a.clientX-this.__pos,a=q?"translate3d("+this.__delta+"px,0px,0)":"translate("+this.__delta+"px,0px)"):(this.__delta=a.changedTouches?a.changedTouches[0].clientY-this.__pos:a.clientY-this.__pos,a=q?"translate3d(0px,"+this.__delta+"px,0)":"translate(0px,"+this.__delta+"px)"),this.__controller__._direction===m.LEFT_OUT||this.__controller__._direction===m.TOP_OUT)if(0>this.__delta)c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a);else{if(d&&(c=this.__controller__._fsm._list_of_state[d])&&
c.comp)a=this.__controller__._direction===m.LEFT_OUT||this.__controller__._direction===m.RIGHT_OUT?q?"translate3d("+(this.__delta-this._size[0])+"px,0px,0)":"translate("+(this.__delta-this._size[0])+"px,0px)":q?"translate3d(0px,"+(this.__delta-this._size[1])+"px,0)":"translate(0px,"+(this.__delta-this._size[1])+"px)",c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a)}else if(0<this.__delta)c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a);else{if(d&&(c=this.__controller__._fsm._list_of_state[d])&&
c.comp)a=this.__controller__._direction===m.LEFT_OUT||this.__controller__._direction===m.RIGHT_OUT?q?"translate3d("+(this._size[0]+this.__delta)+"px,0px,0)":"translate("+(this._size[0]+this.__delta)+"px,0px)":q?"translate3d(0px,"+(this._size[1]+this.__delta)+"px,0)":"translate(0px,"+(this._size[1]+this.__delta)+"px)",c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a)}else if(a.type===n.POINTER_END){c=this.__controller__._fsm._list_of_state[this.__controller__._fsm._current_state];this.__controller__._direction===
m.LEFT_OUT||this.__controller__._direction===m.TOP_OUT?50<this.__delta?b=this.__controller__.goToPreviousView():-50>this.__delta&&(b=this.__controller__.goToNextView()):50<this.__delta?b=this.__controller__.goToNextView():-50>this.__delta&&(b=this.__controller__.goToPreviousView());if(!b)if(b=this.__controller__._states_array.indexOf(this.__controller__._fsm._current_state),0<b&&(d=this.__controller__._states_array[b-1]),(this.__controller__._direction===m.LEFT_OUT||this.__controller__._direction===
m.TOP_OUT)&&0>this.__delta)a=q?"translate3d(0,0,0)":"translate(0,0)",c.comp.view.style.webkitTransitionDuration=this.__controller__._animation_duration+"ms",v(c.comp.view,a);else if((this.__controller__._direction===m.RIGHT_OUT||this.__controller__._direction===m.BOTTOM_OUT)&&0<this.__delta)a=q?"translate3d(0,0,0)":"translate(0,0)",c.comp.view.style.webkitTransitionDuration=this.__controller__._animation_duration+"ms",v(c.comp.view,a);else if(d&&(c=this.__controller__._fsm._list_of_state[d])&&c.comp)a=
this.__controller__._direction===m.LEFT_OUT?"(-100%,0px":this.__controller__._direction===m.RIGHT_OUT?"(100%,0px":this.__controller__._direction===m.BOTTOM_OUT?"(0px,100%":"(0px,-100%",a=q?a+",0)":a+")",c.comp.view.style.webkitTransitionDuration=this.__controller__._animation_duration+"ms",v(c.comp.view,a);j.removePointerListener(t,n.POINTER_END,this,!0);j.removePointerListener(t,n.POINTER_MOVE,this,!0)}},_stackAnimateComponents:function(a,b,c,d,f){var g,e,h,j;0<a?(g=this._transition_in,j=c):(g=this._transition_out,
e=this._transition_in,j=b);e&&(h=e.durations,e.durations="0s");var k=this,m=function(){b.hide();try{k._delegate&&k._delegate.controllerAnimationDidEnd&&k._delegate.controllerAnimationDidEnd(b,c,k),d&&d.call(this.owner)}catch(a){console.error(a)}},n=function(){e&&(e.durations=h);try{c.show();if(f){var a=g.durations;g.durations="0s"}g.process(j,m,k);f&&(g.durations=a)}catch(b){console.error(b)}};e?e.process(c,function(){setTimeout(function(){n()},0)}):n()}});m.ANIMATION_DURATION=300;m.LEFT_OUT=0;m.RIGHT_OUT=
1;m.TOP_OUT=2;m.BOTTOM_OUT=3;u.CardController=m;o._translate_animation=new RotateXYZAnimation(-90,0,0);o._translate_animation.init();o._translate_animation.addKeyFrame("from",{degX:0});o._translate_animation.addKeyFrame(50,{degX:-92});o._translate_animation.addKeyFrame(70,{degX:-84});o._translate_animation.addKeyFrame(80,{degX:-90});o._translate_animation.addKeyFrame(95,{degX:-88});o._translate_animation.durations="2s";o.HORIZONTAL=0;o.VERTICAL=1;o.prototype={_orientation:o.HORIZONTAL,push:function(a,
b,c){if(a){if(!g.isString(a)){var d=this._states_array.length;a.position=[0,0];a.setStyle("z-index",1E3-d)}return h.prototype.push.call(this,a,b,c)}},handleEvent:function(a){var b=!1,c,d;if(a.type===n.POINTER_START)this.__pos=this.__layer._orientation===o.HORIZONTAL?a.changedTouches?a.changedTouches[0].clientX:a.clientX:a.changedTouches?a.changedTouches[0].clientY:a.clientY,j.addPointerListener(t,n.POINTER_END,this,!0),j.addPointerListener(t,n.POINTER_MOVE,this,!0),this.animationDuration=0;else if(a.type===
n.POINTER_MOVE)if(a.preventDefault(),c=this.__layer._list_of_state[this.__layer._current_state],b=this.__layer._states_array.indexOf(this.__layer._current_state),0<b&&(d=this.__layer._states_array[b-1]),this.__layer._orientation===o.HORIZONTAL?(this.__delta=a.changedTouches?a.changedTouches[0].clientX-this.__pos:a.clientX-this.__pos,a=q?"translate3d("+this.__delta+"px,0px,0)":"translate("+this.__delta+"px,0px)"):(this.__delta=a.changedTouches?a.changedTouches[0].clientY-this.__pos:a.clientY-this.__pos,
a=q?"translate3d(0px,"+this.__delta+"px,0)":"translate(0px,"+this.__delta+"px)"),0>this.__delta)c.comp.view.style.webkitTransitionDuration=0,v(c.comp.view,a);else{if(d&&(c=this.__layer._list_of_state[d])&&c.comp)a=this.__layer._orientation===o.HORIZONTAL?q?"translate3d("+(this.__delta-this._size[0])+"px,0px,0)":"translate("+(this.__delta-this._size[0])+"px,0px)":q?"translate3d(0px,"+(this.__delta-this._size[1])+"px,0)":"translate(0px,"+(this.__delta-this._size[1])+"px)",c.comp.view.style.webkitTransitionDuration=
0,v(c.comp.view,a)}else if(a.type===n.POINTER_END){c=this.__layer._list_of_state[this.__layer._current_state];50<this.__delta?b=this.__layer.goToPreviousView():-50>this.__delta&&(b=this.__layer.goToNextView());if(!b)if(b=this.__layer._states_array.indexOf(this.__layer._current_state),0<b&&(d=this.__layer._states_array[b-1]),0>this.__delta)a=q?"translate3d(0,0,0)":"translate(0,0)",c.comp.view.style.webkitTransitionDuration=this.__layer._animation_duration+"ms",v(c.comp.view,a);else if(d&&(c=this.__layer._list_of_state[d])&&
c.comp)a=this.__layer._orientation===o.HORIZONTAL?q?"translate3d("+this._size[0]+"px,0px,0)":"translate("+this._size[0]+"px,0px)":q?"translate3d(0px,-"+this._size[1]+"px,0)":"translate(0px,-"+this._size[1]+"px)",c.comp.view.style.webkitTransitionDuration=this.__layer._animation_duration+"ms",v(c.comp.view,a);j.removePointerListener(t,n.POINTER_END,this,!0);j.removePointerListener(t,n.POINTER_MOVE,this,!0)}},goTo:function(a,b,c){function d(a){var b=this._list_of_state[this._states_array[a]];b&&(b.comp||
(b.comp=this.owner.createAndAddComponent(b.comp_name,b.init_data,b.extension),b.comp.configure(b.init_data),b.comp.style("position","absolute"),b.comp&&b.comp.propertiesDidChange&&b.comp.propertiesDidChange(),b.comp.propertyChange()),b.view?__setPos(b.view,0,0):b.comp.position=[0,0],b.comp.show(),b.comp.style("z-index",1E3-a))}var f=this._states_array.indexOf(a),e=this._list_of_state[this._current_state];h.prototype.goTo.call(this,a,b,c);if(a&&(this.owner.animationDuration=this._animation_duration,
a=this._list_of_state[this._current_state],a.comp.setStyle("position","absolute"),a.comp.position=[0,0],a.comp.setStyle("z-index",1E3-f),e&&a&&(e.comp.setStyle("-webkit-transform","scale3d(.835,.835,.835) translateZ(200px)"),a.comp.setStyle("-webkit-transform","scale3d(.835,.835,.835) rotateX(90deg) translateZ(200px)")),0<f&&d.call(this,f-1),f<this._states_array.length-1&&d.call(this,f+1),c&&c.on===h.NEXT&&e?o._translate_animation.process(this.owner):c&&c.on===h.PRED&&a&&(o._translate_animation.x=
0,o._translate_animation.y=0,o._translate_animation.process(a.comp)),b&&this._output_action[b]))if(f=this._output_action[b],f instanceof Function)f.call(this.owner,c);else if(g.isString(f))this.owner[this._output_action[b]](c)}};g.extendClass(o,h);u.CubicController=o;w._opacity_animation=new OpacityAnimation(1);w._opacity_animation.init();w._opacity_animation.durations="0.2s";w.ANIMATION_DURATION=500;w.prototype={push:function(a,b,c){if(a){if(!g.isString(a)){var d=this._states_array.length;a.position=
[0,0];a.setStyle("z-index",1E3-d)}h.prototype.push.call(this,a,b,c)}},goTo:function(a,b,c){function d(a){var b=this._list_of_state[this._states_array[a]];b&&(b.comp||(b.comp=this.owner.createAndAddComponent(b.comp_name,b.init_data,b.extension),b.comp.configure(b.init_data),b.comp.setStyle("position","absolute"),b.comp&&b.comp.propertiesDidChange&&b.comp.propertiesDidChange(),b.comp.propertyChange()),b.view?__setPos(b.view,0,0):b.comp.position=[0,0],b.comp.show(),b.comp.setStyle("z-index",1E3-a))}
var f=this._states_array.indexOf(a),e=this._list_of_state[this._current_state];h.prototype.goTo.call(this,a,b,c);if(a&&(a=this._list_of_state[this._current_state],a.comp.setStyle("position","absolute"),a.comp.position=[0,0],a.comp.setStyle("z-index",1E3-f),0<f&&d.call(this,f-1),f<this._states_array.length-1&&d.call(this,f+1),c&&c.on===h.NEXT&&e?(w._opacity_animation.value=0,w._opacity_animation.process(e.comp)):c&&c.on===h.PRED&&a&&(w._opacity_animation.value=1,w._opacity_animation.process(a.comp)),
b&&this._output_action[b]))if(f=this._output_action[b],f instanceof Function)f.call(this.owner,c);else if(g.isString(f))this.owner[this._output_action[b]](c)}};g.extendClass(w,h);g.defineClassProperty(w,"animationDuration",{set:function(a){a||(a=0);g.isNumber(a)&&(this._animation_duration=a,w._opacity_animation.durations=a/1E3+"s")}});u.OpacityController=w})(window);
