window.vs={};window.vs.util={};window.vs.core={};window.vs.data={};window.vs.ui={};window.vs.fx={};window.vs.av={};window.vs.ext={};window.vs.ext.ui={};window.vs.ext.fx={};window.vs.SUPPORT_3D_TRANSFORM=!1;
(function(){var h=function(a){this.m11=this.m22=this.m33=this.m44=1;this.m12=this.m13=this.m14=this.m21=this.m23=this.m24=this.m31=this.m32=this.m34=this.m41=this.m42=this.m43=0;"string"==typeof a&&this.setMatrixValue(a)};h.displayName="FirminCSSMatrix";h.degreesToRadians=function(a){return a*Math.PI/180};h.determinant2x2=function(a,b,f,d){return a*d-b*f};h.determinant3x3=function(a,b,f,d,g,j,i,k,m){var o=h.determinant2x2;return a*o(g,j,k,m)-d*o(b,f,k,m)+i*o(b,f,g,j)};h.determinant4x4=function(a){var b=
h.determinant3x3,f=a.m21,d=a.m31,g=a.m41,j=a.m12,i=a.m22,k=a.m32,m=a.m42,o=a.m13,u=a.m23,y=a.m33,z=a.m43,A=a.m14,v=a.m24,w=a.m34,n=a.m44;return a.m11*b(i,u,v,k,y,w,m,z,n)-f*b(j,o,A,k,y,w,m,z,n)+d*b(j,o,A,i,u,v,m,z,n)-g*b(j,o,A,i,u,v,k,y,w)};[["m11","a"],["m12","b"],["m21","c"],["m22","d"],["m41","e"],["m42","f"]].forEach(function(a){var b=a[0];Object.defineProperty(h.prototype,a[1],{set:function(a){this[b]=a},get:function(){return this[b]}})});h.prototype.isAffine=function(){return 0===this.m13&&
0===this.m14&&0===this.m23&&0===this.m24&&0===this.m31&&0===this.m32&&1===this.m33&&0===this.m34&&0===this.m43&&1===this.m44};h.prototype.multiply=function(a){var b=new h;b.m11=a.m11*this.m11+a.m12*this.m21+a.m13*this.m31+a.m14*this.m41;b.m12=a.m11*this.m12+a.m12*this.m22+a.m13*this.m32+a.m14*this.m42;b.m13=a.m11*this.m13+a.m12*this.m23+a.m13*this.m33+a.m14*this.m43;b.m14=a.m11*this.m14+a.m12*this.m24+a.m13*this.m34+a.m14*this.m44;b.m21=a.m21*this.m11+a.m22*this.m21+a.m23*this.m31+a.m24*this.m41;
b.m22=a.m21*this.m12+a.m22*this.m22+a.m23*this.m32+a.m24*this.m42;b.m23=a.m21*this.m13+a.m22*this.m23+a.m23*this.m33+a.m24*this.m43;b.m24=a.m21*this.m14+a.m22*this.m24+a.m23*this.m34+a.m24*this.m44;b.m31=a.m31*this.m11+a.m32*this.m21+a.m33*this.m31+a.m34*this.m41;b.m32=a.m31*this.m12+a.m32*this.m22+a.m33*this.m32+a.m34*this.m42;b.m33=a.m31*this.m13+a.m32*this.m23+a.m33*this.m33+a.m34*this.m43;b.m34=a.m31*this.m14+a.m32*this.m24+a.m33*this.m34+a.m34*this.m44;b.m41=a.m41*this.m11+a.m42*this.m21+a.m43*
this.m31+a.m44*this.m41;b.m42=a.m41*this.m12+a.m42*this.m22+a.m43*this.m32+a.m44*this.m42;b.m43=a.m41*this.m13+a.m42*this.m23+a.m43*this.m33+a.m44*this.m43;b.m44=a.m41*this.m14+a.m42*this.m24+a.m43*this.m34+a.m44*this.m44;return b};h.prototype.isIdentityOrTranslation=function(){return 1===this.m11&&0===this.m12&&0===this.m13&&0===this.m14&&0===this.m21&&1===this.m22&&0===this.m23&&0===this.m24&&0===this.m31&&0===this.m31&&1===this.m33&&0===this.m34&&1===this.m44};h.prototype.adjoint=function(){var a=
new h,b=h.determinant3x3,f=this.m11,d=this.m12,g=this.m13,j=this.m14,i=this.m21,k=this.m22,m=this.m23,o=this.m24,u=this.m31,y=this.m32,z=this.m33,A=this.m34,v=this.m41,w=this.m42,n=this.m43,C=this.m44;a.m11=b(k,y,w,m,z,n,o,A,C);a.m21=-b(i,u,v,m,z,n,o,A,C);a.m31=b(i,u,v,k,y,w,o,A,C);a.m41=-b(i,u,v,k,y,w,m,z,n);a.m12=-b(d,y,w,g,z,n,j,A,C);a.m22=b(f,u,v,g,z,n,j,A,C);a.m32=-b(f,u,v,d,y,w,j,A,C);a.m42=b(f,u,v,d,y,w,g,z,n);a.m13=b(d,k,w,g,m,n,j,o,C);a.m23=-b(f,i,v,g,m,n,j,o,C);a.m33=b(f,i,v,d,k,w,j,o,C);
a.m43=-b(f,i,v,d,k,w,g,m,n);a.m14=-b(d,k,y,g,m,z,j,o,A);a.m24=b(f,i,u,g,m,z,j,o,A);a.m34=-b(f,i,u,d,k,y,j,o,A);a.m44=b(f,i,u,d,k,y,g,m,z);return a};h.prototype.inverse=function(){var a,b,f,d;if(this.isIdentityOrTranslation())return a=new h,0===this.m41&&0===this.m42&&0===this.m43||(a.m41=-this.m41,a.m42=-this.m42,a.m43=-this.m43),a;b=this.adjoint();a=h.determinant4x4(this);if(1.0E-8>Math.abs(a))return null;for(f=1;5>f;f++)for(d=1;5>d;d++)b["m"+f+d]/=a;return b};h.prototype.rotate=function(a,b,f){var d=
h.degreesToRadians;if("number"!=typeof a||isNaN(a))a=0;if(("number"!=typeof b||isNaN(b))&&("number"!=typeof f||isNaN(f)))f=a,b=a=0;if("number"!=typeof b||isNaN(b))b=0;if("number"!=typeof f||isNaN(f))f=0;var a=d(a),b=d(b),f=d(f),d=new h,g=new h,j=new h,i,f=f/2;i=Math.sin(f);f=Math.cos(f);j.m11=j.m22=1-2*i*i;j.m12=j.m21=2*i*f;j.m21*=-1;b/=2;i=Math.sin(b);f=Math.cos(b);g.m11=g.m33=1-2*i*i;g.m13=g.m31=2*i*f;g.m13*=-1;a/=2;i=Math.sin(a);f=Math.cos(a);d.m22=d.m33=1-2*i*i;d.m23=d.m32=2*i*f;d.m32*=-1;return j.multiply(g).multiply(d).multiply(this)};
h.prototype.rotateAxisAngle=function(a,b,f,d){if("number"!=typeof a||isNaN(a))a=0;if("number"!=typeof b||isNaN(b))b=0;if("number"!=typeof f||isNaN(f))f=0;if("number"!=typeof d||isNaN(d))d=0;0===a&&0===b&&0===f&&(f=1);var g=new h,j=Math.sqrt(a*a+b*b+f*f),i,k,m,d=(h.degreesToRadians(d)||0)/2;i=Math.cos(d);k=Math.sin(d);d=k*k;0===j?(b=a=0,f=1):1!==j&&(a/=j,b/=j,f/=j);1===a&&0===b&&0===f?(g.m22=g.m33=1-2*d,g.m23=g.m32=2*i*k,g.m32*=-1):0===a&&1===b&&0===f?(g.m11=g.m33=1-2*d,g.m13=g.m31=2*i*k,g.m13*=-1):
0===a&&0===b&&1===f?(g.m11=g.m22=1-2*d,g.m12=g.m21=2*i*k,g.m21*=-1):(j=k*i,i=a*a,k=b*b,m=f*f,g.m11=1-2*(k+m)*d,g.m12=2*(a*b*d+f*j),g.m13=2*(a*f*d-b*j),g.m21=2*(b*a*d-f*j),g.m22=1-2*(m+i)*d,g.m23=2*(b*f*d+a*j),g.m31=2*(f*a*d+b*j),g.m32=2*(f*b*d-a*j),g.m33=1-2*(i+k)*d);return this.multiply(g)};h.prototype.scale=function(a,b,f){var d=new h;if("number"!=typeof a||isNaN(a))a=1;if("number"!=typeof b||isNaN(b))b=a;if("number"!=typeof f||isNaN(f))f=1;d.m11=a;d.m22=b;d.m33=f;return this.multiply(d)};h.prototype.translate=
function(a,b,f){var d=new h;if("number"!=typeof a||isNaN(a))a=0;if("number"!=typeof b||isNaN(b))b=0;if("number"!=typeof f||isNaN(f))f=0;d.m41=a;d.m42=b;d.m43=f;return this.multiply(d)};h.prototype.setMatrixValue=function(a){var a=a.trim(),b=a.match(/^matrix(3d)?\(\s*(.+)\s*\)$/),f,d,g,h;if(b&&(a=!!b[1],b=b[2].split(/\s*,\s*/),f=b.length,d=Array(f),!(a&&16!==f)&&(a||6===f))){for(g=0;g<f;g++)if(h=b[g],h.match(/^-?\d+(\.\d+)?$/))d[g]=parseFloat(h);else return;for(g=0;g<f;g++)point=a?"m"+(Math.floor(g/
4)+1)+(g%4+1):String.fromCharCode(g+97),this[point]=d[g]}};h.prototype.toString=function(){var a=this,b,f;this.isAffine()?(f="matrix(",b="a,b,c,d,e,f".split(",")):(f="matrix3d(",b="m11,m12,m13,m14,m21,m22,m23,m24,m31,m32,m33,m34,m41,m42,m43,m44".split(","));return f+b.map(function(b){return a[b].toFixed(6)}).join(", ")+")"};this.FirminCSSMatrix=h}).call(this);
(function(){function h(c,r){x.isNumber(c)&&(this.x=c);x.isNumber(r)&&(this.y=r)}function a(c,r){for(var a in r)getter=r.__lookupGetter__(a),setter=r.__lookupSetter__(a),getter&&c.__defineGetter__(a,getter),setter&&c.__defineSetter__(a,setter),!getter&&!setter&&(c[a]=r[a]);return c}function b(c,r){for(var a in r){var b=Object.getOwnPropertyDescriptor(r,a);b&&(b.get||b.set)?x.defineProperty(c,a,b):c[a]=r[a]}return c}function f(c,a,e){if(Object.prototype.hasOwnProperty.call(e,"set")){var b=e.set;k(b)&&
c.__defineSetter__(a,b)}Object.prototype.hasOwnProperty.call(e,"get")&&(b=e.get,k(b)&&c.__defineGetter__(a,b))}function d(c,a,e){function b(c,a){return Object.prototype.hasOwnProperty.call(c,a)}if("object"!=typeof e||null===e)throw new TypeError("bad desc");if("string"!=typeof a||null===a)throw new TypeError("bad property name");var d={};d.enumerable=b(e,"enumerable")?!!e.enumerable:!0;d.configurable=b(e,"configurable")?!!e.configurable:!0;b(e,"value")&&(d.value=e.value);b(e,"writable")&&(d.writable=
!!e.writable);if(b(e,"get")){var f=e.get;k(f)&&(d.get=f)}b(e,"set")&&(e=e.set,k(e)&&(d.set=e));if(("get"in d||"set"in d)&&("value"in d||"writable"in d))throw new TypeError("identity-confused descriptor");Object.defineProperty(c,a,d)}function g(c,a,e){if(e){c.__properties__||(c.__properties__=[]);if(!c.prototype)throw"defineClassProperty on a Class without prototype";x.defineProperty(c.prototype,a,e);!1!=e.enumerable&&c.__properties__.push(a)}}function j(c){var a;switch(c){case null:return null;case void 0:return}switch(E.call(c)){case "[object Object]":case "Object":a=
{};for(var e in c)a[e]=j(c[e]);return a;case "[object Array]":a=[];for(e=0;e<c.length;e++)a[e]=j(c[e]);return a;default:return c}}function i(c){return!!(c&&1===c.nodeType)}function k(c){return"function"===typeof c}function m(c){return"[object String]"===E.call(c)}function o(c){return"undefined"===typeof c}function u(c,a){if(c){var e=c.className;return e&&0<e.length&&(e===a||RegExp("(^|\\s)"+a+"(\\s|$)").test(e))}}function y(){var c=arguments[0],a,e=1;if(c){for(;e<arguments.length;e++)a=arguments[e],
u(c,a)||(c.className=(c.className?c.className+" ":"")+a);return c}}function z(){var c=arguments[0],a,e=1;if(c&&c.className){for(;e<arguments.length;e++)a=arguments[e],c.className=A(c.className.replace(RegExp("(^|\\s+)"+a+"(\\s+|$)")," "));return c}}function A(c){return!m(c)?"":c.replace(/^\s+/,"").replace(/\s+$/,"")}function v(c){if(!m(c))return"";var a=c.split("-"),e=a.length;if(1===e)return a[0];for(var c="-"===c.charAt(0)?a[0].charAt(0).toUpperCase()+a[0].substring(1):a[0],b=1;b<e;b++)c+=a[b].charAt(0).toUpperCase()+
a[b].substring(1);return c}function w(c){if(!i(c))return{};var a=n(c,"display"),e=c.style,b=e.visibility,d=e.position,f=e.display,g=0,h=0;if("none"!==a&&null!==a)return{width:c.offsetWidth,height:c.offsetHeight};e.visibility="hidden";e.position="absolute";e.display="block";g=c.clientWidth;h=c.clientHeight;e.display=f;e.position=d;e.visibility=b;return{width:g,height:h}}function n(c,a){if(i(c)){var a="float"===a?"cssFloat":v(a),e=c.style[a];if(!e||"auto"===e)e=(e=s.defaultView.getComputedStyle(c,null))?
e[a]:null;return"opacity"===a?e?parseFloat(e):1:"auto"===e?null:e}}function C(c,a){if(i(c)){var e=c.style;o(a)&&e.removeProperty("opacity");e.opacity=1===a||""===a?"":1.0E-5>a?0:a}}function R(c,a){if(!c)return null;if(!a&&c.getBoundingClientRect){var e=c.getBoundingClientRect();if(e)return new l.Point(e.left,e.top)}for(var b=e=0,d=c;d;){var f=0,g=0;d!=c&&(f=parseInt(d.currentStyle?d.currentStyle.borderLeftWidth:0,0),g=parseInt(d.currentStyle?d.currentStyle.borderTopWidth:0,0),f=isNaN(f)?0:f,g=isNaN(g)?
0:g);e+=d.offsetLeft-d.scrollLeft+f;b+=d.offsetTop-d.scrollTop+g;d=d.offsetParent}return new l.Point(e,b)}function S(c){var a=R(c);return{width:c.offsetWidth,height:c.offsetWidth,left:a.x,top:a.y}}function Y(c){return c&&c.getBoundingClientRect?c.getBoundingClientRect():null}function V(c){if(c&&c.childNodes)for(var a=c.childNodes.length;a--;)c.removeChild(c.firstChild)}function Z(c,a){c&&c.style?c.style.webkitTransform=a:console.warn("setElementTransform, elem null or without style")}function $(c){if(c)return c.style.webkitTransform}
function p(c,a){c&&c.style?c.style.msTransform=a:console.warn("setElementTransform, elem null or without style")}function J(c){if(c)return c.style.msTransform}function q(c,a){c&&c.style?c.style.MozTransform=a:console.warn("setElementTransform, elem null or without style")}function D(c){if(c)return c.style.MozTransform}function K(c,a){if(!B){var e=s.createElement("style");e.appendChild(s.createTextNode(""));head=s.getElementsByTagName("head")[0];head.appendChild(e);B=s.styleSheets[s.styleSheets.length-
1]}e=0;B.cssRules?e=B.cssRules.length:B.rules&&(e=B.rules.length);B.insertRule?B.insertRule(c+" {"+a+"}",e):B.addRule&&B.addRule(c,a,e)}var l=this.vs=this.vs||{},x=l.util={};h.prototype={x:0,y:0,matrixTransform:function(c){var a=new CSSMatrix,a=a.translate(this.x,this.y,this.z||0),c=c.multiply(a),e=new h(c.m41,c.m42);delete a;delete c;return e}};l.Point=h;var s="undefined"!=typeof window?window.document:null,L=s?s.createElement("vstestelem"):null,t=L?L.style:null,M=/\/Date\((-?\d+)\)\//;t&&(void 0!==
t.webkitTransform?l.SUPPORT_3D_TRANSFORM="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix:void 0!==t.MozTransform?l.SUPPORT_3D_TRANSFORM="MozPerspective"in t:void 0!==t.msTransform&&(l.SUPPORT_3D_TRANSFORM="MSCSSMatrix"in window&&"m11"in new MSCSSMatrix),l.CSS_VENDOR=function(){for(var c=["MozT","msT","OT","webkitT","t"],a,e=c.length;--e;)if(a=c[e]+"ransform",a in t)return c[e].substr(0,c[e].length-1);return null}());l.SUPPORT_CSS_TRANSFORM=null!==l.CSS_VENDOR?!0:!1;l.CSSMatrix="WebKitCSSMatrix"in
window?window.WebKitCSSMatrix:"MSCSSMatrix"in window?window.MSCSSMatrix:FirminCSSMatrix;l.CSSMatrix.prototype.isAffine||(l.CSSMatrix.prototype.isAffine=function(){return!(this.m13||this.m14||this.m23||this.m24||this.m31||this.m32||1!==this.m33&&this.m34||this.m43||1!==this.m44)});l.CSSMatrix.prototype.getMatrix3dStr=function(){return"matrix3d("+[~~(1E6*this.m11)/1E6,~~(1E6*this.m12)/1E6,~~(1E6*this.m13)/1E6,~~(1E6*this.m14)/1E6,~~(1E6*this.m21)/1E6,~~(1E6*this.m22)/1E6,~~(1E6*this.m23)/1E6,~~(1E6*
this.m24)/1E6,~~(1E6*this.m31)/1E6,~~(1E6*this.m32)/1E6,~~(1E6*this.m33)/1E6,~~(1E6*this.m34)/1E6,~~(1E6*this.m41)/1E6,~~(1E6*this.m42)/1E6,~~(1E6*this.m43)/1E6,~~(1E6*this.m44)/1E6].join(", ")+")"};l.requestAnimationFrame=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(c){window.setTimeout(c,1E3/60)}).bind(window);l.cancelRequestAnimationFrame=(window.cancelRequestAnimationFrame||
window.webkitCancelAnimationFrame||window.mozCancelAnimationFrame||window.oCancelAnimationFrame||window.msCancelAnimationFrame||clearTimeout).bind(window);l.util.extend=Object.defineProperty?b:a;var F="function"===typeof Object.keys?Object.keys:function(c){var a=[],e;for(e in c)Object.prototype.hasOwnProperty.call(c,e)&&a.push(e);return a},E=Object.prototype.toString,N=Array.isArray||function(a){return"[object Array]"===E.call(a)},I,G;t&&void 0!==t.webkitTransform?(I=Z,G=$):t&&void 0!==t.msTransform?
(I=p,G=J):t&&void 0!==t.MozTransform&&(I=q,G=D);Array.prototype._remove=function(a,b){var e=this.slice((b||a)+1||this.length);this.length=0>a?this.length+a:a;return this.push.apply(this,e)};var O=function(a,b){for(var e=this.length,b=b?b:0,b=0>b?0:b;b<e;){if(this[b]===a)return b;b++}return-1};Array.prototype.findItem=Array.prototype.indexOf?Array.prototype.indexOf:O;Array.prototype.remove=function(a,b){if("object"===typeof a||x.isString(a))for(var e=0;e<this.length;)this[e]===a?this._remove(e):e++;
else this._remove(a,b);return this};Array.prototype.removeAll=function(){for(;0<this.length;)this._remove(0);return this};Array.prototype.clone=function(){return this.slice()};var B=null;l._current_platform_id=0;x.extend(x,{vsTestElem:L,vsTestStyle:t,extendClass:function(a,b){if(a&&b&&a.prototype&&b.prototype)try{if(Object.__proto__)a.prototype.__proto__=b.prototype;else{var e=a.prototype;a.prototype=new b;x.extend(a.prototype,e)}a.__properties__||(a.__properties__=[]);b.__properties__&&(a.__properties__=
a.__properties__.concat(b.__properties__));return a}catch(d){console.error(d.message())}},defineProperty:Object.defineProperty?d:f,defineClassProperty:g,defineClassProperties:function(a,b){if(!a.prototype)throw"defineClassProperties on a Class without prototype";for(var b=Object(b),e=F(b),d=0;d<e.length;d++)g(a,e[d],b[e[d]])},clone:j,free:function(a){a&&(a._free&&a._free(),a.destructor&&a.destructor(),delete a)},toJSON:function(a){return JSON.stringify(a)},isElement:i,isArray:N,isFunction:k,isString:m,
isNumber:function(a){return"number"===typeof a&&isFinite(a)||a instanceof Number},isUndefined:o,hasClassName:u,addClassName:y,removeClassName:z,toggleClassName:function(a,b){return!a?void 0:u(a,b)?z(a,b):y(a,b)},htmlEncode:function(a){return!m(a)?"":a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},strip:A,camelize:v,capitalize:function(a){return!m(a)?"":a.charAt(0).toUpperCase()+a.substring(1).toLowerCase()},underscore:function(a){return!m(a)?"":a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,
"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/-/g,"_").toLowerCase()},parseJSON:function(a){function b(a){if(m(a)){var c=M.exec(a);c&&c[1]&&(a=new Date(parseInt(c[1])))}else if(N(a))for(c=0;c<a.length;c++)a[c]=b(a[c]);else if(!(a instanceof Date)&&a instanceof Object)for(c in a)a[c]=b(a[c]);return a}if(!a)return null;var e=JSON.parse(a);return!M.test(a)?e:b(e)},addCssRule:K,addCssRules:function(a,b){if(N(b))for(var e=b.length;e--;)K(a,b[e])},getElementHeight:function(a){return!i(a)?void 0:
w(a).height},getElementWidth:function(a){return!i(a)?void 0:w(a).width},getElementDimensions:w,getElementStyle:n,setElementStyle:function(a,b){if(i(a)){var e=a.style,d;for(d in b)"opacity"===d?C(a,b[d]):(b[d]||e.removeProperty(d),e["float"===d||"cssFloat"===d?o(e.styleFloat)?"cssFloat":"styleFloat":d]=b[d])}},setElementOpacity:C,getElementOpacity:function(a){return!i(a)?void 0:n(a,"opacity")},getElementAbsolutePosition:R,setElementPos:function(a,b,e){a&&(a=a.style,a.left=b+"px",a.top=e+"px")},setElementSize:function(a,
b,e){a&&(a=a.style,a.width=b+"px",a.height=e+"px")},setElementVisibility:function(a,b){if(a){var e=a.style;e||x.isString(a.innerHTML)?e.visibility=b?"visible":"hidden":b?a.setAttribute("visibility","visible"):a.setAttribute("visibility","hidden")}},isElementVisible:function(a){if(!a)return!1;var b=a.style;return b||x.isString(a.innerHTML)?"hidden"===b.visibility?!1:!0:a instanceof CharacterData?!0:"hidden"===a.getAttribute("visibility")?!1:!0},removeAllElementChild:V,safeInnerHTML:function(a,b){a&&
m(b)&&(window.MSApp&&window.MSApp.execUnsafeLocalFunction?window.MSApp.execUnsafeLocalFunction(function(){a.innerHTML=b}):(window.toStaticHTML&&(b=window.toStaticHTML(b)),a.innerHTML=b))},setElementInnerText:function(a,b){if(a){V(a);x.isString(b)||(b=void 0===b?"":null===b?"":x.isNumber(b)?""+b:b.toString?b.toString():"");var e=b.split("\n"),d=0;if(e.length){a.appendChild(s.createTextNode(e[d]));for(d++;d<e.length;d++)a.appendChild(s.createElement("br")),a.appendChild(s.createTextNode(e[d]))}}},setElementTransform:I,
getElementTransform:G,setElementTransformOrigin:function(a,b){a&&a.style?a.style["-"+l.CSS_VENDOR.toLowerCase()+"-transform-origin"]=b:console.warn("setElementTransformOrigin, elem null or without style")},getBoundingClientRect:L&&L.getBoundingClientRect?Y:S,importFile:function(a,b,e,d){b||(b=s);var f;if("js"===d||0<=a.search("\\.js"))return d=b.createElement("script"),d.setAttribute("type","text/javascript"),d.setAttribute("src",a),e&&(d.onload=function(){e.call(this,a)}),b.head||(b.head=b.querySelector("head")),
b.head.appendChild(d),d;if("css"===d||0<=a.search("\\.css")){f=b.createElement("link");f.setAttribute("rel","stylesheet");f.setAttribute("type","text/css");f.setAttribute("href",a);f.setAttribute("media","screen");if(x.isFunction(e)){var g=0;(function(){!f.sheet||!f.sheet.cssRules?100>g++?cssTimeout=setTimeout(arguments.callee,100):console.error("CSS load of "+a+" failed!"):f.sheet.cssRules&&0===f.sheet.cssRules.length?console.error("CSS load of "+a+" failed!"):e.call(s,a)})()}b.head||(b.head=b.querySelector("head"));
b.head.appendChild(f);return f}},setActiveStyleSheet:function(a){var b=0,e=s.getElementsByTagName("link"),d,f;l._current_platform_id=a;var g=l.Application_applications;if(g)for(f in g)b=g[f],b.view&&(b.view.style.display="none");for(b=0;b<e.length;b++)d=e[b],d.getAttribute("title")&&(d.getAttribute("title")!==a?d.setAttribute("disabled",!0):d.removeAttribute("disabled"));if(g)for(f in g)b=g[f],b.view&&(b.view.style.display="block")},preloadTemplate:function(a){var b=a+".xhtml",d;if(!l.ui||!l.ui.View||
!l.ui.View.__comp_templates[b])d=new XMLHttpRequest,d.open("GET",b,!1),d.send(null),4===d.readyState?200===d.status||0===d.status?(data=d.responseText,l.ui&&l.ui.View&&(l.ui.View.__comp_templates[b]=data)):console.error("Template file for component '"+a+"' unfound"):console.error("Pb when load the component '"+a+"' template")},__date_reg_exp:M,_findItem:O,_defineProperty_api1:f,_defineProperty_api2:d,_extend_api1:a,_extend_api2:b})}).call(this);
(function(){function h(a){var f=a.vsGetCTM();b.setElementTransform(a,f.toString());delete f}var a=this.vs,b=a.util,f=a&&a.CSSMatrix;b.extend((window&&window.HTMLElement).prototype,{_vs_node_tx:0,_vs_node_ty:0,_vs_node_s:1,_vs_node_r:0,vsTranslate:function(a,b){this._vs_node_tx===a&&this._vs_node_ty===b||(this._vs_node_tx=a,this._vs_node_ty=b,h(this))},vsRotate:function(a){this._vs_node_r!==a&&(this._vs_node_r=a,h(this))},vsScale:function(a){this._vs_node_s!==a&&(this._vs_node_s=a,h(this))},vsSetNewTransformOrigin:function(a){if(a){this._vs_node_origin||
(this._vs_node_origin=[0,0]);var b=new f,b=b.translate(this._vs_node_origin[0],this._vs_node_origin[1],0),b=b.translate(this._vs_node_tx,this._vs_node_ty,0),b=b.rotate(0,0,this._vs_node_r),b=b.scale(this._vs_node_s,this._vs_node_s,1),b=b.translate(-this._vs_node_origin[0],-this._vs_node_origin[1],0);this._vs_transform||(this._vs_transform=b);this._vs_transform=b.multiply(this._vs_transform);delete b;this._vs_node_ty=this._vs_node_tx=0;this._vs_node_s=1;this._vs_node_r=0;this._vs_node_origin=[a.x,
a.y]}},vsClearTransformStack:function(){this._vs_transform&&delete this._vs_transform;this._vs_transform=void 0},vsGetCTM:function(){var a=new f;this._vs_node_origin||(this._vs_node_origin=[0,0]);a=a.translate(this._vs_node_origin[0],this._vs_node_origin[1],0);a=a.translate(this._vs_node_tx,this._vs_node_ty,0);a=a.rotate(0,0,this._vs_node_r);a=a.scale(this._vs_node_s,this._vs_node_s,1);a=a.translate(-this._vs_node_origin[0],-this._vs_node_origin[1],0);return this._vs_transform?a.multiply(this._vs_transform):
a},vsGetParentCTM:function(){function a(b){return!b?new f:a(b.parentNode).multiply(b.vsGetCTM())}return a(this.parentNode)}})}).call(this);
(function(){function h(a,b,c){this.configureWithEvent(a);this.type=b;this.identifier=c}function a(a,b){var c=[];a.nbPointers=a.touches.length;for(var e=0;e<a.nbPointers;e++){var d=a.touches[e],d=new h(d,t.TOUCH,d.identifier);c.push(d)}a.pointerList=c;c=[];for(e=0;e<a.targetTouches.length;e++)d=a.targetTouches[e],b&&M[d.identifier]!=b||(d=new h(d,t.TOUCH,d.identifier),c.push(d));a.targetPointerList=c;c=[];for(e=0;e<a.changedTouches.length;e++)d=a.changedTouches[e],d=new h(d,t.TOUCH,d.identifier),c.push(d);
a.changedPointerList=c}function b(a,b){var c=[];c.push(new h(a,t.MOUSE,L));b?(a.nbPointers=0,a.pointerList=[],a.targetPointerList=c,a.changedPointerList=c):(a.nbPointers=1,a.pointerList=c,a.targetPointerList=c,a.changedPointerList=[])}function f(a,b){var c=[],e=[],d=a.pointerId,f=F[d];if(b){f?(E[d]=f,delete F[d]):(f=E[d],f||(f=new h(a,a.pointerType,d),E[d]=f));for(d in E)e.push(E[d]);E={}}else f?f.configureWithEvent(a):(f=new h(a,a.pointerType,d),F[d]=f);for(d in F)c.push(F[d]);a.nbPointers=c.length;
a.pointerList=c;c=[];for(d in F)f=F[d],c.push(f);a.targetPointerList=c;a.changedPointerList=e}function d(a,c){b(a);c(a)}function g(a,c){b(a);c(a)}function j(a,c){b(a,!0);c(a)}function i(b,c,d){for(var e,f=b.targetTouches.length,g=0;g<f;g++)e=b.targetTouches[g],M[e.identifier]=d;a(b);c(b)}function k(b,c,d){a(b,d);c(b)}function m(b,c){for(var d,e=b.targetTouches.length,f=0;f<e;f++)d=b.changedTouches[f],M[d.identifier]=void 0;a(b);c(b)}function o(b,c){a(b);c(b,c)}function u(a,b,c){M[a.pointerId]=c;f(a,
!1,c);b(a);0===N&&(document.addEventListener("MSPointerUp",I),document.addEventListener("MSPointerCancel",I));N++}function y(a,b,c){f(a,!1,c);b(a)}function z(a,b){f(a,!0);b(a)}function A(a,b){f(a,!0);b(a)}function v(a,b,c){if(!b||!c||!c.__event_listeners)return-1;for(var d=0;d<c.__event_listeners.length;d++){var e=c.__event_listeners[d];if(e.target===a&&e.type===b&&e.listener===c)return d}return-1}function w(a,b,d,e){var f=e.listener?e.listener.id:void 0;switch(b){case K:return e.handler=function(a){G(a,
d,f)},!0;case l:return e.handler=function(a){O(a,d,f)},!0;case x:return e.handler=function(a){B(a,d)},!0;case s:return e.handler=function(a){c(a,d)},!0}return!1}function n(a,b,c){var d=document.createEvent("Event");d.initEvent(a,!0,!0);for(var e in c)d[e]=c[e];b.dispatchEvent(d)}function C(a,b){var c=b.pageX-a.pageX,d=b.pageY-a.pageY;return Math.sqrt(c*c+d*d)}function R(a){var b=a.length,c=0,d=0,e=0;if(0===b)return{X:0,y:0};for(;c<b;c++)var f=a[c],d=d+f.pageX,e=e+f.pageY;return{x:d/b-aa.x,y:e/b-aa.y}}
function S(a){a.centroid={x:a.pageX,y:a.pageY};a.translation=[a.centroid.x-P.x,a.centroid.y-P.y];a.pointerList=[new h(a,t.TOUCH,L)];a.targetPointerList=a.pointerList;a.nbPointers=1}function Y(a,b,c,d){var f=d.listener?d.listener.id:void 0;switch(b){case r:return d.gesture_handler=function(a){G(a,fa,f)},a.addEventListener(p.POINTER_START,d.gesture_handler),d.handler=c,!0;case e:case H:return d.handler=c,!0}return!1}function V(a,b,c,d){switch(b){case r:return d.handler=function(a){P={x:a.pageX,y:a.pageY};
S(a);c(a)},!0;case e:return d.handler=function(a){S(a);c(a)},!0;case H:return d.handler=function(a){S(a);c(a)},!0}return!1}function Z(a,b,c){var d=c.listener?c.listener.id:void 0;switch(b){case r:return a.removeEventListener(p.POINTER_START,c.gesture_handler,d),!0;case e:case H:return!0}return!1}function $(a,b){switch(b){case r:case e:case H:return!0}return!1}var p=this.vs=this.vs||{},J=p.util=p.util||{},q=!1,D=window.navigator.msPointerEnabled;if("undefined"!=typeof document&&"createTouch"in document)q=
!0;else if(D)q=!0;else if("undefined"!=typeof document&&window.navigator&&window.navigator.userAgent&&(-1!==window.navigator.userAgent.indexOf("Android")||-1!==window.navigator.userAgent.indexOf("BlackBerry")))q=!0;var K,l,x,s;q?(K=D?"MSPointerDown":"touchstart",l=D?"MSPointerMove":"touchmove",x=D?"MSPointerUp":"touchend",s=D?"MSPointerCancel":"touchcancel"):(K="mousedown",l="mousemove",s=x="mouseup");var L=31337;h.prototype.configureWithEvent=function(a){this.pageX=a.pageX;this.pageY=a.pageY;this.clientX=
a.clientX;this.clientY=a.clientY;this.target=a.target;this.currentTarget=a.currentTarget};var t={TOUCH:2,PEN:3,MOUSE:4},M=[],F={},E={},N=0,I=function(a){if(a=F[a.pointerId])E[a.identifier]=a,delete F[a.identifier];N--;0===N&&(document.removeEventListener("MSPointerUp",I),document.removeEventListener("MSPointerCancel",I))},G,O,B,c;q?D?(G=u,O=y,B=z,c=A):(G=i,O=k,B=m,c=o):(G=d,O=g,c=B=j);p.createCustomEvent=n;p.removePointerListener=function(a,b,c,d){if(c){var e=v(a,b,c);if(-1===e)console.error("removePointerListener no binding");
else{var f=c.__event_listeners[e];c.__event_listeners.remove(e);a:{switch(b){case K:case l:case x:case s:c=!0;break a}c=!1}c||ga(a,b,f);a.removeEventListener(b,f.handler,d);delete f}}else console.error("removePointerListener no listener")};p.addPointerListener=function(a,b,c,d){if(c){var e=c;J.isFunction(c)||(e=c.handleEvent,J.isFunction(e)&&(e=e.bind(c)));if(-1!==v(a,b,c))console.error("addPointerListener binding already existing");else{c.__event_listeners||(c.__event_listeners=[]);var f={target:a,
type:b,listener:c};c.__event_listeners.push(f);!w(a,b,e,f)&&!ha(a,b,e,f)&&(f.handler=e);a.addEventListener(b,f.handler,d)}}else console.error("addPointerListener no listener")};p.PointerTypes=t;p.POINTER_START=K;p.POINTER_MOVE=l;p.POINTER_END=x;p.POINTER_CANCEL=s;var r,e,H,q={},D=["gesturestart","gesturechange","gestureend"];document.createElement("div");for(var U=0;U<D.length;U++){var Q=D[U],Q="on"+Q,X=Q in J.vsTestElem;X||(J.vsTestElem.setAttribute(Q,"return;"),X="function"==typeof J.vsTestElem[Q]);
q[D[U]]=X}q.gestures=q.gesturestart&&q.gesturechange&&q.gestureend;"MSGestureEvent"in window&&(q.msGestures=!0);q.gestures=!1;q.msGestures=!1;var ca=0,da=0,P,aa,T=function(a,b){var c=b?void 0:R(a.targetPointerList);return{scale:b?void 0:C(a.targetPointerList[0],a.targetPointerList[1])/ca,rotation:b?void 0:180*Math.atan2(a.targetPointerList[1].pageY-a.targetPointerList[0].pageY,a.targetPointerList[1].pageX-a.targetPointerList[0].pageX)/Math.PI-da,translation:b?void 0:[c.x-P.x,c.y-P.y],nbPointers:a.nbPointers,
pointerList:a.pointerList,targetPointerList:a.targetPointerList,centroid:c,changedPointerList:a.changedPointerList}},ba=!1,fa=function(a){2>a.targetPointerList.length||(ba?n(e,a.target,T(a)):(ca=C(a.targetPointerList[0],a.targetPointerList[1]),da=180*Math.atan2(a.targetPointerList[1].pageY-a.targetPointerList[0].pageY,a.targetPointerList[1].pageX-a.targetPointerList[0].pageX)/Math.PI,aa=J.getElementAbsolutePosition(a.targetPointerList[0].target,!0),P=R(a.targetPointerList),document.addEventListener(p.POINTER_MOVE,
ea),document.addEventListener(p.POINTER_END,W),document.addEventListener(p.POINTER_CANCEL,W),n(r,a.target,T(a)),ba=!0))},ea=function(a){O(a,function(a){n(e,a.target,T(a))})},W=function(a){B(a,function(a){2>a.targetPointerList.length?(document.removeEventListener(p.POINTER_MOVE,ea),document.removeEventListener(p.POINTER_END,W),document.removeEventListener(p.POINTER_CANCEL,W),ba=!1,n(H,a.target,T(a,!0))):n(e,a.target,T(a))})};q.msGestures?(r="MSGestureStart",e="MSGestureChange",H="MSGestureEnd"):q.gestures?
(r="gesturestart",e="gesturechange",H="gestureend"):(r="_gesture_start",e="_gesture_change",H="_gesture_end");var ha=q.gestures||q.msGestures?V:Y,ga=q.gestures||q.msGestures?$:Z;p.GESTURE_START=r;p.GESTURE_CHANGE=e;p.GESTURE_END=H}).call(this);
