window.vs={};window.vs.util={};window.vs.core={};window.vs.data={};window.vs.ui={};window.vs.fx={};window.vs.av={};window.vs.ext={};window.vs.ext.ui={};window.vs.ext.fx={};window.vs.SUPPORT_3D_TRANSFORM=!1;
(function(){var g=function(a){this.m11=this.m22=this.m33=this.m44=1;this.m12=this.m13=this.m14=this.m21=this.m23=this.m24=this.m31=this.m32=this.m34=this.m41=this.m42=this.m43=0;"string"==typeof a&&this.setMatrixValue(a)};g.displayName="FirminCSSMatrix";g.degreesToRadians=function(a){return a*Math.PI/180};g.determinant2x2=function(a,b,d,e){return a*e-b*d};g.determinant3x3=function(a,b,d,e,f,i,h,j,l){var o=g.determinant2x2;return a*o(f,i,j,l)-e*o(b,d,j,l)+h*o(b,d,f,i)};g.determinant4x4=function(a){var b=
g.determinant3x3,d=a.m21,e=a.m31,f=a.m41,i=a.m12,h=a.m22,j=a.m32,l=a.m42,o=a.m13,t=a.m23,x=a.m33,y=a.m43,z=a.m14,u=a.m24,v=a.m34,n=a.m44;return a.m11*b(h,t,u,j,x,v,l,y,n)-d*b(i,o,z,j,x,v,l,y,n)+e*b(i,o,z,h,t,u,l,y,n)-f*b(i,o,z,h,t,u,j,x,v)};[["m11","a"],["m12","b"],["m21","c"],["m22","d"],["m41","e"],["m42","f"]].forEach(function(a){var b=a[0];Object.defineProperty(g.prototype,a[1],{set:function(a){this[b]=a},get:function(){return this[b]}})});g.prototype.isAffine=function(){return 0===this.m13&&
0===this.m14&&0===this.m23&&0===this.m24&&0===this.m31&&0===this.m32&&1===this.m33&&0===this.m34&&0===this.m43&&1===this.m44};g.prototype.multiply=function(a){var b=new g;b.m11=a.m11*this.m11+a.m12*this.m21+a.m13*this.m31+a.m14*this.m41;b.m12=a.m11*this.m12+a.m12*this.m22+a.m13*this.m32+a.m14*this.m42;b.m13=a.m11*this.m13+a.m12*this.m23+a.m13*this.m33+a.m14*this.m43;b.m14=a.m11*this.m14+a.m12*this.m24+a.m13*this.m34+a.m14*this.m44;b.m21=a.m21*this.m11+a.m22*this.m21+a.m23*this.m31+a.m24*this.m41;
b.m22=a.m21*this.m12+a.m22*this.m22+a.m23*this.m32+a.m24*this.m42;b.m23=a.m21*this.m13+a.m22*this.m23+a.m23*this.m33+a.m24*this.m43;b.m24=a.m21*this.m14+a.m22*this.m24+a.m23*this.m34+a.m24*this.m44;b.m31=a.m31*this.m11+a.m32*this.m21+a.m33*this.m31+a.m34*this.m41;b.m32=a.m31*this.m12+a.m32*this.m22+a.m33*this.m32+a.m34*this.m42;b.m33=a.m31*this.m13+a.m32*this.m23+a.m33*this.m33+a.m34*this.m43;b.m34=a.m31*this.m14+a.m32*this.m24+a.m33*this.m34+a.m34*this.m44;b.m41=a.m41*this.m11+a.m42*this.m21+a.m43*
this.m31+a.m44*this.m41;b.m42=a.m41*this.m12+a.m42*this.m22+a.m43*this.m32+a.m44*this.m42;b.m43=a.m41*this.m13+a.m42*this.m23+a.m43*this.m33+a.m44*this.m43;b.m44=a.m41*this.m14+a.m42*this.m24+a.m43*this.m34+a.m44*this.m44;return b};g.prototype.isIdentityOrTranslation=function(){return 1===this.m11&&0===this.m12&&0===this.m13&&0===this.m14&&0===this.m21&&1===this.m22&&0===this.m23&&0===this.m24&&0===this.m31&&0===this.m31&&1===this.m33&&0===this.m34&&1===this.m44};g.prototype.adjoint=function(){var a=
new g,b=g.determinant3x3,d=this.m11,e=this.m12,f=this.m13,i=this.m14,h=this.m21,j=this.m22,l=this.m23,o=this.m24,t=this.m31,x=this.m32,y=this.m33,z=this.m34,u=this.m41,v=this.m42,n=this.m43,B=this.m44;a.m11=b(j,x,v,l,y,n,o,z,B);a.m21=-b(h,t,u,l,y,n,o,z,B);a.m31=b(h,t,u,j,x,v,o,z,B);a.m41=-b(h,t,u,j,x,v,l,y,n);a.m12=-b(e,x,v,f,y,n,i,z,B);a.m22=b(d,t,u,f,y,n,i,z,B);a.m32=-b(d,t,u,e,x,v,i,z,B);a.m42=b(d,t,u,e,x,v,f,y,n);a.m13=b(e,j,v,f,l,n,i,o,B);a.m23=-b(d,h,u,f,l,n,i,o,B);a.m33=b(d,h,u,e,j,v,i,o,B);
a.m43=-b(d,h,u,e,j,v,f,l,n);a.m14=-b(e,j,x,f,l,y,i,o,z);a.m24=b(d,h,t,f,l,y,i,o,z);a.m34=-b(d,h,t,e,j,x,i,o,z);a.m44=b(d,h,t,e,j,x,f,l,y);return a};g.prototype.inverse=function(){var a,b,d,e;if(this.isIdentityOrTranslation())return a=new g,0===this.m41&&0===this.m42&&0===this.m43||(a.m41=-this.m41,a.m42=-this.m42,a.m43=-this.m43),a;b=this.adjoint();a=g.determinant4x4(this);if(1.0E-8>Math.abs(a))return null;for(d=1;5>d;d++)for(e=1;5>e;e++)b["m"+d+e]/=a;return b};g.prototype.rotate=function(a,b,d){var e=
g.degreesToRadians;if("number"!=typeof a||isNaN(a))a=0;if(("number"!=typeof b||isNaN(b))&&("number"!=typeof d||isNaN(d)))d=a,b=a=0;if("number"!=typeof b||isNaN(b))b=0;if("number"!=typeof d||isNaN(d))d=0;var a=e(a),b=e(b),d=e(d),e=new g,f=new g,i=new g,h,d=d/2;h=Math.sin(d);d=Math.cos(d);i.m11=i.m22=1-2*h*h;i.m12=i.m21=2*h*d;i.m21*=-1;b/=2;h=Math.sin(b);d=Math.cos(b);f.m11=f.m33=1-2*h*h;f.m13=f.m31=2*h*d;f.m13*=-1;a/=2;h=Math.sin(a);d=Math.cos(a);e.m22=e.m33=1-2*h*h;e.m23=e.m32=2*h*d;e.m32*=-1;return i.multiply(f).multiply(e).multiply(this)};
g.prototype.rotateAxisAngle=function(a,b,d,e){if("number"!=typeof a||isNaN(a))a=0;if("number"!=typeof b||isNaN(b))b=0;if("number"!=typeof d||isNaN(d))d=0;if("number"!=typeof e||isNaN(e))e=0;0===a&&0===b&&0===d&&(d=1);var f=new g,i=Math.sqrt(a*a+b*b+d*d),h,j,l,e=(g.degreesToRadians(e)||0)/2;h=Math.cos(e);j=Math.sin(e);e=j*j;0===i?(b=a=0,d=1):1!==i&&(a/=i,b/=i,d/=i);1===a&&0===b&&0===d?(f.m22=f.m33=1-2*e,f.m23=f.m32=2*h*j,f.m32*=-1):0===a&&1===b&&0===d?(f.m11=f.m33=1-2*e,f.m13=f.m31=2*h*j,f.m13*=-1):
0===a&&0===b&&1===d?(f.m11=f.m22=1-2*e,f.m12=f.m21=2*h*j,f.m21*=-1):(i=j*h,h=a*a,j=b*b,l=d*d,f.m11=1-2*(j+l)*e,f.m12=2*(a*b*e+d*i),f.m13=2*(a*d*e-b*i),f.m21=2*(b*a*e-d*i),f.m22=1-2*(l+h)*e,f.m23=2*(b*d*e+a*i),f.m31=2*(d*a*e+b*i),f.m32=2*(d*b*e-a*i),f.m33=1-2*(h+j)*e);return this.multiply(f)};g.prototype.scale=function(a,b,d){var e=new g;if("number"!=typeof a||isNaN(a))a=1;if("number"!=typeof b||isNaN(b))b=a;if("number"!=typeof d||isNaN(d))d=1;e.m11=a;e.m22=b;e.m33=d;return this.multiply(e)};g.prototype.translate=
function(a,b,d){var e=new g;if("number"!=typeof a||isNaN(a))a=0;if("number"!=typeof b||isNaN(b))b=0;if("number"!=typeof d||isNaN(d))d=0;e.m41=a;e.m42=b;e.m43=d;return this.multiply(e)};g.prototype.setMatrixValue=function(a){var a=a.trim(),b=a.match(/^matrix(3d)?\(\s*(.+)\s*\)$/),d,e,f,g;if(b&&(a=!!b[1],b=b[2].split(/\s*,\s*/),d=b.length,e=Array(d),!(a&&16!==d)&&(a||6===d))){for(f=0;f<d;f++)if(g=b[f],g.match(/^-?\d+(\.\d+)?$/))e[f]=parseFloat(g);else return;for(f=0;f<d;f++)point=a?"m"+(Math.floor(f/
4)+1)+(f%4+1):String.fromCharCode(f+97),this[point]=e[f]}};g.prototype.toString=function(){var a=this,b,d;this.isAffine()?(d="matrix(",b="a,b,c,d,e,f".split(",")):(d="matrix3d(",b="m11,m12,m13,m14,m21,m22,m23,m24,m31,m32,m33,m34,m41,m42,m43,m44".split(","));return d+b.map(function(b){return a[b].toFixed(6)}).join(", ")+")"};this.FirminCSSMatrix=g}).call(this);
(function(){function g(c,p){w.isNumber(c)&&(this.x=c);w.isNumber(p)&&(this.y=p)}function a(c,p){for(var a in p)getter=p.__lookupGetter__(a),setter=p.__lookupSetter__(a),getter&&c.__defineGetter__(a,getter),setter&&c.__defineSetter__(a,setter),!getter&&!setter&&(c[a]=p[a]);return c}function b(c,p){for(var a in p){var b=Object.getOwnPropertyDescriptor(p,a);b&&(b.get||b.set)?w.defineProperty(c,a,b):c[a]=p[a]}return c}function d(c,p,a){if(Object.prototype.hasOwnProperty.call(a,"set")){var b=a.set;j(b)&&
c.__defineSetter__(p,b)}Object.prototype.hasOwnProperty.call(a,"get")&&(b=a.get,j(b)&&c.__defineGetter__(p,b))}function e(c,p,a){function b(c,a){return Object.prototype.hasOwnProperty.call(c,a)}if("object"!=typeof a||null===a)throw new TypeError("bad desc");if("string"!=typeof p||null===p)throw new TypeError("bad property name");var e={};e.enumerable=b(a,"enumerable")?!!a.enumerable:!0;e.configurable=b(a,"configurable")?!!a.configurable:!0;b(a,"value")&&(e.value=a.value);b(a,"writable")&&(e.writable=
!!a.writable);if(b(a,"get")){var d=a.get;j(d)&&(e.get=d)}b(a,"set")&&(a=a.set,j(a)&&(e.set=a));if(("get"in e||"set"in e)&&("value"in e||"writable"in e))throw new TypeError("identity-confused descriptor");Object.defineProperty(c,p,e)}function f(c,a,b){if(b){c.__properties__||(c.__properties__=[]);if(!c.prototype)throw"defineClassProperty on a Class without prototype";w.defineProperty(c.prototype,a,b);!1!=b.enumerable&&c.__properties__.push(a)}}function i(c){var a;switch(c){case null:return null;case void 0:return}if(c.clone)return c.clone();
switch(G.call(c)){case "[object Object]":case "Object":a={};for(var b in c)a[b]=i(c[b]);return a;case "[object Array]":a=[];for(b=0;b<c.length;b++)a[b]=i(c[b]);return a;default:return c}}function h(c){return!!(c&&1===c.nodeType)}function j(c){return"function"===typeof c}function l(c){return"[object String]"===G.call(c)}function o(c){return"undefined"===typeof c}function t(c,a){if(c){var b=c.className;return b&&0<b.length&&(b===a||RegExp("(^|\\s)"+a+"(\\s|$)").test(b))}}function x(){var c=arguments[0],
a,b=1;if(c){for(;b<arguments.length;b++)a=arguments[b],t(c,a)||(c.className=(c.className?c.className+" ":"")+a);return c}}function y(){var c=arguments[0],a,b=1;if(c&&c.className){for(;b<arguments.length;b++)a=arguments[b],c.className=z(c.className.replace(RegExp("(^|\\s+)"+a+"(\\s+|$)")," "));return c}}function z(c){return!l(c)?"":c.replace(/^\s+/,"").replace(/\s+$/,"")}function u(c){if(!l(c))return"";var a=c.split("-"),b=a.length;if(1===b)return a[0];for(var c="-"===c.charAt(0)?a[0].charAt(0).toUpperCase()+
a[0].substring(1):a[0],e=1;e<b;e++)c+=a[e].charAt(0).toUpperCase()+a[e].substring(1);return c}function v(c){if(!h(c))return{};var a=n(c,"display"),b=c.style,e=b.visibility,d=b.position,f=b.display,g=0,i=0;if("none"!==a&&null!==a)return{width:c.offsetWidth,height:c.offsetHeight};b.visibility="hidden";b.position="absolute";b.display="block";g=c.clientWidth;i=c.clientHeight;b.display=f;b.position=d;b.visibility=e;return{width:g,height:i}}function n(c,a){if(h(c)){var a="float"===a?"cssFloat":u(a),b=c.style[a];
if(!b||"auto"===b)b=(b=q.defaultView.getComputedStyle(c,null))?b[a]:null;return"opacity"===a?b?parseFloat(b):1:"auto"===b?null:b}}function B(c,a){if(h(c)){var b=c.style;o(a)&&b.removeProperty("opacity");b.opacity=1===a||""===a?"":1.0E-5>a?0:a}}function U(c,a){if(!c)return null;if(!a&&c.getBoundingClientRect){var b=c.getBoundingClientRect();if(b)return new k.Point(b.left,b.top)}var e=b=0;for(parent=c,borderXOffset=0,borderYOffset=0;parent;)borderYOffset=borderXOffset=0,parent!=c&&(borderXOffset=parseInt(parent.currentStyle?
parent.currentStyle.borderLeftWidth:0,0),borderYOffset=parseInt(parent.currentStyle?parent.currentStyle.borderTopWidth:0,0),borderXOffset=isNaN(borderXOffset)?0:borderXOffset,borderYOffset=isNaN(borderYOffset)?0:borderYOffset),parent instanceof HTMLBodyElement?(b+=parent.offsetLeft-q.documentElement.scrollLeft+borderXOffset,e+=parent.offsetTop-q.documentElement.scrollTop+borderYOffset,parent=null):(b+=parent.offsetLeft-parent.scrollLeft+borderXOffset,e+=parent.offsetTop-parent.scrollTop+borderYOffset,
parent=parent.offsetParent);return new k.Point(b,e)}function X(c){var a=U(c);return{width:c.offsetWidth,height:c.offsetWidth,left:a.x,top:a.y}}function V(c){return c&&c.getBoundingClientRect?c.getBoundingClientRect():null}function Y(c){if(c&&c.childNodes)for(var a=c.childNodes.length;a--;)c.removeChild(c.firstChild)}function aa(c,a){c&&c.style?c.style.webkitTransform=a:console.warn("setElementTransform, elem null or without style")}function ba(c){if(c)return c.style.webkitTransform}function ca(c,
a){c&&c.style?c.style.msTransform=a:console.warn("setElementTransform, elem null or without style")}function m(c){if(c)return c.style.msTransform}function M(c,a){c&&c.style?c.style.MozTransform=a:console.warn("setElementTransform, elem null or without style")}function r(c){if(c)return c.style.MozTransform}function E(c,a){c&&c.style?c.style.transform=a:console.warn("setElementTransform, elem null or without style")}function C(c){if(c)return c.style.transform}function N(c,a){if(!A){var b=q.createElement("style");
b.appendChild(q.createTextNode(""));head=q.getElementsByTagName("head")[0];head.appendChild(b);A=q.styleSheets[q.styleSheets.length-1]}b=0;A.cssRules?b=A.cssRules.length:A.rules&&(b=A.rules.length);A.insertRule?A.insertRule(c+" {"+a+"}",b):A.addRule&&A.addRule(c,a,b)}var k=this.vs=this.vs||{},w=k.util={};g.prototype={x:0,y:0,matrixTransform:function(c){var a=new CSSMatrix,a=a.translate(this.x,this.y,this.z||0),c=c.multiply(a),b=new g(c.m41,c.m42);delete a;delete c;return b}};k.Point=g;var q="undefined"!=
typeof window?window.document:null,O=q?q.createElement("vstestelem"):null,s=O?O.style:null,L=/\/Date\((-?\d+)\)\//;s&&(void 0!==s.webkitTransform?k.SUPPORT_3D_TRANSFORM="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix:void 0!==s.MozTransform?k.SUPPORT_3D_TRANSFORM="MozPerspective"in s:void 0!==s.msTransform&&(k.SUPPORT_3D_TRANSFORM="MSCSSMatrix"in window&&"m11"in new MSCSSMatrix),k.CSS_VENDOR=function(){for(var c=["MozT","msT","OT","webkitT","t"],a,b=c.length;--b;)if(a=c[b]+"ransform",a in
s)return c[b].substr(0,c[b].length-1);return null}());k.SUPPORT_CSS_TRANSFORM=null!==k.CSS_VENDOR?!0:!1;k.CSSMatrix="WebKitCSSMatrix"in window?window.WebKitCSSMatrix:"MSCSSMatrix"in window?window.MSCSSMatrix:FirminCSSMatrix;k.CSSMatrix.prototype.isAffine||(k.CSSMatrix.prototype.isAffine=function(){return!(this.m13||this.m14||this.m23||this.m24||this.m31||this.m32||1!==this.m33&&this.m34||this.m43||1!==this.m44)});k.CSSMatrix.prototype.getMatrixStr=function(){return"matrix("+[~~(1E3*this.a)/1E3,~~(1E3*
this.b)/1E3,~~(1E3*this.c)/1E3,~~(1E3*this.d)/1E3,~~(1E3*this.e)/1E3,~~(1E3*this.f)/1E3].join(", ")+")"};k.CSSMatrix.prototype.getMatrix3dStr=function(){return"matrix3d("+[~~(1E3*this.m11)/1E3,~~(1E3*this.m12)/1E3,~~(1E3*this.m13)/1E3,~~(1E3*this.m14)/1E3,~~(1E3*this.m21)/1E3,~~(1E3*this.m22)/1E3,~~(1E3*this.m23)/1E3,~~(1E3*this.m24)/1E3,~~(1E3*this.m31)/1E3,~~(1E3*this.m32)/1E3,~~(1E3*this.m33)/1E3,~~(1E3*this.m34)/1E3,~~(1E3*this.m41)/1E3,~~(1E3*this.m42)/1E3,~~(1E3*this.m43)/1E3,~~(1E3*this.m44)/
1E3].join(", ")+")"};k.requestAnimationFrame=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(c){window.setTimeout(c,1E3/60)}).bind(window);k.cancelRequestAnimationFrame=(window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.mozCancelAnimationFrame||window.oCancelAnimationFrame||window.msCancelAnimationFrame||clearTimeout).bind(window);k.setImmediate=(window.setImmediate||
function(c,a){return this.setTimeout(c,0,a)}).bind(window);k.clearImmediate=(window.clearImmediate||window.clearTimeout).bind(window);k.util.extend=Object.defineProperty?b:a;var G=Object.prototype.toString,H=Array.isArray||function(c){return"[object Array]"===G.call(c)},I,J;s&&void 0!==s.transform?(I=E,J=C):s&&void 0!==s.webkitTransform?(I=aa,J=ba):s&&void 0!==s.msTransform?(I=ca,J=m):s&&void 0!==s.MozTransform&&(I=M,J=r);Array.prototype._remove=function(c,a){var b=this.slice((a||c)+1||this.length);
this.length=0>c?this.length+c:c;return this.push.apply(this,b)};var P=function(c,a){for(var b=this.length,a=a?a:0,a=0>a?0:a;a<b;){if(this[a]===c)return a;a++}return-1};Array.prototype.findItem=Array.prototype.indexOf?Array.prototype.indexOf:P;Array.prototype.remove=function(a,b){if("object"===typeof a||w.isString(a))for(var e=0;e<this.length;)this[e]===a?this._remove(e):e++;else this._remove(a,b);return this};Array.prototype.removeAll=function(){for(;0<this.length;)this._remove(0);return this};Array.prototype.clone=
function(){for(var a=[],b=0;b<this.length;b++)a[b]=i(this[b]);return a};var A=null;w.extend(w,{vsTestElem:O,vsTestStyle:s,extendClass:function(a,b){if(a&&b&&a.prototype&&b.prototype)try{if(Object.__proto__)a.prototype.__proto__=b.prototype;else{var e=a.prototype;a.prototype=new b;w.extend(a.prototype,e)}a.__properties__||(a.__properties__=[]);b.__properties__&&(a.__properties__=a.__properties__.concat(b.__properties__));return a}catch(d){console.error(d.message())}},defineProperty:Object.defineProperty?
e:d,defineClassProperty:f,defineClassProperties:function(a,b){if(!a.prototype)throw"defineClassProperties on a Class without prototype";for(var e=Object.keys(b),d=0,g=e.length,h,i;d<g;d++)h=e[d],i=b[h],f(a,h,i)},clone:i,free:function(a){a&&(a._free&&a._free(),a.destructor&&a.destructor(),delete a)},toJSON:function(a){return JSON.stringify(a)},isElement:h,isArray:H,isFunction:j,isString:l,isNumber:function(a){return"number"===typeof a&&isFinite(a)||a instanceof Number},isObject:function(a){try{return Object.getPrototypeOf(a)===
Object.prototype}catch(b){return!1}},isUndefined:o,hasClassName:t,addClassName:x,removeClassName:y,toggleClassName:function(a,b){return!a?void 0:t(a,b)?y(a,b):x(a,b)},htmlEncode:function(a){return!l(a)?"":a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},strip:z,camelize:u,capitalize:function(a){return!l(a)?"":a.charAt(0).toUpperCase()+a.substring(1).toLowerCase()},underscore:function(a){return!l(a)?"":a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,
"$1_$2").replace(/-/g,"_").toLowerCase()},parseJSON:function(a){function b(a){if(l(a)){var c=L.exec(a);c&&c[1]&&(a=new Date(parseInt(c[1])))}else if(H(a))for(c=0;c<a.length;c++)a[c]=b(a[c]);else if(!(a instanceof Date)&&a instanceof Object)for(c in a)a[c]=b(a[c]);return a}if(!a)return null;var e=JSON.parse(a);return!L.test(a)?e:b(e)},addCssRule:N,addCssRules:function(a,b){if(H(b))for(var e=b.length;e--;)N(a,b[e])},getElementHeight:function(a){return!h(a)?void 0:v(a).height},getElementWidth:function(a){return!h(a)?
void 0:v(a).width},getElementDimensions:v,getElementStyle:n,setElementStyle:function(a,b){if(h(a)){var e=a.style,d;for(d in b)"opacity"===d?B(a,b[d]):(b[d]||e.removeProperty(d),e["float"===d||"cssFloat"===d?o(e.styleFloat)?"cssFloat":"styleFloat":d]=b[d])}},setElementOpacity:B,getElementOpacity:function(a){return!h(a)?void 0:n(a,"opacity")},getElementAbsolutePosition:U,setElementPos:function(a,b,e){a&&(a=a.style,a.left=b+"px",a.top=e+"px")},setElementSize:function(a,b,e){a&&(a=a.style,a.width=b+"px",
a.height=e+"px")},setElementVisibility:function(a,b){if(a){var e=a.style;e||w.isString(a.innerHTML)?e.visibility=b?"visible":"hidden":b?a.setAttribute("visibility","visible"):a.setAttribute("visibility","hidden")}},isElementVisible:function(a){if(!a)return!1;var b=a.style;return b||w.isString(a.innerHTML)?"hidden"===b.visibility?!1:!0:a instanceof CharacterData?!0:"hidden"===a.getAttribute("visibility")?!1:!0},removeAllElementChild:Y,safeInnerHTML:function(a,b){a&&l(b)&&(window.MSApp&&window.MSApp.execUnsafeLocalFunction?
window.MSApp.execUnsafeLocalFunction(function(){a.innerHTML=b}):a.innerHTML=b)},setElementInnerText:function(a,b){if(a){Y(a);w.isString(b)||(b=void 0===b?"":null===b?"":w.isNumber(b)?""+b:b.toString?b.toString():"");var e=b.split("\n"),d=0;if(e.length){a.appendChild(q.createTextNode(e[d]));for(d++;d<e.length;d++)a.appendChild(q.createElement("br")),a.appendChild(q.createTextNode(e[d]))}}},setElementTransform:I,getElementTransform:J,getElementMatrixTransform:function(a){if(a){var a=q.defaultView.getComputedStyle(a,
null),b;a.transform?b=a.transform:a.webkitTransform?b=a.webkitTransform:a.msTransform?b=a.msTransform:a.MozTransform&&(b=a.MozTransform);if(b)return new k.CSSMatrix(b)}},setElementTransformOrigin:function(a,b){a&&a.style?a.style["-"+k.CSS_VENDOR.toLowerCase()+"-transform-origin"]=b:console.warn("setElementTransformOrigin, elem null or without style")},getBoundingClientRect:O&&O.getBoundingClientRect?V:X,importFile:function(a,b,e,d,f){b||(b=q);var g;if("js"===d||0<=a.search("\\.js"))return d=b.createElement("script"),
d.setAttribute("type","text/javascript"),d.setAttribute("src",a),e&&(d.onload=function(){e.call(this,a)}),b.head||(b.head=b.querySelector("head")),f&&b.head.firstElementChild?b.head.insertBefore(d,b.head.firstElementChild):b.head.appendChild(d),d;if("css"===d||0<=a.search("\\.css")){g=b.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");g.setAttribute("href",a);g.setAttribute("media","screen");if(w.isFunction(e)){var h=0;(function(){g.sheet?e.call(q,a):100>
h++?cssTimeout=setTimeout(arguments.callee,100):console.error("CSS load of "+a+" failed!")})()}b.head||(b.head=b.querySelector("head"));f&&b.head.firstElementChild?b.head.insertBefore(g,b.head.firstElementChild):b.head.appendChild(g);return g}},setActiveStyleSheet:function(a){var b=0,e=q.getElementsByTagName("link"),d,f,g=k.Application_applications;if(g)for(f in g)b=g[f],b.view&&(b.view.style.display="none");for(b=0;b<e.length;b++)d=e[b],d.getAttribute("title")&&(d.getAttribute("title")!==a?d.setAttribute("disabled",
!0):d.removeAttribute("disabled"));if(g)for(f in g)b=g[f],b.view&&(b.view.style.display="block")},preloadTemplate:function(a){var b=a+".xhtml",e;if(!k.ui||!k.ui.View||!k.ui.View.__comp_templates[b])e=new XMLHttpRequest,e.open("GET",b,!1),e.send(null),4===e.readyState?200===e.status||0===e.status?(data=e.responseText,k.ui&&k.ui.View&&(k.ui.View.__comp_templates[b]=data)):console.error("Template file for component '"+a+"' unfound"):console.error("Pb when load the component '"+a+"' template")},__date_reg_exp:L,
_findItem:P,_defineProperty_api1:d,_defineProperty_api2:e,_extend_api1:a,_extend_api2:b})}).call(this);
(function(){function g(a){var d=a.vsGetCTM();b.setElementTransform(a,d.toString());delete d}var a=this.vs,b=a.util,d=a&&a.CSSMatrix;b.extend((window&&window.HTMLElement).prototype,{_vs_node_tx:0,_vs_node_ty:0,_vs_node_s:1,_vs_node_r:0,vsTranslate:function(a,b){this._vs_node_tx===a&&this._vs_node_ty===b||(this._vs_node_tx=a,this._vs_node_ty=b,g(this))},vsRotate:function(a){this._vs_node_r!==a&&(this._vs_node_r=a,g(this))},vsScale:function(a){this._vs_node_s!==a&&(this._vs_node_s=a,g(this))},vsSetNewTransformOrigin:function(a){if(a){this._vs_node_origin||
(this._vs_node_origin=[0,0]);var b=new d,b=b.translate(this._vs_node_origin[0],this._vs_node_origin[1],0),b=b.translate(this._vs_node_tx,this._vs_node_ty,0),b=b.rotate(0,0,this._vs_node_r),b=b.scale(this._vs_node_s,this._vs_node_s,1),b=b.translate(-this._vs_node_origin[0],-this._vs_node_origin[1],0);this._vs_transform||(this._vs_transform=b);this._vs_transform=b.multiply(this._vs_transform);delete b;this._vs_node_ty=this._vs_node_tx=0;this._vs_node_s=1;this._vs_node_r=0;this._vs_node_origin=[a.x,
a.y]}},vsClearTransformStack:function(){this._vs_transform&&delete this._vs_transform;this._vs_transform=void 0},vsGetCTM:function(){var a=new d;this._vs_node_origin||(this._vs_node_origin=[0,0]);a=a.translate(this._vs_node_origin[0],this._vs_node_origin[1],0);a=a.translate(this._vs_node_tx,this._vs_node_ty,0);a=a.rotate(0,0,this._vs_node_r);a=a.scale(this._vs_node_s,this._vs_node_s,1);a=a.translate(-this._vs_node_origin[0],-this._vs_node_origin[1],0);return this._vs_transform?a.multiply(this._vs_transform):
a},vsGetParentCTM:function(){function a(b){return!b?new d:a(b.parentNode).multiply(b.vsGetCTM())}return a(this.parentNode)}})}).call(this);
(function(){function g(a,b,c,e,d,f){this.configureWithEvent(a,e,d,f);this.type=b;this.identifier=c}function a(a,b){var c=[];a.nbPointers=a.touches.length;for(var e=0;e<a.nbPointers;e++){var d=a.touches[e],d=new g(d,s.TOUCH,d.identifier,d.clientX,d.clientY,a);c.push(d)}a.pointerList=c;c=[];for(e=0;e<a.targetTouches.length;e++)d=a.targetTouches[e],b&&L[d.identifier]!=b||(d=new g(d,s.TOUCH,d.identifier,d.clientX,d.clientY,a),c.push(d));a.targetPointerList=c;c=[];for(e=0;e<a.changedTouches.length;e++)d=
a.changedTouches[e],d=new g(d,s.TOUCH,d.identifier,a.clientX,a.clientY,a),c.push(d);a.changedPointerList=c}function b(a,b){var c=[];c.push(new g(a,s.MOUSE,O,a.layerX,a.layerY));b?(a.nbPointers=0,a.pointerList=[],a.targetPointerList=c,a.changedPointerList=c):(a.nbPointers=1,a.pointerList=c,a.targetPointerList=c,a.changedPointerList=[])}function d(a,b,c){var d=[],e=[],f=[],h=a.pointerId,i=G[h];b?(i?(H[h]=i,G[h]=void 0):(i=H[h],i||(i=new g(a,a.pointerType,h,a.layerX,a.layerY),H[h]=i)),H.forEach(function(a){a&&
f.push(a)}),H=[]):i?i.configureWithEvent(a):(i=new g(a,a.pointerType,h,a.layerX,a.layerY),G[h]=i);G.forEach(function(a){a&&(d.push(a),c&&L[a.identifier]!=c||e.push(a))});a.nbPointers=d.length;a.pointerList=d;a.targetPointerList=e;a.changedPointerList=f}function e(a,c){b(a);c(a)}function f(a,c){b(a);c(a)}function i(a,c){b(a,!0);c(a)}function h(b,c,d){for(var e,f=b.targetTouches.length,g=0;g<f;g++)e=b.targetTouches[g],L[e.identifier]=d;a(b);c(b)}function j(b,c,d){a(b,d);c(b)}function l(b,c){for(var d,
e=b.changedTouches.length,f=0;f<e;f++)d=b.changedTouches[f],L[d.identifier]=void 0;a(b);c(b)}function o(b,c){a(b);c(b,c)}function t(a,b,c){L[a.pointerId]=c;d(a,!1,c);b(a);0===I&&(document.addEventListener(E?"pointerup":"MSPointerUp",J),document.addEventListener(E?"pointercancel":"MSPointerCancel",J));I++}function x(a,b,c){d(a,!1,c);b(a)}function y(a,b){d(a,!0);b(a)}function z(a,b){d(a,!0);b(a)}function u(a,b,c){if(!b||!c||!c.__event_listeners)return-1;for(var d=0;d<c.__event_listeners.length;d++){var e=
c.__event_listeners[d];if(e.target===a&&e.type===b&&e.listener===c)return d}return-1}function v(a,b,d,e){var f=e.listener?e.listener.id:void 0;f||(f=""+(new Date).getTime()+""+Math.floor(1E6*Math.random()),e.listener&&(e.listener.id=f));switch(b){case N:return e.handler=function(a){P(a,d,f)},!0;case k:return e.handler=function(a){A(a,d,f)},!0;case w:return e.handler=function(a){c(a,d)},!0;case q:return e.handler=function(a){p(a,d)},!0}return!1}function n(a,b,c){var d=document.createEvent("Event");
d.initEvent(a,!0,!0);for(var e in c)d[e]=c[e];b.dispatchEvent(d)}function B(a,b){if(!a||!b)return 0;var c=b.pageX-a.pageX,d=b.pageY-a.pageY;return Math.sqrt(c*c+d*d)}function U(a,b){return!a||!b?0:180*Math.atan2(b.pageY-a.pageY,b.pageX-a.pageX)/Math.PI}function X(a){var b=a.length,c=0,d=0,e=0;if(0===b)return{X:0,y:0};for(;c<b;c++)var f=a[c],d=d+f.pageX,e=e+f.pageY;return{x:d/b-da.x,y:e/b-da.y}}function V(a){a.centroid={x:a.pageX,y:a.pageY};a.translation=[a.centroid.x-Q.x,a.centroid.y-Q.y];a.pointerList=
[new g(a,s.TOUCH,O)];a.targetPointerList=a.pointerList;a.nbPointers=1}function Y(a,b,c,d){var e=d.listener?d.listener.id:void 0;switch(b){case K:return d.gesture_handler=function(a){P(a,ha,e)},a.addEventListener(m.POINTER_START,d.gesture_handler),d.handler=c,!0;case D:case F:return d.handler=c,!0}return!1}function aa(a,b,c,d){switch(b){case K:return d.handler=function(a){Q={x:a.pageX,y:a.pageY};V(a);c(a)},!0;case D:return d.handler=function(a){V(a);c(a)},!0;case F:return d.handler=function(a){V(a);
c(a)},!0}return!1}function ba(a,b,c){var d=c.listener?c.listener.id:void 0;switch(b){case K:return a.removeEventListener(m.POINTER_START,c.gesture_handler,d),!0;case D:case F:return!0}return!1}function ca(a,b){switch(b){case K:case D:case F:return!0}return!1}var m=this.vs=this.vs||{},M=m.util=m.util||{},r=!1,E=window.navigator.pointerEnabled,C=window.navigator.msPointerEnabled;if("undefined"!=typeof document&&"createTouch"in document)r=!0;else if(E||C)r=!0;else if("undefined"!=typeof document&&window.navigator&&
window.navigator.userAgent&&(-1!==window.navigator.userAgent.indexOf("Android")||-1!==window.navigator.userAgent.indexOf("BlackBerry")))r=!0;var N,k,w,q;r?(N=E?"pointerdown":C?"MSPointerDown":"touchstart",k=E?"pointermove":C?"MSPointerMove":"touchmove",w=E?"pointerup":C?"MSPointerUp":"touchend",q=E?"pointercancel":C?"MSPointerCancel":"touchcancel"):(N="mousedown",k="mousemove",w="mouseup",q=null);var O=31337;g.prototype.configureWithEvent=function(a,b,c,d){this.pageX=a.pageX;this.pageY=a.pageY;"undefiend"!==
typeof b&&(this.clientX=b);"undefiend"!==typeof c&&(this.clientY=c);a.target?this.target=a.target:d&&(this.target=d.target);a.currentTarget?this.currentTarget=a.currentTarget:d&&(this.currentTarget=d.currentTarget)};var s={TOUCH:2,PEN:3,MOUSE:4},L=[],G=[],H=[],I=0,J=function(a){if(a=G[a.pointerId])H[a.identifier]=a,G[a.identifier]=void 0;I--;0===I&&(document.removeEventListener(E?"pointerup":"MSPointerUp",J),document.removeEventListener(E?"pointercancel":"MSPointerCancel",J))},P,A,c,p;r?C?(P=t,A=
x,c=y,p=z):(P=h,A=j,c=l,p=o):(P=e,A=f,p=c=i);m.createCustomEvent=n;m.removePointerListener=function(a,b,c,d){if(b)if(c){var e=u(a,b,c);if(-1===e)console.error("removePointerListener no binding");else{var f=c.__event_listeners[e];c.__event_listeners.remove(e);a:{switch(b){case N:case k:case w:case q:c=!0;break a}c=!1}c||ia(a,b,f);a.removeEventListener(b,f.handler,d);delete f}}else console.error("removePointerListener no listener")};m.addPointerListener=function(a,b,c,d){if(b)if(c){var e=c;M.isFunction(c)||
(e=c.handleEvent,M.isFunction(e)&&(e=e.bind(c)));if(-1!==u(a,b,c))console.error("addPointerListener binding already existing");else{c.__event_listeners||(c.__event_listeners=[]);var f={target:a,type:b,listener:c};c.__event_listeners.push(f);!v(a,b,e,f)&&!ja(a,b,e,f)&&(f.handler=e);a.addEventListener(b,f.handler,d)}}else console.error("addPointerListener no listener")};m.PointerTypes=s;m.POINTER_START=N;m.POINTER_MOVE=k;m.POINTER_END=w;m.POINTER_CANCEL=q;var K,D,F,r={},C=["gesturestart","gesturechange",
"gestureend"];document.createElement("div");for(var W=0;W<C.length;W++){var T=C[W],T="on"+T,$=T in M.vsTestElem;$||(M.vsTestElem.setAttribute(T,"return;"),$="function"==typeof M.vsTestElem[T]);r[C[W]]=$}r.gestures=r.gesturestart&&r.gesturechange&&r.gestureend;"MSGestureEvent"in window&&(r.msGestures=!0);r.gestures=!1;r.msGestures=!1;var fa=0,ga=0,Q,da,R=function(a,b){var c=b?void 0:X(a.targetPointerList);return{scale:b?void 0:B(a.targetPointerList[0],a.targetPointerList[1])/fa,rotation:b?void 0:U(a.targetPointerList[0],
a.targetPointerList[1])-ga,translation:b?void 0:[c.x-Q.x,c.y-Q.y],nbPointers:a.nbPointers,pointerList:a.pointerList,targetPointerList:a.targetPointerList,centroid:c,changedPointerList:a.changedPointerList}},Z=!1,ha=function(a){2>a.targetPointerList.length||(a.preventDefault(),Z?n(D,a.target,R(a)):(fa=B(a.targetPointerList[0],a.targetPointerList[1]),ga=U(a.targetPointerList[0],a.targetPointerList[1]),da=M.getElementAbsolutePosition(a.targetPointerList[0].target,!0),Q=X(a.targetPointerList),document.addEventListener(m.POINTER_MOVE,
ea),document.addEventListener(m.POINTER_END,S),document.addEventListener(m.POINTER_CANCEL,S),n(K,a.target,R(a)),Z=!0))},ea=function(a){a.preventDefault();A(a,function(a){2>a.targetPointerList.length?(document.removeEventListener(m.POINTER_MOVE,ea),document.removeEventListener(m.POINTER_END,S),document.removeEventListener(m.POINTER_CANCEL,S),Z=!1,n(F,a.target,R(a,!0))):n(D,a.target,R(a))})},S=function(a){a.preventDefault();c(a,function(a){2>a.targetPointerList.length?(document.removeEventListener(m.POINTER_MOVE,
ea),document.removeEventListener(m.POINTER_END,S),document.removeEventListener(m.POINTER_CANCEL,S),Z=!1,n(F,a.target,R(a,!0))):n(D,a.target,R(a))})};r.msGestures?(K="MSGestureStart",D="MSGestureChange",F="MSGestureEnd"):r.gestures?(K="gesturestart",D="gesturechange",F="gestureend"):(K="_gesture_start",D="_gesture_change",F="_gesture_end");var ja=r.gestures||r.msGestures?aa:Y,ia=r.gestures||r.msGestures?ca:ba;m.GESTURE_START=K;m.GESTURE_CHANGE=D;m.GESTURE_END=F}).call(this);
