window.CustomElements=window.CustomElements||{flags:{}};
(function(a){function d(){CustomElements.parser.parse(document);CustomElements.upgradeDocument(document);(window.Platform&&Platform.endOfMicrotask?Platform.endOfMicrotask:vs.scheduleAction)(function(){CustomElements.ready=!0;CustomElements.readyTime=Date.now();window.HTMLImports&&(CustomElements.elapsed=CustomElements.readyTime-HTMLImports.readyTime);document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}));window.HTMLImports&&(HTMLImports.__importsParsingHook=function(a){CustomElements.parser.parse(a.import)})})}
"function"!==typeof window.CustomEvent&&(window.CustomEvent=function(a){var d=document.createEvent("HTMLEvents");d.initEvent(a,!0,!0);return d});"complete"===document.readyState||a.flags.eager?d():"interactive"===document.readyState&&!window.attachEvent&&(!window.HTMLImports||window.HTMLImports.ready)?d():window.addEventListener(window.HTMLImports&&!HTMLImports.ready?"HTMLImportsLoaded":"DOMContentLoaded",d)})(window.CustomElements);
(function(a){function d(a,b,c){var e=a.firstElementChild;if(!e)for(e=a.firstChild;e&&e.nodeType!==Node.ELEMENT_NODE;)e=e.nextSibling;for(;e;)!0!==b(e,c)&&d(e,b,c),e=e.nextElementSibling;return null}function c(a,b){for(var d=a.shadowRoot;d;)e(d,b),d=d.olderShadowRoot}function e(a,b){d(a,function(a){if(b(a))return!0;c(a,b)});c(a,b)}function b(m){var b;if(!m.__upgraded__&&m.nodeType===Node.ELEMENT_NODE){var d=m.getAttribute("is")||m.localName;a.registry[d]&&(i.dom&&console.group("upgrade:",m.localName),
a.upgrade(m),i.dom&&console.groupEnd(),b=!0)}if(b)return f(m),!0;o(m)}function g(a){e(a,function(a){if(b(a))return!0})}function h(a){return b(a)||g(a)}function f(a){o(a);p(a)&&e(a,function(a){o(a)})}function j(a){q.push(a);r||(r=!0,(window.Platform&&window.Platform.endOfMicrotask||vs.scheduleAction)(k))}function k(){r=!1;for(var a=q,b=0,d=a.length,e;b<d&&(e=a[b]);b++)e();q=[]}function o(a){s?j(function(){l(a)}):l(a)}function l(a){if(a.attachedCallback||a.detachedCallback||a.__upgraded__&&i.dom)i.dom&&
console.group("inserted:",a.localName),p(a)&&(a.__inserted=(a.__inserted||0)+1,1>a.__inserted&&(a.__inserted=1),1<a.__inserted?i.dom&&console.warn("inserted:",a.localName,"insert/remove count:",a.__inserted):a.attachedCallback&&(i.dom&&console.log("inserted:",a.localName),a.attachedCallback())),i.dom&&console.groupEnd()}function t(a){u(a);e(a,function(a){u(a)})}function u(a){s?j(function(){v(a)}):v(a)}function v(a){if(a.attachedCallback||a.detachedCallback||a.__upgraded__&&i.dom)i.dom&&console.group("removed:",
a.localName),p(a)||(a.__inserted=(a.__inserted||0)-1,0<a.__inserted&&(a.__inserted=0),0>a.__inserted?i.dom&&console.warn("removed:",a.localName,"insert/remove count:",a.__inserted):a.detachedCallback&&a.detachedCallback()),i.dom&&console.groupEnd()}function p(a){for(var b=window.ShadowDOMPolyfill?ShadowDOMPolyfill.wrapIfNeeded(document):document;a;){if(a==b)return!0;a=a.parentNode||a.host}}function w(a){if(i.dom){var b=a[0];if(b&&"childList"===b.type&&b.addedNodes&&b.addedNodes){for(b=b.addedNodes[0];b&&
b!==document&&!b.host;)b=b.parentNode;var d=b&&(b.URL||b._URL||b.host&&b.host.localName)||"",d=d.split("/?").shift().split("/").pop()}console.group("mutations (%d) [%s]",a.length,d||"")}a.forEach(function(a){"childList"===a.type&&(x(a.addedNodes,function(a){a.localName&&h(a)}),x(a.removedNodes,function(a){a.localName&&t(a)}))});i.dom&&console.groupEnd()}function y(a){z.observe(a,{childList:!0,subtree:!0})}function A(a){i.dom&&console.group("upgradeDocument: ",a.baseURI.split("/").pop());h(a);i.dom&&
console.groupEnd()}function n(a){a=window.ShadowDOMPolyfill?ShadowDOMPolyfill.wrapIfNeeded(a):a;A(a);for(var a=a.querySelectorAll("link[rel="+B+"]"),b=0,d=a.length,e;b<d&&(e=a[b]);b++)e.import&&e.import.__parsed&&n(e.import)}var i=window.logFlags||{},B=window.HTMLImports?HTMLImports.IMPORT_LINK_TYPE:"none",s=!window.MutationObserver||window.MutationObserver===window.JsMutationObserver;a.hasPolyfillMutations=s;var r=!1,q=[],z=new MutationObserver(w),x=Array.prototype.forEach.call.bind(Array.prototype.forEach);
a.IMPORT_LINK_TYPE=B;a.watchShadow=function(a){if(a.shadowRoot&&!a.shadowRoot.__watched){i.dom&&console.log("watching shadow-root for: ",a.localName);for(a=a.shadowRoot;a;){var b=a;b.__watched||(y(b),b.__watched=!0);a=a.olderShadowRoot}}};a.upgradeDocumentTree=n;a.upgradeAll=h;a.upgradeSubtree=g;a.observeDocument=function(a){y(a)};a.upgradeDocument=A;a.takeRecords=function(){w(z.takeRecords());k()}})(window.CustomElements);
(function(a){var d=a.IMPORT_LINK_TYPE,c={selectors:["link[rel="+d+"]"],map:{link:"parseLink"},parse:function(a){if(!a.__parsed){a.__parsed=!0;var d=a.querySelectorAll(c.selectors);e(d,function(a){c[c.map[a.localName]](a)});CustomElements.upgradeDocument(a);CustomElements.observeDocument(a)}},parseLink:function(a){"link"===a.localName&&a.getAttribute("rel")===d&&this.parseImport(a)},parseImport:function(a){a.import&&c.parse(a.import)}},e=Array.prototype.forEach.call.bind(Array.prototype.forEach);a.parser=
c;a.IMPORT_LINK_TYPE=d})(window.CustomElements);
(function(a){a||(a=window.CustomElements={flags:{}});var d=Boolean(document.registerElement),c=!a.flags.register&&d&&!window.ShadowDOMPolyfill;if(c){var e=function(){};a.registry={};a.upgradeElement=e;a.watchShadow=e;a.upgrade=e;a.upgradeAll=e;a.upgradeSubtree=e;a.observeDocument=e;a.upgradeDocument=e;a.upgradeDocumentTree=e;a.takeRecords=e}else{var b=function(a){return(a=k(a))?b(a.extends).concat([a]):[]},g=function(b,d){d.is&&b.setAttribute("is",d.is);b.removeAttribute("unresolved");if(!Object.__proto__)for(var e=
d.native,c={},f=d.prototype;f!==e&&f!==HTMLUnknownElement.prototype;){for(var k=Object.getOwnPropertyNames(f),g=0,h;h=k[g];g++)c[h]||(Object.defineProperty(b,h,Object.getOwnPropertyDescriptor(f,h)),c[h]=1);f=Object.getPrototypeOf(f)}b.__proto__=d.prototype;b.__upgraded__=!0;b.createdCallback&&b.createdCallback();a.upgradeSubtree(b);return b},h=function(a){if(!a.setAttribute._polyfilled){var b=a.setAttribute;a.setAttribute=function(a,d){f.call(this,a,d,b)};var d=a.removeAttribute;a.removeAttribute=
function(a){f.call(this,a,null,d)};a.setAttribute._polyfilled=!0}},f=function(a,b,d){var e=this.getAttribute(a);d.apply(this,arguments);var c=this.getAttribute(a);this.attributeChangedCallback&&c!==e&&this.attributeChangedCallback(a,e,c)},j={},k=function(a){if(a)return j[a.toLowerCase()]},o=function(a){return function(){return g(l(a.tag),a)}},l=document.createElement.bind(document),t=Node.prototype.cloneNode;document.registerElement=function(d,e){var c=e||{};if(!d)throw Error("document.registerElement: first argument `name` must not be empty");
if(0>d.indexOf("-"))throw Error("document.registerElement: first argument ('name') must contain a dash ('-'). Argument provided was '"+d+"'.");if(k(d))throw Error("DuplicateDefinitionError: a type with name '"+d+"' is already registered");if(!c.prototype)throw Error("Options missing required prototype property");c.__name=d.toLowerCase();c.lifecycle=c.lifecycle||{};c.ancestry=b(c.extends);for(var f=c.extends,g=0,l;l=c.ancestry[g];g++)f=l.is&&l.tag;c.tag=f||c.__name;f&&(c.is=c.__name);if(!Object.__proto__){var n=
HTMLElement.prototype;c.is&&(n=document.createElement(c.tag),n=Object.getPrototypeOf(n));for(f=c.prototype;f&&f!==n;)g=Object.getPrototypeOf(f),f=f.__proto__=g}c.native=n;h(c.prototype);j[c.__name]=c;c.ctor=o(c);c.ctor.prototype=c.prototype;c.prototype.constructor=c.ctor;a.ready&&a.upgradeDocumentTree(document);return c.ctor};document.createElement=function(a,b){var d=k(b||a);return d?new d.ctor:l(a)};Node.prototype.cloneNode=function(b){b=t.call(this,b);a.upgradeAll(b);return b};a.registry=j;a.upgrade=
function(a){if(!a.__upgraded__&&a.nodeType===Node.ELEMENT_NODE){var b=a.getAttribute("is")||a.localName;return(b=k(b))&&g(a,b)}}}document.register=document.registerElement;a.hasNative=d;a.useNative=c})(window.CustomElements);var UNMUTABLE_ATTRIBUTES="id,is,x-hag-comp,peg,properties,name".split(",");function NO_CONTENT(a){vs.util.removeAllElementChild(a)}function TEXT_CONTENT(a,d){var c=a.textContent;vs.util.removeAllElementChild(a);c&&(d.text=c)}
function RADIO_CHECK_BUTTON_CONTENT(a,d){for(var c=[],e=a.children,b=0,g=e.length,h;b<g;b++)h=e.item(b),"VS-ITEM"==h.nodeName&&c.push(h.textContent);vs.util.removeAllElementChild(a);d.model=c}var EXTERN_COMPONENT={},LOADING_CLBS={};
function get_extern_component(a,d){function c(a,b){var d=LOADING_CLBS[a];d&&(d.forEach(function(a){vs.scheduleAction(function(){a(b)})}),d=[],delete LOADING_CLBS[a])}var e=EXTERN_COMPONENT[a],b;vs.util.isFunction(d)||(d=null);e?d&&d(e):(d&&((b=LOADING_CLBS[a])||(LOADING_CLBS[a]=b=[]),b.push(d)),b=new XMLHttpRequest,b.open("GET",a,!1),b.send(null),4===b.readyState?200===b.status||0===b.status?(e=b.responseText,e=vs.ui.Template.parseHTML(e),EXTERN_COMPONENT[a]=e,c(a,e),b=null):(console.error("Template file for component '"+
comp_name+"' unfound."),c(a,e)):(console.error("Pb when load the component '"+comp_name+"' template."),c(a,e)))}
function declare_extern_component(){var a;a=vs.ui.Template.parseHTML("<div></div>");a=Object.create(a.constructor.prototype);a.createdCallback=function(){var a=this.getAttribute("href");a&&get_extern_component(a)};a.attachedCallback=function(){var a=this,c=this.getAttribute("href"),e=this.getAttribute("id");get_extern_component(c,function(b){if(b){var c=a.parentNode,b=document.importNode(b,!0);e&&b.setAttribute("id",e);console.log(b);c.insertBefore(b,a);c.removeChild(a)}})};a.detachedCallback=function(){console.log("detachedCallback")};
a.attributeChangedCallback=function(){};document.registerElement("vs-import",{prototype:a})}var property_reg=/(\w+):(\w+[.\w+]*)#(\w+)/;function parsePropertiesDeclaration(a){for(var d={},a=a.split(";"),c,e=0;e<a.length;e++)c=property_reg.exec(a[e]),!c||4!=c.length?console.error('Problem with properties declaration "%s"',a[e]):d[c[1]]=[c[2],c[3]];return d}
function _setCompProperties(a,d){var c,e,b;a.__properties__||(a.__properties__=[]);for(e in d)b=d[e],c={},c.set=function(a,b){return function(d){for(var c=this.view,e=a.split(".");c&&e.length;)c=c.querySelector("*[name="+e.shift()+"]");c&&c.setAttribute(b,d);this.propertyChange(b)}}(b[0],b[1]),c.get=function(a,b){return function(){for(var c=this,d=a.split(".");c&&d.length;)c=c[d.shift()];if(c)return c[b]}}(b[0],b[1]),vs.util.defineProperty(a,e,c),a.__properties__.push(e)}
function LIST_TEMPLATE_CONTENT(a,d){for(var c,e,b=a.firstElementChild;b;)if("VS-TEMPLATE"==b.nodeName){var g=b.getAttribute("href");if(g)get_extern_component(g),a.__ext_template=g;else{c=b;for(var b="<li",g=c.attributes,h=g.length,f=void 0;h--;)f=g.item(h),"properties"==f.name?e=parsePropertiesDeclaration(f.value):-1===UNMUTABLE_ATTRIBUTES.indexOf(f.name)&&(b+=" "+f.name+'="'+f.value+'"');b+=">"+c.innerHTML+"</li>";b=new vs.ui.Template(b);c=buildConfiguration(c);c=b.compileView("vs.ui.AbstractListItem",
c);_setCompProperties(c,e)}break}vs.util.removeAllElementChild(a);d.__template_obj=c}
function LIST_ATTACHED_CALLBACK(){if(this._comp_){console.log("LIST attachedCallback");var a=this.__ext_template,d=this;a&&(delete this.__ext_template,get_extern_component(a,function(a){if(a){var b=buildConfiguration(a);b.node=document.importNode(a,!0);b=(new vs.ui.AbstractListItem(b)).init();if(a=a.getAttribute("properties"))a=parsePropertiesDeclaration(a),_setCompProperties(b,a);d._comp_.setItemTemplate(b);d._comp_.inPropertyDidChange()}}));var a=getParentComp(this),c=this.getAttribute("name");
a&&(a.add(this._comp_,this.getAttribute("peg")),c&&(a.isProperty(c)?(console.error('Impossible to define a child, type "%s", with the same name "%s" of a property. Change the component name on your template.',this.nodeName,c),console.log(this)):(a[c]=this._comp_,this.classList.add(c))))}}function ALLOW_CHILD_CONTENT(){}
var LIST_COMPONENT=[["vs.ui.Button","vs-button",TEXT_CONTENT],["vs.ui.Switch","vs-switch",NO_CONTENT],["vs.ui.Slider","vs-slider",NO_CONTENT],["vs.ui.Application","vs-application",ALLOW_CHILD_CONTENT],["vs.ui.Canvas","vs-canvas",NO_CONTENT],["vs.ui.CheckBox","vs-checkbox",RADIO_CHECK_BUTTON_CONTENT],["vs.ui.ComboBox","vs-combobox",NO_CONTENT],["vs.ui.ImageView","vs-image",NO_CONTENT],["vs.ui.InputField","vs-input",NO_CONTENT],["vs.ui.List","vs-list",LIST_TEMPLATE_CONTENT,null,LIST_ATTACHED_CALLBACK],
["vs.ui.NavigationBar","vs-navigation-bar",ALLOW_CHILD_CONTENT],["vs.ui.Picker","vs-picker",NO_CONTENT],["vs.ui.PopOver","vs-popover",ALLOW_CHILD_CONTENT],["vs.ui.ProgressBar","vs-progress-bar",NO_CONTENT],["vs.ui.RadioButton","vs-radiobutton",RADIO_CHECK_BUTTON_CONTENT],["vs.ui.ScrollImageView","vs-scroll-image",NO_CONTENT],["vs.ui.ScrollView","vs-scroll-view",ALLOW_CHILD_CONTENT],["vs.ui.SegmentedButton","vs-segmented-button",NO_CONTENT],["vs.ui.SplitView","vs-split-view",ALLOW_CHILD_CONTENT],["vs.ui.SVGView",
"vs-svg",NO_CONTENT],["vs.ui.TextArea","vs-textarea",NO_CONTENT],["vs.ui.TextLabel","vs-label",TEXT_CONTENT],["vs.ui.ToolBar","vs-toolbar",NO_CONTENT],["vs.ui.View","vs-view",ALLOW_CHILD_CONTENT]];function INT_DECODER(a){return parseInt(a,10)}function BOOL_DECODER(a){return Boolean(a)}function JSON_DECODER(a){var d;try{d=JSON.parse(a)}catch(c){c.stack&&console.error(c.stack),console.error(c)}return d}
function ARRAY_DECODER(a){var d;try{d=JSON.parse(a)}catch(c){c.stack&&console.error(c.stack),console.error(c)}if(vs.util.isArray(d))return d}function OBJECT_DECODER(a){var d;try{d=JSON.parse(a)}catch(c){c.stack&&console.error(c.stack),console.error(c)}return d}function STRING_DECODER(a){return""+a}
function DYNAMIC_DECODER(a,d,c){if(!d||!c)return STRING_DECODER(a);d=d[c];return vs.util.isNumber(d)?INT_DECODER(a):vs.util.isArray(d)?ARRAY_DECODER(a):vs.util.isString(d)||vs.util.isUndefined(d)?STRING_DECODER(a):vs.util.isObject(d)?OBJECT_DECODER(a):STRING_DECODER(a)}var ATTRIBUTE_DECODERS={magnet:INT_DECODER,range:ARRAY_DECODER},ONLOAD_METHODS=[];function resolveClass(a){if(!a)return null;for(var a=a.split("."),d=window;d&&a.length;)d=d[a.shift()];return d}
function buildConfiguration(a){var d={},c=a.attributes,e=c.length,b;for(d.node=a;e--;)if(b=c.item(e),a=vs.util.camelize(b.name),"id"==a)d.id=b.value;else if("class"!=a&&-1===UNMUTABLE_ATTRIBUTES.indexOf(b.name)&&0!==a.indexOf("on"))if(0===a.indexOf("json:"))d[a.replace("json:","")]=JSON_DECODER(b.value);else{var g=ATTRIBUTE_DECODERS[a];d[a]=g?g(b.value):DYNAMIC_DECODER(b.value)}return d}
function buildBinding(a,d){var c=a.attributes,e,b,g;for(e=0;e<c.length;)if(b=c.item(e),name=vs.util.camelize(b.name),"onload"==name){var h=b.value;h&&ONLOAD_METHODS.push(function(){try{eval(h)}catch(a){a.stack&&console.error(a.stack),console.error(a)}});a.removeAttribute(name)}else 0===name.indexOf("on")?(g=name.substring(2),h=b.value,a.removeAttribute(name),d.bind(g,window,function(){try{eval(h)}catch(a){a.stack&&console.error(a.stack),console.error(a)}})):e++}
function getParentComp(a){return!a?null:(a=a.parentNode)&&a._comp_?a._comp_:getParentComp(a)}
function declareComponent(a,d,c,e,b,g){var h=resolveClass(a),f,j;if(h)return"vs.ui.Application"==a?(f=document.createElement("body"),f.className="application",f.setAttribute("x-hag-hole","children")):f=h.prototype.html_template?vs.ui.Template.parseHTML(h.prototype.html_template):vs.ui.Template.parseHTML("<div></div>"),j=Object.create(f.constructor.prototype),j.createdCallback=vs.util.isFunction(e)?e:function(){var a=document.importNode(f,!0).children,b=buildConfiguration(this);this.className=f.className;
c?c(this,b):NO_CONTENT(this);for(var d=0;d<a.length;d++)this.appendChild(a.item(d));a=new h(b);if(b=this.getAttribute("properties"))b=parsePropertiesDeclaration(b),_setCompProperties(a,b);a.init();buildBinding(this,a)},j.attachedCallback=vs.util.isFunction(b)?b:function(){if(this._comp_){var a=getParentComp(this),b=this.getAttribute("name");a&&(a.add(this._comp_,this.getAttribute("peg")),b&&(a.isProperty(b)?(console.error('Impossible to define a child, type "%s", with the same name "%s" of a property. Change the component name on your template.',
this.nodeName,b),console.log(this)):(a[b]=this._comp_,this.classList.add(b))))}},j.detachedCallback=vs.util.isFunction(g)?g:function(){console.log("detachedCallback")},j.attributeChangedCallback=function(a,b,c){if(-1===UNMUTABLE_ATTRIBUTES.indexOf(a)&&(b=this._comp_,a=vs.util.camelize(a),b))if(0===a.indexOf("json:"))a=a.replace("json:",""),b.isProperty(a)&&(b[a]=JSON_DECODER(c));else if(b.isProperty(a)){var d=ATTRIBUTE_DECODERS[a];b[a]=d?d(c):DYNAMIC_DECODER(c,b,a);b.propagateChange(a)}},e={prototype:j},
"vs.ui.Application"==a&&(e.extends="body"),document.registerElement(d,e)}LIST_COMPONENT.forEach(function(a){declareComponent.apply(this,a)});declare_extern_component();window.addEventListener("DOMContentLoaded",function(){document.body.style.opacity=0});window.addEventListener("WebComponentsReady",function(){vs.ui.Application.start();vs.scheduleAction(function(){document.body.style.opacity=1});ONLOAD_METHODS.forEach(function(a){a.call()})});
